#ifndef UE4SS_SDK_DebugTools_UI_HPP
#define UE4SS_SDK_DebugTools_UI_HPP

class UDebugTools_UI_C : public UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* DisplayPopUp;
    class UBorder* Border_83;
    class UDebugTool_Option_C* DebugTool_Option;
    class UDebugTool_Option_C* DebugTool_Option_1;
    class UDebugTool_Option_C* DebugTool_Option_3;
    class UDebugTool_Option_C* DebugTool_Option_45;
    class UDebugTool_Option_C* DebugTool_Option_92;
    class UDebugTool_Option_C* DebugTool_Option_94;
    class UDebugTool_Option_C* DebugTool_Option_96;
    class UDebugTool_Option_C* DebugTool_Option_103;
    class UDebugTool_Option_C* DebugTool_Option_112;
    class UDebugTool_Option_C* DebugTool_Option_135;
    class UDebugTool_Option_C* DebugTool_Option_140;
    class UDebugTool_Option_C* DebugTool_Option_165;
    class UDebugTool_Option_C* DebugTool_Option_197;
    class UDebugTool_Option_C* DebugTool_Option_202;
    class UDebugTool_Option_C* DebugTool_Option_204;
    class UDebugTool_Option_C* DebugTool_Option_240;
    class UDebugTool_Option_C* DebugTool_Option_267;
    class UDebugTool_Option_C* DebugTool_Option_277;
    class UDebugTool_Option_C* DebugTool_Option_306;
    class UDebugTool_Option_C* DebugTool_Option_328;
    class UDebugTool_Option_C* DebugTool_Option_329;
    class UDebugTool_Option_C* DebugTool_Option_351;
    class UDebugTool_Option_C* DebugTool_Option_364;
    class UDebugTool_Option_C* DebugTool_Option_369;
    class UDebugTool_Option_C* DebugTool_Option_464;
    class UDebugTool_Option_C* DebugTool_Option_471;
    class UDebugTool_Option_C* DebugTool_Option_512;
    class UDebugTool_Option_C* DebugTool_Option_623;
    class UDebugTool_Option_C* DebugTool_Option_631;
    class UDebugTool_Option_C* DebugTool_Option_638;
    class UDebugTool_Option_C* DebugTool_Option_784;
    class UDebugTool_Option_C* DebugTool_Option_795;
    class UDebugTool_Option_C* DebugTool_Option_878;
    class UDebugTool_Option_C* DebugTool_Option_AddCash;
    class UDebugTool_Option_C* DebugTool_Option_AddShadowFragments;
    class UDebugTool_Option_C* DebugTool_Option_C;
    class UDebugTool_Option_C* DebugTool_Option_C_0;
    class UDebugTool_Option_C* DebugTool_Option_C_251;
    class UDebugTool_Option_C* DebugTool_Option_C_252;
    class UDebugTool_Option_C* DebugTool_Option_C_254;
    class UDebugTool_Option_C* DebugTool_Option_C_255;
    class UDebugTool_Option_C* DebugTool_Option_C_256;
    class UDebugTool_Option_C* DebugTool_Option_C_257;
    class UDebugTool_Option_C* DebugTool_Option_C_258;
    class UDebugTool_Option_C* DebugTool_Option_C_259;
    class UDebugTool_Option_C* DebugTool_Option_C_260;
    class UDebugTool_Option_C* DebugTool_Option_C_262;
    class UDebugTool_Option_C* DebugTool_Option_LoadLevel;
    class UDebugTool_Option_C* DebugTool_Option_VoidMaster;
    class UTextBlock* Difficulty;
    class UTextBlock* FPS;
    class UImage* Image;
    class UImage* Image_0;
    class UImage* Image_1;
    class UImage* Image_2;
    class UImage* Image_3;
    class UImage* Image_4;
    class UImage* Image_5;
    class UImage* Image_6;
    class UImage* Image_7;
    class UImage* Image_8;
    class UImage* Image_9;
    class UImage* Image_10;
    class UImage* Image_11;
    class UImage* Image_12;
    class UImage* Image_13;
    class UImage* Image_14;
    class UImage* Image_15;
    class UImage* Image_70;
    class UImage* Image_95;
    class UImage* Image_153;
    class UImage* Image_207;
    class UImage* Image_308;
    class UTextBlock* LastSafeSpot;
    class UTextBlock* Location;
    class UTextBlock* PopUp;
    class UScrollBox* ScrollBox_153;
    class UTextBlock* ToolDescription;
    class UTextBlock* ToolName;
    class UDebugTool_Option_C* WarpToVoids;
    class UDebugTool_Option_C* XboxFix;
    TArray<class UDebugTool_Option_C*> DebugTool_OptionsArray;
    int32 SelectedOption;
    TArray<class UDebugTool_Option_C*> Tools;
    class ADebugTools_Control_C* Control;
    class APlayer_Character_BP_C* Player;

    void ShowControls(bool Show);
    void Construct();
    void MoveSelection(bool Up);
    void Confirm();
    void MoveSideSelection(bool Right);
    void UpdateSelection();
    void CheckFreeze();
    void Tick(FGeometry MyGeometry, float InDeltaTime);
    void ShowPopUp(FText InText);
    void ExecuteUbergraph_DebugTools_UI(int32 EntryPoint);
};

#endif
