#ifndef UE4SS_SDK_Door_BP_HPP
#define UE4SS_SDK_Door_BP_HPP

class ADoor_BP_C : public AMechanics_Master_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UAkComponent* AkFenceLoopAmbush;
    class UAkComponent* AkFenceLoop;
    class UAkComponent* AkLoop;
    class UStaticMeshComponent* SM_Fence_Back;
    class UCameraComponent* Camera;
    class UStaticMeshComponent* SM_Fence_Front;
    class UStaticMeshComponent* Lock_Mesh3;
    class UStaticMeshComponent* Lock_Mesh1;
    class UStaticMeshComponent* Lock_Mesh2;
    class USkeletalMeshComponent* SkeletalMesh;
    class USkeletalMeshComponent* SkeletalMesh1;
    class UBillboardComponent* Billboard;
    class UBoxComponent* Box;
    class UParticleSystemComponent* P_Door;
    class UStaticMeshComponent* SM_Door;
    float Dissolve_Lerp_E16D5C494C74A8AF85751AAE5FEA48CE;
    TEnumAsByte<ETimelineDirection::Type> Dissolve__Direction_E16D5C494C74A8AF85751AAE5FEA48CE;
    class UTimelineComponent* Dissolve;
    float Timeline_0_Offset_3FFE9454417CB940F3080E998F81AE4C;
    TEnumAsByte<ETimelineDirection::Type> Timeline_0__Direction_3FFE9454417CB940F3080E998F81AE4C;
    class UTimelineComponent* Timeline_0;
    float OpenCloseTimeline_Position_7F477CB24270FE7FEE978D8094E5C908;
    TEnumAsByte<ETimelineDirection::Type> OpenCloseTimeline__Direction_7F477CB24270FE7FEE978D8094E5C908;
    class UTimelineComponent* OpenCloseTimeline;
    float Fence_Movement_Lerp_7A5A790F495EEC2F06BD4DA809150050;
    float Fence_Movement_Offset_7A5A790F495EEC2F06BD4DA809150050;
    TEnumAsByte<ETimelineDirection::Type> Fence_Movement__Direction_7A5A790F495EEC2F06BD4DA809150050;
    class UTimelineComponent* Fence Movement;
    float MoveFence_Lerp_022D15884C4411C5EBD62280DA02DDBA;
    float MoveFence_Offset_022D15884C4411C5EBD62280DA02DDBA;
    TEnumAsByte<ETimelineDirection::Type> MoveFence__Direction_022D15884C4411C5EBD62280DA02DDBA;
    class UTimelineComponent* MoveFence;
    FVector OriginalLocation;
    bool bLocked;
    float Offset;
    float Offset Fence Back;
    bool Opened;
    float Speed OpenCloseTimeline;
    float Speed FenceMovement;
    float Speed MoveFence;
    int32 NActivates;
    class UPickUp_Action_UI_C* PickUpActionUI;
    bool CanBeOpened;
    int32 DoorType;
    bool TollKeyItem;
    TArray<FText> NegativeText;
    bool RemoveItemOnUse;
    TEnumAsByte<Items::Type> Item;
    int32 ItemAmountRequired;
    TArray<FText> Text;
    class UMainDialogWB_C* Dialog;
    FDoor_BP_CFinishActivate FinishActivate;
    void FinishActivate();
    bool RestoreHudOpenDoor;
    bool Start Open;
    bool Start Open Fence;
    bool Debug Boss Instant Combat;
    float BlendTimeCam;
    bool Play VFX Fence;
    int32 MultiActivateOriginal;
    class APlayer_Character_BP_C* Player;
    bool CanTryToClose;
    class UAkAudioEvent* DoorOpenSound;
    class UAkAudioEvent* DoorCloseSound;
    bool ChangeCamera;
    bool DelayWhenUnlockHint;
    bool Instant;
    bool FenceControlLocked;
    class UAkAudioEvent* FenceSoundClose;
    class UAkAudioEvent* FenceSoundOpen;
    bool Unlocking;
    float DistanceToClose;
    FVector FenceFrontOriginalLocation;
    bool Debug Boss Skip Cutscene;
    int32 Debug Boss Fase;
    bool Debug Location;
    float Lerp Door;
    float Lerp Fence Front;
    class UAkAudioEvent* PlayLoopSound;
    class UAkAudioEvent* StopLoopSound;
    class USkipCutscene_Action_UI_C* SkipCutsceneWidget;
    bool HasCutscene;
    bool CanSkipCutscene;
    class ULevelSequencePlayer* Current Sequence;
    bool UseStingerUnlockSFX;
    bool UseStingerSFX;
    class UMaterialInstanceDynamic* Mat Lock A;
    class UMaterialInstanceDynamic* Mat Lock B;
    class UAkAudioEvent* StingerSFX;
    float Lerp Fence Back;
    class ANPCBound_C* NPCBound;
    bool InvertOffsetForFence;
    bool NoExecuteBuild;
    int32 LoopDoor;
    bool IsDoorOpening;
    bool Debug;
    bool AffectTimer;
    bool bCanFreezeActors;
    TArray<class AMoving_Path_Actor_Loop_C*> ActorsToFreeze;

    void UserConstructionScript();
    void OpenCloseTimeline__FinishedFunc();
    void OpenCloseTimeline__UpdateFunc();
    void MoveFence__FinishedFunc();
    void MoveFence__UpdateFunc();
    void MoveFence__StopSound__EventFunc();
    void MoveFence__StartSound__EventFunc();
    void Fence Movement__FinishedFunc();
    void Fence Movement__UpdateFunc();
    void Fence Movement__SoundStop__EventFunc();
    void Fence Movement__SoundStart__EventFunc();
    void Timeline_0__FinishedFunc();
    void Timeline_0__UpdateFunc();
    void Timeline_0__StopSound__EventFunc();
    void Timeline_0__StartSound__EventFunc();
    void Dissolve__FinishedFunc();
    void Dissolve__UpdateFunc();
    void InpActEvt_PC_Interact_K2Node_InputActionEvent_3(FKey Key);
    void InpActEvt_Gamepad_Interact_Shield_K2Node_InputActionEvent_2(FKey Key);
    void InpActEvt_PC_Back_K2Node_InputActionEvent_1(FKey Key);
    void InpActEvt_Gamepad_Back_K2Node_InputActionEvent_0(FKey Key);
    void BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
    void CustomEvent();
    void QuickEnd();
    void NegativeFinish();
    void OpenAfterActivate();
    void TryToClose();
    void TryToCloseCheck();
    void Set Block Door(bool bLock);
    void Boss Door Fast Open();
    void InputOpenDoor();
    void SkipCutscene();
    void Create NPCBound();
    void ReceiveEndPlay(TEnumAsByte<EEndPlayReason::Type> EndPlayReason);
    void Force Close();
    void ForceEndOverlap();
    void OnRemovePickupUI(bool bRemove);
    void CustomRemovePickupUI(bool bRemove);
    void Open();
    void ReceiveBeginPlay();
    void Close();
    void InstantOpen();
    void ReceiveAnyDamage(float Damage, const class UDamageType* DamageType, class AController* InstigatedBy, class AActor* DamageCauser);
    void Activate(bool ExternalControl, bool BeginPlay, bool ChangeCamera, bool Instant, bool Is Cutscene, bool Affect Timer);
    void Deactivate(bool Instant, bool Change Camera);
    void AlreadyUsed();
    void CloseTimelineRun();
    void OpenTimelineRun();
    void VFX(bool Open);
    void Unlock(bool DontWriteID, bool Is Cutscene);
    void KeyUnlock();
    void FenceUnlock(bool Is Cutscene);
    void FenceOnly();
    void BoxCollision(TEnumAsByte<ECollisionEnabled::Type> NewType);
    void Open Boss Door();
    void InstantUnlock();
    void InstantFenceUnlock();
    void FenceControl(bool Lock, bool Instant);
    void FenceControlLock();
    void FenceControlUnlock();
    void Build();
    void FenceLock();
    void UnlockHint();
    void ExtraFenceOnly();
    void HideFence();
    void Freeze All(bool Freeze);
    void FinishUnlockHint();
    void TriggerCustomFence(bool Instant, int32 Index);
    void InstantCustomFenceUnlock();
    void Unlock Extra();
    void InstantUnlockExtra();
    void InstantFenceUnlockExtra();
    void InstantOpenExtra();
    void Build Extra 1();
    void Destroy Fence Front();
    void BndEvt__SM_Door_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void Lock Dissolve();
    void ForceFenceControl(bool Lock);
    void OpenTimeLineRunSkip();
    void InstaForceClose();
    void RestoreKey();
    void Force Remove Pickup UI();
    void PlayStinger();
    void ExecuteUbergraph_Door_BP(int32 EntryPoint);
    void FinishActivate__DelegateSignature();
};

#endif
