#ifndef UE4SS_SDK_BlueFire_Game_Instance_HPP
#define UE4SS_SDK_BlueFire_Game_Instance_HPP

class UBlueFire_Game_Instance_C : UBFGameInstance
{
    FPointerToUberGraphFrame UberGraphFrame;
    FSave_GameSettings GameSettings;
    FSave_Settings Settings;
    FSave_PlayerAbilities PlayerAbilities;
    FSave_PlayerStats PlayerStats;
    FSave_GameStats GameStats;
    FSave_WorldStats WorldStats;
    FSave_System System;
    bool PlatformIsStadia;
    FString Version;
    TEnumAsByte<Platform::Type> Platform;
    TArray<FInventory> Shop0-Mork;
    TArray<FInventory> Shop1-Onrom;
    TArray<FInventory> Shop2-SpiritHunter;
    TArray<FInventory> Shop3-Ari;
    TArray<FInventory> Shop4-Poti;
    TArray<FInventory> Shop5-POI;
    TArray<FInventory> Shop6-NA;
    TArray<TEnumAsByte<Items::Type>> AlreadyPickedUpItems;
    FPlayer_Equipment PlayerEquipment;
    bool GameStarted;
    TArray<TEnumAsByte<E_Emotes::Type>> Emotes;
    TArray<TEnumAsByte<E_DailyQuest::Type>> Today DailyQuests;
    FDateTime LastPlayDay;
    int32 Selected Emote;
    FBuilding_Inventory_Stats Building_Inventory_Stats;
    TArray<FDressing_Pak> DressingSaves;
    TArray<FSaveQuest_Struct> Quests;
    int32 Demo;
    int32 DebugMode;
    bool IncludesZhAndKo;
    bool IncludesJa;
    bool DemoMode;
    FString Filename;
    FST_PlayerGhost PlayerGhost;
    TArray<FInventory> Shop7-Nilo;
    bool HasBeatenGame;
    bool Brutal Mode Activated;
    TEnumAsByte<Platform::Type> StadiaPreKeyboard;
    bool UniversalHasBeatenGame;
    bool UseSpeedTimer;
    UPCGamepadConnect_C* GamepadUI;
    FBlueFire_Game_Instance_COnXboxSetUserName OnXboxSetUserName;
    void OnXboxSetUserName();
    bool IsControllerConnected;
    int32 ControllerIndex;
    int32 UserIndex;
    UXboxGamepadConnect_C* GamepadXboxUI;
    FBlueFire_Game_Instance_COnXboxLogout OnXboxLogout;
    void OnXboxLogout();
    FBlueFire_Game_Instance_COnXboxChangeUser OnXboxChangeUser;
    void OnXboxChangeUser();
    FBlueFire_Game_Instance_CAddUI AddUI;
    void AddUI();
    FBlueFire_Game_Instance_CRemoveUI RemoveUI;
    void RemoveUI();
    TEnumAsByte<KeyboardType::Type> KeyboardType;
    TArray<FKey> PC_RemapBlockedKeys;
    TArray<FName> PC_Default_KeysToMap;
    TArray<FKey> PC_Default_KeysToMapKeys;
    float SpeedTimerTick;
    FString SpeedTimerSlotName;
    bool HaveDLC_VoidMaster;
    bool HasBeatedDLC_VoidMaster;
    bool IsQA_VoidOfSorrows;
    FString VoidMakerVersion;
    bool Has_VoidMaker;
    bool OpenMasterVoidMakerMode;
    FBlueFire_Game_Instance_CStadiaChangeController StadiaChangeController;
    void StadiaChangeController();
    bool StadiaDefaultInput;
    FString SpeedTimerLastSlotName;
    TMap<FName, FST_AxisMapping> AxisMappings;
    TMap<FName, FST_ActionMapping> ActionMappings;
    TArray<bool> bMakerTutorials;
    bool VMHideShortCuts;
    int32 BossDeaths;
    bool IsGOGLogged;
    FBlueFire_Game_Instance_COnGOGLogin OnGOGLogin;
    void OnGOGLogin(bool IsLogged);
    int32 WeaponsCount;
    int32 TunicsCount;
    UMongoPool* VMMongoPool;
    FString VMMongoDBConnection String;
    FMongoFindOptions VMMongoDBOptions;
    FString VMFoundLevel;
    FBlueFire_Game_Instance_CVMBsonRead VMBsonRead;
    void VMBsonRead(FString BsonString);
    FString VMTagsQuery;
    TEnumAsByte<E_SubPlatforms::Type> SubPlatform;
    bool VMZoomInverted;
    FBlueFire_Game_Instance_CVMImageRead VMImageRead;
    void VMImageRead(FString ImageString);
    FString VMThumbnailPath;
    bool VoidMakerStandalone;
    FBlueFire_Game_Instance_CLevelUpdated LevelUpdated;
    void LevelUpdated();
    FString FavoriteSearchString;
    TArray<FString> VoidNamesBannedWords;
    bool bUseNativeAchievementSystem;
    FBlueFire_Game_Instance_CVoidInserted VoidInserted;
    void VoidInserted();
    FBlueFire_Game_Instance_CVMDownloadLevel VMDownloadLevel;
    void VMDownloadLevel(FString BsonString);
    FBlueFire_Game_Instance_CVMDeleteLevel VMDeleteLevel;
    void VMDeleteLevel();
    TArray<FString> SearchIds;
    FBlueFire_Game_Instance_CVMSearchBar VMSearchBar;
    void VMSearchBar(FString BsonString);
    FBlueFire_Game_Instance_CVMSearchCompleted VMSearchCompleted;
    void VMSearchCompleted(FString MatchIds);
    TArray<FString> NewVar_0;
    bool IsCreditsCompleted;
    bool IsCreditsDLCCompleted;
    bool ForceDefaultLanguage;
    FBlueFire_Game_Instance_CDatabaseConnected DatabaseConnected;
    void DatabaseConnected(bool Failed);
    bool bIsConnectedToDB;
    FBlueFire_Game_Instance_CVMCreatorFound VMCreatorFound;
    void VMCreatorFound(FString CreatorJSON);
    FString DefaultLanguage;

    void SetArrayOfAllIdNames(FString AllIds, FString StringToCompare, FString& SearchIds, FString CallFunc_LeftChop_ReturnValue, int32 Temp_int_Array_Index_Variable, FString CallFunc_RightChop_ReturnValue, TArray<FString>& CallFunc_ParseIntoArray_ReturnValue, int32 Temp_int_Loop_Counter_Variable, FString CallFunc_Array_Get_Item, int32 CallFunc_FindSubstring_ReturnValue, int32 CallFunc_Len_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_FindSubstring_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_FindSubstring_ReturnValue_2, FString CallFunc_GetSubstring_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_2, FString CallFunc_Replace_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_3, FString CallFunc_Concat_StrStr_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_2, FString CallFunc_GetSubstring_ReturnValue_1, int32 CallFunc_FindSubstring_ReturnValue_3, bool CallFunc_NotEqual_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, FString CallFunc_JoinStringArray_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
    void CanPlatformTriggerAchievements(bool& Success, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue);
    void CheckMapName(FString MapnName, bool& InvalidName, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, FString CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_FindSubstring_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_NotEqual_IntInt_ReturnValue);
    void Check State ID(FString ID, bool& Used, bool CallFunc_Array_Contains_ReturnValue);
    void Is Xbox Series X(bool& Result, int32 CallFunc_GetXboxType_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue);
    void Get Xbox Amount Users Logged(int32& Amount Users Logged);
    void Get Xbox Force Login(bool& Force Login);
    void Get Xbox User Is Logged(bool& IsLogged);
    void Get Xbox User Name(FString& User Name, bool Temp_bool_Variable, FString Temp_string_Variable, bool CallFunc_IsEmpty_ReturnValue, FString K2Node_Select_Default);
    void Completed_8943EB0049BFC8602B4DF99B3C453C10(USaveGame* SaveGame, bool bSuccess);
    void OnFailure_044C2AD343A56A0371CA8DA9DD808AC4(FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag);
    void OnSuccess_044C2AD343A56A0371CA8DA9DD808AC4(FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag);
    void BossDeath();
    void ResetBossDeath();
    void GA SendEvent(uint8 GA Selector, FString String, float Value);
    void GA Session();
    void EnemyKilled();
    void GA ParryCount();
    void GA Time(FString VoidName, float Time);
    void DisconnectedFromDB();
    void UpdateProfileIndex(FString ID, int32 NewIndex);
    void SearchCreator(FString Creator OnlineID);
    void SearchBarMore(const TArray<FString>& SearchIds, int32 PageNum);
    void SearchByStrings(FString SearchString);
    void SearchIfBanned(FString MongoId);
    void SearchBannedWords();
    void Get WeaponCount();
    void Get TunicsCount();
    void SearchMyFavorites(const TArray<FString>& MyFavoritesId, int32 PageNum);
    void SearchOneIdUpdate(FString ID);
    void SearchByNewest(int32 PageNum);
    void GetBulkImages(FString LevelIdOne, FString LevelIdTwo, FString LevelIdThree);
    void GetOneimage(FString LevelId);
    void SearchPopularCreator();
    void SearchByPlatformID(FString PlatformID);
    void DeleteLevel(FString ID);
    void SearchPopularThisMonth();
    void SearchByGamemode(int32 GameMode);
    void ProgressionEvent(uint8 Status, FString Progression01);
    void SearchTopRated(int32 PageNum);
    void DesignEvent(FString EventId, float Value);
    void SearchByUsername(const FString Username);
    void GOG Login();
    void SearchByTags(const TArray<uint8>& NewParam);
    void SearchByOneLevelName(FString LevelName);
    void SearchOneId(FString VoidID);
    void SearchByIsFeatured(int32 PageNum);
    void InsertLevelAndThumbnail(FString LevelString, FString ThumbnailString);
    void ConnectToDatabase();
    void UpdateKeyboardType(int32 KeyboardType);
    void AnyKeyPress(FKey Key);
    void StadiaStatCall(int32 Event);
    void XboxShowLoginUI(bool Is Switch Profile);
    void XboxSetUserName();
    void XboxLogin();
    void Xbox Logout Menu();
    void NativeOnLoginUICloseEvent(int32 LocalPlayerNum);
    void OnPlayerLoginStatusChanged(EBPLoginStatus PreviousStatus, EBPLoginStatus NewStatus);
    void NativeOnControllerPairingEvent(int32 ControllerIndex, int32 NewUserId, int32 OldUserId);
    void OnControllerConnectedEvent(int32 Type);
    void OnControllerDisconectedEvent(int32 Type);
    void Set Gamepad Control(int32 Controller);
    void Async Save Game(USaveGame* SaveGameObject, FString SlotName, const int32 UserIndex);
    void ChangeController(int32 InputPin);
    void Set Achievement(FString Stat);
    void ExecuteUbergraph_BlueFire_Game_Instance(int32 EntryPoint, FString CallFunc_Concat_StrStr_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_1, TArray<FFormatArgumentData>& K2Node_MakeArray_Array, int32 CallFunc_Add_IntInt_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue, FName Temp_name_Variable, float CallFunc_Conv_IntToFloat_ReturnValue_1, FText CallFunc_Conv_NameToText_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, FFormatArgumentData K2Node_MakeStruct_FormatArgumentData, FText CallFunc_Conv_NameToText_ReturnValue_1, TArray<FFormatArgumentData>& K2Node_MakeArray_Array_1, FFormatArgumentData K2Node_MakeStruct_FormatArgumentData_1, FText CallFunc_Format_ReturnValue, TArray<FFormatArgumentData>& K2Node_MakeArray_Array_2, FText CallFunc_Format_ReturnValue_1, FText CallFunc_Format_ReturnValue_2, float Temp_float_Variable, int32 Temp_int_Variable, FName K2Node_CustomEvent_WrittenAchievementName, float K2Node_CustomEvent_WrittenProgress, int32 K2Node_CustomEvent_WrittenUserTag, AchievementWriteDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, bool K2Node_SwitchInteger_CmpSuccess, float CallFunc_Conv_IntToFloat_ReturnValue_2, FName K2Node_CustomEvent_WrittenAchievementName_1, float K2Node_CustomEvent_WrittenProgress_1, int32 K2Node_CustomEvent_WrittenUserTag_1, float CallFunc_Conv_IntToFloat_ReturnValue_3, int32 CallFunc_Array_Length_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_4, float CallFunc_Conv_IntToFloat_ReturnValue_5, AchievementWriteDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, int32 CallFunc_Array_Length_ReturnValue_1, uint8 K2Node_CustomEvent_GA_Selector, FString K2Node_CustomEvent_String, float K2Node_CustomEvent_Value_1, float CallFunc_Conv_IntToFloat_ReturnValue_6, FString CallFunc_Concat_StrStr_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_3, FString CallFunc_Concat_StrStr_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_5, FString CallFunc_Concat_StrStr_ReturnValue_6, FString CallFunc_Concat_StrStr_ReturnValue_7, FString CallFunc_Concat_StrStr_ReturnValue_8, FString CallFunc_Concat_StrStr_ReturnValue_9, FString CallFunc_Concat_StrStr_ReturnValue_10, bool K2Node_SwitchEnum_CmpSuccess, FString CallFunc_Concat_StrStr_ReturnValue_11, USaveGame* Temp_object_Variable, FString CallFunc_Concat_StrStr_ReturnValue_12, bool Temp_bool_Variable, USaveGame* K2Node_CustomEvent_SaveGame, bool K2Node_CustomEvent_bSuccess, OnAsyncHandleSaveGame__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FString CallFunc_Concat_StrStr_ReturnValue_13, FString CallFunc_Concat_StrStr_ReturnValue_14, FString CallFunc_Concat_StrStr_ReturnValue_15, FString CallFunc_Concat_StrStr_ReturnValue_16, UXboxGamepadConnect_C* CallFunc_Create_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue_2, bool CallFunc_IsRobiValid_ReturnValue_3, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, uint8 Temp_byte_Variable_2, float CallFunc_Conv_IntToFloat_ReturnValue_7, int32 CallFunc_Multiply_IntInt_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_8, uint8 Temp_byte_Variable_3, uint8 Temp_byte_Variable_4, int32 Temp_int_Variable_1, float CallFunc_Conv_IntToFloat_ReturnValue_9, float CallFunc_Conv_IntToFloat_ReturnValue_10, float CallFunc_Conv_IntToFloat_ReturnValue_11, UPCGamepadConnect_C* CallFunc_Create_ReturnValue_1, UPCGamepadConnect_C* CallFunc_Create_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_1, FSave_PlayerStats K2Node_MakeStruct_Save_PlayerStats, int32 CallFunc_Add_IntInt_ReturnValue_2, FSave_PlayerStats K2Node_MakeStruct_Save_PlayerStats_1, FString CallFunc_Concat_StrStr_ReturnValue_17, FString CallFunc_Concat_StrStr_ReturnValue_18, float CallFunc_Conv_IntToFloat_ReturnValue_12, FString CallFunc_Concat_StrStr_ReturnValue_19, FString K2Node_CustomEvent_VoidName, float K2Node_CustomEvent_Time, FString K2Node_CustomEvent_Id_2, int32 K2Node_CustomEvent_NewIndex, FString K2Node_CustomEvent_Creator_OnlineID, const TArray<FString>& K2Node_CustomEvent_SearchIds, int32 K2Node_CustomEvent_PageNum_4, FString K2Node_CustomEvent_SearchString, FString K2Node_CustomEvent_MongoId, const TArray<FString>& K2Node_CustomEvent_MyFavoritesId, int32 K2Node_CustomEvent_PageNum_3, FString K2Node_CustomEvent_Id_1, int32 K2Node_CustomEvent_PageNum_2, FString K2Node_CustomEvent_LevelIdOne, FString K2Node_CustomEvent_LevelIdTwo, FString K2Node_CustomEvent_LevelIdThree, FString K2Node_CustomEvent_LevelId, FString K2Node_CustomEvent_PlatformID, FString K2Node_CustomEvent_Id, int32 K2Node_CustomEvent_Gamemode, float CallFunc_Conv_IntToFloat_ReturnValue_13, float CallFunc_Conv_IntToFloat_ReturnValue_14, uint8 K2Node_CustomEvent_Status, FString K2Node_CustomEvent_Progression01, int32 K2Node_CustomEvent_PageNum_1, FString K2Node_CustomEvent_EventID, float K2Node_CustomEvent_Value, const FString K2Node_CustomEvent_Username, int32 CallFunc_Array_Length_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_3, const TArray<uint8>& K2Node_CustomEvent_NewParam, FString K2Node_CustomEvent_LevelName, FString K2Node_CustomEvent_VoidID, int32 K2Node_CustomEvent_PageNum, FString CallFunc_Concat_StrStr_ReturnValue_20, FString K2Node_CustomEvent_LevelString, FString K2Node_CustomEvent_ThumbnailString, FString CallFunc_Concat_StrStr_ReturnValue_21, bool CallFunc_IsLoggedIn_ReturnValue, uint8 Temp_byte_Variable_5, int32 K2Node_CustomEvent_KeyboardType, FKey K2Node_CustomEvent_Key, bool CallFunc_Key_IsGamepadKey_ReturnValue, uint8 Temp_byte_Variable_6, int32 K2Node_CustomEvent_Event, bool K2Node_SwitchInteger_CmpSuccess_1, bool K2Node_CustomEvent_Is_Switch_Profile, uint8 Temp_byte_Variable_7, int32 Temp_int_Variable_2, UPlayerController* CallFunc_GetPlayerController_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 Temp_int_Variable_3, FString CallFunc_Concat_StrStr_ReturnValue_22, FString CallFunc_Concat_StrStr_ReturnValue_23, uint8 K2Node_Select_Default, bool CallFunc_EqualEqual_ByteByte_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_24, FString CallFunc_Concat_StrStr_ReturnValue_25, FString CallFunc_Concat_StrStr_ReturnValue_26, FString CallFunc_Concat_StrStr_ReturnValue_27, int32 CallFunc_Get_Xbox_Amount_Users_Logged_Amount_Users_Logged, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 CallFunc_Get_Xbox_Amount_Users_Logged_Amount_Users_Logged_1, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Get_Xbox_Amount_Users_Logged_Amount_Users_Logged_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, FString CallFunc_Conv_IntToString_ReturnValue, int32 K2Node_Event_LocalPlayerNum, EBPLoginStatus K2Node_Event_PreviousStatus, EBPLoginStatus K2Node_Event_NewStatus, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, FString CallFunc_Conv_IntToString_ReturnValue_1, int32 K2Node_Event_ControllerIndex, int32 K2Node_Event_NewUserId, int32 K2Node_Event_OldUserId, FString CallFunc_Concat_StrStr_ReturnValue_28, FString CallFunc_Conv_IntToString_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_29, FString CallFunc_Concat_StrStr_ReturnValue_30, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, FString CallFunc_Conv_IntToString_ReturnValue_3, FString CallFunc_Conv_IntToString_ReturnValue_4, int32 K2Node_Event_type_1, FString CallFunc_Concat_StrStr_ReturnValue_31, FString CallFunc_Concat_StrStr_ReturnValue_32, int32 K2Node_Event_type, FString CallFunc_Concat_StrStr_ReturnValue_33, FString CallFunc_Concat_StrStr_ReturnValue_34, FString CallFunc_Concat_StrStr_ReturnValue_35, FString CallFunc_Concat_StrStr_ReturnValue_36, FString CallFunc_Concat_StrStr_ReturnValue_37, FString CallFunc_Concat_StrStr_ReturnValue_38, FString CallFunc_Concat_StrStr_ReturnValue_39, bool K2Node_SwitchEnum_CmpSuccess_1, bool K2Node_SwitchEnum_CmpSuccess_2, bool CallFunc_IsRobiValid_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_40, bool CallFunc_IsRobiValid_ReturnValue_5, FString CallFunc_Concat_StrStr_ReturnValue_41, int32 K2Node_CustomEvent_Controller, UPlayerController* CallFunc_GetPlayerController_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_42, FString CallFunc_Concat_StrStr_ReturnValue_43, FString CallFunc_Concat_StrStr_ReturnValue_44, FString CallFunc_Concat_StrStr_ReturnValue_45, FString CallFunc_Concat_StrStr_ReturnValue_46, FString CallFunc_Concat_StrStr_ReturnValue_47, FString CallFunc_Concat_StrStr_ReturnValue_48, FString CallFunc_Concat_StrStr_ReturnValue_49, FString CallFunc_Concat_StrStr_ReturnValue_50, FString CallFunc_Concat_StrStr_ReturnValue_51, FString CallFunc_Concat_StrStr_ReturnValue_52, FString CallFunc_Concat_StrStr_ReturnValue_53, USaveGame* K2Node_CustomEvent_SaveGameObject, FString K2Node_CustomEvent_SlotName, const int32 K2Node_CustomEvent_UserIndex, UAsyncActionHandleSaveGame* CallFunc_AsyncSaveGameToSlot_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_4, bool CallFunc_IsValid_ReturnValue, int32 K2Node_CustomEvent_InputPin, uint8 K2Node_Select_Default_1, FString CallFunc_Concat_StrStr_ReturnValue_54, FString CallFunc_Concat_StrStr_ReturnValue_55, FString K2Node_CustomEvent_Stat, FName CallFunc_Conv_StringToName_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue_2, UAchievementWriteCallbackProxy* CallFunc_WriteAchievementProgress_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
    void VMCreatorFound__DelegateSignature(FString CreatorJSON);
    void DatabaseConnected__DelegateSignature(bool Failed);
    void VMSearchCompleted__DelegateSignature(FString MatchIds);
    void VMSearchBar__DelegateSignature(FString BsonString);
    void VMDeleteLevel__DelegateSignature();
    void VMDownloadLevel__DelegateSignature(FString BsonString);
    void VoidInserted__DelegateSignature();
    void LevelUpdated__DelegateSignature();
    void VMImageRead__DelegateSignature(FString ImageString);
    void VMBsonRead__DelegateSignature(FString BsonString);
    void OnGOGLogin__DelegateSignature(bool IsLogged);
    void StadiaChangeController__DelegateSignature();
    void RemoveUI__DelegateSignature();
    void AddUI__DelegateSignature();
    void OnXboxChangeUser__DelegateSignature();
    void OnXboxLogout__DelegateSignature();
    void OnXboxSetUserName__DelegateSignature();
}

#endif
