#ifndef UE4SS_SDK_BP_Boss_Lord_3New_HPP
#define UE4SS_SDK_BP_Boss_Lord_3New_HPP

class ABP_Boss_Lord_3New_C : UEnemy_Character_Parent_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    USceneComponent* ScenePOI;
    USphereComponent* Shield Collider;
    UStaticMeshComponent* Shield;
    UParticleSystemComponent* P_Invocation_Prewarm;
    UParticleSystemComponent* P_Invocation_Laser_2;
    UStaticMeshComponent* SM_HandRunes_3;
    UStaticMeshComponent* SM_HandRunes_2;
    UStaticMeshComponent* SM_HandRunes_1;
    UParticleSystemComponent* P_Runes;
    UStaticMeshComponent* SM_Runes;
    UParticleSystemComponent* P_Tail;
    UParticleSystemComponent* P_Attack01_Sparks;
    UParticleSystemComponent* P_Invocation_Laser_1;
    UCapsuleComponent* Collider;
    UParticleSystemComponent* P_EnemyLens;
    float Timeline_2_Bomb_48180A8B4066F084FF025190AF3ED552;
    TEnumAsByte<ETimelineDirection::Type> Timeline_2__Direction_48180A8B4066F084FF025190AF3ED552;
    UTimelineComponent* Timeline_2;
    float Show_Shield_Lerp_74C8D99041D170AA42CD5388E2A5D6BA;
    TEnumAsByte<ETimelineDirection::Type> Show_Shield__Direction_74C8D99041D170AA42CD5388E2A5D6BA;
    UTimelineComponent* Show Shield;
    float Show_Runes_Lerp_B1EF383C4EA306190121539D72AE8AFB;
    TEnumAsByte<ETimelineDirection::Type> Show_Runes__Direction_B1EF383C4EA306190121539D72AE8AFB;
    UTimelineComponent* Show Runes;
    float Stage_1_Mov_Lerp_Value_6A02EF29424266C06E14798819E90F69;
    TEnumAsByte<ETimelineDirection::Type> Stage_1_Mov__Direction_6A02EF29424266C06E14798819E90F69;
    UTimelineComponent* Stage 1 Mov;
    float Boss_Sine_Mov_Lerp_Value_B630655E4B634AE9CB6632B49A0B096C;
    TEnumAsByte<ETimelineDirection::Type> Boss_Sine_Mov__Direction_B630655E4B634AE9CB6632B49A0B096C;
    UTimelineComponent* Boss Sine Mov;
    float Moving_Up_Position_1275157B4C992C98A0C9EB85382FFB38;
    TEnumAsByte<ETimelineDirection::Type> Moving_Up__Direction_1275157B4C992C98A0C9EB85382FFB38;
    UTimelineComponent* Moving Up;
    float Dissolve_Body_Dissolve_3DF201644093C54569A3D79066240C9B;
    TEnumAsByte<ETimelineDirection::Type> Dissolve_Body__Direction_3DF201644093C54569A3D79066240C9B;
    UTimelineComponent* Dissolve Body;
    float Dissolve_Armor_Dissolve_49D109114FCCC452FAEB929C81E54BAD;
    TEnumAsByte<ETimelineDirection::Type> Dissolve_Armor__Direction_49D109114FCCC452FAEB929C81E54BAD;
    UTimelineComponent* Dissolve Armor;
    float Show_Body_Lerp_Texture_AE7C6E1E42E4072EC2A5FE9376C9703D;
    TEnumAsByte<ETimelineDirection::Type> Show_Body__Direction_AE7C6E1E42E4072EC2A5FE9376C9703D;
    UTimelineComponent* Show Body;
    float Show_Armor_Amount_FA979D084B6611161ABBE69A595B17C1;
    TEnumAsByte<ETimelineDirection::Type> Show_Armor__Direction_FA979D084B6611161ABBE69A595B17C1;
    UTimelineComponent* Show Armor;
    UMaterialInstanceDynamic* SelfMat;
    FBP_Boss_Lord_3New_CFaseChange FaseChange;
    void FaseChange(int32 Fase);
    ULord_Smoke_Skeleton_AnimBlueprint_C* AnimInst;
    bool Hidden;
    FString ID;
    AActor* Boss Room Actor;
    AActor* Cutscene Camera;
    int32 Attack Counter;
    float Fase_01_Damage_0;
    float Fase_02_Damage_0;
    float Fase_03_Damage_0;
    bool Is Stuck;
    float Player Z Location;
    FString Name Move Back ;
    bool Changing Fase;
    float Lock Distance;
    UAnimMontage* Current AnimMontage;
    UMaterialInstanceDynamic* Decal Explosion;
    UMaterialInstanceDynamic* MatBody;
    UMaterialInstanceDynamic* MatArmor;
    ABP_BossRoom_3_C* Boss Room;
    bool Is Up;
    FVector Laser Hit Location;
    FVector Capsule Location;
    float Capsule Height;
    float Sine Play Rate;
    float Capsule Offset;
    float Runes Play Rate;
    UMaterialInstanceDynamic* Mat Runes;
    TArray<TEnumAsByte<Areas::Type>> Placeholder;
    ULevelSequence* Cutscene Fase 2;
    ULevelSequence* Cutscene Fase 3;
    FVector Capsule Bot Location;
    float Top Z Value;
    int32 Index Attack;
    UMaterialInstanceDynamic* Mat Runes ATK1;
    UMaterialInstanceDynamic* Mat Runes ATK2;
    bool Is Shield Visible;
    AActor* TargetLocation;
    AActor* TargetLocation2;
    int32 StunnedSound;
    float IntensityFire;
    bool Runes Instant;
    bool ShowRunes;

    void Dissolve Armor__FinishedFunc();
    void Dissolve Armor__UpdateFunc();
    void Timeline_2__FinishedFunc();
    void Timeline_2__UpdateFunc();
    void Show Body__FinishedFunc();
    void Show Body__UpdateFunc();
    void Stage 1 Mov__FinishedFunc();
    void Stage 1 Mov__UpdateFunc();
    void Show Armor__FinishedFunc();
    void Show Armor__UpdateFunc();
    void Show Shield__FinishedFunc();
    void Show Shield__UpdateFunc();
    void Show Runes__FinishedFunc();
    void Show Runes__UpdateFunc();
    void Moving Up__FinishedFunc();
    void Moving Up__UpdateFunc();
    void Dissolve Body__FinishedFunc();
    void Dissolve Body__UpdateFunc();
    void Boss Sine Mov__FinishedFunc();
    void Boss Sine Mov__UpdateFunc();
    void OnNotifyEnd_DD5C4341431F83138BC6F88EA5E99DEB(FName NotifyName);
    void OnNotifyBegin_DD5C4341431F83138BC6F88EA5E99DEB(FName NotifyName);
    void OnInterrupted_DD5C4341431F83138BC6F88EA5E99DEB(FName NotifyName);
    void OnBlendOut_DD5C4341431F83138BC6F88EA5E99DEB(FName NotifyName);
    void OnCompleted_DD5C4341431F83138BC6F88EA5E99DEB(FName NotifyName);
    void OnNotifyEnd_B3132A8C4CE20835ED0F1486D6933A1B(FName NotifyName);
    void OnNotifyBegin_B3132A8C4CE20835ED0F1486D6933A1B(FName NotifyName);
    void OnInterrupted_B3132A8C4CE20835ED0F1486D6933A1B(FName NotifyName);
    void OnBlendOut_B3132A8C4CE20835ED0F1486D6933A1B(FName NotifyName);
    void OnCompleted_B3132A8C4CE20835ED0F1486D6933A1B(FName NotifyName);
    void OnNotifyEnd_705D6D5546C63CB6F9F8F983D753E36C(FName NotifyName);
    void OnNotifyBegin_705D6D5546C63CB6F9F8F983D753E36C(FName NotifyName);
    void OnInterrupted_705D6D5546C63CB6F9F8F983D753E36C(FName NotifyName);
    void OnBlendOut_705D6D5546C63CB6F9F8F983D753E36C(FName NotifyName);
    void OnCompleted_705D6D5546C63CB6F9F8F983D753E36C(FName NotifyName);
    void OnNotifyEnd_65369A1F48600585A1973483D6240943(FName NotifyName);
    void OnNotifyBegin_65369A1F48600585A1973483D6240943(FName NotifyName);
    void OnInterrupted_65369A1F48600585A1973483D6240943(FName NotifyName);
    void OnBlendOut_65369A1F48600585A1973483D6240943(FName NotifyName);
    void OnCompleted_65369A1F48600585A1973483D6240943(FName NotifyName);
    void OnNotifyEnd_0C20688747594F709D9FFD90F4F1B088(FName NotifyName);
    void OnNotifyBegin_0C20688747594F709D9FFD90F4F1B088(FName NotifyName);
    void OnInterrupted_0C20688747594F709D9FFD90F4F1B088(FName NotifyName);
    void OnBlendOut_0C20688747594F709D9FFD90F4F1B088(FName NotifyName);
    void OnCompleted_0C20688747594F709D9FFD90F4F1B088(FName NotifyName);
    void OnNotifyEnd_F544CAD749D9A58D3E982DA87616B594(FName NotifyName);
    void OnNotifyBegin_F544CAD749D9A58D3E982DA87616B594(FName NotifyName);
    void OnInterrupted_F544CAD749D9A58D3E982DA87616B594(FName NotifyName);
    void OnBlendOut_F544CAD749D9A58D3E982DA87616B594(FName NotifyName);
    void OnCompleted_F544CAD749D9A58D3E982DA87616B594(FName NotifyName);
    void OnNotifyEnd_9907DA564CE3E518344520B69C41AD58(FName NotifyName);
    void OnNotifyBegin_9907DA564CE3E518344520B69C41AD58(FName NotifyName);
    void OnInterrupted_9907DA564CE3E518344520B69C41AD58(FName NotifyName);
    void OnBlendOut_9907DA564CE3E518344520B69C41AD58(FName NotifyName);
    void OnCompleted_9907DA564CE3E518344520B69C41AD58(FName NotifyName);
    void OnNotifyEnd_60E0D1F2430F2182976C88AA04693C87(FName NotifyName);
    void OnNotifyBegin_60E0D1F2430F2182976C88AA04693C87(FName NotifyName);
    void OnInterrupted_60E0D1F2430F2182976C88AA04693C87(FName NotifyName);
    void OnBlendOut_60E0D1F2430F2182976C88AA04693C87(FName NotifyName);
    void OnCompleted_60E0D1F2430F2182976C88AA04693C87(FName NotifyName);
    void OnNotifyEnd_E56D27A44753F653B2AA3F9AC21C53B9(FName NotifyName);
    void OnNotifyBegin_E56D27A44753F653B2AA3F9AC21C53B9(FName NotifyName);
    void OnInterrupted_E56D27A44753F653B2AA3F9AC21C53B9(FName NotifyName);
    void OnBlendOut_E56D27A44753F653B2AA3F9AC21C53B9(FName NotifyName);
    void OnCompleted_E56D27A44753F653B2AA3F9AC21C53B9(FName NotifyName);
    void OnNotifyEnd_C898D60B4D5248E507AC38BE1ECB51DA(FName NotifyName);
    void OnNotifyBegin_C898D60B4D5248E507AC38BE1ECB51DA(FName NotifyName);
    void OnInterrupted_C898D60B4D5248E507AC38BE1ECB51DA(FName NotifyName);
    void OnBlendOut_C898D60B4D5248E507AC38BE1ECB51DA(FName NotifyName);
    void OnCompleted_C898D60B4D5248E507AC38BE1ECB51DA(FName NotifyName);
    void Call Event(FString Event Name);
    void Attack03(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Laser Aim();
    void Laser Shoot();
    void Laser Cancel();
    void Anim Attack 01();
    void Anim Idle();
    void Attack02(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Attack01(int32 Count, int32 Max Count, bool Use Custom Counter);
    void VFX Body Particle(bool Show);
    void Attack04(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Attack05(int32 Count, int32 Max Count, bool Use Custom Counter);
    void VFX Dissolve Armor(bool Show);
    void Anim Attack 02();
    void AttackExpression_03();
    void AttackExpression_01();
    void AttackExpression_04();
    void LightUpStart(float IntensityFire);
    void LightUpEnd();
    void AttackExpression_05();
    void AttackExpression_06();
    void VFX Mat Body(bool Show, bool Instant);
    void Reset Idle();
    void StartBoss();
    void EndBoss();
    void VFX Mat Armor(bool Show, bool Instant);
    void VFX Change State();
    void Boss Appear();
    void Boss Desappear();
    void Set New Player Location(FVector New Location);
    void Show Teleport();
    void PlayCustomCutsceneExtra();
    void ResumeCustomCutsceneExtra();
    void Relocate Player();
    void IntroSamaelVO();
    void FadeWhiteIn();
    void FadeWhiteOut();
    void ReceiveBeginPlay();
    void ReceiveAnyDamage(float Damage, const UDamageType* DamageType, AController* InstigatedBy, AActor* DamageCauser);
    void VFX Shield(bool Show);
    void Fase Change();
    void In Room Center(bool CheckPlayerIsDead);
    void Anim Move Back(bool Move);
    void Anim Move Front(bool Move);
    void VFX Runes(bool Show, bool Instant, int32 Attack);
    void TeleportIn();
    void TeleportOut();
    void VFX Tail Particle(bool Show);
    void VFX Dissolve Body(bool Show);
    void Move Up(bool Move Up, bool Instant);
    void Damage Player(const AActor*& Actor, bool Check if is Player Attacking, float Launch Multiplier);
    void Area Damage(const FVector& Start, const FVector& End, float Radius, float Launch Multiplier);
    void Play Sine Movement();
    void Stop Sine Movement();
    void Restart();
    void BndEvt__Shield Collider_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void On Player Die();
    void VFX Smoke Spawn();
    void GA SendEvent();
    void ExecuteUbergraph_BP_Boss_Lord_3New(int32 EntryPoint, FName K2Node_CustomEvent_NotifyName_48, FName K2Node_CustomEvent_NotifyName_47, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FName K2Node_CustomEvent_NotifyName_46, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FName K2Node_CustomEvent_NotifyName_45, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FName Temp_name_Variable, int32 Temp_int_Variable, float Temp_float_Variable, bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, const TArray<AActor*>& Temp_object_Variable, bool Temp_bool_Variable_1, FName K2Node_CustomEvent_NotifyName_44, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, FName K2Node_CustomEvent_NotifyName_43, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, FName K2Node_CustomEvent_NotifyName_42, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, FName K2Node_CustomEvent_NotifyName_41, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, FName K2Node_CustomEvent_NotifyName_40, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, FName Temp_name_Variable_1, const TArray<AActor*>& Temp_object_Variable_1, int32 Temp_int_Variable_1, float Temp_float_Variable_1, float Temp_float_Variable_2, float Temp_float_Variable_3, bool Temp_bool_Variable_2, uint8 Temp_byte_Variable_2, uint8 Temp_byte_Variable_3, FName K2Node_CustomEvent_NotifyName_39, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, FName K2Node_CustomEvent_NotifyName_38, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, FName K2Node_CustomEvent_NotifyName_37, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, FName K2Node_CustomEvent_NotifyName_36, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_11, FName K2Node_CustomEvent_NotifyName_35, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_12, FName Temp_name_Variable_2, int32 Temp_int_Variable_2, bool Temp_bool_Variable_3, bool Temp_bool_Variable_4, bool Temp_bool_Variable_5, bool Temp_bool_Variable_6, FName K2Node_CustomEvent_NotifyName_34, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_13, FName K2Node_CustomEvent_NotifyName_33, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_14, FName K2Node_CustomEvent_NotifyName_32, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_15, FName K2Node_CustomEvent_NotifyName_31, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_16, FName K2Node_CustomEvent_NotifyName_30, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_17, FName Temp_name_Variable_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_18, FName K2Node_CustomEvent_NotifyName_29, FName K2Node_CustomEvent_NotifyName_28, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_19, FName K2Node_CustomEvent_NotifyName_27, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_20, FName K2Node_CustomEvent_NotifyName_26, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_21, FName K2Node_CustomEvent_NotifyName_25, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_22, FName Temp_name_Variable_4, int32 Temp_int_Variable_3, float Temp_float_Variable_4, float Temp_float_Variable_5, float Temp_float_Variable_6, int32 Temp_int_Variable_4, float Temp_float_Variable_7, float Temp_float_Variable_8, float Temp_float_Variable_9, int32 Temp_int_Variable_5, float Temp_float_Variable_10, float Temp_float_Variable_11, float Temp_float_Variable_12, int32 Temp_int_Variable_6, float Temp_float_Variable_13, float Temp_float_Variable_14, float Temp_float_Variable_15, int32 Temp_int_Variable_7, float Temp_float_Variable_16, float Temp_float_Variable_17, float Temp_float_Variable_18, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_23, FName K2Node_CustomEvent_NotifyName_24, FName K2Node_CustomEvent_NotifyName_23, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_24, FName K2Node_CustomEvent_NotifyName_22, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_25, FName K2Node_CustomEvent_NotifyName_21, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_26, FName K2Node_CustomEvent_NotifyName_20, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_27, FName Temp_name_Variable_5, FName K2Node_CustomEvent_NotifyName_19, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_28, FName K2Node_CustomEvent_NotifyName_18, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_29, FName K2Node_CustomEvent_NotifyName_17, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_30, FName K2Node_CustomEvent_NotifyName_16, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_31, FName K2Node_CustomEvent_NotifyName_15, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_32, FName Temp_name_Variable_6, int32 Temp_int_Variable_8, ULevelSequence* Temp_object_Variable_2, ULevelSequence* Temp_object_Variable_3, float CallFunc_Lerp_ReturnValue, FVector CallFunc_Conv_FloatToVector_ReturnValue, OnMovieSceneSequencePlayerEvent__DelegateSignature K2Node_CreateDelegate_OutputDelegate_33, int32 Temp_int_Variable_9, FName K2Node_CustomEvent_NotifyName_14, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_34, FName K2Node_CustomEvent_NotifyName_13, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_35, FName K2Node_CustomEvent_NotifyName_12, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_36, FName K2Node_CustomEvent_NotifyName_11, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_37, FName K2Node_CustomEvent_NotifyName_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_38, FName Temp_name_Variable_7, int32 Temp_int_Variable_10, float Temp_float_Variable_19, float Temp_float_Variable_20, bool Temp_bool_Variable_7, float Temp_float_Variable_21, float CallFunc_Lerp_ReturnValue_1, FVector CallFunc_Conv_FloatToVector_ReturnValue_1, FName K2Node_CustomEvent_NotifyName_9, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_39, FName K2Node_CustomEvent_NotifyName_8, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_40, FName K2Node_CustomEvent_NotifyName_7, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_41, FName K2Node_CustomEvent_NotifyName_6, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_42, FName K2Node_CustomEvent_NotifyName_5, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_43, FName Temp_name_Variable_8, FName K2Node_CustomEvent_NotifyName_4, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_44, FName K2Node_CustomEvent_NotifyName_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_45, FName K2Node_CustomEvent_NotifyName_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_46, FName K2Node_CustomEvent_NotifyName_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_47, FName K2Node_CustomEvent_NotifyName, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_48, FName Temp_name_Variable_9, int32 Temp_int_Variable_11, UAnimMontage* Temp_object_Variable_4, UAnimMontage* Temp_object_Variable_5, UAnimMontage* Temp_object_Variable_6, FRotator CallFunc_MakeRotator_ReturnValue, FRotator CallFunc_MakeRotator_ReturnValue_1, int32 Temp_int_Variable_12, float Temp_float_Variable_22, float Temp_float_Variable_23, float Temp_float_Variable_24, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_49, FVector CallFunc_K2_GetActorLocation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue, uint8 K2Node_Select_Default, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, FTransform CallFunc_MakeTransform_ReturnValue, FString K2Node_Event_Event_Name, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, FTimerHandle CallFunc_K2_SetTimer_ReturnValue, ABP_Invocation_Area_C* CallFunc_FinishSpawningActor_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, int32 K2Node_Event_Count_4, int32 K2Node_Event_Max_Count_4, bool K2Node_Event_Use_Custom_Counter_4, int32 CallFunc_PostEventAtLocation_ReturnValue_3, APawn* CallFunc_GetPlayerPawn_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_1, FTransform CallFunc_MakeTransform_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_4, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1, ABP_Invocation_Area_C* CallFunc_FinishSpawningActor_ReturnValue_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 K2Node_Event_Count_3, int32 K2Node_Event_Max_Count_3, bool K2Node_Event_Use_Custom_Counter_3, FVector CallFunc_GetSocketLocation_ReturnValue, FVector CallFunc_GetSocketLocation_ReturnValue_1, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 K2Node_Event_Count_2, int32 K2Node_Event_Max_Count_2, bool K2Node_Event_Use_Custom_Counter_2, uint8 K2Node_Select_Default_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue, FHitResult CallFunc_LineTraceSingle_OutHit, bool CallFunc_LineTraceSingle_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue_2, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, FVector CallFunc_BreakHitResult_Location, FVector CallFunc_BreakHitResult_ImpactPoint, FVector CallFunc_BreakHitResult_Normal, FVector CallFunc_BreakHitResult_ImpactNormal, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, AActor* CallFunc_BreakHitResult_HitActor, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, FName CallFunc_BreakHitResult_HitBoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_FaceIndex, FVector CallFunc_BreakHitResult_TraceStart, FVector CallFunc_BreakHitResult_TraceEnd, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2, FVector K2Node_Select_Default_2, ABP_Invocation_Throw_C* CallFunc_FinishSpawningActor_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_6, bool K2Node_CustomEvent_Show_7, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1, float K2Node_Select_Default_3, float CallFunc_ApplyDamage_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 K2Node_Event_Count_1, int32 K2Node_Event_Max_Count_1, bool K2Node_Event_Use_Custom_Counter_1, int32 K2Node_Event_Count, int32 K2Node_Event_Max_Count, bool K2Node_Event_Use_Custom_Counter, bool K2Node_CustomEvent_Show_6, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_7, bool K2Node_Select_Default_4, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, int32 CallFunc_PostEventAtLocation_ReturnValue_8, FVector CallFunc_Add_VectorVector_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_8, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_9, float K2Node_CustomEvent_IntensityFire, bool K2Node_CustomEvent_Show_5, bool K2Node_CustomEvent_Instant_3, float CallFunc_Lerp_ReturnValue_2, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_3, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_4, float K2Node_Select_Default_5, float K2Node_Select_Default_6, float K2Node_Select_Default_7, float K2Node_Select_Default_8, float K2Node_Select_Default_9, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_5, bool CallFunc_IsValid_ReturnValue_5, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Lerp_ReturnValue_3, FVector CallFunc_MakeVector_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_6, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult, bool CallFunc_IsValid_ReturnValue_6, bool K2Node_CustomEvent_Show_4, bool K2Node_CustomEvent_Instant_2, bool K2Node_SwitchInteger_CmpSuccess, FVector CallFunc_K2_GetActorLocation_ReturnValue_9, int32 CallFunc_PostEventAtLocation_ReturnValue_10, bool CallFunc_Not_PreBool_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_10, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_11, FVector CallFunc_K2_GetActorLocation_ReturnValue_11, int32 CallFunc_PostEventAtLocation_ReturnValue_12, FVector K2Node_Event_New_Location, ULevelSequence* K2Node_Select_Default_10, float CallFunc_Cutscene_OutputPin, bool CallFunc_IsRobiValid_ReturnValue, ALevelSequenceActor* CallFunc_CreateLevelSequencePlayer_OutActor, ULevelSequencePlayer* CallFunc_CreateLevelSequencePlayer_ReturnValue, float CallFunc_Cutscene_OutputPin_1, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, bool CallFunc_K2_SetActorRotation_ReturnValue, float CallFunc_Cutscene_OutputPin_2, UPlayerController* CallFunc_GetPlayerController_ReturnValue, AActor* K2Node_Select_Default_11, int32 CallFunc_PostEventAtLocation_ReturnValue_13, FVector CallFunc_K2_GetActorLocation_ReturnValue_12, FRotator CallFunc_K2_GetActorRotation_ReturnValue, FHitResult CallFunc_K2_SetActorLocationAndRotation_SweepHitResult, bool CallFunc_K2_SetActorLocationAndRotation_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_14, int32 CallFunc_PostEventAtLocation_ReturnValue_15, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_16, int32 CallFunc_PostEventAtLocation_ReturnValue_17, bool CallFunc_EqualEqual_IntInt_ReturnValue_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_18, int32 CallFunc_PostEventAtLocation_ReturnValue_19, FVector CallFunc_K2_GetActorLocation_ReturnValue_13, int32 CallFunc_PostEventAtLocation_ReturnValue_20, float K2Node_Event_Damage, const UDamageType* K2Node_Event_DamageType, AController* K2Node_Event_InstigatedBy, AActor* K2Node_Event_DamageCauser, TSubclassOf<UDamageType> CallFunc_GetObjectClass_ReturnValue, bool CallFunc_EqualEqual_ClassClass_ReturnValue, bool CallFunc_RecieveHit_Dead, bool K2Node_CustomEvent_Show_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_14, int32 CallFunc_PostEventAtLocation_ReturnValue_21, UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_15, ULord_Smoke_Skeleton_AnimBlueprint_C* K2Node_DynamicCast_AsLord_Smoke_Skeleton_Anim_Blueprint, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_PostEventAtLocation_ReturnValue_22, int32 CallFunc_PostEventAtLocation_ReturnValue_23, bool CallFunc_IsRobiValid_ReturnValue_1, float CallFunc_NormalizeToRange_ReturnValue, FName K2Node_CustomEvent_NotifyName_49, float K2Node_Select_Default_12, bool K2Node_SwitchInteger_CmpSuccess_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_7, bool CallFunc_IsValid_ReturnValue_7, bool CallFunc_Not_PreBool_ReturnValue_3, float K2Node_Select_Default_13, bool CallFunc_Less_FloatFloat_ReturnValue, bool K2Node_Event_CheckPlayerIsDead, int32 CallFunc_PostEventAtLocation_ReturnValue_24, int32 CallFunc_PostEventAtLocation_ReturnValue_25, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, bool K2Node_Event_Move_1, bool K2Node_Event_Move, bool K2Node_CustomEvent_Show_2, bool K2Node_CustomEvent_Instant_1, int32 K2Node_CustomEvent_Attack, float K2Node_Select_Default_14, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_1, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_2, APawn* CallFunc_GetPlayerPawn_ReturnValue_2, bool K2Node_CustomEvent_Show_1, bool K2Node_CustomEvent_Show, ABP_BossRoom_3_C* K2Node_DynamicCast_AsBP_Boss_Room_3, bool K2Node_DynamicCast_bSuccess_1, bool K2Node_CustomEvent_Move_Up, bool K2Node_CustomEvent_Instant, const AActor* K2Node_CustomEvent_Actor, bool K2Node_CustomEvent_Check_if_is_Player_Attacking, float K2Node_CustomEvent_Launch_Multiplier_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_8, bool CallFunc_IsValid_ReturnValue_8, const FVector K2Node_CustomEvent_Start, const FVector K2Node_CustomEvent_End, float K2Node_CustomEvent_Radius, float K2Node_CustomEvent_Launch_Multiplier, FVector CallFunc_BreakTransform_Location_1, FRotator CallFunc_BreakTransform_Rotation_1, FVector CallFunc_BreakTransform_Scale_1, bool CallFunc_EqualEqual_IntInt_ReturnValue_6, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_50, float CallFunc_BreakVector_X_2, float CallFunc_BreakVector_Y_2, float CallFunc_BreakVector_Z_2, float CallFunc_Add_FloatFloat_ReturnValue, const TArray<uint8>& K2Node_MakeArray_Array, float CallFunc_Lerp_ReturnValue_4, FHitResult CallFunc_SphereTraceSingleForObjects_OutHit, bool CallFunc_SphereTraceSingleForObjects_ReturnValue, FVector CallFunc_MakeVector_ReturnValue_1, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult, bool CallFunc_BreakHitResult_bBlockingHit_1, bool CallFunc_BreakHitResult_bInitialOverlap_1, float CallFunc_BreakHitResult_Time_1, float CallFunc_BreakHitResult_Distance_1, FVector CallFunc_BreakHitResult_Location_1, FVector CallFunc_BreakHitResult_ImpactPoint_1, FVector CallFunc_BreakHitResult_Normal_1, FVector CallFunc_BreakHitResult_ImpactNormal_1, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat_1, AActor* CallFunc_BreakHitResult_HitActor_1, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent_1, FName CallFunc_BreakHitResult_HitBoneName_1, int32 CallFunc_BreakHitResult_HitItem_1, int32 CallFunc_BreakHitResult_FaceIndex_1, FVector CallFunc_BreakHitResult_TraceStart_1, FVector CallFunc_BreakHitResult_TraceEnd_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_9, bool CallFunc_IsValid_ReturnValue_9, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, int32 Temp_int_Variable_13, int32 CallFunc_RandomIntegerInRange_ReturnValue, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_3, UAnimMontage* K2Node_Select_Default_15, FVector CallFunc_K2_GetActorLocation_ReturnValue_16, float CallFunc_PlayAnimMontage_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_26, int32 CallFunc_PostEventAtLocation_ReturnValue_27, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, float CallFunc_Add_FloatFloat_ReturnValue_1, float CallFunc_Lerp_ReturnValue_5, bool CallFunc_Not_PreBool_ReturnValue_4, FVector CallFunc_MakeVector_ReturnValue_2, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult, bool CallFunc_K2_SetActorLocation_ReturnValue, FVector CallFunc_MakeVector_ReturnValue_3, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult_1, bool CallFunc_K2_SetActorLocation_ReturnValue_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_HitComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, FVector K2Node_ComponentBoundEvent_NormalImpulse, const FHitResult K2Node_ComponentBoundEvent_Hit, bool CallFunc_BreakHitResult_bBlockingHit_2, bool CallFunc_BreakHitResult_bInitialOverlap_2, float CallFunc_BreakHitResult_Time_2, float CallFunc_BreakHitResult_Distance_2, FVector CallFunc_BreakHitResult_Location_2, FVector CallFunc_BreakHitResult_ImpactPoint_2, FVector CallFunc_BreakHitResult_Normal_2, FVector CallFunc_BreakHitResult_ImpactNormal_2, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat_2, AActor* CallFunc_BreakHitResult_HitActor_2, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent_2, FName CallFunc_BreakHitResult_HitBoneName_2, int32 CallFunc_BreakHitResult_HitItem_2, int32 CallFunc_BreakHitResult_FaceIndex_2, FVector CallFunc_BreakHitResult_TraceStart_2, FVector CallFunc_BreakHitResult_TraceEnd_2, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue_5, bool CallFunc_BooleanAND_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_28, int32 CallFunc_PostEventAtLocation_ReturnValue_29, FVector CallFunc_GetSocketLocation_ReturnValue_2, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, FVector CallFunc_GetSocketLocation_ReturnValue_3, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_2, FString CallFunc_CheckState_Same_ID, bool CallFunc_CheckState_Used, bool CallFunc_NotEqual_IntInt_ReturnValue, int32 Temp_int_Variable_14, FVector CallFunc_K2_GetActorLocation_ReturnValue_17, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_3, UAnimMontage* CallFunc_GetCurrentMontage_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_18, int32 CallFunc_PostEventAtLocation_ReturnValue_30, float K2Node_Select_Default_16);
    void FaseChange__DelegateSignature(int32 Fase);
}

#endif
