#ifndef UE4SS_SDK_BP_Boss_Lord_2_HPP
#define UE4SS_SDK_BP_Boss_Lord_2_HPP

class ABP_Boss_Lord_2_C : UEnemy_Character_Parent_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    USceneComponent* ScenePOI;
    UAkComponent* Ak;
    UParticleSystemComponent* P_Sword_Prewarm;
    UStaticMeshComponent* Shield;
    USphereComponent* Shield Collider;
    UArrowComponent* Arrow_Forward;
    UParticleSystemComponent* P_Tornado;
    UDecalComponent* Decal Shadow;
    UDecalComponent* Decal Sword;
    UParticleSystemComponent* P_Smoke_Body;
    UStaticMeshComponent* BigSword;
    USphereComponent* AreaDamage;
    UParticleSystemComponent* P_LordDissolve;
    UCapsuleComponent* Collider;
    float Decal_Radius_Radius_B227B22D4C122D2FDBF9C1BC9391CFA9;
    TEnumAsByte<ETimelineDirection::Type> Decal_Radius__Direction_B227B22D4C122D2FDBF9C1BC9391CFA9;
    UTimelineComponent* Decal Radius;
    float Timeline_1_0_Bomb_691C1F0A45ACE313F43204B052F893C6;
    TEnumAsByte<ETimelineDirection::Type> Timeline_1_0__Direction_691C1F0A45ACE313F43204B052F893C6;
    UTimelineComponent* Timeline_1_0;
    float Freeze_Beira_Freeze_AAE60CFD414AEE0B52B0FEB3882FA87B;
    TEnumAsByte<ETimelineDirection::Type> Freeze_Beira__Direction_AAE60CFD414AEE0B52B0FEB3882FA87B;
    UTimelineComponent* Freeze Beira;
    float Show_Shield_Lerp_B2AC85D940B58DE05E9D19ACEAB70BA5;
    TEnumAsByte<ETimelineDirection::Type> Show_Shield__Direction_B2AC85D940B58DE05E9D19ACEAB70BA5;
    UTimelineComponent* Show Shield;
    float Timeline_2_Fade_D8690788492D4AABECFBCFB050AFCBEF;
    TEnumAsByte<ETimelineDirection::Type> Timeline_2__Direction_D8690788492D4AABECFBCFB050AFCBEF;
    UTimelineComponent* Timeline_2;
    float Glow_Sword_Glow_85D4D75348CDDDA4F2A611B78FFE9E40;
    TEnumAsByte<ETimelineDirection::Type> Glow_Sword__Direction_85D4D75348CDDDA4F2A611B78FFE9E40;
    UTimelineComponent* Glow Sword;
    float Big_Sword_On_Scale_C681CAB54C40386F9B353DB47633D2F6;
    TEnumAsByte<ETimelineDirection::Type> Big_Sword_On__Direction_C681CAB54C40386F9B353DB47633D2F6;
    UTimelineComponent* Big Sword On;
    float Big_Sword_Off_Scale_6FC5B3524072F439885F47A90E716701;
    TEnumAsByte<ETimelineDirection::Type> Big_Sword_Off__Direction_6FC5B3524072F439885F47A90E716701;
    UTimelineComponent* Big Sword Off;
    float Ball_Glow_Glow_4852739B4484E3C738C5BCA143004779;
    TEnumAsByte<ETimelineDirection::Type> Ball_Glow__Direction_4852739B4484E3C738C5BCA143004779;
    UTimelineComponent* Ball Glow;
    float Dissolve_Body_Dissolve_0B8FF3914CF8039B0CAA44A8551F37E7;
    TEnumAsByte<ETimelineDirection::Type> Dissolve_Body__Direction_0B8FF3914CF8039B0CAA44A8551F37E7;
    UTimelineComponent* Dissolve Body;
    float Dissolve_Armor_Dissolve_AB347B3F42AD4FFCB4FA4DB6956CE84E;
    TEnumAsByte<ETimelineDirection::Type> Dissolve_Armor__Direction_AB347B3F42AD4FFCB4FA4DB6956CE84E;
    UTimelineComponent* Dissolve Armor;
    float Show_Fase_3_Lerp_Texture_394926274E693C98ED58169BD5630526;
    float Show_Fase_3_Glow_394926274E693C98ED58169BD5630526;
    TEnumAsByte<ETimelineDirection::Type> Show_Fase_3__Direction_394926274E693C98ED58169BD5630526;
    UTimelineComponent* Show Fase 3;
    float Show_Body_Lerp_Texture_F8C1D1AA492867A40E413DBBE948BEDC;
    TEnumAsByte<ETimelineDirection::Type> Show_Body__Direction_F8C1D1AA492867A40E413DBBE948BEDC;
    UTimelineComponent* Show Body;
    float Show_Armor_Glow_EFF746B14FEDF41BAF6DA091AE2679A3;
    TEnumAsByte<ETimelineDirection::Type> Show_Armor__Direction_EFF746B14FEDF41BAF6DA091AE2679A3;
    UTimelineComponent* Show Armor;
    UMaterialInstanceDynamic* SelfMat;
    FBP_Boss_Lord_2_CFaseChange FaseChange;
    void FaseChange(int32 Fase);
    ULord_2_Skeleton_AnimBlueprint_C* AnimInst;
    bool Hidden;
    FString ID;
    AActor* Boss Room Actor;
    FTransform InitialLoc;
    int32 Attack Counter;
    bool Is Stuck;
    float Player Z Location;
    FString Name Move Back ;
    bool Changing Fase;
    float Spawn Ball Heigth;
    float Spawn Ball Width;
    float Rolling Ball Delay;
    UAnimMontage* Current AnimMontage;
    float Show Ball Play Rate;
    UMaterialInstanceDynamic* Decal Explosion;
    UMaterialInstanceDynamic* MatBody;
    UMaterialInstanceDynamic* MatArmor;
    UMaterialInstanceDynamic* Mat Big Sword;
    bool Interrumpt Balls;
    ABP_BossRoom_2_C* BossRoom;
    UMaterialInstanceDynamic* MatDecalSword;
    TArray<TEnumAsByte<Areas::Type>> Placeholder;
    AActor* Cutscene Camera;
    ULevelSequence* Cutscene Fase 2;
    ULevelSequence* Cutscene Fase 3;
    bool Is Shield Visible;
    bool In Tornado;
    AActor* TargetLocation;
    int32 StopBreath;
    float IntensityFire;
    bool Tornado;

    void UserConstructionScript();
    void Decal Radius__FinishedFunc();
    void Decal Radius__UpdateFunc();
    void Big Sword On__FinishedFunc();
    void Big Sword On__UpdateFunc();
    void Big Sword Off__FinishedFunc();
    void Big Sword Off__UpdateFunc();
    void Show Shield__FinishedFunc();
    void Show Shield__UpdateFunc();
    void Timeline_1_0__FinishedFunc();
    void Timeline_1_0__UpdateFunc();
    void Freeze Beira__FinishedFunc();
    void Freeze Beira__UpdateFunc();
    void Timeline_2__FinishedFunc();
    void Timeline_2__UpdateFunc();
    void Glow Sword__FinishedFunc();
    void Glow Sword__UpdateFunc();
    void Ball Glow__FinishedFunc();
    void Ball Glow__UpdateFunc();
    void Dissolve Body__FinishedFunc();
    void Dissolve Body__UpdateFunc();
    void Show Fase 3__FinishedFunc();
    void Show Fase 3__UpdateFunc();
    void Dissolve Armor__FinishedFunc();
    void Dissolve Armor__UpdateFunc();
    void Show Armor__FinishedFunc();
    void Show Armor__UpdateFunc();
    void Show Body__FinishedFunc();
    void Show Body__UpdateFunc();
    void OnNotifyEnd_215C7F48460A73428E62C0AE1EFD8578(FName NotifyName);
    void OnNotifyBegin_215C7F48460A73428E62C0AE1EFD8578(FName NotifyName);
    void OnInterrupted_215C7F48460A73428E62C0AE1EFD8578(FName NotifyName);
    void OnBlendOut_215C7F48460A73428E62C0AE1EFD8578(FName NotifyName);
    void OnCompleted_215C7F48460A73428E62C0AE1EFD8578(FName NotifyName);
    void OnNotifyEnd_8A386BC44BAC027665EB7885CEEABE90(FName NotifyName);
    void OnNotifyBegin_8A386BC44BAC027665EB7885CEEABE90(FName NotifyName);
    void OnInterrupted_8A386BC44BAC027665EB7885CEEABE90(FName NotifyName);
    void OnBlendOut_8A386BC44BAC027665EB7885CEEABE90(FName NotifyName);
    void OnCompleted_8A386BC44BAC027665EB7885CEEABE90(FName NotifyName);
    void OnNotifyEnd_B34C82B0431237DFF92DD19E18E18681(FName NotifyName);
    void OnNotifyBegin_B34C82B0431237DFF92DD19E18E18681(FName NotifyName);
    void OnInterrupted_B34C82B0431237DFF92DD19E18E18681(FName NotifyName);
    void OnBlendOut_B34C82B0431237DFF92DD19E18E18681(FName NotifyName);
    void OnCompleted_B34C82B0431237DFF92DD19E18E18681(FName NotifyName);
    void OnNotifyEnd_1016DD6A4455E35EE200D48DB8581989(FName NotifyName);
    void OnNotifyBegin_1016DD6A4455E35EE200D48DB8581989(FName NotifyName);
    void OnInterrupted_1016DD6A4455E35EE200D48DB8581989(FName NotifyName);
    void OnBlendOut_1016DD6A4455E35EE200D48DB8581989(FName NotifyName);
    void OnCompleted_1016DD6A4455E35EE200D48DB8581989(FName NotifyName);
    void OnNotifyEnd_E8647D6A4C3D033EF488CBB311954CD3(FName NotifyName);
    void OnNotifyBegin_E8647D6A4C3D033EF488CBB311954CD3(FName NotifyName);
    void OnInterrupted_E8647D6A4C3D033EF488CBB311954CD3(FName NotifyName);
    void OnBlendOut_E8647D6A4C3D033EF488CBB311954CD3(FName NotifyName);
    void OnCompleted_E8647D6A4C3D033EF488CBB311954CD3(FName NotifyName);
    void OnNotifyEnd_4B19A15040350143CFB41F8E22FFF761(FName NotifyName);
    void OnNotifyBegin_4B19A15040350143CFB41F8E22FFF761(FName NotifyName);
    void OnInterrupted_4B19A15040350143CFB41F8E22FFF761(FName NotifyName);
    void OnBlendOut_4B19A15040350143CFB41F8E22FFF761(FName NotifyName);
    void OnCompleted_4B19A15040350143CFB41F8E22FFF761(FName NotifyName);
    void OnNotifyEnd_23C35BFE49D9884FE9A1F38DABCE80CB(FName NotifyName);
    void OnNotifyBegin_23C35BFE49D9884FE9A1F38DABCE80CB(FName NotifyName);
    void OnInterrupted_23C35BFE49D9884FE9A1F38DABCE80CB(FName NotifyName);
    void OnBlendOut_23C35BFE49D9884FE9A1F38DABCE80CB(FName NotifyName);
    void OnCompleted_23C35BFE49D9884FE9A1F38DABCE80CB(FName NotifyName);
    void OnNotifyEnd_62EF94D84815C421322D2B961E31475E(FName NotifyName);
    void OnNotifyBegin_62EF94D84815C421322D2B961E31475E(FName NotifyName);
    void OnInterrupted_62EF94D84815C421322D2B961E31475E(FName NotifyName);
    void OnBlendOut_62EF94D84815C421322D2B961E31475E(FName NotifyName);
    void OnCompleted_62EF94D84815C421322D2B961E31475E(FName NotifyName);
    void OnNotifyEnd_BD038D804C72BDC38AF97EB47FD65EF7(FName NotifyName);
    void OnNotifyBegin_BD038D804C72BDC38AF97EB47FD65EF7(FName NotifyName);
    void OnInterrupted_BD038D804C72BDC38AF97EB47FD65EF7(FName NotifyName);
    void OnBlendOut_BD038D804C72BDC38AF97EB47FD65EF7(FName NotifyName);
    void OnCompleted_BD038D804C72BDC38AF97EB47FD65EF7(FName NotifyName);
    void OnNotifyEnd_7DF2B59B4BBAA1BF3F44DD8FE9E951E0(FName NotifyName);
    void OnNotifyBegin_7DF2B59B4BBAA1BF3F44DD8FE9E951E0(FName NotifyName);
    void OnInterrupted_7DF2B59B4BBAA1BF3F44DD8FE9E951E0(FName NotifyName);
    void OnBlendOut_7DF2B59B4BBAA1BF3F44DD8FE9E951E0(FName NotifyName);
    void OnCompleted_7DF2B59B4BBAA1BF3F44DD8FE9E951E0(FName NotifyName);
    void Attack01(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Attack02(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Attack03(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Area Damage(const FVector& Start, const FVector& End, float Radius, float Launch Multiplier XY, float Launch Multiplier Z);
    void VFX Decal Ice(bool Show, float Time);
    void Damage Player(const AActor*& Actor, bool Check if is Player Attacking, float Launch Multiplier XY, float Launch Multiplier Z);
    void Show Big Sword(bool Show);
    void Enable Area Damage(bool Enable);
    void BndEvt__AreaDamage_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void Call Event(FString Event Name);
    void Anim Attack 03();
    void Anim Idle();
    void BndEvt__Shield Collider_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void VFX Shield(bool Show, bool UseRoom);
    void VFX Tornado(bool Show);
    void AttackExpression_01();
    void AttackExpression_02();
    void LightUpStart(float IntensityFire);
    void LightUpEnd();
    void AttackExpression_03();
    void AttackExpression_04();
    void AttackExpression_05();
    void Anim Idle Room();
    void BndEvt__Shield Collider_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void VFX Replace Boss(bool Is Start);
    void StartBoss();
    void EndBoss();
    void RadialBlur();
    void VFX Decal Sword(bool Show);
    void Boss Appear();
    void Boss Desappear();
    void Set New Player Location(FVector New Location);
    void Show Teleport();
    void PlayCustomCutsceneExtra();
    void ResumeCustomCutsceneExtra();
    void Relocate Player();
    void BeiraIntroAppear();
    void BeiraDeathVO();
    void FadeWhiteIn();
    void FadeWhiteOut();
    void ReceiveBeginPlay();
    void ReceiveAnyDamage(float Damage, const UDamageType* DamageType, AController* InstigatedBy, AActor* DamageCauser);
    void VFX Body Smoke(bool Show);
    void VFX Slash Boss(bool Is Left);
    void Fase Change();
    void In Room Center(bool CheckPlayerIsDead);
    void VFX Sword Ground(FVector Location);
    void VFX Mat Sword(bool Show);
    void Anim Move Back(bool Move);
    void Anim Move Front(bool Move);
    void VFX Change State();
    void DecalIce();
    void VFX Ball Glow(bool Show, bool Instant, bool Delay, float Delay Time, float Play Rate);
    void VFX Dissolve Body(bool Show);
    void VFX Body Particle(bool Show);
    void VFX Dissolve Armor(bool Show);
    void Restart();
    void Move to Center(bool Moving);
    void VFX Mat Armor(bool Show);
    void On Player Die();
    void VFX Mat Body(bool Show);
    void GA SendEvent();
    void ExecuteUbergraph_BP_Boss_Lord_2(int32 EntryPoint, float CallFunc_PlayAnimMontage_ReturnValue, FName K2Node_CustomEvent_NotifyName_48, FName K2Node_CustomEvent_NotifyName_47, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FName K2Node_CustomEvent_NotifyName_46, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FName K2Node_CustomEvent_NotifyName_45, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FName Temp_name_Variable, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, FName K2Node_CustomEvent_NotifyName_44, FName K2Node_CustomEvent_NotifyName_43, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, FName K2Node_CustomEvent_NotifyName_42, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, FName K2Node_CustomEvent_NotifyName_41, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, FName K2Node_CustomEvent_NotifyName_40, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, FName Temp_name_Variable_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, FName K2Node_CustomEvent_NotifyName_39, FName K2Node_CustomEvent_NotifyName_38, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, FName K2Node_CustomEvent_NotifyName_37, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, FName K2Node_CustomEvent_NotifyName_36, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_11, FName K2Node_CustomEvent_NotifyName_35, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_12, FName Temp_name_Variable_2, bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, FVector CallFunc_MakeVector_ReturnValue, FVector CallFunc_MakeVector_ReturnValue_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_13, FName K2Node_CustomEvent_NotifyName_34, FName K2Node_CustomEvent_NotifyName_33, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_14, FName K2Node_CustomEvent_NotifyName_32, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_15, FName K2Node_CustomEvent_NotifyName_31, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_16, FName K2Node_CustomEvent_NotifyName_30, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_17, FName Temp_name_Variable_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_18, FName K2Node_CustomEvent_NotifyName_29, FName K2Node_CustomEvent_NotifyName_28, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_19, FName K2Node_CustomEvent_NotifyName_27, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_20, FName K2Node_CustomEvent_NotifyName_26, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_21, FName K2Node_CustomEvent_NotifyName_25, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_22, FName Temp_name_Variable_4, const TArray<AActor*>& Temp_object_Variable, bool Temp_bool_Variable_1, FVector Temp_struct_Variable, FVector Temp_struct_Variable_1, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_2, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable, FName K2Node_CustomEvent_NotifyName_24, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_23, FName K2Node_CustomEvent_NotifyName_23, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_24, FName K2Node_CustomEvent_NotifyName_22, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_25, FName K2Node_CustomEvent_NotifyName_21, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_26, FName K2Node_CustomEvent_NotifyName_20, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_27, FName Temp_name_Variable_5, int32 Temp_int_Variable, float Temp_float_Variable, float Temp_float_Variable_1, float Temp_float_Variable_2, float Temp_float_Variable_3, int32 Temp_int_Variable_1, int32 Temp_int_Variable_2, float Temp_float_Variable_4, float Temp_float_Variable_5, float Temp_float_Variable_6, float Temp_float_Variable_7, int32 Temp_int_Variable_3, float Temp_float_Variable_8, float Temp_float_Variable_9, float Temp_float_Variable_10, float Temp_float_Variable_11, int32 Temp_int_Variable_4, float Temp_float_Variable_12, float Temp_float_Variable_13, float Temp_float_Variable_14, FName K2Node_CustomEvent_NotifyName_19, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_28, FName K2Node_CustomEvent_NotifyName_18, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_29, FName K2Node_CustomEvent_NotifyName_17, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_30, FName K2Node_CustomEvent_NotifyName_16, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_31, FName K2Node_CustomEvent_NotifyName_15, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_32, FName Temp_name_Variable_6, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_33, FName K2Node_CustomEvent_NotifyName_14, FName K2Node_CustomEvent_NotifyName_13, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_34, FName K2Node_CustomEvent_NotifyName_12, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_35, FName K2Node_CustomEvent_NotifyName_11, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_36, FName K2Node_CustomEvent_NotifyName_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_37, FName Temp_name_Variable_7, int32 Temp_int_Variable_5, ULevelSequence* Temp_object_Variable_1, ULevelSequence* Temp_object_Variable_2, OnMovieSceneSequencePlayerEvent__DelegateSignature K2Node_CreateDelegate_OutputDelegate_38, FName K2Node_CustomEvent_NotifyName_9, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_39, FName K2Node_CustomEvent_NotifyName_8, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_40, FName K2Node_CustomEvent_NotifyName_7, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_41, FName K2Node_CustomEvent_NotifyName_6, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_42, FName K2Node_CustomEvent_NotifyName_5, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_43, FName Temp_name_Variable_8, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_44, FName K2Node_CustomEvent_NotifyName_4, FName K2Node_CustomEvent_NotifyName_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_45, FName K2Node_CustomEvent_NotifyName_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_46, FName K2Node_CustomEvent_NotifyName_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_47, FName K2Node_CustomEvent_NotifyName, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_48, FName Temp_name_Variable_9, int32 Temp_int_Variable_6, float Temp_float_Variable_15, float Temp_float_Variable_16, bool Temp_bool_Variable_2, float Temp_float_Variable_17, FRotator CallFunc_MakeRotator_ReturnValue, bool Temp_bool_Variable_3, uint8 Temp_byte_Variable_2, uint8 Temp_byte_Variable_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_49, int32 K2Node_Event_Count_2, int32 K2Node_Event_Max_Count_2, bool K2Node_Event_Use_Custom_Counter_2, int32 K2Node_Event_Count_1, int32 K2Node_Event_Max_Count_1, bool K2Node_Event_Use_Custom_Counter_1, int32 K2Node_Event_Count, int32 K2Node_Event_Max_Count, bool K2Node_Event_Use_Custom_Counter, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, bool K2Node_SwitchInteger_CmpSuccess, FVector CallFunc_K2_GetActorLocation_ReturnValue, const FVector K2Node_CustomEvent_Start, const FVector K2Node_CustomEvent_End, float K2Node_CustomEvent_Radius, float K2Node_CustomEvent_Launch_Multiplier_XY_1, float K2Node_CustomEvent_Launch_Multiplier_Z_1, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, const TArray<uint8>& K2Node_MakeArray_Array, FVector CallFunc_MakeVector_ReturnValue_2, bool K2Node_CustomEvent_Show_12, float K2Node_CustomEvent_Time, FTimerHandle CallFunc_K2_SetTimer_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1, const AActor* K2Node_CustomEvent_Actor, bool K2Node_CustomEvent_Check_if_is_Player_Attacking, float K2Node_CustomEvent_Launch_Multiplier_XY, float K2Node_CustomEvent_Launch_Multiplier_Z, bool CallFunc_IsValid_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, bool Temp_bool_Variable_4, bool CallFunc_Not_PreBool_ReturnValue, FName K2Node_CustomEvent_NotifyName_49, bool K2Node_CustomEvent_Show_11, uint8 K2Node_Select_Default, FHitResult CallFunc_SphereTraceSingleForObjects_OutHit, bool CallFunc_SphereTraceSingleForObjects_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, FVector CallFunc_BreakHitResult_Location, FVector CallFunc_BreakHitResult_ImpactPoint, FVector CallFunc_BreakHitResult_Normal, FVector CallFunc_BreakHitResult_ImpactNormal, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, AActor* CallFunc_BreakHitResult_HitActor, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, FName CallFunc_BreakHitResult_HitBoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_FaceIndex, FVector CallFunc_BreakHitResult_TraceStart, FVector CallFunc_BreakHitResult_TraceEnd, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_2, bool K2Node_CustomEvent_Enable, bool CallFunc_Not_PreBool_ReturnValue_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_1, AActor* K2Node_ComponentBoundEvent_OtherActor_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_2, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_1, bool K2Node_ComponentBoundEvent_bFromSweep_1, const FHitResult K2Node_ComponentBoundEvent_SweepResult_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, FVector CallFunc_GetSocketLocation_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3, ABP_Sword_C* CallFunc_FinishSpawningActor_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_EqualEqual_ByteByte_ReturnValue, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_50, float CallFunc_RandomFloatInRange_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_4, FVector CallFunc_Conv_FloatToVector_ReturnValue, bool CallFunc_IsValid_ReturnValue_4, FString K2Node_Event_Event_Name, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_1, FHitResult CallFunc_K2_SetRelativeLocationAndRotation_SweepHitResult, bool CallFunc_K2_AttachToComponent_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_4, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, int32 CallFunc_PostEventAtLocation_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_6, int32 CallFunc_PostEventAtLocation_ReturnValue_7, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, int32 CallFunc_PostEventAtLocation_ReturnValue_8, int32 CallFunc_PostEventAtLocation_ReturnValue_9, float CallFunc_BreakVector_X_2, float CallFunc_BreakVector_Y_2, float CallFunc_BreakVector_Z_2, float CallFunc_Multiply_FloatFloat_ReturnValue, FVector CallFunc_GetRightVector_ReturnValue, FVector CallFunc_GetForwardVector_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue_3, UPrimitiveComponent* K2Node_ComponentBoundEvent_HitComponent, AActor* K2Node_ComponentBoundEvent_OtherActor_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, FVector K2Node_ComponentBoundEvent_NormalImpulse, const FHitResult K2Node_ComponentBoundEvent_Hit, FVector CallFunc_Add_VectorVector_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_8, FVector CallFunc_Subtract_VectorVector_ReturnValue, FVector CallFunc_Add_VectorVector_ReturnValue_1, bool K2Node_CustomEvent_Show_10, bool K2Node_CustomEvent_UseRoom, float CallFunc_RandomFloatInRange_ReturnValue_1, FRotator CallFunc_MakeRotator_ReturnValue_1, FTransform CallFunc_MakeTransform_ReturnValue_1, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1, ADecal_Ice_C* CallFunc_FinishSpawningActor_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_10, int32 CallFunc_PostEventAtLocation_ReturnValue_11, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_9, FVector CallFunc_K2_GetActorLocation_ReturnValue_10, bool K2Node_CustomEvent_Show_9, FVector CallFunc_K2_GetComponentLocation_ReturnValue_4, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_11, int32 CallFunc_PostEventAtLocation_ReturnValue_12, AActor* CallFunc_GetOwner_ReturnValue, int32 CallFunc_PostEvent_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, float CallFunc_PlayAnimMontage_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_12, int32 CallFunc_PostEventAtLocation_ReturnValue_13, float K2Node_CustomEvent_IntensityFire, float CallFunc_Lerp_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_5, bool CallFunc_IsValid_ReturnValue_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_13, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, float Temp_float_Variable_18, float K2Node_Select_Default_1, float K2Node_Select_Default_2, float K2Node_Select_Default_3, float K2Node_Select_Default_4, bool K2Node_CustomEvent_Is_Start, float CallFunc_ApplyDamage_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, float K2Node_Select_Default_5, int32 CallFunc_PostEventAtLocation_ReturnValue_14, int32 CallFunc_PostEventAtLocation_ReturnValue_15, int32 CallFunc_PostEventAtLocation_ReturnValue_16, bool K2Node_CustomEvent_Show_8, int32 CallFunc_PostEventAtLocation_ReturnValue_17, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_6, bool CallFunc_IsValid_ReturnValue_6, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_7, bool CallFunc_IsValid_ReturnValue_7, ULevelSequence* K2Node_Select_Default_6, float CallFunc_Cutscene_OutputPin, bool CallFunc_IsRobiValid_ReturnValue, ALevelSequenceActor* CallFunc_CreateLevelSequencePlayer_OutActor, ULevelSequencePlayer* CallFunc_CreateLevelSequencePlayer_ReturnValue, float CallFunc_Cutscene_OutputPin_1, const FTransform CallFunc_GetTransform_ReturnValue, FVector K2Node_Event_New_Location, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, FVector CallFunc_Add_VectorVector_ReturnValue_2, float CallFunc_Add_FloatFloat_ReturnValue, FRotator CallFunc_MakeRotator_ReturnValue_2, UParticleSystemComponent* CallFunc_SpawnEmitterAttached_ReturnValue, float CallFunc_Cutscene_OutputPin_2, FVector CallFunc_BreakTransform_Location_1, FRotator CallFunc_BreakTransform_Rotation_1, FVector CallFunc_BreakTransform_Scale_1, bool CallFunc_K2_SetActorRotation_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable, FVector CallFunc_K2_GetComponentLocation_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_18, UPlayerController* CallFunc_GetPlayerController_ReturnValue, FRotator CallFunc_K2_GetActorRotation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_14, FHitResult CallFunc_K2_SetActorLocationAndRotation_SweepHitResult, bool CallFunc_K2_SetActorLocationAndRotation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_19, int32 CallFunc_PostEventAtLocation_ReturnValue_20, int32 CallFunc_PostEventAtLocation_ReturnValue_21, int32 CallFunc_PostEventAtLocation_ReturnValue_22, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_23, int32 CallFunc_PostEventAtLocation_ReturnValue_24, bool CallFunc_EqualEqual_IntInt_ReturnValue_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_25, int32 CallFunc_PostEventAtLocation_ReturnValue_26, bool Temp_bool_IsClosed_Variable, APawn* CallFunc_GetPlayerPawn_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, float K2Node_Event_Damage, const UDamageType* K2Node_Event_DamageType, AController* K2Node_Event_InstigatedBy, AActor* K2Node_Event_DamageCauser, TSubclassOf<UDamageType> CallFunc_GetObjectClass_ReturnValue, bool CallFunc_RecieveHit_Dead, bool CallFunc_EqualEqual_ClassClass_ReturnValue, bool K2Node_CustomEvent_Show_7, UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, ULord_2_Skeleton_AnimBlueprint_C* K2Node_DynamicCast_AsLord_2_Skeleton_Anim_Blueprint, bool K2Node_DynamicCast_bSuccess, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_15, int32 CallFunc_PostEventAtLocation_ReturnValue_27, int32 CallFunc_PostEventAtLocation_ReturnValue_28, bool K2Node_CustomEvent_Is_Left, bool CallFunc_IsRobiValid_ReturnValue_1, FVector K2Node_Select_Default_7, float CallFunc_NormalizeToRange_ReturnValue, float Temp_float_Variable_19, float K2Node_Select_Default_8, bool K2Node_SwitchInteger_CmpSuccess_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_8, bool CallFunc_IsValid_ReturnValue_8, FVector CallFunc_K2_GetActorLocation_ReturnValue_16, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, float K2Node_Select_Default_9, bool CallFunc_Less_FloatFloat_ReturnValue, bool Temp_bool_Variable_5, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, float K2Node_Select_Default_10, float CallFunc_Lerp_ReturnValue_1, bool K2Node_Event_CheckPlayerIsDead, FVector CallFunc_Conv_FloatToVector_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue_3, FVector CallFunc_GetRightVector_ReturnValue_1, FVector CallFunc_Add_VectorVector_ReturnValue_3, FVector CallFunc_Multiply_VectorFloat_ReturnValue_2, FRotator CallFunc_Conv_VectorToRotator_ReturnValue, float CallFunc_BreakRotator_Roll_1, float CallFunc_BreakRotator_Pitch_1, float CallFunc_BreakRotator_Yaw_1, FRotator CallFunc_MakeRotator_ReturnValue_3, float CallFunc_PlayAnimMontage_ReturnValue_2, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_29, int32 CallFunc_PostEventAtLocation_ReturnValue_30, FVector K2Node_CustomEvent_Location, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_3, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_9, bool K2Node_CustomEvent_Show_6, float CallFunc_SelectFloat_ReturnValue, bool CallFunc_IsValid_ReturnValue_9, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, bool K2Node_Event_Move_1, bool K2Node_Event_Move, APawn* CallFunc_GetPlayerPawn_ReturnValue_2, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_2, FVector CallFunc_GetSocketLocation_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_4, bool Temp_bool_Variable_6, USphereComponent* K2Node_Select_Default_11, APawn* CallFunc_GetPlayerPawn_ReturnValue_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_17, bool K2Node_SwitchInteger_CmpSuccess_2, ABP_BossRoom_2_C* K2Node_DynamicCast_AsBP_Boss_Room_2, bool K2Node_DynamicCast_bSuccess_1, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_1, bool K2Node_CustomEvent_Show_5, bool K2Node_CustomEvent_Instant, bool K2Node_CustomEvent_Delay, float K2Node_CustomEvent_Delay_Time, float K2Node_CustomEvent_Play_Rate, bool K2Node_CustomEvent_Show_4, float CallFunc_PlayAnimMontage_ReturnValue_3, bool Temp_bool_Variable_7, bool CallFunc_Not_PreBool_ReturnValue_2, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_2, bool K2Node_CustomEvent_Show_3, FVector CallFunc_GetSocketLocation_ReturnValue_2, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_5, FVector CallFunc_GetSocketLocation_ReturnValue_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_18, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_6, int32 CallFunc_PostEventAtLocation_ReturnValue_31, bool Temp_bool_Variable_8, UStaticMeshComponent* K2Node_Select_Default_12, bool K2Node_CustomEvent_Show_2, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_3, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_4, bool CallFunc_Not_PreBool_ReturnValue_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_19, int32 CallFunc_PostEventAtLocation_ReturnValue_32, bool CallFunc_Not_PreBool_ReturnValue_4, bool CallFunc_Not_PreBool_ReturnValue_5, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_33, FVector CallFunc_K2_GetActorLocation_ReturnValue_20, int32 CallFunc_PostEventAtLocation_ReturnValue_34, FVector CallFunc_K2_GetActorLocation_ReturnValue_21, int32 CallFunc_PostEventAtLocation_ReturnValue_35, bool K2Node_Event_Moving, uint8 K2Node_Select_Default_13, bool K2Node_CustomEvent_Show_1, FString CallFunc_CheckState_Same_ID, bool CallFunc_CheckState_Used, int32 CallFunc_PostEventAtLocation_ReturnValue_36, int32 CallFunc_PostEventAtLocation_ReturnValue_37, int32 Temp_int_Variable_7, bool K2Node_CustomEvent_Show, UAnimMontage* CallFunc_GetCurrentMontage_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_2, uint8 CallFunc_GetCollisionEnabled_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_22, int32 CallFunc_PostEventAtLocation_ReturnValue_38);
    void FaseChange__DelegateSignature(int32 Fase);
}

#endif
