#ifndef UE4SS_SDK_BP_Boo_HPP
#define UE4SS_SDK_BP_Boo_HPP

class ABP_Boo_C : UEnemy_Character_Parent_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    USceneComponent* ScenePOI;
    UArrowComponent* Arrow_Ground;
    UCapsuleComponent* Collider;
    UParticleSystemComponent* P_Scream;
    UParticleSystemComponent* P_GroundMove;
    UAkComponent* Ak_Out;
    UAkComponent* Ak_Enter;
    UParticleSystemComponent* EnemyLens_VFX;
    float Timeline_2_Size_AAA03EE243081FDAF4F21BA55DB9EC8D;
    TEnumAsByte<ETimelineDirection::Type> Timeline_2__Direction_AAA03EE243081FDAF4F21BA55DB9EC8D;
    UTimelineComponent* Timeline_2;
    float Shadow_Size_975BEE1A4A3501E6A5CC60B6835EDDC4;
    TEnumAsByte<ETimelineDirection::Type> Shadow__Direction_975BEE1A4A3501E6A5CC60B6835EDDC4;
    UTimelineComponent* Shadow;
    float Damage Radius;
    FString ID;
    int32 Max Minions;
    int32 Current Minions;
    bool Changing Fase;
    bool Has Received Damage;
    float Offset Decal;
    UBoo_SkelMesh_Skeleton_AnimBlueprint_C* Anim BP;
    bool Can Dig;
    UMaterialInstanceDynamic* Mat Eye;
    float DelayStartIntroMusic;
    UMaterialInstanceDynamic* ShadowMat;
    TArray<AActor*> SpawnPoints;

    void Shadow__FinishedFunc();
    void Shadow__UpdateFunc();
    void Timeline_2__FinishedFunc();
    void Timeline_2__UpdateFunc();
    void OnNotifyEnd_4165A5E642FD3D5BFCC9E0A7F7346CD4(FName NotifyName);
    void OnNotifyBegin_4165A5E642FD3D5BFCC9E0A7F7346CD4(FName NotifyName);
    void OnInterrupted_4165A5E642FD3D5BFCC9E0A7F7346CD4(FName NotifyName);
    void OnBlendOut_4165A5E642FD3D5BFCC9E0A7F7346CD4(FName NotifyName);
    void OnCompleted_4165A5E642FD3D5BFCC9E0A7F7346CD4(FName NotifyName);
    void OnNotifyEnd_11B79B5A423562C9135D61A17D6210AB(FName NotifyName);
    void OnNotifyBegin_11B79B5A423562C9135D61A17D6210AB(FName NotifyName);
    void OnInterrupted_11B79B5A423562C9135D61A17D6210AB(FName NotifyName);
    void OnBlendOut_11B79B5A423562C9135D61A17D6210AB(FName NotifyName);
    void OnCompleted_11B79B5A423562C9135D61A17D6210AB(FName NotifyName);
    void OnNotifyEnd_50BA343D406CEC1889FCF39F747AE6BF(FName NotifyName);
    void OnNotifyBegin_50BA343D406CEC1889FCF39F747AE6BF(FName NotifyName);
    void OnInterrupted_50BA343D406CEC1889FCF39F747AE6BF(FName NotifyName);
    void OnBlendOut_50BA343D406CEC1889FCF39F747AE6BF(FName NotifyName);
    void OnCompleted_50BA343D406CEC1889FCF39F747AE6BF(FName NotifyName);
    void OnNotifyEnd_013DFF724D85CDC52B237787F3D39CA7(FName NotifyName);
    void OnNotifyBegin_013DFF724D85CDC52B237787F3D39CA7(FName NotifyName);
    void OnInterrupted_013DFF724D85CDC52B237787F3D39CA7(FName NotifyName);
    void OnBlendOut_013DFF724D85CDC52B237787F3D39CA7(FName NotifyName);
    void OnCompleted_013DFF724D85CDC52B237787F3D39CA7(FName NotifyName);
    void OnNotifyEnd_98B52F6E483CCBC9FA53C8AA83724CC4(FName NotifyName);
    void OnNotifyBegin_98B52F6E483CCBC9FA53C8AA83724CC4(FName NotifyName);
    void OnInterrupted_98B52F6E483CCBC9FA53C8AA83724CC4(FName NotifyName);
    void OnBlendOut_98B52F6E483CCBC9FA53C8AA83724CC4(FName NotifyName);
    void OnCompleted_98B52F6E483CCBC9FA53C8AA83724CC4(FName NotifyName);
    void OnNotifyEnd_8564317D42146F40F489599BAFFA52F9(FName NotifyName);
    void OnNotifyBegin_8564317D42146F40F489599BAFFA52F9(FName NotifyName);
    void OnInterrupted_8564317D42146F40F489599BAFFA52F9(FName NotifyName);
    void OnBlendOut_8564317D42146F40F489599BAFFA52F9(FName NotifyName);
    void OnCompleted_8564317D42146F40F489599BAFFA52F9(FName NotifyName);
    void OnNotifyEnd_A902542E47C7B610BF612EA9A184C5F7(FName NotifyName);
    void OnNotifyBegin_A902542E47C7B610BF612EA9A184C5F7(FName NotifyName);
    void OnInterrupted_A902542E47C7B610BF612EA9A184C5F7(FName NotifyName);
    void OnBlendOut_A902542E47C7B610BF612EA9A184C5F7(FName NotifyName);
    void OnCompleted_A902542E47C7B610BF612EA9A184C5F7(FName NotifyName);
    void StartBoss();
    void EndBoss();
    void Boss Appear();
    void Boss Desappear();
    void VFX Ground Splash(bool Shake);
    void Replace by Statue(float Delay);
    void Attack01(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Remove Minion();
    void Teleport to Random Point();
    void Spawn Wave();
    void Spawn Baby Boo();
    void Call Event(FString Event Name);
    void Call VFX Pop();
    void Attack02(int32 Count, int32 Max Count, bool Use Custom Counter);
    void VFX Decal();
    void VFX Body Particle(bool Show);
    void Call Stop VFX Body();
    void Attack03(int32 Count, int32 Max Count, bool Use Custom Counter);
    void VFX Scream();
    void VFX Ground Pop(bool Shake);
    void Attack04(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Attack05(int32 Count, int32 Max Count, bool Use Custom Counter);
    void VFX Ground Move(bool Show);
    void ReceiveAnyDamage(float Damage, const UDamageType* DamageType, AController* InstigatedBy, AActor* DamageCauser);
    void ReceiveBeginPlay();
    void ReceiveHit(UPrimitiveComponent* MyComp, AActor* Other, UPrimitiveComponent* OtherComp, bool bSelfMoved, FVector HitLocation, FVector HitNormal, FVector NormalImpulse, const FHitResult& Hit);
    void Restart();
    void On Landed Extra();
    void TeleportOut();
    void TeleportIn();
    void Fase Change();
    void On Player Die();
    void ScaleShadow(bool Big);
    void ShadowBurst();
    void GA SendEvent();
    void ExecuteUbergraph_BP_Boo(int32 EntryPoint, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FName K2Node_CustomEvent_NotifyName_29, FName K2Node_CustomEvent_NotifyName_28, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FName K2Node_CustomEvent_NotifyName_27, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FName K2Node_CustomEvent_NotifyName_26, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, FName K2Node_CustomEvent_NotifyName_25, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, FName Temp_name_Variable, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable, FName Temp_name_Variable_1, bool Temp_bool_Variable, Die__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, const TArray<AActor*>& Temp_object_Variable, FName K2Node_CustomEvent_NotifyName_24, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, FName K2Node_CustomEvent_NotifyName_23, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, FName K2Node_CustomEvent_NotifyName_22, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, FName K2Node_CustomEvent_NotifyName_21, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, FName K2Node_CustomEvent_NotifyName_20, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, FName Temp_name_Variable_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_11, FName K2Node_CustomEvent_NotifyName_19, FName K2Node_CustomEvent_NotifyName_18, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_12, FName K2Node_CustomEvent_NotifyName_17, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_13, FName K2Node_CustomEvent_NotifyName_16, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_14, FName K2Node_CustomEvent_NotifyName_15, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_15, FName Temp_name_Variable_3, int32 Temp_int_Variable, float Temp_float_Variable, float Temp_float_Variable_1, float Temp_float_Variable_2, bool Temp_bool_Variable_1, UAnimMontage* Temp_object_Variable_1, UAnimMontage* Temp_object_Variable_2, bool Temp_bool_Variable_2, bool Temp_bool_Variable_3, UAnimMontage* Temp_object_Variable_3, UAnimMontage* Temp_object_Variable_4, FName K2Node_CustomEvent_NotifyName_14, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_16, FName K2Node_CustomEvent_NotifyName_13, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_17, FName K2Node_CustomEvent_NotifyName_12, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_18, FName K2Node_CustomEvent_NotifyName_11, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_19, FName K2Node_CustomEvent_NotifyName_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_20, FName Temp_name_Variable_4, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_21, FName K2Node_CustomEvent_NotifyName_9, FName K2Node_CustomEvent_NotifyName_8, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_22, FName K2Node_CustomEvent_NotifyName_7, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_23, FName K2Node_CustomEvent_NotifyName_6, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_24, FName K2Node_CustomEvent_NotifyName_5, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_25, FName Temp_name_Variable_5, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_1, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_1, const TArray<AActor*>& Temp_object_Variable_5, bool Temp_bool_Variable_4, uint8 Temp_byte_Variable_2, uint8 Temp_byte_Variable_3, bool Temp_bool_Variable_5, float Temp_float_Variable_3, FString CallFunc_Conv_IntToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_26, FName K2Node_CustomEvent_NotifyName_4, FName K2Node_CustomEvent_NotifyName_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_27, FName K2Node_CustomEvent_NotifyName_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_28, FName K2Node_CustomEvent_NotifyName_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_29, FName K2Node_CustomEvent_NotifyName, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_30, FName Temp_name_Variable_6, int32 Temp_int_Variable_1, float Temp_float_Variable_4, float Temp_float_Variable_5, float Temp_float_Variable_6, float CallFunc_Lerp_ReturnValue, int32 Temp_int_Variable_2, float Temp_float_Variable_7, float Temp_float_Variable_8, float Temp_float_Variable_9, bool K2Node_CustomEvent_Shake_1, FVector CallFunc_K2_GetActorLocation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_2, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, bool CallFunc_IsValid_ReturnValue, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_31, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_3, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1, UAIController* CallFunc_GetAIController_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, float K2Node_Event_Delay, APawn* CallFunc_GetPlayerPawn_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_4, int32 CallFunc_PostEventAtLocation_ReturnValue_5, int32 K2Node_Event_Count_4, int32 K2Node_Event_Max_Count_4, bool K2Node_Event_Use_Custom_Counter_4, float CallFunc_RandomFloatInRange_ReturnValue, FVector CallFunc_Conv_FloatToVector_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_6, bool CallFunc_IsRobiValid_ReturnValue, int32 CallFunc_PostAssociatedAkEvent_ReturnValue, FName K2Node_CustomEvent_NotifyName_33, float CallFunc_Multiply_FloatFloat_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue_2, FRotator CallFunc_K2_GetActorRotation_ReturnValue, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, FVector CallFunc_RandomUnitVector_ReturnValue, float CallFunc_RandomFloatInRange_ReturnValue_3, FVector CallFunc_Multiply_VectorFloat_ReturnValue, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, FVector CallFunc_MakeVector_ReturnValue, FVector CallFunc_Add_VectorVector_ReturnValue, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult, bool CallFunc_K2_SetActorLocation_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, float CallFunc_Add_FloatFloat_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue_1, FString K2Node_Event_Event_Name, FTimerHandle CallFunc_K2_SetTimer_ReturnValue, int32 K2Node_Event_Count_3, int32 K2Node_Event_Max_Count_3, bool K2Node_Event_Use_Custom_Counter_3, float CallFunc_RandomFloatInRange_ReturnValue_4, float CallFunc_Add_FloatFloat_ReturnValue_2, bool K2Node_CustomEvent_Show_1, FRotator CallFunc_MakeRotator_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, int32 K2Node_Event_Count_2, int32 K2Node_Event_Max_Count_2, bool K2Node_Event_Use_Custom_Counter_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_32, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, FVector CallFunc_Subtract_VectorVector_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, AWave_C* CallFunc_FinishSpawningActor_ReturnValue, bool K2Node_CustomEvent_Shake, int32 K2Node_Event_Count_1, int32 K2Node_Event_Max_Count_1, bool K2Node_Event_Use_Custom_Counter_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, const TArray<uint8>& K2Node_MakeArray_Array, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, FVector CallFunc_GetActorForwardVector_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue_1, FVector CallFunc_Add_VectorVector_ReturnValue_1, uint8 K2Node_Select_Default, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2, FHitResult CallFunc_SphereTraceSingleForObjects_OutHit, bool CallFunc_SphereTraceSingleForObjects_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, FVector CallFunc_BreakHitResult_Location, FVector CallFunc_BreakHitResult_ImpactPoint, FVector CallFunc_BreakHitResult_Normal, FVector CallFunc_BreakHitResult_ImpactNormal, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, AActor* CallFunc_BreakHitResult_HitActor, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, FName CallFunc_BreakHitResult_HitBoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_FaceIndex, FVector CallFunc_BreakHitResult_TraceStart, FVector CallFunc_BreakHitResult_TraceEnd, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_1, float CallFunc_ApplyDamage_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, int32 K2Node_Event_Count, int32 K2Node_Event_Max_Count, bool K2Node_Event_Use_Custom_Counter, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, int32 CallFunc_PostEventAtLocation_ReturnValue_7, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_8, bool K2Node_CustomEvent_Show, FName K2Node_CustomEvent_NotifyName_34, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue, float K2Node_Select_Default_1, int32 CallFunc_Array_LastIndex_ReturnValue, float K2Node_Event_Damage, const UDamageType* K2Node_Event_DamageType, AController* K2Node_Event_InstigatedBy, AActor* K2Node_Event_DamageCauser, TSubclassOf<UDamageType> CallFunc_GetObjectClass_ReturnValue, bool CallFunc_RecieveHit_Dead, bool CallFunc_EqualEqual_ClassClass_ReturnValue, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_33, UPrimitiveComponent* K2Node_Event_MyComp, AActor* K2Node_Event_Other, UPrimitiveComponent* K2Node_Event_OtherComp, bool K2Node_Event_bSelfMoved, FVector K2Node_Event_HitLocation, FVector K2Node_Event_HitNormal, FVector K2Node_Event_NormalImpulse, const FHitResult K2Node_Event_Hit, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, int32 Temp_int_Variable_3, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_3, AActor* CallFunc_Array_Get_Item, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, bool CallFunc_LessEqual_IntInt_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue_1, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, UBP_BabyBoo_C* CallFunc_FinishSpawningActor_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_8, int32 CallFunc_PostEventAtLocation_ReturnValue_9, uint8 CallFunc_MakeLiteralByte_ReturnValue, FName K2Node_CustomEvent_NotifyName_30, FVector CallFunc_K2_GetActorLocation_ReturnValue_9, const TArray<uint8>& K2Node_MakeArray_Array_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_34, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_4, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_5, bool CallFunc_IsValid_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_5, TArray<FName>& K2Node_MakeArray_Array_2, TArray<FName>& K2Node_MakeArray_Array_3, bool CallFunc_IsRobiValid_ReturnValue_2, int32 CallFunc_PostAssociatedAkEvent_ReturnValue_1, int32 Temp_int_Variable_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, uint8 K2Node_Select_Default_2, FHitResult CallFunc_SphereTraceSingleForObjects_OutHit_1, bool CallFunc_SphereTraceSingleForObjects_ReturnValue_1, bool CallFunc_BreakHitResult_bBlockingHit_1, bool CallFunc_BreakHitResult_bInitialOverlap_1, float CallFunc_BreakHitResult_Time_1, float CallFunc_BreakHitResult_Distance_1, FVector CallFunc_BreakHitResult_Location_1, FVector CallFunc_BreakHitResult_ImpactPoint_1, FVector CallFunc_BreakHitResult_Normal_1, FVector CallFunc_BreakHitResult_ImpactNormal_1, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat_1, AActor* CallFunc_BreakHitResult_HitActor_1, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent_1, FName CallFunc_BreakHitResult_HitBoneName_1, int32 CallFunc_BreakHitResult_HitItem_1, int32 CallFunc_BreakHitResult_FaceIndex_1, FVector CallFunc_BreakHitResult_TraceStart_1, FVector CallFunc_BreakHitResult_TraceEnd_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue_3, float CallFunc_ApplyDamage_ReturnValue_1, float K2Node_Select_Default_3, int32 CallFunc_Add_IntInt_ReturnValue_2, bool K2Node_SwitchInteger_CmpSuccess, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_6, bool CallFunc_IsValid_ReturnValue_6, int32 CallFunc_PostEventAtLocation_ReturnValue_10, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, float K2Node_Select_Default_4, FName K2Node_CustomEvent_NotifyName_31, bool CallFunc_Less_FloatFloat_ReturnValue, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_1, UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, UBoo_SkelMesh_Skeleton_AnimBlueprint_C* K2Node_DynamicCast_AsBoo_Skel_Mesh_Skeleton_Anim_Blueprint, bool K2Node_DynamicCast_bSuccess, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_2, bool Temp_bool_Variable_6, UAnimMontage* K2Node_Select_Default_5, bool CallFunc_Not_PreBool_ReturnValue_1, UAnimMontage* K2Node_Select_Default_6, UAnimMontage* K2Node_Select_Default_7, float CallFunc_PlayAnimMontage_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_11, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_35, int32 CallFunc_PostEventAtLocation_ReturnValue_12, FString CallFunc_CheckState_Same_ID, bool CallFunc_CheckState_Used, bool K2Node_CustomEvent_Big, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, FString CallFunc_Conv_BoolToString_ReturnValue, FName K2Node_CustomEvent_NotifyName_32, int32 Temp_int_Variable_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_11, int32 CallFunc_PostEventAtLocation_ReturnValue_13, float K2Node_Select_Default_8);
}

#endif
