#ifndef UE4SS_SDK_BP_BossDoor_DarkVon_HPP
#define UE4SS_SDK_BP_BossDoor_DarkVon_HPP

class ABP_BossDoor_DarkVon_C : AActor
{
    FPointerToUberGraphFrame UberGraphFrame;
    UAkComponent* Ak;
    UArrowComponent* PlayerDirection;
    UBillboardComponent* Ghost Location;
    UCameraComponent* Camera;
    UBoxComponent* Box;
    USceneComponent* DefaultSceneRoot;
    float DrawTransition_Draw_7B88C04841C72160DD406B8DF898678F;
    TEnumAsByte<ETimelineDirection::Type> DrawTransition__Direction_7B88C04841C72160DD406B8DF898678F;
    UTimelineComponent* DrawTransition;
    bool Debug Instant Combat;
    int32 Debug Fase;
    bool Debug Start Cutscene;
    ULevelSequence* Sequence Start;
    ULevelSequence* Sequence End;
    AEnemy_Character_Parent_C* Boss DarkVon;
    APlayer_Character_BP_C* Player;
    FText Boss Name;
    FText Boss Subtitle;
    ULevelSequencePlayer* Current Sequence;
    bool CanSkipCutscene;
    ANPCBound_C* NPCBound;
    ULevelSequencePlayer* Last Cutscene;
    USkipCutscene_Action_UI_C* SkipCutsceneUI;
    UNPC_Intro_C* NPCIntro;
    FString ID Boss SkipCutscene;
    UVonBetray_Cutscene_UI_C* UI_Cutscene;
    int32 DebugCounter;
    int32 PreBetrayalMusic;
    ABP_BossRoom_DarkVon_C* Boss Room;
    ABP_Lighting_C* Lightning;
    ABP_Rain_C* Rain;
    UAnimMontage* LastPlayerMontage;
    AActor* Target;
    ADarkVon_Cinematics_C* DarkVon cinematics;

    void DrawTransition__FinishedFunc();
    void DrawTransition__UpdateFunc();
    void OnNotifyEnd_948D199945EF208A626515924D28450C(FName NotifyName);
    void OnNotifyBegin_948D199945EF208A626515924D28450C(FName NotifyName);
    void OnInterrupted_948D199945EF208A626515924D28450C(FName NotifyName);
    void OnBlendOut_948D199945EF208A626515924D28450C(FName NotifyName);
    void OnCompleted_948D199945EF208A626515924D28450C(FName NotifyName);
    void OnNotifyEnd_9A1B28F14CE027CE224749AED09AF0D3(FName NotifyName);
    void OnNotifyBegin_9A1B28F14CE027CE224749AED09AF0D3(FName NotifyName);
    void OnInterrupted_9A1B28F14CE027CE224749AED09AF0D3(FName NotifyName);
    void OnBlendOut_9A1B28F14CE027CE224749AED09AF0D3(FName NotifyName);
    void OnCompleted_9A1B28F14CE027CE224749AED09AF0D3(FName NotifyName);
    void OnNotifyEnd_0C00C8BC4F3017DEF910FA8678FC60EE(FName NotifyName);
    void OnNotifyBegin_0C00C8BC4F3017DEF910FA8678FC60EE(FName NotifyName);
    void OnInterrupted_0C00C8BC4F3017DEF910FA8678FC60EE(FName NotifyName);
    void OnBlendOut_0C00C8BC4F3017DEF910FA8678FC60EE(FName NotifyName);
    void OnCompleted_0C00C8BC4F3017DEF910FA8678FC60EE(FName NotifyName);
    void OnNotifyEnd_FBD7194D43F5143122B18895B8F92DDE(FName NotifyName);
    void OnNotifyBegin_FBD7194D43F5143122B18895B8F92DDE(FName NotifyName);
    void OnInterrupted_FBD7194D43F5143122B18895B8F92DDE(FName NotifyName);
    void OnBlendOut_FBD7194D43F5143122B18895B8F92DDE(FName NotifyName);
    void OnCompleted_FBD7194D43F5143122B18895B8F92DDE(FName NotifyName);
    void OnNotifyEnd_7D4BD9A74679FD94639A4EAA98B9AF16(FName NotifyName);
    void OnNotifyBegin_7D4BD9A74679FD94639A4EAA98B9AF16(FName NotifyName);
    void OnInterrupted_7D4BD9A74679FD94639A4EAA98B9AF16(FName NotifyName);
    void OnBlendOut_7D4BD9A74679FD94639A4EAA98B9AF16(FName NotifyName);
    void OnCompleted_7D4BD9A74679FD94639A4EAA98B9AF16(FName NotifyName);
    void OnNotifyEnd_4472E38B47836939ECB92EB26FD13D04(FName NotifyName);
    void OnNotifyBegin_4472E38B47836939ECB92EB26FD13D04(FName NotifyName);
    void OnInterrupted_4472E38B47836939ECB92EB26FD13D04(FName NotifyName);
    void OnBlendOut_4472E38B47836939ECB92EB26FD13D04(FName NotifyName);
    void OnCompleted_4472E38B47836939ECB92EB26FD13D04(FName NotifyName);
    void Player Anim Cutscene End();
    void TX1 END();
    void TX2 END();
    void CustomEvent_2();
    void TX3 END();
    void UmbraHeroic2();
    void Show Sealed Land End();
    void UmbraLookPillars();
    void Umbra180_Betray();
    void StartUI();
    void TX2();
    void endDialogue();
    void TX3();
    void TX4();
    void TX5();
    void TX6();
    void TX7();
    void TX8();
    void TX9();
    void TX10();
    void TX11();
    void FadeTransition();
    void TX2B();
    void TX1();
    void Boss Title();
    void Remove Title();
    void Draws Transition ();
    void UmbraLIstenVon();
    void TX3B();
    void StopIdleCam();
    void UmbraAfraid_1();
    void UmbraAfraid_2();
    void UmbraAfraid_3();
    void Dark_Von_End_Transformation();
    void Start_Chimes();
    void Stop_Chimes();
    void FadeWhiteIn();
    void FadeWhiteOut();
    void StartTaleCutscene();
    void EndTaleCutscene();
    void WhooshIn();
    void WhooshOut();
    void FadeToBlack();
    void PlayPreFightDrone();
    void StopPreFightDrone();
    void PlayFlapsAndRocks();
    void FadeOutFinal();
    void DarkVonDeathDisolve();
    void ReceiveBeginPlay();
    void Reset Door();
    void Kill Von();
    void Relocate Player();
    void Play DarkVon Cutscene();
    void Resume Start();
    void BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void Resume End();
    void SkipCutscene();
    void Resume Last Cutscene Von();
    void Instant Combat();
    void Resume Start Cutscene();
    void SkipCutscene Controller(bool Spawn);
    void DebugFase4(int32 Debug Fase);
    void ShowCastle();
    void Relocate Player to Target();
    void ExecuteUbergraph_BP_BossDoor_DarkVon(int32 EntryPoint, FName Temp_name_Variable, UVonBetray_Cutscene_UI_C* CallFunc_Create_ReturnValue, Finished__DelegateSignature K2Node_CreateDelegate_OutputDelegate, UNPC_Intro_C* CallFunc_Create_ReturnValue_1, Finished__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FName K2Node_CustomEvent_NotifyName_19, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FName K2Node_CustomEvent_NotifyName_18, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, FName K2Node_CustomEvent_NotifyName_17, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, FName K2Node_CustomEvent_NotifyName_16, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, FName K2Node_CustomEvent_NotifyName_15, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, FName Temp_name_Variable_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, FName K2Node_CustomEvent_NotifyName_14, FName K2Node_CustomEvent_NotifyName_13, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, FName K2Node_CustomEvent_NotifyName_12, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, FName K2Node_CustomEvent_NotifyName_11, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, FName K2Node_CustomEvent_NotifyName_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_11, FName Temp_name_Variable_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_12, FName K2Node_CustomEvent_NotifyName_9, FName K2Node_CustomEvent_NotifyName_8, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_13, FName K2Node_CustomEvent_NotifyName_7, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_14, FName K2Node_CustomEvent_NotifyName_6, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_15, FName K2Node_CustomEvent_NotifyName_5, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_16, FName Temp_name_Variable_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_17, FName K2Node_CustomEvent_NotifyName_4, FName K2Node_CustomEvent_NotifyName_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_18, FName K2Node_CustomEvent_NotifyName_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_19, FName K2Node_CustomEvent_NotifyName_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_20, FName K2Node_CustomEvent_NotifyName, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_21, FName Temp_name_Variable_4, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_1, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_1, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_2, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_2, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_3, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_3, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_4, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_4, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_5, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_5, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_6, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_6, Die__DelegateSignature K2Node_CreateDelegate_OutputDelegate_22, Die__DelegateSignature K2Node_CreateDelegate_OutputDelegate_23, bool CallFunc_IsValid_ReturnValue, OnMovieSceneSequencePlayerEvent__DelegateSignature K2Node_CreateDelegate_OutputDelegate_24, ALevelSequenceActor* CallFunc_CreateLevelSequencePlayer_OutActor, ULevelSequencePlayer* CallFunc_CreateLevelSequencePlayer_ReturnValue, OnMovieSceneSequencePlayerEvent__DelegateSignature K2Node_CreateDelegate_OutputDelegate_25, SkipCutscene__DelegateSignature K2Node_CreateDelegate_OutputDelegate_26, USkipCutscene_Action_UI_C* CallFunc_Create_ReturnValue_2, FRotator CallFunc_MakeRotator_ReturnValue, FRotator CallFunc_MakeRotator_ReturnValue_1, bool Temp_bool_Has_Been_Initd_Variable, bool CallFunc_IsValid_ReturnValue_1, bool Temp_bool_Variable, bool CallFunc_Not_PreBool_ReturnValue, const TArray<FText>& K2Node_MakeArray_Array, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_1, const TArray<FText>& K2Node_MakeArray_Array_2, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_3, FText CallFunc_MakeLiteralText_ReturnValue, bool K2Node_SwitchInteger_CmpSuccess, const TArray<FText>& K2Node_MakeArray_Array_4, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_5, bool Temp_bool_IsClosed_Variable, bool CallFunc_IsRobiValid_ReturnValue, ULevelStreaming* CallFunc_GetStreamingLevel_ReturnValue, FName Temp_name_Variable_5, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_3, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_5, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_6, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_5, bool CallFunc_IsValid_ReturnValue_7, FName K2Node_CustomEvent_NotifyName_25, const TArray<FText>& K2Node_MakeArray_Array_6, bool CallFunc_IsRobiValid_ReturnValue_1, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_7, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_27, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_8, FText CallFunc_MakeLiteralText_ReturnValue_1, bool K2Node_SwitchInteger_CmpSuccess_1, FName K2Node_CustomEvent_NotifyName_20, const TArray<FText>& K2Node_MakeArray_Array_9, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_10, const TArray<FText>& K2Node_MakeArray_Array_11, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_12, APawn* CallFunc_GetPlayerPawn_ReturnValue, const TArray<FText>& K2Node_MakeArray_Array_13, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_14, const TArray<FText>& K2Node_MakeArray_Array_15, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_16, const TArray<FText>& K2Node_MakeArray_Array_17, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_18, const TArray<FText>& K2Node_MakeArray_Array_19, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_20, const TArray<FText>& K2Node_MakeArray_Array_21, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_22, const TArray<FText>& K2Node_MakeArray_Array_23, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_24, FName K2Node_CustomEvent_NotifyName_26, bool Temp_bool_Has_Been_Initd_Variable_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_28, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_29, const TArray<FText>& K2Node_MakeArray_Array_25, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_26, FName K2Node_CustomEvent_NotifyName_21, bool Temp_bool_IsClosed_Variable_1, bool CallFunc_IsRobiValid_ReturnValue_2, bool CallFunc_IsInViewport_ReturnValue, FName K2Node_CustomEvent_NotifyName_27, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_27, const TArray<FText>& K2Node_MakeArray_Array_28, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_30, int32 CallFunc_Add_IntInt_ReturnValue, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, FName K2Node_CustomEvent_NotifyName_28, const TArray<FText>& K2Node_MakeArray_Array_29, int32 CallFunc_PostEventAtLocation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_6, bool CallFunc_EqualEqual_IntInt_ReturnValue_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_7, int32 CallFunc_PostEventAtLocation_ReturnValue_8, int32 CallFunc_PostEventAtLocation_ReturnValue_9, bool K2Node_MultiGate_FirstRun, int32 K2Node_MultiGate_Data, bool K2Node_MultiGate_ScratchBool, int32 K2Node_MultiGate_ScratchIndex, bool K2Node_MultiGate_1_FirstRun, int32 K2Node_MultiGate_1_Data, int32 CallFunc_PostEventAtLocation_ReturnValue_10, int32 CallFunc_PostEventAtLocation_ReturnValue_11, bool CallFunc_EqualEqual_IntInt_ReturnValue_6, bool CallFunc_EqualEqual_IntInt_ReturnValue_7, int32 CallFunc_PostEventAtLocation_ReturnValue_12, int32 CallFunc_PostEventAtLocation_ReturnValue_13, bool CallFunc_EqualEqual_IntInt_ReturnValue_8, bool CallFunc_EqualEqual_IntInt_ReturnValue_9, int32 CallFunc_PostEventAtLocation_ReturnValue_14, int32 CallFunc_PostEventAtLocation_ReturnValue_15, int32 CallFunc_PostEventAtLocation_ReturnValue_16, bool CallFunc_EqualEqual_IntInt_ReturnValue_10, bool CallFunc_EqualEqual_IntInt_ReturnValue_11, int32 CallFunc_PostEventAtLocation_ReturnValue_17, int32 CallFunc_PostEventAtLocation_ReturnValue_18, int32 CallFunc_PostAkEvent_ReturnValue, int32 CallFunc_PostEvent_ReturnValue, int32 CallFunc_PostEvent_ReturnValue_1, int32 CallFunc_PostEvent_ReturnValue_2, int32 CallFunc_PostEvent_ReturnValue_3, int32 CallFunc_PostAkEvent_ReturnValue_1, int32 CallFunc_PostAkEvent_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_12, bool CallFunc_EqualEqual_IntInt_ReturnValue_13, int32 CallFunc_PostEventAtLocation_ReturnValue_19, int32 CallFunc_PostEventAtLocation_ReturnValue_20, bool Temp_bool_Variable_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_31, bool CallFunc_Not_PreBool_ReturnValue_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_32, FName K2Node_CustomEvent_NotifyName_29, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_33, ALevelSequenceActor* CallFunc_CreateLevelSequencePlayer_OutActor_1, ULevelSequencePlayer* CallFunc_CreateLevelSequencePlayer_ReturnValue_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, float CallFunc_Cutscene_OutputPin, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, APawn* CallFunc_GetPlayerPawn_ReturnValue_2, bool Temp_bool_Variable_2, UPlayer_Character_BP_C* K2Node_DynamicCast_AsPlayer_Character_BP, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Not_PreBool_ReturnValue_2, UPlayerController* CallFunc_GetPlayerController_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_21, int32 CallFunc_PostEventAtLocation_ReturnValue_22, bool CallFunc_NotEqual_IntInt_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_23, bool K2Node_CustomEvent_Spawn, Finished__DelegateSignature K2Node_CreateDelegate_OutputDelegate_34, bool CallFunc_IsRobiValid_ReturnValue_3, bool CallFunc_IsRobiValid_ReturnValue_4, UPlayerController* CallFunc_GetPlayerController_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_24, bool CallFunc_IsValid_ReturnValue_8, FString CallFunc_CheckState_Same_ID, bool CallFunc_CheckState_Used, const FTransform CallFunc_GetTransform_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, ANPCBound_C* CallFunc_FinishSpawningActor_ReturnValue, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue_2, FRotator CallFunc_K2_GetComponentRotation_ReturnValue, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, FVector CallFunc_K2_GetComponentLocation_ReturnValue, FRotator CallFunc_MakeRotator_ReturnValue_2, FRotator CallFunc_MakeRotator_ReturnValue_3, FHitResult CallFunc_K2_SetActorLocationAndRotation_SweepHitResult, bool CallFunc_K2_SetActorLocationAndRotation_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, FName K2Node_CustomEvent_NotifyName_22, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_35, FName K2Node_CustomEvent_NotifyName_23, int32 K2Node_CustomEvent_Debug_Fase, bool CallFunc_EqualEqual_IntInt_ReturnValue_14, bool CallFunc_IsPackagedForDistribution_ReturnValue, ULevelStreaming* CallFunc_GetStreamingLevel_ReturnValue_1, int32 Temp_int_Variable, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_36, UPlayerController* CallFunc_GetPlayerController_ReturnValue_3, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, FHitResult CallFunc_K2_SetActorLocationAndRotation_SweepHitResult_1, bool CallFunc_K2_SetActorLocationAndRotation_ReturnValue_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue_4, FName K2Node_CustomEvent_NotifyName_24, USceneComponent* CallFunc_K2_GetRootComponent_ReturnValue, FRotator CallFunc_K2_GetComponentRotation_ReturnValue_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_37, float CallFunc_BreakRotator_Roll_1, float CallFunc_BreakRotator_Pitch_1, float CallFunc_BreakRotator_Yaw_1, FRotator CallFunc_MakeRotator_ReturnValue_4, FRotator CallFunc_MakeRotator_ReturnValue_5, FVector CallFunc_K2_GetComponentLocation_ReturnValue_3, FHitResult CallFunc_K2_SetActorLocationAndRotation_SweepHitResult_2, bool CallFunc_K2_SetActorLocationAndRotation_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_25, int32 CallFunc_PostEventAtLocation_ReturnValue_26, int32 CallFunc_PostEventAtLocation_ReturnValue_27, int32 CallFunc_PostEventAtLocation_ReturnValue_28, int32 CallFunc_PostEventAtLocation_ReturnValue_29, int32 CallFunc_PostEventAtLocation_ReturnValue_30, int32 CallFunc_PostEventAtLocation_ReturnValue_31, int32 CallFunc_PostEventAtLocation_ReturnValue_32, int32 CallFunc_PostEventAtLocation_ReturnValue_33, int32 CallFunc_PostEventAtLocation_ReturnValue_34, int32 CallFunc_PostEventAtLocation_ReturnValue_35, int32 CallFunc_PostEventAtLocation_ReturnValue_36, bool CallFunc_Not_PreBool_ReturnValue_3, float CallFunc_Cutscene_OutputPin_1, bool CallFunc_Not_PreBool_ReturnValue_4, float CallFunc_Cutscene_OutputPin_2);
}

#endif
