#ifndef UE4SS_SDK_BP_BossRoom_2_HPP
#define UE4SS_SDK_BP_BossRoom_2_HPP

class ABP_BossRoom_2_C : AActor
{
    FPointerToUberGraphFrame UberGraphFrame;
    UParticleSystemComponent* P_Smoke_A;
    USphereComponent* Shield Collider;
    UStaticMeshComponent* Shield;
    UStaticMeshComponent* AreaDamageCylinder;
    UBillboardComponent* CurrencyLocation;
    UStaticMeshComponent* Room2_Fence_B;
    UParticleSystemComponent* P_Smoke_C;
    UStaticMeshComponent* Area_C;
    UStaticMeshComponent* Area_B;
    UStaticMeshComponent* Area_A;
    UStaticMeshComponent* Room2_Fence_C;
    UStaticMeshComponent* Room2_Fence_A;
    UBoxComponent* AreaDamage;
    UDecalComponent* RedZone;
    UParticleSystemComponent* P_GroundPound;
    UParticleSystemComponent* P_Smoke_B;
    UStaticMeshComponent* Room2_Platform_3;
    UStaticMeshComponent* Room2_Platform_2;
    UStaticMeshComponent* Room2_Platform_1;
    UStaticMeshComponent* Room2_Platform_0;
    USceneComponent* DefaultSceneRoot;
    float Fence_Wave_Lerp_A42639BF4F124825FFBA0E91FECA8428;
    float Fence_Wave_Erode_A42639BF4F124825FFBA0E91FECA8428;
    float Fence_Wave_Z_Value_A42639BF4F124825FFBA0E91FECA8428;
    TEnumAsByte<ETimelineDirection::Type> Fence_Wave__Direction_A42639BF4F124825FFBA0E91FECA8428;
    UTimelineComponent* Fence Wave;
    float Highlight_Base_Lerp_E3A10E754ABD519490036099E0026361;
    float Highlight_Base_Amount_E3A10E754ABD519490036099E0026361;
    TEnumAsByte<ETimelineDirection::Type> Highlight_Base__Direction_E3A10E754ABD519490036099E0026361;
    UTimelineComponent* Highlight Base;
    float To_Ice_Ice_033497794D751E38FB2487AFD5AECC88;
    TEnumAsByte<ETimelineDirection::Type> To_Ice__Direction_033497794D751E38FB2487AFD5AECC88;
    UTimelineComponent* To Ice;
    float Move_Border_Down_Lerp_19921DAD4CCAF161044D93A0A555A37A;
    TEnumAsByte<ETimelineDirection::Type> Move_Border_Down__Direction_19921DAD4CCAF161044D93A0A555A37A;
    UTimelineComponent* Move Border Down;
    float Move_Border_Up_Lerp_38AFEDB94F141589E36B9484D85E5AFF;
    TEnumAsByte<ETimelineDirection::Type> Move_Border_Up__Direction_38AFEDB94F141589E36B9484D85E5AFF;
    UTimelineComponent* Move Border Up;
    float Hide_State_1A80A4C643253CE90DFBFDB5738D4A97;
    TEnumAsByte<ETimelineDirection::Type> Hide__Direction_1A80A4C643253CE90DFBFDB5738D4A97;
    UTimelineComponent* Hide;
    float Rotate_Platform_Rotation_F83624BB4877D9F610E20AB64F7D5C9C;
    TEnumAsByte<ETimelineDirection::Type> Rotate_Platform__Direction_F83624BB4877D9F610E20AB64F7D5C9C;
    UTimelineComponent* Rotate Platform;
    FRotator Rotation A;
    FRotator Rotation B;
    FRotator Rotation C;
    float Damage Fence;
    float Reset Ground Time;
    float Reset Platform Time;
    float Rotate Speed Fase 1;
    float Rotate Speed Fase 2;
    float Rotate Speed Fase 3;
    UMaterialInstanceDynamic* Mat A;
    UMaterialInstanceDynamic* Mat B;
    UMaterialInstanceDynamic* Mat C;
    APlayer_Character_BP_C* Player;
    float Hide Speed Fase 1;
    float Hide Speed Fase 2;
    float Hide Speed Fase 3;
    bool Show Trace;
    bool canDamage;
    UMaterialInstanceDynamic* Mat Base;
    bool Lock A;
    bool Lock B;
    bool Lock C;
    bool Lock D;
    UMaterialInstanceDynamic* Mat D;
    FRotator Rotacion D;
    UMaterialInstanceDynamic* Mat Base Ice;
    bool IsIce;
    UMaterialInstanceDynamic* MatRedZone;
    float Fence Start;
    float Fence End;
    int32 Fence Index;
    UMaterialInstanceDynamic* Mat Area A;
    UMaterialInstanceDynamic* Mat Area B;
    UMaterialInstanceDynamic* Mat Area C;
    int32 Current Battle Fase;
    ABP_TeleportToEntrance_C* TeleportEntrance;

    void Hide__FinishedFunc();
    void Hide__UpdateFunc();
    void Move Border Up__FinishedFunc();
    void Move Border Up__UpdateFunc();
    void Move Border Up__SoundUp__EventFunc();
    void Move Border Down__FinishedFunc();
    void Move Border Down__UpdateFunc();
    void Move Border Down__SoundDown__EventFunc();
    void To Ice__FinishedFunc();
    void To Ice__UpdateFunc();
    void Rotate Platform__FinishedFunc();
    void Rotate Platform__UpdateFunc();
    void Highlight Base__FinishedFunc();
    void Highlight Base__UpdateFunc();
    void Fence Wave__FinishedFunc();
    void Fence Wave__UpdateFunc();
    void Fence Wave__SoundDown__EventFunc();
    void Fence Wave__SoundUp__EventFunc();
    void Fence Wave__Particle__EventFunc();
    void Fence Wave__Enable Collision__EventFunc();
    void Hide Platform(int32 Platform);
    void Show Platforms(int32 Platform);
    void BndEvt__Room2_Platform_A_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void BndEvt__Room2_Platform_B_K2Node_ComponentBoundEvent_1_ComponentHitSignature__DelegateSignature(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void BndEvt__Room2_Platform_C_K2Node_ComponentBoundEvent_2_ComponentHitSignature__DelegateSignature(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void Ground Damage(bool Activate);
    void Change State(int32 Battle Fase);
    void BndEvt__Room2_Platform_3_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void Show Fence(bool Show, int32 Index);
    void Enable Smoke(bool Enable);
    void Ice Ground(bool Is Ice);
    void Reset();
    void BndEvt__AreaDamage_K2Node_ComponentBoundEvent_9_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void ReceiveBeginPlay();
    void Start Fence Wave();
    void End Fence Wave();
    void BndEvt__Room2_Fence_B_K2Node_ComponentBoundEvent_7_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Room2_Fence_A_K2Node_ComponentBoundEvent_8_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Room2_Fence_C_K2Node_ComponentBoundEvent_11_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void Damage Player(float Damage, FVector Hit Origin);
    void WriteID(FString ID);
    void BndEvt__AreaDamageCylinder_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void ReverseFade();
    void BndEvt__Sphere Collider_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void BndEvt__Shield Collider_K2Node_ComponentBoundEvent_10_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void ExecuteUbergraph_BP_BossRoom_2(int32 EntryPoint, int32 Temp_int_Variable, int32 Temp_int_Variable_1, int32 Temp_int_Variable_2, int32 Temp_int_Variable_3, bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, int32 Temp_int_Variable_4, float CallFunc_Lerp_ReturnValue, int32 Temp_int_Variable_5, float CallFunc_Lerp_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue, int32 Temp_int_Variable_6, int32 Temp_int_Variable_7, int32 Temp_int_Variable_8, int32 Temp_int_Variable_9, float Temp_float_Variable, float Temp_float_Variable_1, float Temp_float_Variable_2, float Temp_float_Variable_3, int32 Temp_int_Variable_10, float Temp_float_Variable_4, float Temp_float_Variable_5, float Temp_float_Variable_6, float Temp_float_Variable_7, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, float K2Node_Select_Default, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_1, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_2, int32 K2Node_CustomEvent_Platform_1, bool K2Node_SwitchInteger_CmpSuccess, int32 K2Node_CustomEvent_Platform, bool K2Node_SwitchInteger_CmpSuccess_1, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, float CallFunc_BreakRotator_Roll_1, float CallFunc_BreakRotator_Pitch_1, float CallFunc_BreakRotator_Yaw_1, float CallFunc_Add_FloatFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue_1, FRotator CallFunc_MakeRotator_ReturnValue, FRotator CallFunc_MakeRotator_ReturnValue_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_HitComponent_4, AActor* K2Node_ComponentBoundEvent_OtherActor_10, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_10, FVector K2Node_ComponentBoundEvent_NormalImpulse_4, const FHitResult K2Node_ComponentBoundEvent_Hit_4, UPrimitiveComponent* K2Node_ComponentBoundEvent_HitComponent_3, AActor* K2Node_ComponentBoundEvent_OtherActor_9, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_9, FVector K2Node_ComponentBoundEvent_NormalImpulse_3, const FHitResult K2Node_ComponentBoundEvent_Hit_3, UPrimitiveComponent* K2Node_ComponentBoundEvent_HitComponent_2, AActor* K2Node_ComponentBoundEvent_OtherActor_8, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_8, FVector K2Node_ComponentBoundEvent_NormalImpulse_2, const FHitResult K2Node_ComponentBoundEvent_Hit_2, APawn* CallFunc_GetPlayerPawn_ReturnValue, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, FHitResult CallFunc_K2_SetWorldRotation_SweepHitResult, bool K2Node_CustomEvent_Activate, FHitResult CallFunc_K2_SetWorldRotation_SweepHitResult_1, FVector CallFunc_K2_GetActorLocation_ReturnValue, int32 K2Node_CustomEvent_Battle_Fase, bool K2Node_SwitchInteger_CmpSuccess_2, float CallFunc_BreakRotator_Roll_2, float CallFunc_BreakRotator_Pitch_2, float CallFunc_BreakRotator_Yaw_2, float CallFunc_Add_FloatFloat_ReturnValue_2, FRotator CallFunc_MakeRotator_ReturnValue_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_HitComponent_1, AActor* K2Node_ComponentBoundEvent_OtherActor_7, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_7, FVector K2Node_ComponentBoundEvent_NormalImpulse_1, const FHitResult K2Node_ComponentBoundEvent_Hit_1, APawn* CallFunc_GetPlayerPawn_ReturnValue_2, FHitResult CallFunc_K2_SetWorldRotation_SweepHitResult_2, UStaticMeshComponent* K2Node_Select_Default_1, UStaticMeshComponent* K2Node_Select_Default_2, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_3, UMaterialInstanceDynamic* K2Node_Select_Default_3, bool K2Node_CustomEvent_Show, int32 K2Node_CustomEvent_Index, UMaterialInstanceDynamic* K2Node_Select_Default_4, uint8 K2Node_Select_Default_5, APawn* CallFunc_GetPlayerPawn_ReturnValue_3, float CallFunc_BreakRotator_Roll_3, float CallFunc_BreakRotator_Pitch_3, float CallFunc_BreakRotator_Yaw_3, float CallFunc_Add_FloatFloat_ReturnValue_3, FRotator CallFunc_MakeRotator_ReturnValue_3, FHitResult CallFunc_K2_SetWorldRotation_SweepHitResult_3, bool K2Node_CustomEvent_Enable, bool K2Node_CustomEvent_Is_Ice, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_4, float K2Node_Select_Default_6, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_5, AActor* K2Node_ComponentBoundEvent_OtherActor_6, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_6, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_5, bool K2Node_ComponentBoundEvent_bFromSweep_5, const FHitResult K2Node_ComponentBoundEvent_SweepResult_5, UStaticMeshComponent* K2Node_Select_Default_7, float CallFunc_Lerp_ReturnValue_2, FVector CallFunc_MakeVector_ReturnValue_1, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult, float CallFunc_Lerp_ReturnValue_3, FVector CallFunc_MakeVector_ReturnValue_2, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult_1, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, UStaticMeshComponent* K2Node_Select_Default_8, APawn* CallFunc_GetPlayerPawn_ReturnValue_4, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult_2, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_5, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_6, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_7, UMaterialInstanceDynamic* K2Node_Select_Default_9, FVector CallFunc_MakeVector_ReturnValue_3, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult_3, int32 Temp_int_Variable_11, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_4, AActor* K2Node_ComponentBoundEvent_OtherActor_5, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_5, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_4, bool K2Node_ComponentBoundEvent_bFromSweep_4, const FHitResult K2Node_ComponentBoundEvent_SweepResult_4, UParticleSystemComponent* K2Node_Select_Default_10, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, FVector CallFunc_BreakHitResult_Location, FVector CallFunc_BreakHitResult_ImpactPoint, FVector CallFunc_BreakHitResult_Normal, FVector CallFunc_BreakHitResult_ImpactNormal, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, AActor* CallFunc_BreakHitResult_HitActor, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, FName CallFunc_BreakHitResult_HitBoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_FaceIndex, FVector CallFunc_BreakHitResult_TraceStart, FVector CallFunc_BreakHitResult_TraceEnd, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_3, AActor* K2Node_ComponentBoundEvent_OtherActor_4, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_4, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_3, bool K2Node_ComponentBoundEvent_bFromSweep_3, const FHitResult K2Node_ComponentBoundEvent_SweepResult_3, bool CallFunc_BreakHitResult_bBlockingHit_1, bool CallFunc_BreakHitResult_bInitialOverlap_1, float CallFunc_BreakHitResult_Time_1, float CallFunc_BreakHitResult_Distance_1, FVector CallFunc_BreakHitResult_Location_1, FVector CallFunc_BreakHitResult_ImpactPoint_1, FVector CallFunc_BreakHitResult_Normal_1, FVector CallFunc_BreakHitResult_ImpactNormal_1, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat_1, AActor* CallFunc_BreakHitResult_HitActor_1, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent_1, FName CallFunc_BreakHitResult_HitBoneName_1, int32 CallFunc_BreakHitResult_HitItem_1, int32 CallFunc_BreakHitResult_FaceIndex_1, FVector CallFunc_BreakHitResult_TraceStart_1, FVector CallFunc_BreakHitResult_TraceEnd_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_2, AActor* K2Node_ComponentBoundEvent_OtherActor_3, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_3, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_2, bool K2Node_ComponentBoundEvent_bFromSweep_2, const FHitResult K2Node_ComponentBoundEvent_SweepResult_2, float K2Node_CustomEvent_Damage, FVector K2Node_CustomEvent_Hit_Origin, bool CallFunc_BreakHitResult_bBlockingHit_2, bool CallFunc_BreakHitResult_bInitialOverlap_2, float CallFunc_BreakHitResult_Time_2, float CallFunc_BreakHitResult_Distance_2, FVector CallFunc_BreakHitResult_Location_2, FVector CallFunc_BreakHitResult_ImpactPoint_2, FVector CallFunc_BreakHitResult_Normal_2, FVector CallFunc_BreakHitResult_ImpactNormal_2, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat_2, AActor* CallFunc_BreakHitResult_HitActor_2, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent_2, FName CallFunc_BreakHitResult_HitBoneName_2, int32 CallFunc_BreakHitResult_HitItem_2, int32 CallFunc_BreakHitResult_FaceIndex_2, FVector CallFunc_BreakHitResult_TraceStart_2, FVector CallFunc_BreakHitResult_TraceEnd_2, float CallFunc_ApplyDamage_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_4, int32 CallFunc_PostEventAtLocation_ReturnValue_5, FString K2Node_CustomEvent_Id, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_1, AActor* K2Node_ComponentBoundEvent_OtherActor_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_2, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_1, bool K2Node_ComponentBoundEvent_bFromSweep_1, const FHitResult K2Node_ComponentBoundEvent_SweepResult_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_3, TArray<AActor*>& CallFunc_GetOverlappingActors_OverlappingActors, bool CallFunc_Array_IsValidIndex_ReturnValue, UPrimitiveComponent* K2Node_ComponentBoundEvent_HitComponent, AActor* K2Node_ComponentBoundEvent_OtherActor_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, FVector K2Node_ComponentBoundEvent_NormalImpulse, const FHitResult K2Node_ComponentBoundEvent_Hit, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_4, float K2Node_Select_Default_11, float CallFunc_ApplyDamage_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_8);
}

#endif
