#ifndef UE4SS_SDK_BP_Boss_Lord_1_HPP
#define UE4SS_SDK_BP_Boss_Lord_1_HPP

class ABP_Boss_Lord_1_C : UEnemy_Character_Parent_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    USceneComponent* ScenePOI;
    UArrowComponent* Arrow_Up;
    USphereComponent* Shield Collider;
    UStaticMeshComponent* Shield;
    UCapsuleComponent* Collider;
    UArrowComponent* Arrow_Forward;
    UParticleSystemComponent* P_LordDissolve;
    UParticleSystemComponent* P_Ball_03;
    UParticleSystemComponent* P_Ball_02;
    UParticleSystemComponent* P_Ball_01;
    UStaticMeshComponent* Ball_03;
    UStaticMeshComponent* Ball_02;
    UStaticMeshComponent* Ball_01;
    float LightUp_Bomb_2F8DD6C542940A244161108420EAB4CF;
    TEnumAsByte<ETimelineDirection::Type> LightUp__Direction_2F8DD6C542940A244161108420EAB4CF;
    UTimelineComponent* LightUp;
    float Show_Fire_Lerp_Texture_C1C7674F4A338C458320C9863AEFBBFE;
    float Show_Fire_Amount_C1C7674F4A338C458320C9863AEFBBFE;
    TEnumAsByte<ETimelineDirection::Type> Show_Fire__Direction_C1C7674F4A338C458320C9863AEFBBFE;
    UTimelineComponent* Show Fire;
    float Ball_Glow_Glow_BA2E2F54405DC41A219847B46C4C71D5;
    TEnumAsByte<ETimelineDirection::Type> Ball_Glow__Direction_BA2E2F54405DC41A219847B46C4C71D5;
    UTimelineComponent* Ball Glow;
    float Dissolve_Body_Dissolve_1B598CF34E2DAF53FC5C89BD2717486A;
    TEnumAsByte<ETimelineDirection::Type> Dissolve_Body__Direction_1B598CF34E2DAF53FC5C89BD2717486A;
    UTimelineComponent* Dissolve Body;
    float Dissolve_Armor_Dissolve_9207A0114AFB06298D3DE9AE84CB0164;
    TEnumAsByte<ETimelineDirection::Type> Dissolve_Armor__Direction_9207A0114AFB06298D3DE9AE84CB0164;
    UTimelineComponent* Dissolve Armor;
    float Show_Body_Lerp_Texture_B56F1EE04E6453B57F40059858FC894D;
    TEnumAsByte<ETimelineDirection::Type> Show_Body__Direction_B56F1EE04E6453B57F40059858FC894D;
    UTimelineComponent* Show Body;
    float Show_Armor_Amount_Fase_3_2B3DEC754D37FDF7F58445959EE45767;
    float Show_Armor_Amount_Fase_2_2B3DEC754D37FDF7F58445959EE45767;
    TEnumAsByte<ETimelineDirection::Type> Show_Armor__Direction_2B3DEC754D37FDF7F58445959EE45767;
    UTimelineComponent* Show Armor;
    float Ball_1_On_Scale_4CCDB0EC432C549BDC050A9DD4574CA6;
    TEnumAsByte<ETimelineDirection::Type> Ball_1_On__Direction_4CCDB0EC432C549BDC050A9DD4574CA6;
    UTimelineComponent* Ball 1 On;
    float Ball_1_Off_Scale_3AA90DDE416E24BED4718585D9FDF54E;
    TEnumAsByte<ETimelineDirection::Type> Ball_1_Off__Direction_3AA90DDE416E24BED4718585D9FDF54E;
    UTimelineComponent* Ball 1 Off;
    float Ball_2_On_Scale_FE2630484C48F084D0B4428EB9AFDC8B;
    TEnumAsByte<ETimelineDirection::Type> Ball_2_On__Direction_FE2630484C48F084D0B4428EB9AFDC8B;
    UTimelineComponent* Ball 2 On;
    float Ball_2_Off_Scale_001DD0F54CDDC699D33DDDA61F0D93AA;
    TEnumAsByte<ETimelineDirection::Type> Ball_2_Off__Direction_001DD0F54CDDC699D33DDDA61F0D93AA;
    UTimelineComponent* Ball 2 Off;
    float Balls_3_On_Scale_3FBA96B8422D3F45E2FEAD82B19FF839;
    TEnumAsByte<ETimelineDirection::Type> Balls_3_On__Direction_3FBA96B8422D3F45E2FEAD82B19FF839;
    UTimelineComponent* Balls 3 On;
    float Ball_3_Off_Scale_AB314B304DF7B526DE56CBA4C36A57FA;
    TEnumAsByte<ETimelineDirection::Type> Ball_3_Off__Direction_AB314B304DF7B526DE56CBA4C36A57FA;
    UTimelineComponent* Ball 3 Off;
    float HideBall_Scale_092DA4FE456B82387238EBB1EB5FFD07;
    TEnumAsByte<ETimelineDirection::Type> HideBall__Direction_092DA4FE456B82387238EBB1EB5FFD07;
    UTimelineComponent* HideBall;
    float Rolling_Rate_Rate_3D28D5614FA1405D3C5C3DAF27FEF70B;
    TEnumAsByte<ETimelineDirection::Type> Rolling_Rate__Direction_3D28D5614FA1405D3C5C3DAF27FEF70B;
    UTimelineComponent* Rolling Rate;
    UMaterialInstanceDynamic* SelfMat;
    FBP_Boss_Lord_1_CFaseChange FaseChange;
    void FaseChange(int32 Fase);
    ULord_1_Skeleton_AnimBlueprint_C* AnimInst;
    bool Hidden;
    FTransform InitialLoc;
    int32 Attack Counter;
    bool Is Stuck;
    float Player Z Location;
    FString Name Move Back ;
    bool Changing Fase;
    float Spawn Ball Heigth;
    float Spawn Ball Width;
    float Rolling Ball Delay;
    UAnimMontage* Current AnimMontage;
    float Show Ball Play Rate;
    UMaterialInstanceDynamic* Decal Explosion;
    UMaterialInstanceDynamic* MatBody;
    UMaterialInstanceDynamic* MatArmor;
    UMaterialInstanceDynamic* Mat Ball 01;
    UMaterialInstanceDynamic* Mat Spikes 01;
    UMaterialInstanceDynamic* Mat Ball 02;
    UMaterialInstanceDynamic* Mat Spikes 02;
    UMaterialInstanceDynamic* Mat Ball 03;
    UMaterialInstanceDynamic* Mat Spikes 03;
    bool Interrumpt Balls;
    TArray<TEnumAsByte<Areas::Type>> Placeholder;
    FString ID;
    float Claw Radius;
    float Attack Distance;
    float Offset Claw;
    AActor* Boss Room Actor;
    AActor* Cutscene Camera;
    ULevelSequence* Cutscene Fase 2;
    ULevelSequence* Cutscene Fase 3;
    int32 Random Selection;
    ABP_BossRoom_1_C* Boss Room;
    AActor* TargetLocation;
    FVector New Player Location;
    int32 StunnedSound;
    FVector BallLocation;
    bool Protected;
    float IntensityFire;

    void UserConstructionScript();
    void Ball 3 Off__FinishedFunc();
    void Ball 3 Off__UpdateFunc();
    void Balls 3 On__FinishedFunc();
    void Balls 3 On__UpdateFunc();
    void Rolling Rate__FinishedFunc();
    void Rolling Rate__UpdateFunc();
    void HideBall__FinishedFunc();
    void HideBall__UpdateFunc();
    void Ball 1 On__FinishedFunc();
    void Ball 1 On__UpdateFunc();
    void Ball 1 Off__FinishedFunc();
    void Ball 1 Off__UpdateFunc();
    void Ball 2 On__FinishedFunc();
    void Ball 2 On__UpdateFunc();
    void Ball 2 Off__FinishedFunc();
    void Ball 2 Off__UpdateFunc();
    void LightUp__FinishedFunc();
    void LightUp__UpdateFunc();
    void Show Fire__FinishedFunc();
    void Show Fire__UpdateFunc();
    void Show Fire__Trigger Blur__EventFunc();
    void Ball Glow__FinishedFunc();
    void Ball Glow__UpdateFunc();
    void Dissolve Body__FinishedFunc();
    void Dissolve Body__UpdateFunc();
    void Dissolve Armor__FinishedFunc();
    void Dissolve Armor__UpdateFunc();
    void Show Body__FinishedFunc();
    void Show Body__UpdateFunc();
    void Show Armor__FinishedFunc();
    void Show Armor__UpdateFunc();
    void OnNotifyEnd_B1B159E64B3E13371AA0338A739BB1B3(FName NotifyName);
    void OnNotifyBegin_B1B159E64B3E13371AA0338A739BB1B3(FName NotifyName);
    void OnInterrupted_B1B159E64B3E13371AA0338A739BB1B3(FName NotifyName);
    void OnBlendOut_B1B159E64B3E13371AA0338A739BB1B3(FName NotifyName);
    void OnCompleted_B1B159E64B3E13371AA0338A739BB1B3(FName NotifyName);
    void OnNotifyEnd_FB3035044F3575A205D91DBE5BD4C674(FName NotifyName);
    void OnNotifyBegin_FB3035044F3575A205D91DBE5BD4C674(FName NotifyName);
    void OnInterrupted_FB3035044F3575A205D91DBE5BD4C674(FName NotifyName);
    void OnBlendOut_FB3035044F3575A205D91DBE5BD4C674(FName NotifyName);
    void OnCompleted_FB3035044F3575A205D91DBE5BD4C674(FName NotifyName);
    void OnNotifyEnd_9E9CCFCD4B50A028A2EDBCA8F72D28E3(FName NotifyName);
    void OnNotifyBegin_9E9CCFCD4B50A028A2EDBCA8F72D28E3(FName NotifyName);
    void OnInterrupted_9E9CCFCD4B50A028A2EDBCA8F72D28E3(FName NotifyName);
    void OnBlendOut_9E9CCFCD4B50A028A2EDBCA8F72D28E3(FName NotifyName);
    void OnCompleted_9E9CCFCD4B50A028A2EDBCA8F72D28E3(FName NotifyName);
    void OnNotifyEnd_046CCDF7457E42C18144278930EC8AD3(FName NotifyName);
    void OnNotifyBegin_046CCDF7457E42C18144278930EC8AD3(FName NotifyName);
    void OnInterrupted_046CCDF7457E42C18144278930EC8AD3(FName NotifyName);
    void OnBlendOut_046CCDF7457E42C18144278930EC8AD3(FName NotifyName);
    void OnCompleted_046CCDF7457E42C18144278930EC8AD3(FName NotifyName);
    void OnNotifyEnd_015B64D9494DF5EF28B094BD6558F2E2(FName NotifyName);
    void OnNotifyBegin_015B64D9494DF5EF28B094BD6558F2E2(FName NotifyName);
    void OnInterrupted_015B64D9494DF5EF28B094BD6558F2E2(FName NotifyName);
    void OnBlendOut_015B64D9494DF5EF28B094BD6558F2E2(FName NotifyName);
    void OnCompleted_015B64D9494DF5EF28B094BD6558F2E2(FName NotifyName);
    void OnNotifyEnd_8CD556454305625639B209AED4E45759(FName NotifyName);
    void OnNotifyBegin_8CD556454305625639B209AED4E45759(FName NotifyName);
    void OnInterrupted_8CD556454305625639B209AED4E45759(FName NotifyName);
    void OnBlendOut_8CD556454305625639B209AED4E45759(FName NotifyName);
    void OnCompleted_8CD556454305625639B209AED4E45759(FName NotifyName);
    void OnNotifyEnd_BD26C2AC498AE11105E33F9BA89E099C(FName NotifyName);
    void OnNotifyBegin_BD26C2AC498AE11105E33F9BA89E099C(FName NotifyName);
    void OnInterrupted_BD26C2AC498AE11105E33F9BA89E099C(FName NotifyName);
    void OnBlendOut_BD26C2AC498AE11105E33F9BA89E099C(FName NotifyName);
    void OnCompleted_BD26C2AC498AE11105E33F9BA89E099C(FName NotifyName);
    void OnNotifyEnd_021931DD4D170028BDD6D79E3FA3A7E5(FName NotifyName);
    void OnNotifyBegin_021931DD4D170028BDD6D79E3FA3A7E5(FName NotifyName);
    void OnInterrupted_021931DD4D170028BDD6D79E3FA3A7E5(FName NotifyName);
    void OnBlendOut_021931DD4D170028BDD6D79E3FA3A7E5(FName NotifyName);
    void OnCompleted_021931DD4D170028BDD6D79E3FA3A7E5(FName NotifyName);
    void OnNotifyEnd_FE67B52D40ED631EDF323D8ED965C486(FName NotifyName);
    void OnNotifyBegin_FE67B52D40ED631EDF323D8ED965C486(FName NotifyName);
    void OnInterrupted_FE67B52D40ED631EDF323D8ED965C486(FName NotifyName);
    void OnBlendOut_FE67B52D40ED631EDF323D8ED965C486(FName NotifyName);
    void OnCompleted_FE67B52D40ED631EDF323D8ED965C486(FName NotifyName);
    void OnNotifyEnd_3B1CDE38467C498C222F3FA794ADE8B5(FName NotifyName);
    void OnNotifyBegin_3B1CDE38467C498C222F3FA794ADE8B5(FName NotifyName);
    void OnInterrupted_3B1CDE38467C498C222F3FA794ADE8B5(FName NotifyName);
    void OnBlendOut_3B1CDE38467C498C222F3FA794ADE8B5(FName NotifyName);
    void OnCompleted_3B1CDE38467C498C222F3FA794ADE8B5(FName NotifyName);
    void OnNotifyEnd_CAC41CAC4D9799A085A2A7B57090DE65(FName NotifyName);
    void OnNotifyBegin_CAC41CAC4D9799A085A2A7B57090DE65(FName NotifyName);
    void OnInterrupted_CAC41CAC4D9799A085A2A7B57090DE65(FName NotifyName);
    void OnBlendOut_CAC41CAC4D9799A085A2A7B57090DE65(FName NotifyName);
    void OnCompleted_CAC41CAC4D9799A085A2A7B57090DE65(FName NotifyName);
    void OnNotifyEnd_D29C14754969013E056C33AD1AE65C04(FName NotifyName);
    void OnNotifyBegin_D29C14754969013E056C33AD1AE65C04(FName NotifyName);
    void OnInterrupted_D29C14754969013E056C33AD1AE65C04(FName NotifyName);
    void OnBlendOut_D29C14754969013E056C33AD1AE65C04(FName NotifyName);
    void OnCompleted_D29C14754969013E056C33AD1AE65C04(FName NotifyName);
    void OnNotifyEnd_DE4A102F48528004A9EE06878891DB4A(FName NotifyName);
    void OnNotifyBegin_DE4A102F48528004A9EE06878891DB4A(FName NotifyName);
    void OnInterrupted_DE4A102F48528004A9EE06878891DB4A(FName NotifyName);
    void OnBlendOut_DE4A102F48528004A9EE06878891DB4A(FName NotifyName);
    void OnCompleted_DE4A102F48528004A9EE06878891DB4A(FName NotifyName);
    void Damage Player(const AActor*& Actor, bool Check if is Player Attacking, float Launch Multiplier);
    void Rolling Balls(bool Make Roll);
    void Spawn Ball();
    void Hide Ball(int32 Value);
    void Claw Attack(int32 Counter Limit);
    void Show Ball 3(bool Show);
    void Show Ball 1(bool Show);
    void Area Damage(const FVector& Start, const FVector& End, float Radius, float Launch Multiplier);
    void Show Ball 2(bool Show);
    void Interrupt Balls();
    void BndEvt__Ball_01_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Ball_02_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Ball_03_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Shield Collider_K2Node_ComponentBoundEvent_2_ComponentHitSignature__DelegateSignature(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void Attack03(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Attack02(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Attack01(int32 Count, int32 Max Count, bool Use Custom Counter);
    void AttackExpression_03();
    void AttackExpression_01();
    void AttackExpression_04();
    void LightUpStart(float IntensityFire);
    void LightUpEnd();
    void VFX Slash(float Delay, float Rotation, float Scale);
    void VFX Shield(bool Show);
    void AttackExpression_05();
    void AttackExpression_06();
    void Force Stop All Balls();
    void Force LightUpEnd();
    void StartBoss();
    void EndBoss();
    void RadialBlur();
    void Boss Appear();
    void Boss Desappear();
    void Relocate Player();
    void Set New Player Location(FVector New Location);
    void Event Boss Up();
    void Show Teleport();
    void PlayCustomCutsceneExtra();
    void ResumeCustomCutsceneExtra();
    void SirionIntroVO();
    void FadeWhiteIn();
    void FadeWhiteOut();
    void ReceiveBeginPlay();
    void ReceiveAnyDamage(float Damage, const UDamageType* DamageType, AController* InstigatedBy, AActor* DamageCauser);
    void VFX Ball Glow(bool Show, bool Instant, bool Delay, float Delay Time, float Play Rate);
    void Fase Change();
    void VFX Dissolve Body(bool Show);
    void In Room Center(bool CheckPlayerIsDead);
    void VFX Body Particle(bool Show);
    void SFX Lava();
    void VFX Dissolve Armor(bool Show);
    void VFX Mat Body(bool Show);
    void Anim Move Back(bool Move);
    void Anim Move Front(bool Move);
    void VFX Slash Boss();
    void VFX Mat Armor(bool Show);
    void VFX Change State();
    void ReceiveHit(UPrimitiveComponent* MyComp, AActor* Other, UPrimitiveComponent* OtherComp, bool bSelfMoved, FVector HitLocation, FVector HitNormal, FVector NormalImpulse, const FHitResult& Hit);
    void Restart();
    void On Player Die();
    void GA SendEvent();
    void ExecuteUbergraph_BP_Boss_Lord_1(int32 EntryPoint, float CallFunc_PlayAnimMontage_ReturnValue, FName K2Node_CustomEvent_NotifyName_62, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FName K2Node_CustomEvent_NotifyName_61, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FName K2Node_CustomEvent_NotifyName_60, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FName Temp_name_Variable, FVector CallFunc_MakeVector_ReturnValue, FVector CallFunc_MakeVector_ReturnValue_1, int32 Temp_int_Variable, int32 Temp_int_Variable_1, FVector CallFunc_MakeVector_ReturnValue_2, float Temp_float_Variable, float Temp_float_Variable_1, float Temp_float_Variable_2, float Temp_float_Variable_3, int32 Temp_int_Variable_2, UAnimMontage* Temp_object_Variable, UAnimMontage* Temp_object_Variable_1, int32 Temp_int_Variable_3, bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, FVector CallFunc_MakeVector_ReturnValue_3, FVector CallFunc_MakeVector_ReturnValue_4, FVector CallFunc_MakeVector_ReturnValue_5, FVector CallFunc_MakeVector_ReturnValue_6, FName K2Node_CustomEvent_NotifyName_59, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, FName K2Node_CustomEvent_NotifyName_58, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, FName K2Node_CustomEvent_NotifyName_57, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, FName K2Node_CustomEvent_NotifyName_56, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, FName K2Node_CustomEvent_NotifyName_55, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, FName Temp_name_Variable_1, FVector CallFunc_MakeVector_ReturnValue_7, const TArray<AActor*>& Temp_object_Variable_2, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, bool Temp_bool_Variable_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, FName K2Node_CustomEvent_NotifyName_54, FName K2Node_CustomEvent_NotifyName_53, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, FName K2Node_CustomEvent_NotifyName_52, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, FName K2Node_CustomEvent_NotifyName_51, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_11, FName K2Node_CustomEvent_NotifyName_50, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_12, FName Temp_name_Variable_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_13, FName K2Node_CustomEvent_NotifyName_49, FName K2Node_CustomEvent_NotifyName_48, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_14, FName K2Node_CustomEvent_NotifyName_47, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_15, FName K2Node_CustomEvent_NotifyName_46, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_16, FName K2Node_CustomEvent_NotifyName_45, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_17, FName Temp_name_Variable_3, bool Temp_bool_Variable_4, uint8 Temp_byte_Variable_2, uint8 Temp_byte_Variable_3, FTransform CallFunc_MakeTransform_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, ABP_Ball_Lord1_C* CallFunc_FinishSpawningActor_ReturnValue, bool Temp_bool_Variable_5, FName K2Node_CustomEvent_NotifyName_44, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_18, FName K2Node_CustomEvent_NotifyName_43, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_19, FName K2Node_CustomEvent_NotifyName_42, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_20, FName K2Node_CustomEvent_NotifyName_41, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_21, FName K2Node_CustomEvent_NotifyName_40, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_22, FName Temp_name_Variable_4, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_23, FName K2Node_CustomEvent_NotifyName_39, FName K2Node_CustomEvent_NotifyName_38, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_24, FName K2Node_CustomEvent_NotifyName_37, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_25, FName K2Node_CustomEvent_NotifyName_36, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_26, FName K2Node_CustomEvent_NotifyName_35, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_27, FName Temp_name_Variable_5, int32 Temp_int_Variable_4, int32 Temp_int_Variable_5, float Temp_float_Variable_4, float Temp_float_Variable_5, float Temp_float_Variable_6, float Temp_float_Variable_7, int32 Temp_int_Variable_6, float Temp_float_Variable_8, float Temp_float_Variable_9, float Temp_float_Variable_10, float Temp_float_Variable_11, int32 Temp_int_Variable_7, FVector Temp_struct_Variable, FVector Temp_struct_Variable_1, FVector Temp_struct_Variable_2, int32 Temp_int_Variable_8, float Temp_float_Variable_12, float Temp_float_Variable_13, float Temp_float_Variable_14, FName K2Node_CustomEvent_NotifyName_34, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_28, FName K2Node_CustomEvent_NotifyName_33, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_29, FName K2Node_CustomEvent_NotifyName_32, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_30, FName K2Node_CustomEvent_NotifyName_31, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_31, FName K2Node_CustomEvent_NotifyName_30, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_32, FName Temp_name_Variable_6, int32 Temp_int_Variable_9, UParticleSystem* Temp_object_Variable_3, UParticleSystem* Temp_object_Variable_4, UParticleSystem* Temp_object_Variable_5, UParticleSystem* Temp_object_Variable_6, int32 Temp_int_Variable_10, ULevelSequence* Temp_object_Variable_7, ULevelSequence* Temp_object_Variable_8, FName K2Node_CustomEvent_NotifyName_29, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_33, FName K2Node_CustomEvent_NotifyName_28, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_34, FName K2Node_CustomEvent_NotifyName_27, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_35, FName K2Node_CustomEvent_NotifyName_26, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_36, FName K2Node_CustomEvent_NotifyName_25, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_37, FName Temp_name_Variable_7, FRotator CallFunc_MakeRotator_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue, FRotator CallFunc_MakeRotator_ReturnValue_1, FName K2Node_CustomEvent_NotifyName_24, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_38, FName K2Node_CustomEvent_NotifyName_23, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_39, FName K2Node_CustomEvent_NotifyName_22, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_40, FName K2Node_CustomEvent_NotifyName_21, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_41, FName K2Node_CustomEvent_NotifyName_20, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_42, FName Temp_name_Variable_8, int32 Temp_int_Variable_11, UAnimMontage* Temp_object_Variable_9, UAnimMontage* Temp_object_Variable_10, OnMovieSceneSequencePlayerEvent__DelegateSignature K2Node_CreateDelegate_OutputDelegate_43, FName K2Node_CustomEvent_NotifyName_19, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_44, FName K2Node_CustomEvent_NotifyName_18, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_45, FName K2Node_CustomEvent_NotifyName_17, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_46, FName K2Node_CustomEvent_NotifyName_16, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_47, FName K2Node_CustomEvent_NotifyName_15, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_48, FName Temp_name_Variable_9, FRotator CallFunc_MakeRotator_ReturnValue_2, FName K2Node_CustomEvent_NotifyName_14, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_49, FName K2Node_CustomEvent_NotifyName_13, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_50, FName K2Node_CustomEvent_NotifyName_12, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_51, FName K2Node_CustomEvent_NotifyName_11, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_52, FName K2Node_CustomEvent_NotifyName_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_53, FName Temp_name_Variable_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_54, bool K2Node_SwitchName_CmpSuccess, bool K2Node_SwitchName_CmpSuccess_1, FName K2Node_CustomEvent_NotifyName_9, FName K2Node_CustomEvent_NotifyName_8, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_55, FName K2Node_CustomEvent_NotifyName_7, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_56, FName K2Node_CustomEvent_NotifyName_6, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_57, FName K2Node_CustomEvent_NotifyName_5, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_58, FName Temp_name_Variable_11, bool Temp_bool_Variable_6, int32 Temp_int_Variable_12, float Temp_float_Variable_15, float Temp_float_Variable_16, bool Temp_bool_Variable_7, float Temp_float_Variable_17, int32 Temp_int_Variable_13, float Temp_float_Variable_18, float Temp_float_Variable_19, float Temp_float_Variable_20, int32 Temp_int_Variable_14, float Temp_float_Variable_21, float Temp_float_Variable_22, float Temp_float_Variable_23, float Temp_float_Variable_24, FName K2Node_CustomEvent_NotifyName_4, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_59, FName K2Node_CustomEvent_NotifyName_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_60, FName K2Node_CustomEvent_NotifyName_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_61, FName K2Node_CustomEvent_NotifyName_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_62, FName K2Node_CustomEvent_NotifyName, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_63, FName Temp_name_Variable_12, bool CallFunc_EqualEqual_IntInt_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, bool CallFunc_IsValid_ReturnValue, const AActor* K2Node_CustomEvent_Actor, bool K2Node_CustomEvent_Check_if_is_Player_Attacking, float K2Node_CustomEvent_Launch_Multiplier_1, FVector CallFunc_K2_GetActorLocation_ReturnValue, bool K2Node_CustomEvent_Make_Roll, bool CallFunc_Not_PreBool_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue, int32 K2Node_CustomEvent_Value, bool CallFunc_GreaterEqual_IntInt_ReturnValue_1, UStaticMeshComponent* K2Node_Select_Default, int32 K2Node_CustomEvent_Counter_Limit, bool K2Node_CustomEvent_Show_9, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, float CallFunc_Multiply_FloatFloat_ReturnValue, FVector CallFunc_MakeVector_ReturnValue_8, float CallFunc_RandomFloatInRange_ReturnValue, const TArray<uint8>& K2Node_MakeArray_Array, float CallFunc_Multiply_FloatFloat_ReturnValue_1, float CallFunc_RandomFloatInRange_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue_9, float K2Node_Select_Default_1, FVector CallFunc_Add_VectorVector_ReturnValue, float K2Node_Select_Default_2, float K2Node_Select_Default_3, UParticleSystemComponent* K2Node_Select_Default_4, uint8 K2Node_Select_Default_5, bool K2Node_CustomEvent_Show_8, const FVector K2Node_CustomEvent_Start, const FVector K2Node_CustomEvent_End, float K2Node_CustomEvent_Radius, float K2Node_CustomEvent_Launch_Multiplier, FHitResult CallFunc_SphereTraceSingleForObjects_OutHit, bool CallFunc_SphereTraceSingleForObjects_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, FVector CallFunc_BreakHitResult_Location, FVector CallFunc_BreakHitResult_ImpactPoint, FVector CallFunc_BreakHitResult_Normal, FVector CallFunc_BreakHitResult_ImpactNormal, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, AActor* CallFunc_BreakHitResult_HitActor, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, FName CallFunc_BreakHitResult_HitBoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_FaceIndex, FVector CallFunc_BreakHitResult_TraceStart, FVector CallFunc_BreakHitResult_TraceEnd, bool K2Node_CustomEvent_Show_7, FName K2Node_CustomEvent_NotifyName_63, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_4, int32 CallFunc_PostEventAtLocation_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_6, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_7, int32 CallFunc_PostEventAtLocation_ReturnValue_8, int32 CallFunc_PostEventAtLocation_ReturnValue_9, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_10, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_11, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_12, int32 CallFunc_PostEventAtLocation_ReturnValue_13, int32 CallFunc_PostEventAtLocation_ReturnValue_14, int32 CallFunc_PostEventAtLocation_ReturnValue_15, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_2, AActor* K2Node_ComponentBoundEvent_OtherActor_3, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_3, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_2, bool K2Node_ComponentBoundEvent_bFromSweep_2, const FHitResult K2Node_ComponentBoundEvent_SweepResult_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_1, AActor* K2Node_ComponentBoundEvent_OtherActor_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_2, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_1, bool K2Node_ComponentBoundEvent_bFromSweep_1, const FHitResult K2Node_ComponentBoundEvent_SweepResult_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, float CallFunc_Add_FloatFloat_ReturnValue, FVector CallFunc_GetRightVector_ReturnValue, FVector CallFunc_GetForwardVector_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_3, FVector CallFunc_Multiply_VectorFloat_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue_1, FVector CallFunc_Add_VectorVector_ReturnValue_1, FVector CallFunc_GetActorScale3D_ReturnValue, FVector CallFunc_Subtract_VectorVector_ReturnValue, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, FVector CallFunc_Add_VectorVector_ReturnValue_2, float CallFunc_BreakVector_X_2, float CallFunc_BreakVector_Y_2, float CallFunc_BreakVector_Z_2, int32 CallFunc_RandomIntegerInRange_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue_2, bool K2Node_SwitchInteger_CmpSuccess, float CallFunc_Multiply_FloatFloat_ReturnValue_3, int32 CallFunc_RandomIntegerInRange_ReturnValue_1, bool K2Node_SwitchInteger_CmpSuccess_1, UAnimMontage* K2Node_Select_Default_6, bool K2Node_SwitchInteger_CmpSuccess_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_HitComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, FVector K2Node_ComponentBoundEvent_NormalImpulse, const FHitResult K2Node_ComponentBoundEvent_Hit, bool CallFunc_BreakHitResult_bBlockingHit_1, bool CallFunc_BreakHitResult_bInitialOverlap_1, float CallFunc_BreakHitResult_Time_1, float CallFunc_BreakHitResult_Distance_1, FVector CallFunc_BreakHitResult_Location_1, FVector CallFunc_BreakHitResult_ImpactPoint_1, FVector CallFunc_BreakHitResult_Normal_1, FVector CallFunc_BreakHitResult_ImpactNormal_1, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat_1, AActor* CallFunc_BreakHitResult_HitActor_1, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent_1, FName CallFunc_BreakHitResult_HitBoneName_1, int32 CallFunc_BreakHitResult_HitItem_1, int32 CallFunc_BreakHitResult_FaceIndex_1, FVector CallFunc_BreakHitResult_TraceStart_1, FVector CallFunc_BreakHitResult_TraceEnd_1, FVector CallFunc_GetRightVector_ReturnValue_1, FVector CallFunc_Multiply_VectorFloat_ReturnValue_2, FVector CallFunc_GetForwardVector_ReturnValue_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue_4, FVector CallFunc_Multiply_VectorFloat_ReturnValue_3, FVector CallFunc_Add_VectorVector_ReturnValue_3, FVector CallFunc_Subtract_VectorVector_ReturnValue_1, FVector CallFunc_Add_VectorVector_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_2, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_3, int32 K2Node_Event_Count_2, int32 K2Node_Event_Max_Count_2, bool K2Node_Event_Use_Custom_Counter_2, bool K2Node_Select_Default_7, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, int32 K2Node_Event_Count_1, int32 K2Node_Event_Max_Count_1, bool K2Node_Event_Use_Custom_Counter_1, bool K2Node_Select_Default_8, int32 K2Node_Event_Count, int32 K2Node_Event_Max_Count, bool K2Node_Event_Use_Custom_Counter, APawn* CallFunc_GetPlayerPawn_ReturnValue, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, APawn* CallFunc_GetPlayerPawn_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_8, APawn* CallFunc_GetPlayerPawn_ReturnValue_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_9, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_64, FVector CallFunc_K2_GetActorLocation_ReturnValue_10, int32 CallFunc_PostEventAtLocation_ReturnValue_16, FVector CallFunc_Add_VectorVector_ReturnValue_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_11, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_17, float K2Node_CustomEvent_IntensityFire, float K2Node_Event_Delay, float K2Node_Event_Rotation, float K2Node_Event_Scale, float CallFunc_Multiply_FloatFloat_ReturnValue_4, FVector CallFunc_GetRightVector_ReturnValue_2, FVector CallFunc_MakeVector_ReturnValue_10, FVector CallFunc_Multiply_VectorFloat_ReturnValue_4, FVector CallFunc_K2_GetActorLocation_ReturnValue_12, FRotator CallFunc_Conv_VectorToRotator_ReturnValue, FVector CallFunc_Subtract_VectorVector_ReturnValue_2, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, FRotator CallFunc_MakeRotator_ReturnValue_3, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_2, FParticleSysParam K2Node_MakeStruct_ParticleSysParam, TArray<FParticleSysParam>& K2Node_MakeArray_Array_1, bool CallFunc_Not_PreBool_ReturnValue_1, bool K2Node_CustomEvent_Show_6, bool CallFunc_Not_PreBool_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue, uint8 K2Node_Select_Default_9, float CallFunc_Lerp_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_4, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_5, bool CallFunc_IsValid_ReturnValue_5, float K2Node_Select_Default_10, float CallFunc_ApplyDamage_ReturnValue, float K2Node_Select_Default_11, int32 CallFunc_PostEventAtLocation_ReturnValue_18, int32 CallFunc_PostEventAtLocation_ReturnValue_19, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_6, FVector CallFunc_K2_GetActorLocation_ReturnValue_13, int32 CallFunc_PostEventAtLocation_ReturnValue_20, bool CallFunc_IsValid_ReturnValue_6, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue_2, UParticleSystem* K2Node_Select_Default_12, int32 K2Node_Select_Default_13, bool K2Node_SwitchInteger_CmpSuccess_3, FVector K2Node_Select_Default_14, APawn* CallFunc_GetPlayerPawn_ReturnValue_4, FVector K2Node_Event_New_Location, ULevelSequence* K2Node_Select_Default_15, bool CallFunc_IsRobiValid_ReturnValue, ALevelSequenceActor* CallFunc_CreateLevelSequencePlayer_OutActor, ULevelSequencePlayer* CallFunc_CreateLevelSequencePlayer_ReturnValue, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, float CallFunc_Cutscene_OutputPin, bool CallFunc_K2_SetActorRotation_ReturnValue, float CallFunc_Cutscene_OutputPin_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_7, bool CallFunc_IsValid_ReturnValue_7, float CallFunc_Cutscene_OutputPin_2, bool Temp_bool_Variable_8, bool CallFunc_Not_PreBool_ReturnValue_3, FVector CallFunc_GetSocketLocation_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_3, FVector CallFunc_GetSocketLocation_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_2, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_8, bool CallFunc_IsValid_ReturnValue_8, int32 CallFunc_PostEventAtLocation_ReturnValue_21, int32 CallFunc_RandomIntegerInRange_ReturnValue_2, UAnimMontage* K2Node_Select_Default_16, float CallFunc_PlayAnimMontage_ReturnValue_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue, FRotator CallFunc_K2_GetActorRotation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_14, FHitResult CallFunc_K2_SetActorLocationAndRotation_SweepHitResult, bool CallFunc_K2_SetActorLocationAndRotation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_22, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_23, int32 CallFunc_PostEventAtLocation_ReturnValue_24, bool CallFunc_EqualEqual_IntInt_ReturnValue_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_25, int32 CallFunc_PostEventAtLocation_ReturnValue_26, bool CallFunc_EqualEqual_IntInt_ReturnValue_6, bool CallFunc_EqualEqual_IntInt_ReturnValue_7, int32 CallFunc_PostEventAtLocation_ReturnValue_27, int32 CallFunc_PostEventAtLocation_ReturnValue_28, FVector CallFunc_K2_GetActorLocation_ReturnValue_15, int32 CallFunc_PostEventAtLocation_ReturnValue_29, int32 CallFunc_PostEventAtLocation_ReturnValue_30, APawn* CallFunc_GetPlayerPawn_ReturnValue_5, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_9, bool CallFunc_IsValid_ReturnValue_9, float K2Node_Event_Damage, const UDamageType* K2Node_Event_DamageType, AController* K2Node_Event_InstigatedBy, AActor* K2Node_Event_DamageCauser, TSubclassOf<UDamageType> CallFunc_GetObjectClass_ReturnValue, bool CallFunc_RecieveHit_Dead, bool CallFunc_EqualEqual_ClassClass_ReturnValue, bool K2Node_CustomEvent_Show_5, bool K2Node_CustomEvent_Instant, bool K2Node_CustomEvent_Delay, float K2Node_CustomEvent_Delay_Time, float K2Node_CustomEvent_Play_Rate, int32 CallFunc_Add_IntInt_ReturnValue_3, FVector CallFunc_GetSocketLocation_ReturnValue_2, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_5, UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, ULord_1_Skeleton_AnimBlueprint_C* K2Node_DynamicCast_AsLord_1_Skeleton_Anim_Blueprint, bool K2Node_DynamicCast_bSuccess, APawn* CallFunc_GetPlayerPawn_ReturnValue_6, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_31, bool CallFunc_IsRobiValid_ReturnValue_1, float CallFunc_NormalizeToRange_ReturnValue, FName K2Node_CustomEvent_NotifyName_64, float K2Node_Select_Default_17, bool K2Node_SwitchInteger_CmpSuccess_4, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_10, bool CallFunc_IsValid_ReturnValue_10, bool K2Node_CustomEvent_Show_4, float K2Node_Select_Default_18, float K2Node_Select_Default_19, bool CallFunc_Less_FloatFloat_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_65, bool K2Node_Event_CheckPlayerIsDead, bool K2Node_CustomEvent_Show_3, int32 CallFunc_PostEventAtLocation_ReturnValue_32, int32 CallFunc_PostEventAtLocation_ReturnValue_33, FVector CallFunc_K2_GetActorLocation_ReturnValue_16, int32 CallFunc_PostEventAtLocation_ReturnValue_34, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_11, bool K2Node_CustomEvent_Show_2, bool CallFunc_IsValid_ReturnValue_11, bool K2Node_CustomEvent_Show_1, bool K2Node_Event_Move_1, bool K2Node_Event_Move, bool K2Node_CustomEvent_Show, float K2Node_Select_Default_20, int32 Temp_int_Variable_15, bool K2Node_SwitchInteger_CmpSuccess_5, int32 Temp_int_Variable_16, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue_11, FVector CallFunc_GetRightVector_ReturnValue_3, FVector CallFunc_Multiply_VectorFloat_ReturnValue_5, FRotator CallFunc_Conv_VectorToRotator_ReturnValue_1, float CallFunc_BreakRotator_Roll_1, float CallFunc_BreakRotator_Pitch_1, float CallFunc_BreakRotator_Yaw_1, float CallFunc_ApplyDamage_ReturnValue_1, FRotator CallFunc_MakeRotator_ReturnValue_4, FRotator CallFunc_MakeRotator_ReturnValue_5, UPrimitiveComponent* K2Node_Event_MyComp, AActor* K2Node_Event_Other, UPrimitiveComponent* K2Node_Event_OtherComp, bool K2Node_Event_bSelfMoved, FVector K2Node_Event_HitLocation, FVector K2Node_Event_HitNormal, FVector K2Node_Event_NormalImpulse, const FHitResult K2Node_Event_Hit, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_2, bool CallFunc_Not_PreBool_ReturnValue_4, ABP_BossRoom_1_C* K2Node_DynamicCast_AsBP_Boss_Room_1, bool K2Node_DynamicCast_bSuccess_1, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, float K2Node_Select_Default_21, FVector CallFunc_K2_GetActorLocation_ReturnValue_17, FString CallFunc_CheckState_Same_ID, bool CallFunc_CheckState_Used, int32 CallFunc_PostEventAtLocation_ReturnValue_35, int32 CallFunc_PostEventAtLocation_ReturnValue_36, int32 CallFunc_PostEventAtLocation_ReturnValue_37, FVector CallFunc_K2_GetActorLocation_ReturnValue_18, FVector CallFunc_Add_VectorVector_ReturnValue_6, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_6, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_7, int32 Temp_int_Variable_17, UAnimMontage* CallFunc_GetCurrentMontage_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_2, APawn* CallFunc_GetPlayerPawn_ReturnValue_7, FVector CallFunc_K2_GetActorLocation_ReturnValue_19, float CallFunc_ApplyDamage_ReturnValue_2, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_12, bool CallFunc_IsValid_ReturnValue_12, FVector CallFunc_K2_GetActorLocation_ReturnValue_20, int32 CallFunc_PostEventAtLocation_ReturnValue_38, float CallFunc_PlayAnimMontage_ReturnValue_2);
    void FaseChange__DelegateSignature(int32 Fase);
}

#endif
