#ifndef UE4SS_SDK_BP_Fire_Centry_HPP
#define UE4SS_SDK_BP_Fire_Centry_HPP

class ABP_Fire_Centry_C : UEnemy_Character_Parent_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    USceneComponent* ScenePOI;
    UParticleSystemComponent* P_Implosion_Warm;
    UParticleSystemComponent* Explosion;
    USphereComponent* Sphere;
    float Timeline_1_0A_Dissolve_BB1F04E347DA729F13777BA8AACE7568;
    TEnumAsByte<ETimelineDirection::Type> Timeline_1_0A__Direction_BB1F04E347DA729F13777BA8AACE7568;
    UTimelineComponent* Timeline_1_0A;
    FVector MoveBackDire_0;
    FVector MoveBackOriginal_0;
    UMaterialInstanceDynamic* New BodyMaterial;
    AEnemy_Character_Parent_C* Father;
    bool Play Show Montange;
    bool IsBoss;
    float Custom Damage;
    UAkAudioEvent* SoundCentryAttackExplosion;
    UAkAudioEvent* SoundCentryAttackCharge;
    float Radius Explode;

    void UserConstructionScript(FParticleSysParam K2Node_MakeStruct_ParticleSysParam, TArray<FParticleSysParam>& K2Node_MakeArray_Array);
    void Timeline_1_0A__FinishedFunc();
    void Timeline_1_0A__UpdateFunc();
    void OnNotifyEnd_32C43296423EC7616D7BCCAAC90440AA(FName NotifyName);
    void OnNotifyBegin_32C43296423EC7616D7BCCAAC90440AA(FName NotifyName);
    void OnInterrupted_32C43296423EC7616D7BCCAAC90440AA(FName NotifyName);
    void OnBlendOut_32C43296423EC7616D7BCCAAC90440AA(FName NotifyName);
    void OnCompleted_32C43296423EC7616D7BCCAAC90440AA(FName NotifyName);
    void OnNotifyEnd_3AC915E34C3954EE0EFAAFAEA3FF4ADB(FName NotifyName);
    void OnNotifyBegin_3AC915E34C3954EE0EFAAFAEA3FF4ADB(FName NotifyName);
    void OnInterrupted_3AC915E34C3954EE0EFAAFAEA3FF4ADB(FName NotifyName);
    void OnBlendOut_3AC915E34C3954EE0EFAAFAEA3FF4ADB(FName NotifyName);
    void OnCompleted_3AC915E34C3954EE0EFAAFAEA3FF4ADB(FName NotifyName);
    void OnNotifyEnd_EEE6EBDC4C97DBE8D006D7ACB3F06C14(FName NotifyName);
    void OnNotifyBegin_EEE6EBDC4C97DBE8D006D7ACB3F06C14(FName NotifyName);
    void OnInterrupted_EEE6EBDC4C97DBE8D006D7ACB3F06C14(FName NotifyName);
    void OnBlendOut_EEE6EBDC4C97DBE8D006D7ACB3F06C14(FName NotifyName);
    void OnCompleted_EEE6EBDC4C97DBE8D006D7ACB3F06C14(FName NotifyName);
    void OnNotifyEnd_335ECA8F4BD02A9511F83F897EFD9CC6(FName NotifyName);
    void OnNotifyBegin_335ECA8F4BD02A9511F83F897EFD9CC6(FName NotifyName);
    void OnInterrupted_335ECA8F4BD02A9511F83F897EFD9CC6(FName NotifyName);
    void OnBlendOut_335ECA8F4BD02A9511F83F897EFD9CC6(FName NotifyName);
    void OnCompleted_335ECA8F4BD02A9511F83F897EFD9CC6(FName NotifyName);
    void OnNotifyEnd_0081E35245FE20B70BDDD895BC69E743(FName NotifyName);
    void OnNotifyBegin_0081E35245FE20B70BDDD895BC69E743(FName NotifyName);
    void OnInterrupted_0081E35245FE20B70BDDD895BC69E743(FName NotifyName);
    void OnBlendOut_0081E35245FE20B70BDDD895BC69E743(FName NotifyName);
    void OnCompleted_0081E35245FE20B70BDDD895BC69E743(FName NotifyName);
    void Attack01(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Explode();
    void MoveIn();
    void Attack03(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Start Agro(bool Start);
    void RetriggerSound();
    void Instant Combat Extra();
    void ReceiveAnyDamage(float Damage, const UDamageType* DamageType, AController* InstigatedBy, AActor* DamageCauser);
    void ReceiveBeginPlay();
    void ReceiveHit(UPrimitiveComponent* MyComp, AActor* Other, UPrimitiveComponent* OtherComp, bool bSelfMoved, FVector HitLocation, FVector HitNormal, FVector NormalImpulse, const FHitResult& Hit);
    void ExecuteUbergraph_BP_Fire_Centry(int32 EntryPoint, FName K2Node_CustomEvent_NotifyName_21, FName K2Node_CustomEvent_NotifyName_20, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FName Temp_name_Variable, bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, const TArray<AActor*>& Temp_object_Variable, FName K2Node_CustomEvent_NotifyName_19, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FName K2Node_CustomEvent_NotifyName_18, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FName K2Node_CustomEvent_NotifyName_17, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, FName K2Node_CustomEvent_NotifyName_16, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, FName K2Node_CustomEvent_NotifyName_15, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, FName Temp_name_Variable_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, FName K2Node_CustomEvent_NotifyName_14, FName K2Node_CustomEvent_NotifyName_13, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, FName K2Node_CustomEvent_NotifyName_12, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, FName K2Node_CustomEvent_NotifyName_11, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, FName K2Node_CustomEvent_NotifyName_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, FName Temp_name_Variable_2, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_11, FName K2Node_CustomEvent_NotifyName_9, FName K2Node_CustomEvent_NotifyName_8, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_12, FName K2Node_CustomEvent_NotifyName_7, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_13, FName K2Node_CustomEvent_NotifyName_6, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_14, FName K2Node_CustomEvent_NotifyName_5, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_15, FName Temp_name_Variable_3, bool Temp_bool_Variable_1, UAnimMontage* Temp_object_Variable_1, UAnimMontage* Temp_object_Variable_2, uint8 Temp_byte_Variable_2, UBehaviorTree* Temp_object_Variable_3, UBehaviorTree* Temp_object_Variable_4, UBehaviorTree* Temp_object_Variable_5, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_16, FName K2Node_CustomEvent_NotifyName_4, FName K2Node_CustomEvent_NotifyName_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_17, FName K2Node_CustomEvent_NotifyName_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_18, FName K2Node_CustomEvent_NotifyName_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_19, FName K2Node_CustomEvent_NotifyName, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_20, FName Temp_name_Variable_4, bool Temp_bool_Has_Been_Initd_Variable, APawn* CallFunc_GetPlayerPawn_ReturnValue, bool Temp_bool_Variable_2, FName K2Node_CustomEvent_NotifyName_23, UAnimMontage* K2Node_Select_Default, bool CallFunc_Not_PreBool_ReturnValue, int32 K2Node_Event_Count_1, int32 K2Node_Event_Max_Count_1, bool K2Node_Event_Use_Custom_Counter_1, bool Temp_bool_IsClosed_Variable, FVector CallFunc_K2_GetActorLocation_ReturnValue, const TArray<uint8>& K2Node_MakeArray_Array, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, FVector CallFunc_MakeVector_ReturnValue, FVector CallFunc_GetDirectionUnitVector_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue, FVector CallFunc_Add_VectorVector_ReturnValue, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult, bool CallFunc_K2_SetActorLocation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, int32 CallFunc_PostEventAtLocation_ReturnValue, int32 K2Node_Event_Count, int32 K2Node_Event_Max_Count, bool K2Node_Event_Use_Custom_Counter, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_21, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, uint8 K2Node_Select_Default_1, bool CallFunc_IsValid_ReturnValue_2, float CallFunc_GetActorTimeDilation_ReturnValue, bool CallFunc_EqualEqual_FloatFloat_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1, APawn* CallFunc_GetPlayerPawn_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_3, FTimerHandle CallFunc_K2_SetTimer_ReturnValue, bool K2Node_Event_Start, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, int32 CallFunc_PostEventAtLocation_ReturnValue_2, float CallFunc_RandomFloatInRange_ReturnValue, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_22, FName K2Node_CustomEvent_NotifyName_24, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, bool CallFunc_IsValid_ReturnValue_4, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_23, FHitResult CallFunc_SphereTraceSingleForObjects_OutHit, bool CallFunc_SphereTraceSingleForObjects_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, FVector CallFunc_BreakHitResult_Location, FVector CallFunc_BreakHitResult_ImpactPoint, FVector CallFunc_BreakHitResult_Normal, FVector CallFunc_BreakHitResult_ImpactNormal, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, AActor* CallFunc_BreakHitResult_HitActor, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, FName CallFunc_BreakHitResult_HitBoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_FaceIndex, FVector CallFunc_BreakHitResult_TraceStart, FVector CallFunc_BreakHitResult_TraceEnd, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue, float CallFunc_ApplyDamage_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, float K2Node_Event_Damage, const UDamageType* K2Node_Event_DamageType, AController* K2Node_Event_InstigatedBy, AActor* K2Node_Event_DamageCauser, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, bool CallFunc_RecieveHit_Dead, FName K2Node_CustomEvent_NotifyName_22, bool Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_24, bool Temp_bool_Has_Been_Initd_Variable_1, bool Temp_bool_Has_Been_Initd_Variable_2, UPrimitiveComponent* K2Node_Event_MyComp, AActor* K2Node_Event_Other, UPrimitiveComponent* K2Node_Event_OtherComp, bool K2Node_Event_bSelfMoved, FVector K2Node_Event_HitLocation, FVector K2Node_Event_HitNormal, FVector K2Node_Event_NormalImpulse, const FHitResult K2Node_Event_Hit, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3, UPlayer_Character_BP_C* K2Node_DynamicCast_AsPlayer_Character_BP, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_8, int32 CallFunc_PostEventAtLocation_ReturnValue_3, bool Temp_bool_IsClosed_Variable_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_9, int32 CallFunc_PostEventAtLocation_ReturnValue_4, float CallFunc_ApplyDamage_ReturnValue_1, bool Temp_bool_IsClosed_Variable_2, UBehaviorTree* K2Node_Select_Default_2, int32 CallFunc_PostEventAtLocation_ReturnValue_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_10, UMaterialInterface* CallFunc_GetMaterial_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_6, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, TArray<FName>& K2Node_MakeArray_Array_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_6, FVector CallFunc_K2_GetActorLocation_ReturnValue_11, int32 CallFunc_PostEventAtLocation_ReturnValue_7);
}

#endif
