#ifndef UE4SS_SDK_BP_Penumbra_HPP
#define UE4SS_SDK_BP_Penumbra_HPP

class ABP_Penumbra_C : UEnemy_Character_Parent_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    USceneComponent* ScenePOI;
    USceneComponent* Scene;
    UParticleSystemComponent* P_Goddess_Prewarm;
    UAkComponent* Ak;
    UBillboardComponent* Billboard;
    UParticleSystemComponent* P_Scream;
    UArrowComponent* Arrow_Forward;
    USphereComponent* Shield Collider;
    UStaticMeshComponent* Shield;
    UParticleSystemComponent* P_Laser;
    UCapsuleComponent* Collider;
    UBillboardComponent* NewPlayerLocation;
    UArrowComponent* Spawn;
    float Timeline_2_Alpha_FF615C394EC803A50A20F2B057BAEF0D;
    TEnumAsByte<ETimelineDirection::Type> Timeline_2__Direction_FF615C394EC803A50A20F2B057BAEF0D;
    UTimelineComponent* Timeline_2;
    float BlankifyTimeline_Alpha_3AD9B2BC4D181472E5D585AA3E9ED45F;
    TEnumAsByte<ETimelineDirection::Type> BlankifyTimeline__Direction_3AD9B2BC4D181472E5D585AA3E9ED45F;
    UTimelineComponent* BlankifyTimeline;
    float DarkenBody_Alpha_5F293CFC4C04B02DBF349196CD169AF5;
    TEnumAsByte<ETimelineDirection::Type> DarkenBody__Direction_5F293CFC4C04B02DBF349196CD169AF5;
    UTimelineComponent* DarkenBody;
    float Timeline_1_0_Darkness_675269D14A9D6F8D612665AA99624E5E;
    TEnumAsByte<ETimelineDirection::Type> Timeline_1_0__Direction_675269D14A9D6F8D612665AA99624E5E;
    UTimelineComponent* Timeline_1_0;
    float Expand_Shield_Lerp_Scale_4396F9264D6EF5F5082B8D88F17C6CB0;
    TEnumAsByte<ETimelineDirection::Type> Expand_Shield__Direction_4396F9264D6EF5F5082B8D88F17C6CB0;
    UTimelineComponent* Expand Shield;
    float Darkness_Darkness_7F18D3674F2987645C4C47A709ED06DD;
    TEnumAsByte<ETimelineDirection::Type> Darkness__Direction_7F18D3674F2987645C4C47A709ED06DD;
    UTimelineComponent* Darkness;
    float Blur_Blue_Small_0872E4974A0FC59FA44D739CCA891717;
    float Blur_Blur_Large_0872E4974A0FC59FA44D739CCA891717;
    TEnumAsByte<ETimelineDirection::Type> Blur__Direction_0872E4974A0FC59FA44D739CCA891717;
    UTimelineComponent* Blur;
    float Show_Shield_Lerp_0377C70E435CA4E1A8BDFDAEB32604A7;
    TEnumAsByte<ETimelineDirection::Type> Show_Shield__Direction_0377C70E435CA4E1A8BDFDAEB32604A7;
    UTimelineComponent* Show Shield;
    AActor* StartCam;
    AGoddess_MainPlatform_C* MainField;
    ALight_Goddess_Platform_BP_C* LightGoddessPlatform;
    bool CurrentPlatformA;
    ALight_Goddess_Platform_BP_C* LightGoddessPlatform2;
    FVector OriginalLocation;
    FBP_Penumbra_CCallB CallB;
    void CallB();
    AActor* Target;
    AGoddess_SphereAttack_C* SphereAttack;
    int32 BombHits;
    int32 LastRotation;
    int32 NextRotation;
    FString ID;
    AActor* Boss Room Actor;
    AActor* Cutscene Camera;
    ULevelSequence* Cutscene Change Fase;
    bool Changing Fase;
    int32 Attack Counter;
    bool Is Shield Visible;
    UPenumbraSkelMesh_Skeleton_AnimBlueprint_C* Anim Inst;
    int32 Amount Minion;
    int32 Max Minions;
    float Fase_04_Damage;
    float Health To Fase 4;
    int32 Current Minions;
    ABP_BossRoom_Goddess_C* Boss Room;
    FVector Laser Hit Location;
    bool Is Custom Teleport;
    bool Hit State;
    bool Is Clon Visible;
    UMaterialInstanceDynamic* Mat Body;
    bool Can Shield Stop Expand;
    bool CanReceiveDamage;
    float Darkness Play Rate;
    bool Is Darkness;
    int32 Max Attack Counter;
    UAnimMontage* Current Anim Montage;
    float Laser Window;
    bool Cancel Laser;
    int32 Index Hit Received;
    bool Is Shield Expanding;
    UMaterialInstanceDynamic* Mat Eye;
    int32 ExpandSound;
    int32 StunCry;
    UMaterialInstanceDynamic* Mat Body Dark;
    UMaterialInstanceDynamic* Mat Body Normal;
    bool QueenIsDead;
    bool BattleEnd;
    AActor* TargetLocation;

    void Darkness__FinishedFunc();
    void Darkness__UpdateFunc();
    void Blur__FinishedFunc();
    void Blur__UpdateFunc();
    void Expand Shield__FinishedFunc();
    void Expand Shield__UpdateFunc();
    void Expand Shield__Audio__EventFunc();
    void Show Shield__FinishedFunc();
    void Show Shield__UpdateFunc();
    void Timeline_1_0__FinishedFunc();
    void Timeline_1_0__UpdateFunc();
    void DarkenBody__FinishedFunc();
    void DarkenBody__UpdateFunc();
    void BlankifyTimeline__FinishedFunc();
    void BlankifyTimeline__UpdateFunc();
    void Timeline_2__FinishedFunc();
    void Timeline_2__UpdateFunc();
    void OnNotifyEnd_2822CFCE4187AC154BE0BBB1624A0043(FName NotifyName);
    void OnNotifyBegin_2822CFCE4187AC154BE0BBB1624A0043(FName NotifyName);
    void OnInterrupted_2822CFCE4187AC154BE0BBB1624A0043(FName NotifyName);
    void OnBlendOut_2822CFCE4187AC154BE0BBB1624A0043(FName NotifyName);
    void OnCompleted_2822CFCE4187AC154BE0BBB1624A0043(FName NotifyName);
    void OnNotifyEnd_D64A715F490E9C6811803BA3ACE9DE11(FName NotifyName);
    void OnNotifyBegin_D64A715F490E9C6811803BA3ACE9DE11(FName NotifyName);
    void OnInterrupted_D64A715F490E9C6811803BA3ACE9DE11(FName NotifyName);
    void OnBlendOut_D64A715F490E9C6811803BA3ACE9DE11(FName NotifyName);
    void OnCompleted_D64A715F490E9C6811803BA3ACE9DE11(FName NotifyName);
    void OnNotifyEnd_415CB91041C35E5F993ED2BC70175737(FName NotifyName);
    void OnNotifyBegin_415CB91041C35E5F993ED2BC70175737(FName NotifyName);
    void OnInterrupted_415CB91041C35E5F993ED2BC70175737(FName NotifyName);
    void OnBlendOut_415CB91041C35E5F993ED2BC70175737(FName NotifyName);
    void OnCompleted_415CB91041C35E5F993ED2BC70175737(FName NotifyName);
    void OnNotifyEnd_A694DD7E413C590DCD44B58F88829AE9(FName NotifyName);
    void OnNotifyBegin_A694DD7E413C590DCD44B58F88829AE9(FName NotifyName);
    void OnInterrupted_A694DD7E413C590DCD44B58F88829AE9(FName NotifyName);
    void OnBlendOut_A694DD7E413C590DCD44B58F88829AE9(FName NotifyName);
    void OnCompleted_A694DD7E413C590DCD44B58F88829AE9(FName NotifyName);
    void OnNotifyEnd_3030E9104F51A281A4A04F9517266E12(FName NotifyName);
    void OnNotifyBegin_3030E9104F51A281A4A04F9517266E12(FName NotifyName);
    void OnInterrupted_3030E9104F51A281A4A04F9517266E12(FName NotifyName);
    void OnBlendOut_3030E9104F51A281A4A04F9517266E12(FName NotifyName);
    void OnCompleted_3030E9104F51A281A4A04F9517266E12(FName NotifyName);
    void OnNotifyEnd_E3A33C394A8EB0D84FB576B7A0280E56(FName NotifyName);
    void OnNotifyBegin_E3A33C394A8EB0D84FB576B7A0280E56(FName NotifyName);
    void OnInterrupted_E3A33C394A8EB0D84FB576B7A0280E56(FName NotifyName);
    void OnBlendOut_E3A33C394A8EB0D84FB576B7A0280E56(FName NotifyName);
    void OnCompleted_E3A33C394A8EB0D84FB576B7A0280E56(FName NotifyName);
    void OnNotifyEnd_62CAF3A14FCFD090BF63E3B178F77BCE(FName NotifyName);
    void OnNotifyBegin_62CAF3A14FCFD090BF63E3B178F77BCE(FName NotifyName);
    void OnInterrupted_62CAF3A14FCFD090BF63E3B178F77BCE(FName NotifyName);
    void OnBlendOut_62CAF3A14FCFD090BF63E3B178F77BCE(FName NotifyName);
    void OnCompleted_62CAF3A14FCFD090BF63E3B178F77BCE(FName NotifyName);
    void OnNotifyEnd_20D2304844B4F6838EB609A1B707519F(FName NotifyName);
    void OnNotifyBegin_20D2304844B4F6838EB609A1B707519F(FName NotifyName);
    void OnInterrupted_20D2304844B4F6838EB609A1B707519F(FName NotifyName);
    void OnBlendOut_20D2304844B4F6838EB609A1B707519F(FName NotifyName);
    void OnCompleted_20D2304844B4F6838EB609A1B707519F(FName NotifyName);
    void OnNotifyEnd_178D8EA3497642F6EA57A097E33D12DC(FName NotifyName);
    void OnNotifyBegin_178D8EA3497642F6EA57A097E33D12DC(FName NotifyName);
    void OnInterrupted_178D8EA3497642F6EA57A097E33D12DC(FName NotifyName);
    void OnBlendOut_178D8EA3497642F6EA57A097E33D12DC(FName NotifyName);
    void OnCompleted_178D8EA3497642F6EA57A097E33D12DC(FName NotifyName);
    void OnNotifyEnd_A82A7CA34DF98E3E9E9C23A89D257D7F(FName NotifyName);
    void OnNotifyBegin_A82A7CA34DF98E3E9E9C23A89D257D7F(FName NotifyName);
    void OnInterrupted_A82A7CA34DF98E3E9E9C23A89D257D7F(FName NotifyName);
    void OnBlendOut_A82A7CA34DF98E3E9E9C23A89D257D7F(FName NotifyName);
    void OnCompleted_A82A7CA34DF98E3E9E9C23A89D257D7F(FName NotifyName);
    void OnNotifyEnd_53319A6A42BA95BB65FB8688CD222865(FName NotifyName);
    void OnNotifyBegin_53319A6A42BA95BB65FB8688CD222865(FName NotifyName);
    void OnInterrupted_53319A6A42BA95BB65FB8688CD222865(FName NotifyName);
    void OnBlendOut_53319A6A42BA95BB65FB8688CD222865(FName NotifyName);
    void OnCompleted_53319A6A42BA95BB65FB8688CD222865(FName NotifyName);
    void OnNotifyEnd_5245F82E4E65E366FFFC72B438324321(FName NotifyName);
    void OnNotifyBegin_5245F82E4E65E366FFFC72B438324321(FName NotifyName);
    void OnInterrupted_5245F82E4E65E366FFFC72B438324321(FName NotifyName);
    void OnBlendOut_5245F82E4E65E366FFFC72B438324321(FName NotifyName);
    void OnCompleted_5245F82E4E65E366FFFC72B438324321(FName NotifyName);
    void OnNotifyEnd_6D847B274AD4C9A8173E90BD32D87487(FName NotifyName);
    void OnNotifyBegin_6D847B274AD4C9A8173E90BD32D87487(FName NotifyName);
    void OnInterrupted_6D847B274AD4C9A8173E90BD32D87487(FName NotifyName);
    void OnBlendOut_6D847B274AD4C9A8173E90BD32D87487(FName NotifyName);
    void OnCompleted_6D847B274AD4C9A8173E90BD32D87487(FName NotifyName);
    void OnNotifyEnd_5EFADE4643F7EE1898C1EEAE4689137C(FName NotifyName);
    void OnNotifyBegin_5EFADE4643F7EE1898C1EEAE4689137C(FName NotifyName);
    void OnInterrupted_5EFADE4643F7EE1898C1EEAE4689137C(FName NotifyName);
    void OnBlendOut_5EFADE4643F7EE1898C1EEAE4689137C(FName NotifyName);
    void OnCompleted_5EFADE4643F7EE1898C1EEAE4689137C(FName NotifyName);
    void OnNotifyEnd_8DA775E3454849C6054E7BA2E1061690(FName NotifyName);
    void OnNotifyBegin_8DA775E3454849C6054E7BA2E1061690(FName NotifyName);
    void OnInterrupted_8DA775E3454849C6054E7BA2E1061690(FName NotifyName);
    void OnBlendOut_8DA775E3454849C6054E7BA2E1061690(FName NotifyName);
    void OnCompleted_8DA775E3454849C6054E7BA2E1061690(FName NotifyName);
    void OnNotifyEnd_6DAE37E14557A01865436E8C2DF001D7(FName NotifyName);
    void OnNotifyBegin_6DAE37E14557A01865436E8C2DF001D7(FName NotifyName);
    void OnInterrupted_6DAE37E14557A01865436E8C2DF001D7(FName NotifyName);
    void OnBlendOut_6DAE37E14557A01865436E8C2DF001D7(FName NotifyName);
    void OnCompleted_6DAE37E14557A01865436E8C2DF001D7(FName NotifyName);
    void VFX Glow(bool Show);
    void VFX Scream();
    void VFX Darkness(bool Show);
    void Force Close Shield();
    void ReceiveDestroyed();
    void ReceiveEndPlay(uint8 EndPlayReason);
    void StartBoss();
    void VFX Shield Expand(bool Reset);
    void VFX Shield Show(bool Show, bool Instant);
    void Set Visibility UI(bool Visibility);
    void Boss Appear();
    void Boss Desappear();
    void Relocate Player();
    void EndBoss();
    void Radial Blur();
    void Ignore Stop Time(bool Ignore);
    void Stun Boss();
    void PostProcess();
    void PlayCustomCutsceneExtra();
    void ResumeCustomCutsceneExtra();
    void EndMusicPenumbra();
    void EventGoddessPain();
    void EventGoddessImplosion();
    void DestroyQueen();
    void Beat Game();
    void DieVFX();
    void StopAnim();
    void PerformAttack();
    void Attack01(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Attack02(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Attack03(int32 Count, int32 Max Count, bool Use Custom Counter);
    void VFX Smoke Spawn();
    void Remove Minion();
    void Attack04(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Laser Aim();
    void Laser Shoot();
    void Laser Cancel();
    void BndEvt__Shield Collider_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void Call Event(FString Event Name);
    void Call Show Shield();
    void Call Hide Shield();
    void Call Attack Line Wave Play();
    void Call Attack Wave Play();
    void Call Attack Wave Stop();
    void Call Attack Line Wave Stop();
    void Call Teleport Random Show();
    void Call Teleport Random Hide();
    void Call Reset Hit State();
    void Call Attack Light Trap Play();
    void Call Attack Light Trap Stop();
    void Check Clon State(bool Is Goddess);
    void Call Teleport Clon Hide();
    void Call Teleport Clon Show();
    void Attack05(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Call Destroy Clone();
    void Area Damage(float Radius);
    void Call Laser Tired();
    void Break Combat();
    void Detect Player Inside Shield();
    void ReceiveAnyDamage(float Damage, const UDamageType* DamageType, AController* InstigatedBy, AActor* DamageCauser);
    void ReceiveBeginPlay();
    void Fase Change();
    void On Player Die();
    void TeleportInExtra();
    void TeleportOutExtra();
    void MoveTrail();
    void TeleportOut();
    void TeleportIn();
    void Custom Teleport(bool In);
    void Restart();
    void Back to Agro();
    void Teleport Stunned();
    void Make Stun();
    void VFX Shield Stop Expand();
    void Force MidFase();
    void DebugEnding();
    void Blankify();
    void Glow();
    void Reset State();
    void Clear State();
    void GA SendEvent();
    void ExecuteUbergraph_BP_Penumbra(int32 EntryPoint, FName K2Node_CustomEvent_NotifyName_71, FName K2Node_CustomEvent_NotifyName_70, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FName Temp_name_Variable, bool Temp_bool_Variable, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_1, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_1, int32 Temp_int_Variable, float Temp_float_Variable, float Temp_float_Variable_1, float Temp_float_Variable_2, float Temp_float_Variable_3, float Temp_float_Variable_4, int32 Temp_int_Variable_1, float Temp_float_Variable_5, float Temp_float_Variable_6, float Temp_float_Variable_7, float Temp_float_Variable_8, float Temp_float_Variable_9, int32 Temp_int_Variable_2, int32 Temp_int_Variable_3, float Temp_float_Variable_10, float Temp_float_Variable_11, float Temp_float_Variable_12, float Temp_float_Variable_13, float Temp_float_Variable_14, float CallFunc_Lerp_ReturnValue, int32 Temp_int_Variable_4, FVector CallFunc_Conv_FloatToVector_ReturnValue, float Temp_float_Variable_15, float Temp_float_Variable_16, float Temp_float_Variable_17, float Temp_float_Variable_18, float Temp_float_Variable_19, int32 Temp_int_Variable_5, float Temp_float_Variable_20, float Temp_float_Variable_21, float Temp_float_Variable_22, float Temp_float_Variable_23, float Temp_float_Variable_24, int32 Temp_int_Variable_6, bool Temp_bool_Variable_1, ESlateVisibility Temp_byte_Variable_2, ESlateVisibility Temp_byte_Variable_3, int32 Temp_int_Variable_7, float Temp_float_Variable_25, float Temp_float_Variable_26, float Temp_float_Variable_27, float Temp_float_Variable_28, float Temp_float_Variable_29, int32 Temp_int_Variable_8, float Temp_float_Variable_30, bool Temp_bool_Variable_2, float Temp_float_Variable_31, bool Temp_bool_Variable_3, FName K2Node_CustomEvent_NotifyName_69, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FName K2Node_CustomEvent_NotifyName_68, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FName K2Node_CustomEvent_NotifyName_67, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, FName K2Node_CustomEvent_NotifyName_66, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, FName K2Node_CustomEvent_NotifyName_65, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, FName Temp_name_Variable_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, FName K2Node_CustomEvent_NotifyName_64, FName K2Node_CustomEvent_NotifyName_63, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, FName K2Node_CustomEvent_NotifyName_62, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, FName K2Node_CustomEvent_NotifyName_61, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, FName K2Node_CustomEvent_NotifyName_60, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, FName Temp_name_Variable_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_11, FName K2Node_CustomEvent_NotifyName_59, FName K2Node_CustomEvent_NotifyName_58, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_12, FName K2Node_CustomEvent_NotifyName_57, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_13, FName K2Node_CustomEvent_NotifyName_56, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_14, FName K2Node_CustomEvent_NotifyName_55, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_15, FName Temp_name_Variable_3, int32 Temp_int_Variable_9, float Temp_float_Variable_32, float Temp_float_Variable_33, float Temp_float_Variable_34, float Temp_float_Variable_35, float Temp_float_Variable_36, int32 Temp_int_Variable_10, OnMovieSceneSequencePlayerEvent__DelegateSignature K2Node_CreateDelegate_OutputDelegate_16, float Temp_float_Variable_37, float Temp_float_Variable_38, float Temp_float_Variable_39, float Temp_float_Variable_40, float Temp_float_Variable_41, const TArray<AActor*>& Temp_object_Variable, bool Temp_bool_Variable_4, uint8 Temp_byte_Variable_4, uint8 Temp_byte_Variable_5, int32 Temp_int_Variable_11, int32 Temp_int_Variable_12, float Temp_float_Variable_42, float Temp_float_Variable_43, float Temp_float_Variable_44, float Temp_float_Variable_45, float Temp_float_Variable_46, int32 Temp_int_Variable_13, int32 Temp_int_Variable_14, bool Temp_bool_Variable_5, bool Temp_bool_Variable_6, bool Temp_bool_Variable_7, bool Temp_bool_Variable_8, bool Temp_bool_Variable_9, const TArray<AActor*>& Temp_object_Variable_1, bool Temp_bool_Variable_10, bool Temp_bool_Variable_11, uint8 Temp_byte_Variable_6, uint8 Temp_byte_Variable_7, int32 Temp_int_Variable_15, bool Temp_bool_Variable_12, bool Temp_bool_Variable_13, bool Temp_bool_Variable_14, bool Temp_bool_Variable_15, bool Temp_bool_Variable_16, int32 Temp_int_Variable_16, bool Temp_bool_Variable_17, bool Temp_bool_Variable_18, bool Temp_bool_Variable_19, bool Temp_bool_Variable_20, bool Temp_bool_Variable_21, int32 Temp_int_Variable_17, float Temp_float_Variable_47, float Temp_float_Variable_48, float Temp_float_Variable_49, float Temp_float_Variable_50, float Temp_float_Variable_51, bool Temp_bool_Variable_22, float Temp_float_Variable_52, float Temp_float_Variable_53, int32 Temp_int_Variable_18, float Temp_float_Variable_54, float Temp_float_Variable_55, float Temp_float_Variable_56, float Temp_float_Variable_57, float Temp_float_Variable_58, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_17, FName K2Node_CustomEvent_NotifyName_54, FName K2Node_CustomEvent_NotifyName_53, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_18, FName K2Node_CustomEvent_NotifyName_52, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_19, FName K2Node_CustomEvent_NotifyName_51, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_20, FName K2Node_CustomEvent_NotifyName_50, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_21, FName Temp_name_Variable_4, int32 Temp_int_Variable_19, float Temp_float_Variable_59, float Temp_float_Variable_60, float Temp_float_Variable_61, float Temp_float_Variable_62, float Temp_float_Variable_63, bool Temp_bool_Variable_23, uint8 Temp_byte_Variable_8, uint8 Temp_byte_Variable_9, bool Temp_bool_Variable_24, uint8 Temp_byte_Variable_10, uint8 Temp_byte_Variable_11, const TArray<AActor*>& Temp_object_Variable_2, FName K2Node_CustomEvent_NotifyName_49, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_22, FName K2Node_CustomEvent_NotifyName_48, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_23, FName K2Node_CustomEvent_NotifyName_47, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_24, FName K2Node_CustomEvent_NotifyName_46, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_25, FName K2Node_CustomEvent_NotifyName_45, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_26, FName Temp_name_Variable_5, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_27, FName K2Node_CustomEvent_NotifyName_44, FName K2Node_CustomEvent_NotifyName_43, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_28, FName K2Node_CustomEvent_NotifyName_42, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_29, FName K2Node_CustomEvent_NotifyName_41, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_30, FName K2Node_CustomEvent_NotifyName_40, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_31, FName Temp_name_Variable_6, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_32, FName K2Node_CustomEvent_NotifyName_39, FName K2Node_CustomEvent_NotifyName_38, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_33, FName K2Node_CustomEvent_NotifyName_37, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_34, FName K2Node_CustomEvent_NotifyName_36, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_35, FName K2Node_CustomEvent_NotifyName_35, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_36, FName Temp_name_Variable_7, bool Temp_bool_Variable_25, UAnimMontage* Temp_object_Variable_3, UAnimMontage* Temp_object_Variable_4, FName K2Node_CustomEvent_NotifyName_34, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_37, FName K2Node_CustomEvent_NotifyName_33, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_38, FName K2Node_CustomEvent_NotifyName_32, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_39, FName K2Node_CustomEvent_NotifyName_31, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_40, FName K2Node_CustomEvent_NotifyName_30, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_41, FName Temp_name_Variable_8, bool Temp_bool_Variable_26, float Temp_float_Variable_64, float Temp_float_Variable_65, bool Temp_bool_Variable_27, float Temp_float_Variable_66, float Temp_float_Variable_67, Break Combat__DelegateSignature K2Node_CreateDelegate_OutputDelegate_42, int32 Temp_int_Variable_20, UAnimMontage* Temp_object_Variable_5, UAnimMontage* Temp_object_Variable_6, FString CallFunc_Conv_IntToString_ReturnValue, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_43, FString CallFunc_Concat_StrStr_ReturnValue, FName K2Node_CustomEvent_NotifyName_29, FName K2Node_CustomEvent_NotifyName_28, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_44, FName K2Node_CustomEvent_NotifyName_27, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_45, FName K2Node_CustomEvent_NotifyName_26, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_46, FName K2Node_CustomEvent_NotifyName_25, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_47, FName Temp_name_Variable_9, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_48, bool K2Node_SwitchName_CmpSuccess, FName K2Node_CustomEvent_NotifyName_24, FName K2Node_CustomEvent_NotifyName_23, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_49, FName K2Node_CustomEvent_NotifyName_22, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_50, FName K2Node_CustomEvent_NotifyName_21, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_51, FName K2Node_CustomEvent_NotifyName_20, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_52, FName Temp_name_Variable_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_53, bool K2Node_SwitchName_CmpSuccess_1, bool K2Node_SwitchName_CmpSuccess_2, FName K2Node_CustomEvent_NotifyName_19, FName K2Node_CustomEvent_NotifyName_18, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_54, FName K2Node_CustomEvent_NotifyName_17, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_55, FName K2Node_CustomEvent_NotifyName_16, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_56, FName K2Node_CustomEvent_NotifyName_15, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_57, FName Temp_name_Variable_11, int32 Temp_int_Variable_21, bool K2Node_SwitchName_CmpSuccess_3, float Temp_float_Variable_68, float Temp_float_Variable_69, float Temp_float_Variable_70, float Temp_float_Variable_71, float Temp_float_Variable_72, int32 Temp_int_Variable_22, float Temp_float_Variable_73, float Temp_float_Variable_74, float Temp_float_Variable_75, float Temp_float_Variable_76, float Temp_float_Variable_77, int32 Temp_int_Variable_23, float Temp_float_Variable_78, float Temp_float_Variable_79, float Temp_float_Variable_80, float Temp_float_Variable_81, float Temp_float_Variable_82, int32 Temp_int_Variable_24, int32 Temp_int_Variable_25, float Temp_float_Variable_83, float Temp_float_Variable_84, float Temp_float_Variable_85, float Temp_float_Variable_86, float Temp_float_Variable_87, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_58, FName K2Node_CustomEvent_NotifyName_14, FName K2Node_CustomEvent_NotifyName_13, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_59, FName K2Node_CustomEvent_NotifyName_12, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_60, FName K2Node_CustomEvent_NotifyName_11, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_61, FName K2Node_CustomEvent_NotifyName_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_62, FName Temp_name_Variable_12, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_63, bool CallFunc_EqualEqual_NameName_ReturnValue, FName K2Node_CustomEvent_NotifyName_9, FName K2Node_CustomEvent_NotifyName_8, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_64, FName K2Node_CustomEvent_NotifyName_7, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_65, FName K2Node_CustomEvent_NotifyName_6, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_66, FName K2Node_CustomEvent_NotifyName_5, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_67, FName Temp_name_Variable_13, bool CallFunc_EqualEqual_NameName_ReturnValue_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_68, FName K2Node_CustomEvent_NotifyName_4, FName K2Node_CustomEvent_NotifyName_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_69, FName K2Node_CustomEvent_NotifyName_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_70, FName K2Node_CustomEvent_NotifyName_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_71, FName K2Node_CustomEvent_NotifyName, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_72, FName Temp_name_Variable_14, int32 Temp_int_Variable_26, UAnimMontage* Temp_object_Variable_7, UAnimMontage* Temp_object_Variable_8, UAnimMontage* Temp_object_Variable_9, bool Temp_bool_Variable_28, UAnimMontage* Temp_object_Variable_10, UAnimMontage* Temp_object_Variable_11, int32 Temp_int_Variable_27, float Temp_float_Variable_88, float Temp_float_Variable_89, float Temp_float_Variable_90, float Temp_float_Variable_91, float Temp_float_Variable_92, int32 Temp_int_Variable_28, float Temp_float_Variable_93, float Temp_float_Variable_94, float Temp_float_Variable_95, float Temp_float_Variable_96, float Temp_float_Variable_97, int32 Temp_int_Variable_29, int32 Temp_int_Variable_30, float Temp_float_Variable_98, float Temp_float_Variable_99, float Temp_float_Variable_100, float Temp_float_Variable_101, float Temp_float_Variable_102, FLinearColor CallFunc_LinearColorLerp_ReturnValue, float CallFunc_Lerp_ReturnValue_1, float CallFunc_Lerp_ReturnValue_2, int32 Temp_int_Variable_31, FLinearColor CallFunc_LinearColorLerp_ReturnValue_1, float CallFunc_Lerp_ReturnValue_3, float CallFunc_Lerp_ReturnValue_4, int32 Temp_int_Variable_32, float Temp_float_Variable_103, float Temp_float_Variable_104, float Temp_float_Variable_105, int32 Temp_int_Variable_33, float Temp_float_Variable_106, float Temp_float_Variable_107, float Temp_float_Variable_108, float Temp_float_Variable_109, float Temp_float_Variable_110, int32 Temp_int_Variable_34, float Temp_float_Variable_111, float Temp_float_Variable_112, float Temp_float_Variable_113, float Temp_float_Variable_114, float Temp_float_Variable_115, bool K2Node_CustomEvent_Show_2, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool K2Node_CustomEvent_Show_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, FName K2Node_CustomEvent_NotifyName_78, int32 CallFunc_PostEventAtLocation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_73, APawn* CallFunc_GetPlayerPawn_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_2, AActor* CallFunc_GetOwner_ReturnValue, int32 CallFunc_PostEvent_ReturnValue, uint8 K2Node_Event_EndPlayReason, float CallFunc_Cutscene_OutputPin, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, int32 CallFunc_PostEvent_ReturnValue_1, bool K2Node_CustomEvent_Reset, float K2Node_Select_Default, float K2Node_Select_Default_1, float K2Node_Select_Default_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_74, float K2Node_Select_Default_3, FName K2Node_CustomEvent_NotifyName_79, bool K2Node_CustomEvent_Show, bool K2Node_CustomEvent_Instant, uint8 K2Node_Select_Default_4, float K2Node_Select_Default_5, FVector CallFunc_Conv_FloatToVector_ReturnValue_1, float K2Node_Select_Default_6, float K2Node_Select_Default_7, bool K2Node_Event_Visibility, float K2Node_Select_Default_8, ESlateVisibility K2Node_Select_Default_9, float CallFunc_Cutscene_OutputPin_1, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, bool CallFunc_K2_SetActorRotation_ReturnValue, ALevelSequenceActor* CallFunc_CreateLevelSequencePlayer_OutActor, ULevelSequencePlayer* CallFunc_CreateLevelSequencePlayer_ReturnValue, TArray<FName>& K2Node_MakeArray_Array, bool K2Node_CustomEvent_Ignore, TArray<FName>& K2Node_MakeArray_Array_1, TArray<FName>& K2Node_Select_Default_10, bool CallFunc_NotEqual_IntInt_ReturnValue, float K2Node_Select_Default_11, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_75, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_2, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_4, FVector CallFunc_K2_GetComponentLocation_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, float K2Node_Select_Default_12, bool CallFunc_Less_FloatFloat_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_2, float CallFunc_Cutscene_OutputPin_2, int32 CallFunc_PostEventAtLocation_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_4, int32 CallFunc_PostEventAtLocation_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_6, int32 CallFunc_PostEventAtLocation_ReturnValue_7, float K2Node_Select_Default_13, float K2Node_Select_Default_14, float K2Node_Select_Default_15, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, float K2Node_Select_Default_16, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_8, UBlueFireSaveGame_C* CallFunc_CreateSaveGameObject_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_1, FSave_GameStats K2Node_MakeStruct_Save_GameStats, float K2Node_Select_Default_17, int32 CallFunc_PostEventAtLocation_ReturnValue_9, UParticleSystemComponent* CallFunc_SpawnEmitterAttached_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_10, FName K2Node_CustomEvent_NotifyName_72, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_76, USaveGame* CallFunc_LoadGameFromSlot_ReturnValue, UBlueFireSaveGame_C* K2Node_DynamicCast_AsBlue_Fire_Save_Game, bool K2Node_DynamicCast_bSuccess, bool K2Node_SwitchEnum_CmpSuccess, FName K2Node_CustomEvent_NotifyName_73, bool CallFunc_SaveGameToSlot_ReturnValue, float Temp_float_Variable_116, UGameInstance* CallFunc_GetGameInstance_ReturnValue, UBlueFire_Game_Instance_C* K2Node_DynamicCast_AsBlue_Fire_Game_Instance, bool K2Node_DynamicCast_bSuccess_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_77, UPlayerController* CallFunc_GetPlayerController_ReturnValue, const TArray<uint8>& K2Node_MakeArray_Array_2, FRotator CallFunc_K2_GetActorRotation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, FHitResult CallFunc_K2_SetActorLocationAndRotation_SweepHitResult, bool CallFunc_K2_SetActorLocationAndRotation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, float Temp_float_Variable_117, uint8 K2Node_Select_Default_18, int32 K2Node_Event_Count_4, int32 K2Node_Event_Max_Count_4, bool K2Node_Event_Use_Custom_Counter_4, FHitResult CallFunc_SphereTraceSingleForObjects_OutHit, bool CallFunc_SphereTraceSingleForObjects_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, FVector CallFunc_BreakHitResult_Location, FVector CallFunc_BreakHitResult_ImpactPoint, FVector CallFunc_BreakHitResult_Normal, FVector CallFunc_BreakHitResult_ImpactNormal, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, AActor* CallFunc_BreakHitResult_HitActor, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, FName CallFunc_BreakHitResult_HitBoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_FaceIndex, FVector CallFunc_BreakHitResult_TraceStart, FVector CallFunc_BreakHitResult_TraceEnd, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, bool Temp_bool_Variable_29, FTransform CallFunc_MakeTransform_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, float K2Node_Select_Default_19, UInvocation_Bomb_C* CallFunc_FinishSpawningActor_ReturnValue, int32 K2Node_Event_Count_3, int32 K2Node_Event_Max_Count_3, bool K2Node_Event_Use_Custom_Counter_3, int32 K2Node_Event_Count_2, int32 K2Node_Event_Max_Count_2, bool K2Node_Event_Use_Custom_Counter_2, float Temp_float_Variable_118, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, bool K2Node_Select_Default_20, bool K2Node_Select_Default_21, bool K2Node_Select_Default_22, int32 K2Node_Event_Count_1, int32 K2Node_Event_Max_Count_1, bool K2Node_Event_Use_Custom_Counter_1, FTransform CallFunc_MakeTransform_ReturnValue_1, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1, UInvocation_Bomb_C* CallFunc_FinishSpawningActor_ReturnValue_1, float Temp_float_Variable_119, FTimerHandle CallFunc_K2_SetTimer_ReturnValue, uint8 K2Node_Select_Default_23, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, FHitResult CallFunc_LineTraceSingle_OutHit, bool CallFunc_LineTraceSingle_ReturnValue, bool Temp_bool_Variable_30, bool CallFunc_BreakHitResult_bBlockingHit_1, bool CallFunc_BreakHitResult_bInitialOverlap_1, float CallFunc_BreakHitResult_Time_1, float CallFunc_BreakHitResult_Distance_1, FVector CallFunc_BreakHitResult_Location_1, FVector CallFunc_BreakHitResult_ImpactPoint_1, FVector CallFunc_BreakHitResult_Normal_1, FVector CallFunc_BreakHitResult_ImpactNormal_1, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat_1, AActor* CallFunc_BreakHitResult_HitActor_1, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent_1, FName CallFunc_BreakHitResult_HitBoneName_1, int32 CallFunc_BreakHitResult_HitItem_1, int32 CallFunc_BreakHitResult_FaceIndex_1, FVector CallFunc_BreakHitResult_TraceStart_1, FVector CallFunc_BreakHitResult_TraceEnd_1, float K2Node_Select_Default_24, FVector K2Node_Select_Default_25, float CallFunc_Lerp_ReturnValue_5, FVector CallFunc_Conv_FloatToVector_ReturnValue_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, float CallFunc_ApplyDamage_ReturnValue, FString K2Node_Event_Event_Name, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_1, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, float K2Node_Select_Default_26, float K2Node_Select_Default_27, float K2Node_Select_Default_28, float K2Node_Select_Default_29, float CallFunc_ApplyDamage_ReturnValue_1, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, FVector CallFunc_GetSocketLocation_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue_2, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2, AInvocation_Throw_C* CallFunc_FinishSpawningActor_ReturnValue_2, bool K2Node_CustomEvent_Is_Goddess, uint8 K2Node_Select_Default_30, int32 K2Node_Event_Count, int32 K2Node_Event_Max_Count, bool K2Node_Event_Use_Custom_Counter, float K2Node_CustomEvent_Radius, const TArray<uint8>& K2Node_MakeArray_Array_3, APawn* CallFunc_GetPlayerPawn_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, FVector CallFunc_K2_GetActorLocation_ReturnValue_8, uint8 K2Node_Select_Default_31, FHitResult CallFunc_SphereTraceSingleForObjects_OutHit_1, bool CallFunc_SphereTraceSingleForObjects_ReturnValue_1, bool CallFunc_BreakHitResult_bBlockingHit_2, bool CallFunc_BreakHitResult_bInitialOverlap_2, float CallFunc_BreakHitResult_Time_2, float CallFunc_BreakHitResult_Distance_2, FVector CallFunc_BreakHitResult_Location_2, FVector CallFunc_BreakHitResult_ImpactPoint_2, FVector CallFunc_BreakHitResult_Normal_2, FVector CallFunc_BreakHitResult_ImpactNormal_2, UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat_2, AActor* CallFunc_BreakHitResult_HitActor_2, UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent_2, FName CallFunc_BreakHitResult_HitBoneName_2, int32 CallFunc_BreakHitResult_HitItem_2, int32 CallFunc_BreakHitResult_FaceIndex_2, FVector CallFunc_BreakHitResult_TraceStart_2, FVector CallFunc_BreakHitResult_TraceEnd_2, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_5, bool CallFunc_IsValid_ReturnValue_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_9, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_6, bool CallFunc_IsValid_ReturnValue_6, FVector CallFunc_GetSocketLocation_ReturnValue_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_7, bool CallFunc_IsValid_ReturnValue_7, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_8, float K2Node_Select_Default_32, bool CallFunc_IsValid_ReturnValue_8, float K2Node_Select_Default_33, int32 CallFunc_PostEventAtLocation_ReturnValue_11, FVector CallFunc_K2_GetActorLocation_ReturnValue_10, int32 CallFunc_PostEventAtLocation_ReturnValue_12, FName K2Node_CustomEvent_NotifyName_74, int32 CallFunc_PostEventAtLocation_ReturnValue_13, int32 CallFunc_PostEventAtLocation_ReturnValue_14, FVector CallFunc_K2_GetActorLocation_ReturnValue_11, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_78, int32 CallFunc_PostEventAtLocation_ReturnValue_15, FVector CallFunc_K2_GetActorLocation_ReturnValue_12, FVector CallFunc_K2_GetActorLocation_ReturnValue_13, int32 CallFunc_PostEventAtLocation_ReturnValue_16, int32 CallFunc_PostEventAtLocation_ReturnValue_17, int32 CallFunc_PostEventAtLocation_ReturnValue_18, FVector CallFunc_K2_GetActorLocation_ReturnValue_14, FVector CallFunc_K2_GetActorLocation_ReturnValue_15, int32 CallFunc_PostEventAtLocation_ReturnValue_19, int32 CallFunc_PostEventAtLocation_ReturnValue_20, bool CallFunc_EqualEqual_IntInt_ReturnValue_4, TArray<AActor*>& CallFunc_GetOverlappingActors_OverlappingActors, FVector CallFunc_K2_GetActorLocation_ReturnValue_16, int32 CallFunc_Array_Length_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_17, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_4, int32 Temp_int_Array_Index_Variable, FName Temp_name_Variable_15, AActor* CallFunc_Array_Get_Item, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_2, float K2Node_Event_Damage, const UDamageType* K2Node_Event_DamageType, AController* K2Node_Event_InstigatedBy, AActor* K2Node_Event_DamageCauser, TSubclassOf<UDamageType> CallFunc_GetObjectClass_ReturnValue, bool CallFunc_RecieveHit_Dead, bool CallFunc_EqualEqual_ClassClass_ReturnValue, int32 Temp_int_Variable_35, FName K2Node_CustomEvent_NotifyName_75, bool CallFunc_IsRobiValid_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_18, int32 CallFunc_RandomIntegerInRange_ReturnValue, UAnimMontage* K2Node_Select_Default_34, int32 CallFunc_Add_IntInt_ReturnValue_1, float CallFunc_PlayAnimMontage_ReturnValue, bool K2Node_SwitchInteger_CmpSuccess, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_9, bool CallFunc_IsValid_ReturnValue_9, int32 CallFunc_PostEventAtLocation_ReturnValue_21, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_22, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_10, float K2Node_Select_Default_35, bool CallFunc_IsValid_ReturnValue_10, float K2Node_Select_Default_36, float K2Node_Select_Default_37, int32 CallFunc_PostEventAtLocation_ReturnValue_23, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_11, bool CallFunc_IsValid_ReturnValue_11, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_19, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_5, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_2, bool CallFunc_IsRobiValid_ReturnValue_3, bool CallFunc_IsRobiValid_ReturnValue_4, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult, bool Temp_bool_Has_Been_Initd_Variable, bool K2Node_CustomEvent_In, bool Temp_bool_IsClosed_Variable, bool Temp_bool_Variable_31, UAnimMontage* K2Node_Select_Default_38, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_12, float K2Node_Select_Default_39, bool CallFunc_IsValid_ReturnValue_12, bool CallFunc_Not_PreBool_ReturnValue_3, float K2Node_Select_Default_40, float K2Node_Select_Default_41, float K2Node_Select_Default_42, float K2Node_Select_Default_43, float CallFunc_ApplyDamage_ReturnValue_2, ABP_BossRoom_Goddess_C* K2Node_DynamicCast_AsBP_Boss_Room_Goddess, bool K2Node_DynamicCast_bSuccess_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_20, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_6, FVector CallFunc_K2_GetActorLocation_ReturnValue_21, FRotator CallFunc_FindLookAtRotation_ReturnValue, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, FRotator CallFunc_MakeRotator_ReturnValue, bool CallFunc_K2_SetActorRotation_ReturnValue_1, UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, UPenumbraSkelMesh_Skeleton_AnimBlueprint_C* K2Node_DynamicCast_AsPenumbra_Skel_Mesh_Skeleton_Anim_Blueprint, bool K2Node_DynamicCast_bSuccess_3, UMaterialInterface* CallFunc_GetMaterial_ReturnValue, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_24, APawn* CallFunc_GetPlayerPawn_ReturnValue_3, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_79, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, UAnimMontage* K2Node_Select_Default_44, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_13, bool CallFunc_IsValid_ReturnValue_13, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_14, FVector CallFunc_K2_GetActorLocation_ReturnValue_22, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, bool CallFunc_IsValid_ReturnValue_14, FVector CallFunc_BreakTransform_Location_1, FRotator CallFunc_BreakTransform_Rotation_1, FVector CallFunc_BreakTransform_Scale_1, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, UAnimMontage* K2Node_Select_Default_45, FVector CallFunc_MakeVector_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_15, FHitResult CallFunc_K2_SetActorLocationAndRotation_SweepHitResult_1, bool CallFunc_K2_SetActorLocationAndRotation_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_15, int32 CallFunc_Add_IntInt_ReturnValue_3, bool CallFunc_EqualEqual_IntInt_ReturnValue_5, bool CallFunc_Not_PreBool_ReturnValue_4, FName K2Node_CustomEvent_NotifyName_76, FVector CallFunc_K2_GetActorLocation_ReturnValue_23, int32 CallFunc_PostEventAtLocation_ReturnValue_25, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_80, FVector CallFunc_K2_GetActorLocation_ReturnValue_24, int32 CallFunc_PostEventAtLocation_ReturnValue_26, int32 CallFunc_PostEventAtLocation_ReturnValue_27, int32 CallFunc_PostEventAtLocation_ReturnValue_28, int32 CallFunc_PostEventAtLocation_ReturnValue_29, FVector CallFunc_K2_GetActorLocation_ReturnValue_25, int32 CallFunc_PostEventAtLocation_ReturnValue_30, int32 CallFunc_PostEventAtLocation_ReturnValue_31, int32 CallFunc_PostEventAtLocation_ReturnValue_32, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_1, float K2Node_Select_Default_46, float K2Node_Select_Default_47, int32 Temp_int_Variable_36, float K2Node_Select_Default_48, float K2Node_Select_Default_49, FName K2Node_CustomEvent_NotifyName_77, UParticleSystemComponent* CallFunc_SpawnEmitterAttached_ReturnValue_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_81, FVector CallFunc_K2_GetActorLocation_ReturnValue_26, int32 CallFunc_PostEventAtLocation_ReturnValue_33, float K2Node_Select_Default_50, bool CallFunc_Not_PreBool_ReturnValue_5, bool CallFunc_BooleanAND_ReturnValue_1);
    void CallB__DelegateSignature();
}

#endif
