#ifndef UE4SS_SDK_DebugTools_UI_HPP
#define UE4SS_SDK_DebugTools_UI_HPP

class UDebugTools_UI_C : UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UWidgetAnimation* DisplayPopUp;
    UBorder* Border_83;
    UDebugTool_Option_C* DebugTool_Option;
    UDebugTool_Option_C* DebugTool_Option_1;
    UDebugTool_Option_C* DebugTool_Option_3;
    UDebugTool_Option_C* DebugTool_Option_45;
    UDebugTool_Option_C* DebugTool_Option_92;
    UDebugTool_Option_C* DebugTool_Option_94;
    UDebugTool_Option_C* DebugTool_Option_96;
    UDebugTool_Option_C* DebugTool_Option_103;
    UDebugTool_Option_C* DebugTool_Option_112;
    UDebugTool_Option_C* DebugTool_Option_135;
    UDebugTool_Option_C* DebugTool_Option_140;
    UDebugTool_Option_C* DebugTool_Option_165;
    UDebugTool_Option_C* DebugTool_Option_197;
    UDebugTool_Option_C* DebugTool_Option_202;
    UDebugTool_Option_C* DebugTool_Option_204;
    UDebugTool_Option_C* DebugTool_Option_240;
    UDebugTool_Option_C* DebugTool_Option_267;
    UDebugTool_Option_C* DebugTool_Option_277;
    UDebugTool_Option_C* DebugTool_Option_306;
    UDebugTool_Option_C* DebugTool_Option_328;
    UDebugTool_Option_C* DebugTool_Option_329;
    UDebugTool_Option_C* DebugTool_Option_351;
    UDebugTool_Option_C* DebugTool_Option_364;
    UDebugTool_Option_C* DebugTool_Option_369;
    UDebugTool_Option_C* DebugTool_Option_464;
    UDebugTool_Option_C* DebugTool_Option_471;
    UDebugTool_Option_C* DebugTool_Option_512;
    UDebugTool_Option_C* DebugTool_Option_623;
    UDebugTool_Option_C* DebugTool_Option_631;
    UDebugTool_Option_C* DebugTool_Option_638;
    UDebugTool_Option_C* DebugTool_Option_784;
    UDebugTool_Option_C* DebugTool_Option_795;
    UDebugTool_Option_C* DebugTool_Option_878;
    UDebugTool_Option_C* DebugTool_Option_AddCash;
    UDebugTool_Option_C* DebugTool_Option_AddShadowFragments;
    UDebugTool_Option_C* DebugTool_Option_C;
    UDebugTool_Option_C* DebugTool_Option_C_0;
    UDebugTool_Option_C* DebugTool_Option_C_251;
    UDebugTool_Option_C* DebugTool_Option_C_252;
    UDebugTool_Option_C* DebugTool_Option_C_254;
    UDebugTool_Option_C* DebugTool_Option_C_255;
    UDebugTool_Option_C* DebugTool_Option_C_256;
    UDebugTool_Option_C* DebugTool_Option_C_257;
    UDebugTool_Option_C* DebugTool_Option_C_258;
    UDebugTool_Option_C* DebugTool_Option_C_259;
    UDebugTool_Option_C* DebugTool_Option_C_260;
    UDebugTool_Option_C* DebugTool_Option_C_262;
    UDebugTool_Option_C* DebugTool_Option_LoadLevel;
    UDebugTool_Option_C* DebugTool_Option_VoidMaster;
    UTextBlock* Difficulty;
    UTextBlock* FPS;
    UImage* Image;
    UImage* Image_0;
    UImage* Image_1;
    UImage* Image_2;
    UImage* Image_3;
    UImage* Image_4;
    UImage* Image_5;
    UImage* Image_6;
    UImage* Image_7;
    UImage* Image_8;
    UImage* Image_9;
    UImage* Image_10;
    UImage* Image_11;
    UImage* Image_12;
    UImage* Image_13;
    UImage* Image_14;
    UImage* Image_15;
    UImage* Image_70;
    UImage* Image_95;
    UImage* Image_153;
    UImage* Image_207;
    UImage* Image_308;
    UTextBlock* LastSafeSpot;
    UTextBlock* Location;
    UTextBlock* PopUp;
    UScrollBox* ScrollBox_153;
    UTextBlock* ToolDescription;
    UTextBlock* ToolName;
    UDebugTool_Option_C* WarpToVoids;
    UDebugTool_Option_C* XboxFix;
    TArray<UDebugTool_Option_C*> DebugTool_OptionsArray;
    int32 SelectedOption;
    TArray<UDebugTool_Option_C*> Tools;
    ADebugTools_Control_C* Control;
    APlayer_Character_BP_C* Player;

    void ShowControls(bool Show);
    void Construct();
    void MoveSelection(bool Up);
    void Confirm();
    void MoveSideSelection(bool Right);
    void UpdateSelection();
    void CheckFreeze();
    void Tick(FGeometry MyGeometry, float InDeltaTime);
    void ShowPopUp(FText InText);
    void ExecuteUbergraph_DebugTools_UI(int32 EntryPoint, bool Temp_bool_Variable, bool Temp_bool_Variable_1, bool K2Node_CustomEvent_Show, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Variable_1, bool K2Node_CustomEvent_Up, bool K2Node_CustomEvent_Right, UDebugTool_Option_C* CallFunc_Array_Get_Item, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue_1, bool Temp_bool_Variable_2, bool Temp_bool_Variable_3, int32 Temp_int_Variable_2, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, UDebugTool_Option_C* CallFunc_Array_Get_Item_1, int32 CallFunc_PostEventAtLocation_ReturnValue, int32 Temp_int_Variable_3, UWidget* CallFunc_GetChildAt_ReturnValue, UWidget* CallFunc_GetChildAt_ReturnValue_1, int32 CallFunc_GetChildrenCount_ReturnValue, UDebugTool_Option_C* K2Node_DynamicCast_AsDebug_Tool_Option, bool K2Node_DynamicCast_bSuccess, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, UDebugTool_Option_C* CallFunc_Array_Get_Item_2, UDebugTool_Option_C* CallFunc_Array_Get_Item_3, UWidget* K2Node_Select_Default, int32 CallFunc_Array_Add_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 Temp_int_Variable_4, bool CallFunc_LessEqual_IntInt_ReturnValue_1, int32 K2Node_Select_Default_1, int32 CallFunc_Add_IntInt_ReturnValue_2, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, int32 K2Node_Select_Default_2, FGeometry K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, int32 K2Node_Select_Default_3, float CallFunc_Divide_FloatFloat_ReturnValue, int32 CallFunc_FTrunc_ReturnValue, FText CallFunc_Conv_IntToText_ReturnValue, FText K2Node_CustomEvent_InText, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue, FString CallFunc_Conv_VectorToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, FFormatArgumentData K2Node_MakeStruct_FormatArgumentData, FText CallFunc_Conv_StringToText_ReturnValue_2, TArray<FFormatArgumentData>& K2Node_MakeArray_Array, FVector CallFunc_K2_GetActorLocation_ReturnValue, FText CallFunc_Format_ReturnValue, FString CallFunc_Conv_VectorToString_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_1, FText CallFunc_Conv_StringToText_ReturnValue_3);
}

#endif
