#ifndef UE4SS_SDK_Door_BP_HPP
#define UE4SS_SDK_Door_BP_HPP

class ADoor_BP_C : AMechanics_Master_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    UAkComponent* AkFenceLoopAmbush;
    UAkComponent* AkFenceLoop;
    UAkComponent* AkLoop;
    UStaticMeshComponent* SM_Fence_Back;
    UCameraComponent* Camera;
    UStaticMeshComponent* SM_Fence_Front;
    UStaticMeshComponent* Lock_Mesh3;
    UStaticMeshComponent* Lock_Mesh1;
    UStaticMeshComponent* Lock_Mesh2;
    USkeletalMeshComponent* SkeletalMesh;
    USkeletalMeshComponent* SkeletalMesh1;
    UBillboardComponent* Billboard;
    UBoxComponent* Box;
    UParticleSystemComponent* P_Door;
    UStaticMeshComponent* SM_Door;
    float Dissolve_Lerp_E16D5C494C74A8AF85751AAE5FEA48CE;
    TEnumAsByte<ETimelineDirection::Type> Dissolve__Direction_E16D5C494C74A8AF85751AAE5FEA48CE;
    UTimelineComponent* Dissolve;
    float Timeline_0_Offset_3FFE9454417CB940F3080E998F81AE4C;
    TEnumAsByte<ETimelineDirection::Type> Timeline_0__Direction_3FFE9454417CB940F3080E998F81AE4C;
    UTimelineComponent* Timeline_0;
    float OpenCloseTimeline_Position_7F477CB24270FE7FEE978D8094E5C908;
    TEnumAsByte<ETimelineDirection::Type> OpenCloseTimeline__Direction_7F477CB24270FE7FEE978D8094E5C908;
    UTimelineComponent* OpenCloseTimeline;
    float Fence_Movement_Lerp_7A5A790F495EEC2F06BD4DA809150050;
    float Fence_Movement_Offset_7A5A790F495EEC2F06BD4DA809150050;
    TEnumAsByte<ETimelineDirection::Type> Fence_Movement__Direction_7A5A790F495EEC2F06BD4DA809150050;
    UTimelineComponent* Fence Movement;
    float MoveFence_Lerp_022D15884C4411C5EBD62280DA02DDBA;
    float MoveFence_Offset_022D15884C4411C5EBD62280DA02DDBA;
    TEnumAsByte<ETimelineDirection::Type> MoveFence__Direction_022D15884C4411C5EBD62280DA02DDBA;
    UTimelineComponent* MoveFence;
    FVector OriginalLocation;
    bool bLocked;
    float Offset;
    float Offset Fence Back;
    bool Opened;
    float Speed OpenCloseTimeline;
    float Speed FenceMovement;
    float Speed MoveFence;
    int32 NActivates;
    UPickUp_Action_UI_C* PickUpActionUI;
    bool CanBeOpened;
    int32 DoorType;
    bool TollKeyItem;
    TArray<FText> NegativeText;
    bool RemoveItemOnUse;
    TEnumAsByte<Items::Type> Item;
    int32 ItemAmountRequired;
    TArray<FText> Text;
    UMainDialogWB_C* Dialog;
    FDoor_BP_CFinishActivate FinishActivate;
    void FinishActivate();
    bool RestoreHudOpenDoor;
    bool Start Open;
    bool Start Open Fence;
    bool Debug Boss Instant Combat;
    float BlendTimeCam;
    bool Play VFX Fence;
    int32 MultiActivateOriginal;
    APlayer_Character_BP_C* Player;
    bool CanTryToClose;
    UAkAudioEvent* DoorOpenSound;
    UAkAudioEvent* DoorCloseSound;
    bool ChangeCamera;
    bool DelayWhenUnlockHint;
    bool Instant;
    bool FenceControlLocked;
    UAkAudioEvent* FenceSoundClose;
    UAkAudioEvent* FenceSoundOpen;
    bool Unlocking;
    float DistanceToClose;
    FVector FenceFrontOriginalLocation;
    bool Debug Boss Skip Cutscene;
    int32 Debug Boss Fase;
    bool Debug Location;
    float Lerp Door;
    float Lerp Fence Front;
    UAkAudioEvent* PlayLoopSound;
    UAkAudioEvent* StopLoopSound;
    USkipCutscene_Action_UI_C* SkipCutsceneWidget;
    bool HasCutscene;
    bool CanSkipCutscene;
    ULevelSequencePlayer* Current Sequence;
    bool UseStingerUnlockSFX;
    bool UseStingerSFX;
    UMaterialInstanceDynamic* Mat Lock A;
    UMaterialInstanceDynamic* Mat Lock B;
    UAkAudioEvent* StingerSFX;
    float Lerp Fence Back;
    ANPCBound_C* NPCBound;
    bool InvertOffsetForFence;
    bool NoExecuteBuild;
    int32 LoopDoor;
    bool IsDoorOpening;
    bool Debug;
    bool AffectTimer;
    bool bCanFreezeActors;
    TArray<AMoving_Path_Actor_Loop_C*> ActorsToFreeze;

    void UserConstructionScript(float CallFunc_Lerp_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, FVector CallFunc_MakeVector_ReturnValue, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Lerp_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue_1, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult, float CallFunc_BreakVector_X_2, float CallFunc_BreakVector_Y_2, float CallFunc_BreakVector_Z_2, float CallFunc_Subtract_FloatFloat_ReturnValue_1, float CallFunc_Lerp_ReturnValue_2, FVector CallFunc_MakeVector_ReturnValue_2, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult_1);
    void OpenCloseTimeline__FinishedFunc();
    void OpenCloseTimeline__UpdateFunc();
    void MoveFence__FinishedFunc();
    void MoveFence__UpdateFunc();
    void MoveFence__StopSound__EventFunc();
    void MoveFence__StartSound__EventFunc();
    void Fence Movement__FinishedFunc();
    void Fence Movement__UpdateFunc();
    void Fence Movement__SoundStop__EventFunc();
    void Fence Movement__SoundStart__EventFunc();
    void Timeline_0__FinishedFunc();
    void Timeline_0__UpdateFunc();
    void Timeline_0__StopSound__EventFunc();
    void Timeline_0__StartSound__EventFunc();
    void Dissolve__FinishedFunc();
    void Dissolve__UpdateFunc();
    void InpActEvt_PC_Interact_K2Node_InputActionEvent_3(FKey Key);
    void InpActEvt_Gamepad_Interact_Shield_K2Node_InputActionEvent_2(FKey Key);
    void InpActEvt_PC_Back_K2Node_InputActionEvent_1(FKey Key);
    void InpActEvt_Gamepad_Back_K2Node_InputActionEvent_0(FKey Key);
    void BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void BndEvt__Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
    void CustomEvent();
    void QuickEnd();
    void NegativeFinish();
    void OpenAfterActivate();
    void TryToClose();
    void TryToCloseCheck();
    void Set Block Door(bool bLock);
    void Boss Door Fast Open();
    void InputOpenDoor();
    void SkipCutscene();
    void Create NPCBound();
    void ReceiveEndPlay(uint8 EndPlayReason);
    void Force Close();
    void ForceEndOverlap();
    void OnRemovePickupUI(bool bRemove);
    void CustomRemovePickupUI(bool bRemove);
    void Open();
    void ReceiveBeginPlay();
    void Close();
    void InstantOpen();
    void ReceiveAnyDamage(float Damage, const UDamageType* DamageType, AController* InstigatedBy, AActor* DamageCauser);
    void Activate(bool ExternalControl, bool BeginPlay, bool ChangeCamera, bool Instant, bool Is Cutscene, bool Affect Timer);
    void Deactivate(bool Instant, bool Change Camera);
    void AlreadyUsed();
    void CloseTimelineRun();
    void OpenTimelineRun();
    void VFX(bool Open);
    void Unlock(bool DontWriteID, bool Is Cutscene);
    void KeyUnlock();
    void FenceUnlock(bool Is Cutscene);
    void FenceOnly();
    void BoxCollision(uint8 NewType);
    void Open Boss Door();
    void InstantUnlock();
    void InstantFenceUnlock();
    void FenceControl(bool Lock, bool Instant);
    void FenceControlLock();
    void FenceControlUnlock();
    void Build();
    void FenceLock();
    void UnlockHint();
    void ExtraFenceOnly();
    void HideFence();
    void Freeze All(bool Freeze);
    void FinishUnlockHint();
    void TriggerCustomFence(bool Instant, int32 Index);
    void InstantCustomFenceUnlock();
    void Unlock Extra();
    void InstantUnlockExtra();
    void InstantFenceUnlockExtra();
    void InstantOpenExtra();
    void Build Extra 1();
    void Destroy Fence Front();
    void BndEvt__SM_Door_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void Lock Dissolve();
    void ForceFenceControl(bool Lock);
    void OpenTimeLineRunSkip();
    void InstaForceClose();
    void RestoreKey();
    void Force Remove Pickup UI();
    void PlayStinger();
    void ExecuteUbergraph_Door_BP(int32 EntryPoint, bool K2Node_SwitchEnum_CmpSuccess, bool K2Node_SwitchEnum_CmpSuccess_1, bool K2Node_SwitchEnum_CmpSuccess_2, bool K2Node_SwitchEnum_CmpSuccess_3, bool Temp_bool_Variable, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, UMessage_PopUp_C* CallFunc_Create_ReturnValue, bool Temp_bool_Variable_3, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, bool Temp_bool_Variable_4, bool Temp_bool_Variable_5, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_1, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_1, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_2, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_2, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_3, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_3, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_4, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_4, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_5, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_5, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_6, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_6, bool CallFunc_EqualEqual_IntInt_ReturnValue, float CallFunc_Lerp_ReturnValue, bool Temp_bool_Variable_6, bool Temp_bool_Variable_7, float Temp_float_Variable, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsInViewport_ReturnValue, bool Temp_bool_Variable_8, UAkAudioEvent* Temp_object_Variable, UAkAudioEvent* Temp_object_Variable_1, bool Temp_bool_Has_Been_Initd_Variable, bool Temp_bool_IsClosed_Variable, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent_1, AActor* K2Node_ComponentBoundEvent_OtherActor_2, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_2, int32 K2Node_ComponentBoundEvent_OtherBodyIndex_1, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor_1, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp_1, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, APawn* CallFunc_GetPlayerPawn_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue_2, bool CallFunc_IsRobiValid_ReturnValue, bool K2Node_SwitchInteger_CmpSuccess, bool K2Node_SwitchInteger_CmpSuccess_1, bool K2Node_SwitchInteger_CmpSuccess_2, bool Temp_bool_Has_Been_Initd_Variable_1, const TArray<FText>& K2Node_MakeArray_Array, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_1, const TArray<UAkAudioEvent*>& K2Node_MakeArray_Array_2, const TArray<FText>& K2Node_MakeArray_Array_3, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue_1, FinishActivate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, FVector CallFunc_MakeVector_ReturnValue, FVector CallFunc_MakeVector_ReturnValue_1, FVector CallFunc_Subtract_VectorVector_ReturnValue, float CallFunc_VSize_ReturnValue, FTimerHandle CallFunc_K2_SetTimer_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool K2Node_SwitchInteger_CmpSuccess_3, bool CallFunc_BooleanAND_ReturnValue, FText Temp_text_Variable, bool K2Node_CustomEvent_Block, FText Temp_text_Variable_1, Finished__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, ExitDialog__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, bool CallFunc_Greater_FloatFloat_ReturnValue, bool Temp_bool_Variable_9, Finished__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, UPlayerController* CallFunc_GetPlayerController_ReturnValue_3, OnRemovePickupUI__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, bool CallFunc_IsRobiValid_ReturnValue_2, bool CallFunc_IsInViewport_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue_3, FText Temp_text_Variable_2, float CallFunc_PlayAnimMontage_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_4, bool CallFunc_IsRobiValid_ReturnValue_5, const FTransform CallFunc_GetTransform_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, ANPCBound_C* CallFunc_FinishSpawningActor_ReturnValue, bool K2Node_SwitchInteger_CmpSuccess_4, uint8 K2Node_Event_EndPlayReason, FText Temp_text_Variable_3, float CallFunc_BreakVector_X_2, float CallFunc_BreakVector_Y_2, float CallFunc_BreakVector_Z_2, FVector CallFunc_MakeVector_ReturnValue_2, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_7, bool CallFunc_IsRobiValid_ReturnValue_6, bool CallFunc_IsRobiValid_ReturnValue_7, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, bool CallFunc_IsRobiValid_ReturnValue_8, int32 CallFunc_PostEventAtLocation_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_9, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, bool CallFunc_IsPlaying_ReturnValue, bool CallFunc_HasItem_Success, int32 CallFunc_HasItem_ItemAmount, bool CallFunc_UseItem_Success, int32 CallFunc_UseItem_CurrentAmount, float CallFunc_Cutscene_OutputPin, float CallFunc_Cutscene_OutputPin_1, bool K2Node_CustomEvent_bRemove_1, bool Temp_bool_Variable_10, bool CallFunc_IsRobiValid_ReturnValue_10, FText K2Node_Select_Default, bool CallFunc_IsInViewport_ReturnValue_2, FText K2Node_Select_Default_1, bool K2Node_CustomEvent_bRemove, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, float CallFunc_BreakVector_X_3, float CallFunc_BreakVector_Y_3, float CallFunc_BreakVector_Z_3, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Lerp_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue_3, float K2Node_Event_Damage, const UDamageType* K2Node_Event_DamageType, AController* K2Node_Event_InstigatedBy, AActor* K2Node_Event_DamageCauser, bool CallFunc_EqualEqual_FloatFloat_ReturnValue, bool K2Node_Event_ExternalControl, bool K2Node_Event_BeginPlay, bool K2Node_Event_ChangeCamera, bool K2Node_Event_Instant_1, bool K2Node_Event_Is_Cutscene, bool K2Node_Event_Affect_Timer, bool K2Node_Event_Instant, bool K2Node_Event_Change_Camera, bool K2Node_Select_Default_2, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_Clamp_ReturnValue, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult_1, UPlayerController* CallFunc_GetPlayerController_ReturnValue_4, bool CallFunc_IsInViewport_ReturnValue_3, bool K2Node_CustomEvent_Open, bool K2Node_CustomEvent_DontWriteID, bool K2Node_CustomEvent_Is_Cutscene_1, bool K2Node_SwitchInteger_CmpSuccess_5, UPickUp_Action_UI_C* CallFunc_Create_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, bool K2Node_CustomEvent_Is_Cutscene, UPlayerController* CallFunc_GetPlayerController_ReturnValue_5, UPlayerController* CallFunc_GetPlayerController_ReturnValue_6, APawn* CallFunc_GetPlayerPawn_ReturnValue_2, uint8 K2Node_CustomEvent_NewType, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, int32 CallFunc_PostEventAtLocation_ReturnValue_1, FString CallFunc_CheckState_Same_ID, bool CallFunc_CheckState_Used, bool K2Node_SwitchInteger_CmpSuccess_6, bool K2Node_CustomEvent_Lock_1, bool K2Node_CustomEvent_Instant_1, float CallFunc_BreakVector_X_4, float CallFunc_BreakVector_Y_4, float CallFunc_BreakVector_Z_4, float CallFunc_BreakVector_X_5, float CallFunc_BreakVector_Y_5, float CallFunc_BreakVector_Z_5, FVector CallFunc_MakeVector_ReturnValue_4, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult, bool K2Node_SwitchInteger_CmpSuccess_7, FString CallFunc_GetDisplayName_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue_7, bool K2Node_SwitchInteger_CmpSuccess_8, float CallFunc_Add_FloatFloat_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue_8, UPlayerController* CallFunc_GetPlayerController_ReturnValue_9, APawn* CallFunc_GetPlayerPawn_ReturnValue_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, int32 CallFunc_PostEventAtLocation_ReturnValue_2, float CallFunc_Add_FloatFloat_ReturnValue_1, float CallFunc_Add_FloatFloat_ReturnValue_2, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_7, int32 CallFunc_PostAkEvent_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, FString CallFunc_Conv_IntToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, bool K2Node_CustomEvent_Freeze, float CallFunc_GetTimelineLength_ReturnValue, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_1, uint8 K2Node_Select_Default_3, UAkAudioEvent* K2Node_Select_Default_4, bool CallFunc_Not_PreBool_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_3, bool CallFunc_EqualEqual_IntInt_ReturnValue_4, bool K2Node_CustomEvent_Instant, int32 K2Node_CustomEvent_Index, int32 CallFunc_PostEventAtLocation_ReturnValue_4, bool CallFunc_IsRobiValid_ReturnValue_11, bool CallFunc_IsRobiValid_ReturnValue_12, int32 CallFunc_PostEventAtLocation_ReturnValue_5, bool CallFunc_IsRobiValid_ReturnValue_13, int32 CallFunc_PostEventAtLocation_ReturnValue_6, int32 CallFunc_PostEventAtLocation_ReturnValue_7, bool CallFunc_IsRobiValid_ReturnValue_14, bool CallFunc_IsRobiValid_ReturnValue_15, int32 CallFunc_PostEventAtLocation_ReturnValue_8, int32 CallFunc_PostEventAtLocation_ReturnValue_9, FText CallFunc_MakeLiteralText_ReturnValue, FText CallFunc_MakeLiteralText_ReturnValue_1, FText CallFunc_MakeLiteralText_ReturnValue_2, FString CallFunc_Conv_TextToString_ReturnValue, const FText K2Node_Select_Default_5, FString CallFunc_Conv_TextToString_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_3, FText CallFunc_Conv_StringToText_ReturnValue, USkipCutscene_Action_UI_C* CallFunc_Create_ReturnValue_2, APawn* CallFunc_GetPlayerPawn_ReturnValue_4, FKey K2Node_InputActionEvent_Key, UPlayer_Character_BP_C* K2Node_DynamicCast_AsPlayer_Character_BP, bool K2Node_DynamicCast_bSuccess, FKey K2Node_InputActionEvent_Key_1, FKey K2Node_InputActionEvent_Key_2, bool CallFunc_IsRobiValid_ReturnValue_16, float CallFunc_BreakVector_X_6, float CallFunc_BreakVector_Y_6, float CallFunc_BreakVector_Z_6, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, float CallFunc_Multiply_FloatFloat_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_8, bool CallFunc_IsValid_ReturnValue_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue_2, FVector K2Node_Select_Default_6, bool CallFunc_IsRobiValid_ReturnValue_17, int32 CallFunc_PostAkEvent_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue_18, bool CallFunc_IsRobiValid_ReturnValue_19, int32 CallFunc_PostAkEvent_ReturnValue_2, int32 CallFunc_PostAkEvent_ReturnValue_3, bool CallFunc_IsRobiValid_ReturnValue_20, bool CallFunc_IsRobiValid_ReturnValue_21, int32 CallFunc_PostAkEvent_ReturnValue_4, int32 CallFunc_PostAkEvent_ReturnValue_5, bool CallFunc_IsRobiValid_ReturnValue_22, bool CallFunc_IsRobiValid_ReturnValue_23, int32 CallFunc_PostAkEvent_ReturnValue_6, int32 CallFunc_PostAkEvent_ReturnValue_7, FVector CallFunc_K2_GetActorLocation_ReturnValue_9, FVector CallFunc_K2_GetActorLocation_ReturnValue_10, int32 CallFunc_PostEventAtLocation_ReturnValue_10, int32 CallFunc_PostEventAtLocation_ReturnValue_11, int32 CallFunc_PostEventAtLocation_ReturnValue_12, int32 CallFunc_PostEventAtLocation_ReturnValue_13, int32 CallFunc_PostEventAtLocation_ReturnValue_14, int32 CallFunc_PostEventAtLocation_ReturnValue_15, int32 CallFunc_PostEventAtLocation_ReturnValue_16, int32 CallFunc_PostEventAtLocation_ReturnValue_17, FVector CallFunc_K2_GetComponentLocation_ReturnValue_3, float CallFunc_BreakVector_X_7, float CallFunc_BreakVector_Y_7, float CallFunc_BreakVector_Z_7, FVector CallFunc_MakeVector_ReturnValue_5, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult_1, bool CallFunc_IsRobiValid_ReturnValue_24, USceneComponent* CallFunc_GetChildComponent_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_25, UPrimitiveComponent* K2Node_ComponentBoundEvent_HitComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, FVector K2Node_ComponentBoundEvent_NormalImpulse, const FHitResult K2Node_ComponentBoundEvent_Hit, int32 CallFunc_MakeLiteralInt_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_26, UMaterialInterface* CallFunc_GetMaterial_ReturnValue, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, int32 CallFunc_MakeLiteralInt_ReturnValue_1, UMaterialInterface* CallFunc_GetMaterial_ReturnValue_1, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue_27, int32 CallFunc_PostEventAtLocation_ReturnValue_18, int32 CallFunc_PostEventAtLocation_ReturnValue_19, float CallFunc_Lerp_ReturnValue_2, APawn* CallFunc_GetPlayerPawn_ReturnValue_5, FVector CallFunc_MakeVector_ReturnValue_6, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult_2, APawn* CallFunc_GetPlayerPawn_ReturnValue_6, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_2, float K2Node_Select_Default_7, float CallFunc_Subtract_FloatFloat_ReturnValue_1, float CallFunc_Lerp_ReturnValue_3, FVector CallFunc_MakeVector_ReturnValue_7, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult_2, bool Temp_bool_IsClosed_Variable_1, FKey K2Node_InputActionEvent_Key_3, bool Temp_bool_Variable_11, bool K2Node_CustomEvent_Lock, float K2Node_Select_Default_8, float CallFunc_BreakVector_X_8, float CallFunc_BreakVector_Y_8, float CallFunc_BreakVector_Z_8, FVector CallFunc_MakeVector_ReturnValue_8, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult_3, float CallFunc_BreakVector_X_9, float CallFunc_BreakVector_Y_9, float CallFunc_BreakVector_Z_9, float CallFunc_Subtract_FloatFloat_ReturnValue_2, FVector CallFunc_MakeVector_ReturnValue_9, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult_3, UPlayer_Character_BP_C* CallFunc_GetActorOfClass_ReturnValue, float CallFunc_BreakVector_X_10, float CallFunc_BreakVector_Y_10, float CallFunc_BreakVector_Z_10, FVector CallFunc_MakeVector_ReturnValue_10, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult_4, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult_5, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult_4, bool CallFunc_IsRobiValid_ReturnValue_28, bool CallFunc_IsRobiValid_ReturnValue_29, bool CallFunc_IsRobiValid_ReturnValue_30, APawn* CallFunc_GetPlayerPawn_ReturnValue_7, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_3, FString CallFunc_Concat_StrStr_ReturnValue_4, FString CallFunc_CheckState_Same_ID_1, bool CallFunc_CheckState_Used_1, bool Temp_bool_Variable_12, int32 CallFunc_PostEventAtLocation_ReturnValue_20, int32 Temp_int_Variable, bool K2Node_Select_Default_9);
    void FinishActivate__DelegateSignature();
}

#endif
