#ifndef UE4SS_SDK_enemy_character_parent_HPP
#define UE4SS_SDK_enemy_character_parent_HPP

class AEnemy_Character_Parent_C : UCharacter
{
    FPointerToUberGraphFrame UberGraphFrame;
    UAkComponent* Play_Vanish_SFX;
    UWidgetComponent* Alert;
    UDecalComponent* Decal_Shadow;
    UParticleSystemComponent* P_ShowMinion;
    UParticleSystemComponent* P_BlackSubstance;
    UPawnSensingComponent* PawnSensing;
    UWidgetComponent* Widget;
    float Timeline_1_Blur_822C98F144BAA83DF21B958EA7E6AA4E;
    TEnumAsByte<ETimelineDirection::Type> Timeline_1__Direction_822C98F144BAA83DF21B958EA7E6AA4E;
    UTimelineComponent* Timeline_1;
    float SineMovement_Lerp_97C5E80B4F1D34AD62B657BC40A0A270;
    TEnumAsByte<ETimelineDirection::Type> SineMovement__Direction_97C5E80B4F1D34AD62B657BC40A0A270;
    UTimelineComponent* SineMovement;
    float Move_Backwards_Alpha_60266F6B46FD51D6B3490E8251C4D0E5;
    TEnumAsByte<ETimelineDirection::Type> Move_Backwards__Direction_60266F6B46FD51D6B3490E8251C4D0E5;
    UTimelineComponent* Move Backwards;
    float Timeline_0_Blur_825C187D417DDC103C47C7A39E34CFE1;
    TEnumAsByte<ETimelineDirection::Type> Timeline_0__Direction_825C187D417DDC103C47C7A39E34CFE1;
    UTimelineComponent* Timeline_0;
    float HitBodyFlashTimeline_Hit_97A5830442F72E299E04F098996B4BEA;
    TEnumAsByte<ETimelineDirection::Type> HitBodyFlashTimeline__Direction_97A5830442F72E299E04F098996B4BEA;
    UTimelineComponent* HitBodyFlashTimeline;
    float RelocateTimeline_Alpha_B4D969DC4291BC66716E99B174DB08EB;
    TEnumAsByte<ETimelineDirection::Type> RelocateTimeline__Direction_B4D969DC4291BC66716E99B174DB08EB;
    UTimelineComponent* RelocateTimeline;
    bool Recorder Mode;
    AActor* TargetActor;
    bool Instant Kill;
    bool Min Health;
    float Health;
    FText Name;
    bool Is Boss;
    float CamMaxDistance;
    float MaxHealth;
    float Damage;
    float Damage Body;
    FEnemy_Character_Parent_CDie Die;
    void Die();
    UWidgetComponent* Widget_0;
    UEnemyHealth_C* HealthBar-DEPRECATED;
    bool Active;
    bool ShowHealthBar;
    bool AutoStart;
    bool Attacking;
    AShadowDecal_C* ShadowDecal;
    TEnumAsByte<E_EnemyBehaviour::Type> Behaviour;
    UBehaviorTree* BT;
    bool UseExpression;
    FST_Expression Expression Detect;
    FST_Expression Expression Angry;
    FST_Expression Expression Unreachable;
    bool Use AgroArea;
    int32 Currency;
    bool StartHidden;
    bool Fighting;
    FLinearColor FogColor;
    int32 BattleFase;
    UAudioComponent* BossAudio;
    float ShadowScale;
    bool TargetOn;
    TEnumAsByte<EnemyStates::Type> EnemyState;
    bool SkipIntro;
    bool AerialRise;
    bool CanAerialRise;
    bool CanBeBlasted;
    float Fase_01_Damage;
    float Fase_02_Damage;
    float Fase_03_Damage;
    float Health To Fase 2;
    float Health To Fase 3;
    FEnemy_Character_Parent_CTeleportOutDone TeleportOutDone;
    void TeleportOutDone();
    FEnemy_Character_Parent_CTeleportInDone TeleportInDone;
    void TeleportInDone();
    bool CanBeLocked;
    int32 ConsecutiveHits;
    FEnemy_Character_Parent_CRelocateFinished RelocateFinished;
    void RelocateFinished();
    bool Show Trace;
    bool Print Life;
    float OriginalGravity;
    TEnumAsByte<Directions::Type> HitDirection;
    APlayer_Character_BP_C* PlayerCharacter;
    TArray<AAttack_Master_C*> Attacks;
    UMaterialInstanceDynamic* BodyMaterial;
    bool PlayerInAgro;
    bool TeleportedIn;
    bool Stun;
    bool Angry;
    FEnemy_Character_Parent_CCallA CallA;
    void CallA();
    bool HasShadowDecal;
    UAkAudioEvent* AwareSound;
    TEnumAsByte<Items::Type> ItemDrop;
    bool DropItem;
    FTransform Initial Transform;
    UEnemyHealth_C* EnemyHealthUI;
    UBossHealth_C* Boss Health UI;
    bool Moving to Center;
    bool Use Nav Mesh;
    float Check Distance;
    bool Hit Player;
    FEnemy_Character_Parent_COnPlayerWarp OnPlayerWarp;
    void OnPlayerWarp();
    bool Mode Ambush;
    bool Skip Drop;
    bool Heal when Die;
    bool Is Hidden;
    int32 MaxCurrencyDrop;
    int32 MinCurrencyDrop;
    bool BT Flip Flop;
    bool Spawn Fast;
    bool Spawn Black Substance;
    bool Minus5dB;
    TEnumAsByte<EMovementMode> StartMovementMode;
    bool SetIdleInCutscene;
    bool TempIdle;
    FVector PreFreezeVelocity;
    float OriginalDamage;
    float OriginalMaxHealth;
    FVector MoveBackOriginal;
    FVector MoveBackDire;
    bool ShowTraceCheckWall;
    float BodyParticleFastRate;
    FColor VFX Color;
    FVector StartAttackLocation;
    bool IsDead;
    float LockCamPitchOffset;
    float LockCamDistanceOffset;
    bool FreezePause;
    float ChangeCurrencyShadow;
    UEnemy_Behaviour_FX_C* AlertUI;
    bool HitSuccess;
    FName HealthParentBone;
    FVector HealthParentOffset;
    FVector Start Relative Location;
    float Sine Speed;
    float Sine Max Position;
    bool IsPlayingExpression;
    FVector Last Player Location;
    float VFX Death Scale;
    int32 Current Difficulty;
    bool IsParry;
    float LockCamZOffset;
    float VerticalSeeDistance;
    float PlayerDirectionChase;
    FEnemy_Character_Parent_CBreak Attack Break Attack;
    void Break Attack();
    float LockOffsetDisplay;
    bool DestroyAnimInstanceOnPause;
    float LastMaxWalkSpeed;
    TEnumAsByte<EPhysicalSurface> EnemySurface;
    AEnemy_Master_AiController_C* IAMaster;
    int32 LoopCurrentValue;
    int32 LoopMaxValue;
    UAnimMontage* CurrentAnimMontage;
    FName CurrentSection;
    int32 DamageCounter;
    int32 MaxDamageCounter;
    bool CanModifyBrakingFriction;
    int32 Random Index;

    void PlayAnim(UAnimMontage* Current Montage, uint8 SectionName, bool Is Attacking, bool IsPlayingExpression, USkeletalMeshComponent*& Skeletal Mesh, UAnimMontage*& Montage to Play, FName& Section, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue, FName CallFunc_Conv_StringToName_ReturnValue);
    void CanSkipSequence(bool& Skip);
    void RandomLoop(bool& Set, FIntVector& Set Values, bool& Loop Completed, int32 Temp_int_Variable, int32 CallFunc_RandomIntegerInRange_ReturnValue, FString CallFunc_Conv_IntToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, FString CallFunc_Conv_IntToString_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue, FString CallFunc_Conv_IntToString_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_1, bool CallFunc_EqualEqual_IntInt_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_3);
    void GetDifficulty(float Newcomer, float Recommended, float Brutal, float& Result, int32& Difficulty, int32 Temp_int_Variable, float K2Node_Select_Default);
    void RecieveHit(float Damage, TSubclassOf<UCameraShake> Shake, UAkAudioEvent* AkEvent, bool OverrideHitTimeline, bool Cancel Rotate, bool Reset Agro, bool VFX Hit, const UDamageType* DamageType, bool& Dead, bool CallFunc_IsRobiValid_ReturnValue, TSubclassOf<UDamageType> CallFunc_GetObjectClass_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_1, bool CallFunc_EqualEqual_ClassClass_ReturnValue, TSubclassOf<UDamageType> CallFunc_GetObjectClass_ReturnValue_1, bool CallFunc_EqualEqual_ClassClass_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue, TArray<FName>& K2Node_MakeArray_Array, TArray<UActorComponent*>& CallFunc_GetComponentsByTag_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue, APawn* CallFunc_GetPlayerPawn_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, float CallFunc_Multiply_IntFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, FString CallFunc_Conv_TextToString_ReturnValue, int32 Temp_int_Array_Index_Variable, FString CallFunc_Concat_StrStr_ReturnValue, UActorComponent* CallFunc_Array_Get_Item, FString CallFunc_Concat_StrStr_ReturnValue_1, FString CallFunc_GetDisplayName_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue, bool Temp_bool_Variable, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_1, bool CallFunc_LessEqual_FloatFloat_ReturnValue, FString CallFunc_Conv_FloatToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_2, bool Temp_bool_Variable_1, float K2Node_Select_Default, float K2Node_Select_Default_1, int32 Temp_int_Array_Index_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_2, AAttack_Master_C* CallFunc_Array_Get_Item_1, bool CallFunc_IsRobiValid_ReturnValue_2, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Subtract_FloatFloat_ReturnValue_1);
    void RelocateTimeline__FinishedFunc();
    void RelocateTimeline__UpdateFunc();
    void HitBodyFlashTimeline__FinishedFunc();
    void HitBodyFlashTimeline__UpdateFunc();
    void SineMovement__FinishedFunc();
    void SineMovement__UpdateFunc();
    void Move Backwards__FinishedFunc();
    void Move Backwards__UpdateFunc();
    void Timeline_0__FinishedFunc();
    void Timeline_0__UpdateFunc();
    void Timeline_1__FinishedFunc();
    void Timeline_1__UpdateFunc();
    void OnNotifyEnd_E4A3E4BE4FEA9C6B20F39295875BC5AE(FName NotifyName);
    void OnNotifyBegin_E4A3E4BE4FEA9C6B20F39295875BC5AE(FName NotifyName);
    void OnInterrupted_E4A3E4BE4FEA9C6B20F39295875BC5AE(FName NotifyName);
    void OnBlendOut_E4A3E4BE4FEA9C6B20F39295875BC5AE(FName NotifyName);
    void OnCompleted_E4A3E4BE4FEA9C6B20F39295875BC5AE(FName NotifyName);
    void VFX Rate Body(bool Rate Fast);
    void VFX Dash(float Delay, float Lerp Distance);
    void VFX Slash(float Delay, float Rotation, float Scale);
    void VFX Shadow(bool Visibility);
    void VFX Body Particle(bool Show);
    void VFX Death();
    void VFX Teleport();
    void SFX Death();
    void TeleportOut();
    void TeleportIn();
    void Relocate(FVector CurrentLocation, FVector Target, float Duration, bool Stop);
    void TeleportInExtra();
    void TeleportOutExtra();
    void RotateToPlayer(bool SingleBurst, bool On, float RotateSpeed, float RotateSpeedCurve(1isnone), bool Rotation to Movement);
    void RotateToPlayerTick();
    void RotateToPlayerInstant();
    void CancelRotToPlayer();
    void StartTimerA(float Time);
    void CallTimerA();
    void CancelTimerA();
    void StartTimerACall();
    void CancelTimerACall();
    void Attack(int32 Selection, int32 Count, int32 Max Count, bool Use Custom Counter);
    void Attack01(int32 Count, int32 Max Count, bool Use Custom Counter);
    void AttackWindowOpen();
    void AttackWindowClose();
    void AttackWindowOpenCall();
    void AttackWindowCloseCall();
    void Attack02(int32 Count, int32 Max Count, bool Use Custom Counter);
    void HitBodyFlash();
    void StopStun();
    void StartStun();
    void CancelFollow();
    void Attack03(int32 Count, int32 Max Count, bool Use Custom Counter);
    void ExitBounds();
    void BeginAwareSound();
    void Start Movement(int32 N);
    void End Movement(int32 N);
    void RotateToInit(const float& Rotate Speed, const float& Rotate Speed Curve, const bool& On);
    void RotateToInitTick();
    void Update Health UI(float Health, float Max Health);
    void Restore Health();
    void In Room Center(bool CheckPlayerIsDead);
    void Anim Move Front(bool Move);
    void Anim Move Back(bool Move);
    void Call Event(FString Event Name);
    void Agro();
    void BndEvt__PawnSensing_K2Node_ComponentBoundEvent_2_SeePawnDelegate__DelegateSignature(APawn* Pawn);
    void BndEvt__PawnSensing_K2Node_ComponentBoundEvent_3_HearNoiseDelegate__DelegateSignature(APawn* Instigator, const FVector& Location, float Volume);
    void CheckDistance();
    void Start Agro(bool Start);
    void Attack04(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Attack05(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Instant Combat(float Delay);
    void Death Minion();
    void Show Minion();
    void Hide Minion();
    void Show Minion Extra();
    void Hide Minion Extra();
    void OnLanded(const FHitResult& Hit);
    void On Landed Extra();
    void Instant Combat Extra();
    void Set Visible Mesh(bool Visible);
    void CheckWall();
    void FreezeState(bool Freeze);
    void ExtraFreeze();
    void ExtraUnfreeze();
    void Force Idle State();
    void Force Agro State(APawn* Actor);
    void Force Idle State Extra();
    void Expression(uint8 Expression);
    void Sine(bool Play);
    void AttackExpression(int32 Number);
    void AttackExpression_01();
    void AttackExpression_02();
    void AttackExpression_03();
    void AttackExpression_04();
    void AttackExpression_05();
    void AttackExpression_06();
    void ReturnHandler1(bool Bool1, bool Bool2);
    void StartHealing();
    void StopDodge();
    void Attack 06(int32 Count, int32 Max Count, bool Use Custom Counter);
    void Idle Post Combat();
    void ReceiveEnemyHandler01(bool HitA, bool HitB);
    void ReceiveEnemyFunc03(bool Hit, FVector Location, FRotator Rotation, uint8 SurfaceType);
    void Rise(float DropOn, bool KeepInAir);
    void TickAdjusttoPlayerZ();
    void EndRise();
    void BndEvt__CapsuleComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void EnemyLaunch(uint8 Direction, FVector Origin);
    void RiseMontage();
    void FinishRise();
    void Make Flip Flop();
    void Back to Original Transform();
    void PlayBounceBack(float Force, bool UsePlayerZ);
    void StopMoveBack();
    void Set Braking Friction(bool SeparateBrakingFriction);
    void ReceiveBeginPlay();
    void ShadowLoop();
    void ReceiveDestroyed();
    void DestroyCall();
    void UpdateState(bool Active - Deprecated, bool ChangeState, uint8 EnemyState, bool NextFase);
    void ReceiveEndPlay(uint8 EndPlayReason);
    void SpawnShadow();
    void StartBoss();
    void ShowName();
    void EndIntro();
    void BossName();
    void RadialBlurGrowl(bool Scream, float ScreamScale, bool ShortScream);
    void LockedOn();
    void LockedOff();
    void EndBoss();
    void On Player Die();
    void Boss Appear();
    void Boss Desappear();
    void Restart();
    void Play Custom Cutscene();
    void Resume Custom Cutscene();
    void Relocate Player();
    void Set New Player Location(FVector New Location);
    void PlayerDieRun();
    void Create UI();
    void Set Visibility UI(bool Visibility);
    void Set One Hit Health();
    void Set Custom Health(float Health);
    void Replace by Statue(float Delay);
    void UnloadCall();
    void Move to Center(bool Moving);
    void Destroy Used();
    void Destroy Used Extra();
    void Show Teleport();
    void On Stream Out();
    void PlayCustomCutsceneExtra();
    void ResumeCustomCutsceneExtra();
    void AdjustDifficulty(bool BeginPlay);
    void AdjustHealthonDifficultyChange();
    void Kill();
    void CustomDamage(float Damage, bool Play Custom Animation);
    void DestroyStatue();
    void DontDestroyPawnSensing();
    void Fade Boss Health();
    void RetryBeginPlay();
    void Force Idle Animation();
    void UpdateBehaviour(int32 Behaviour);
    void Control Anim Montage(bool Stop);
    void OnAgroStateChanged(bool IsAgro);
    void Set Max Heal UI(bool Show, float Health);
    void MoveToRandomPlarform();
    void ReceiveEnemyFunc02(bool Hit, FVector Location, FRotator Rotation, uint8 SurfaceType);
    void ExecuteUbergraph_Enemy_Character_Parent(int32 EntryPoint, uint8 Temp_byte_Variable, FST_Expression Temp_struct_Variable, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FName K2Node_CustomEvent_NotifyName_4, FName K2Node_CustomEvent_NotifyName_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FName K2Node_CustomEvent_NotifyName_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FName K2Node_CustomEvent_NotifyName_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, FName K2Node_CustomEvent_NotifyName, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, FName Temp_name_Variable, bool Temp_bool_Variable, UParticleSystem* Temp_object_Variable, DelegateCustomLineTraceForObjectsBool__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, uint8 Temp_byte_Variable_1, DelegateCustomEnemy__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, FVector Temp_struct_Variable_1, FVector Temp_struct_Variable_2, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, UParticleSystem* Temp_object_Variable_1, bool CallFunc_IsRobiValid_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, UAreaIntro_C* CallFunc_Create_ReturnValue, WarpCall__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, Die__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, StreamOut__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, int32 Temp_int_Variable, float Temp_float_Variable, float Temp_float_Variable_1, float Temp_float_Variable_2, float Temp_float_Variable_3, int32 Temp_int_Variable_1, float Temp_float_Variable_4, float Temp_float_Variable_5, float Temp_float_Variable_6, float Temp_float_Variable_7, bool Temp_bool_Variable_3, bool Temp_bool_Variable_4, bool CallFunc_IsValid_ReturnValue_1, ESlateVisibility CallFunc_GetVisibility_ReturnValue, ESlateVisibility Temp_byte_Variable_2, ESlateVisibility Temp_byte_Variable_3, int32 Temp_int_Variable_2, float Temp_float_Variable_8, float Temp_float_Variable_9, float Temp_float_Variable_10, float Temp_float_Variable_11, bool CallFunc_IsValid_ReturnValue_2, DelegateCustomEnemy__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, UParticleSystem* Temp_object_Variable_2, bool K2Node_CustomEvent_Rate_Fast, float K2Node_CustomEvent_Delay_3, float K2Node_CustomEvent_Lerp_Distance, FParticleSysParam K2Node_MakeStruct_ParticleSysParam, TArray<FParticleSysParam>& K2Node_MakeArray_Array, const FTransform CallFunc_GetTransform_ReturnValue, float K2Node_CustomEvent_Delay_2, float K2Node_CustomEvent_Rotation_2, float K2Node_CustomEvent_Scale, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, float CallFunc_Multiply_FloatFloat_ReturnValue, FVector CallFunc_VLerp_ReturnValue, FVector CallFunc_MakeVector_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, FVector CallFunc_GetRightVector_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue, FParticleSysParam K2Node_MakeStruct_ParticleSysParam_1, FRotator CallFunc_Conv_VectorToRotator_ReturnValue, TArray<FParticleSysParam>& K2Node_MakeArray_Array_1, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, bool K2Node_CustomEvent_Visibility_1, FRotator CallFunc_MakeRotator_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, bool K2Node_CustomEvent_Show_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_2, FVector CallFunc_Conv_FloatToVector_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_3, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_2, bool CallFunc_Not_PreBool_ReturnValue_3, bool CallFunc_BooleanAND_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue, FVector K2Node_CustomEvent_CurrentLocation, FVector K2Node_CustomEvent_Target, float K2Node_CustomEvent_Duration, bool K2Node_CustomEvent_Stop_1, float CallFunc_GetTimelineLength_ReturnValue, float CallFunc_GetPlaybackPosition_ReturnValue, float CallFunc_NormalizeToRange_ReturnValue, FVector CallFunc_VLerp_ReturnValue_1, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult, bool CallFunc_K2_SetActorLocation_ReturnValue, bool K2Node_CustomEvent_SingleBurst, bool K2Node_CustomEvent_On_1, float K2Node_CustomEvent_RotateSpeed, float K2Node_CustomEvent_RotateSpeedCurve_1isnone_, bool K2Node_CustomEvent_Rotation_to_Movement, FTimerHandle CallFunc_K2_SetTimer_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, APawn* CallFunc_GetPlayerPawn_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_3, FVector CallFunc_K2_GetActorLocation_ReturnValue_4, FRotator CallFunc_FindLookAtRotation_ReturnValue, FRotator CallFunc_K2_GetActorRotation_ReturnValue, float CallFunc_BreakRotator_Roll_1, float CallFunc_BreakRotator_Pitch_1, float CallFunc_BreakRotator_Yaw_1, FRotator CallFunc_MakeRotator_ReturnValue_1, bool CallFunc_K2_SetActorRotation_ReturnValue, float K2Node_CustomEvent_Time, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_1, UParticleSystem* Temp_object_Variable_3, int32 K2Node_CustomEvent_Selection, int32 K2Node_CustomEvent_Count_6, int32 K2Node_CustomEvent_Max_Count_6, bool K2Node_CustomEvent_Use_Custom_Counter_6, int32 K2Node_CustomEvent_Count_5, int32 K2Node_CustomEvent_Max_Count_5, bool K2Node_CustomEvent_Use_Custom_Counter_5, bool K2Node_SwitchInteger_CmpSuccess, int32 K2Node_CustomEvent_Count_4, int32 K2Node_CustomEvent_Max_Count_4, bool K2Node_CustomEvent_Use_Custom_Counter_4, bool CallFunc_IsRobiValid_ReturnValue_2, bool CallFunc_IsRobiValid_ReturnValue_3, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult_1, bool CallFunc_K2_SetActorLocation_ReturnValue_1, int32 K2Node_CustomEvent_Count_3, int32 K2Node_CustomEvent_Max_Count_3, bool K2Node_CustomEvent_Use_Custom_Counter_3, UParticleSystem* Temp_object_Variable_4, int32 K2Node_CustomEvent_N_1, int32 K2Node_CustomEvent_N, const float K2Node_CustomEvent_Rotate_Speed, const float K2Node_CustomEvent_Rotate_Speed_Curve, const bool K2Node_CustomEvent_On, float CallFunc_Divide_FloatFloat_ReturnValue_1, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_2, FRotator CallFunc_K2_GetActorRotation_ReturnValue_1, FVector CallFunc_BreakTransform_Location_1, FRotator CallFunc_BreakTransform_Rotation_1, FVector CallFunc_BreakTransform_Scale_1, float K2Node_CustomEvent_Health_2, float K2Node_CustomEvent_Max_Health, FRotator CallFunc_NormalizedDeltaRotator_ReturnValue, float CallFunc_BreakRotator_Roll_2, float CallFunc_BreakRotator_Pitch_2, float CallFunc_BreakRotator_Yaw_2, bool CallFunc_IsRobiValid_ReturnValue_4, float CallFunc_Divide_FloatFloat_ReturnValue_2, float CallFunc_Multiply_FloatFloat_ReturnValue_1, FRotator CallFunc_MakeRotator_ReturnValue_2, FHitResult CallFunc_K2_AddActorWorldRotation_SweepHitResult, bool K2Node_CustomEvent_CheckPlayerIsDead, bool CallFunc_IsRobiValid_ReturnValue_5, bool K2Node_CustomEvent_Move_1, bool K2Node_CustomEvent_Move, FString K2Node_CustomEvent_Event_Name, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_3, APawn* K2Node_ComponentBoundEvent_Pawn, APawn* K2Node_ComponentBoundEvent_Instigator, const FVector K2Node_ComponentBoundEvent_Location, float K2Node_ComponentBoundEvent_Volume, bool CallFunc_IsRobiValid_ReturnValue_6, bool K2Node_CustomEvent_Start, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_4, int32 K2Node_CustomEvent_Count_2, int32 K2Node_CustomEvent_Max_Count_2, bool K2Node_CustomEvent_Use_Custom_Counter_2, int32 K2Node_CustomEvent_Count_1, int32 K2Node_CustomEvent_Max_Count_1, bool K2Node_CustomEvent_Use_Custom_Counter_1, float K2Node_CustomEvent_Delay_1, bool CallFunc_IsRobiValid_ReturnValue_7, bool CallFunc_IsRobiValid_ReturnValue_8, const FHitResult K2Node_Event_Hit, UParticleSystem* Temp_object_Variable_5, UParticleSystem* Temp_object_Variable_6, UParticleSystem* Temp_object_Variable_7, UParticleSystem* Temp_object_Variable_8, bool K2Node_CustomEvent_Visible, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_5, bool K2Node_CustomEvent_Freeze, bool CallFunc_NotEqual_ByteByte_ReturnValue, UParticleSystem* Temp_object_Variable_9, bool Temp_bool_Has_Been_Initd_Variable, bool Temp_bool_IsClosed_Variable, bool CallFunc_BooleanOR_ReturnValue, APawn* K2Node_CustomEvent_Actor, UPlayer_Character_BP_C* K2Node_DynamicCast_AsPlayer_Character_BP, bool K2Node_DynamicCast_bSuccess, FVector CallFunc_K2_GetActorLocation_ReturnValue_5, bool CallFunc_Not_PreBool_ReturnValue_4, UParticleSystem* Temp_object_Variable_10, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_2, uint8 K2Node_CustomEvent_Expression, bool CallFunc_IsRobiValid_ReturnValue_9, UParticleSystem* Temp_object_Variable_11, bool CallFunc_IsRobiValid_ReturnValue_10, bool K2Node_CustomEvent_Play, UParticleSystem* Temp_object_Variable_12, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, float CallFunc_Add_FloatFloat_ReturnValue, float CallFunc_Lerp_ReturnValue, FVector CallFunc_MakeVector_ReturnValue_1, FHitResult CallFunc_K2_SetRelativeLocation_SweepHitResult, FVector CallFunc_K2_GetActorLocation_ReturnValue_6, bool CallFunc_PlayerDistance_True, FST_Expression K2Node_Select_Default, bool CallFunc_IsRobiValid_ReturnValue_11, int32 CallFunc_PostEventAtLocation_ReturnValue_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_12, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_IsRobiValid_ReturnValue_13, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, UParticleSystem* Temp_object_Variable_13, APawn* CallFunc_GetPlayerPawn_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_7, FVector CallFunc_K2_GetActorLocation_ReturnValue_8, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, float CallFunc_BreakVector_X_2, float CallFunc_BreakVector_Y_2, float CallFunc_BreakVector_Z_2, float CallFunc_Subtract_FloatFloat_ReturnValue, uint8 CallFunc_MakeLiteralByte_ReturnValue, float CallFunc_Abs_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable_1, uint8 CallFunc_MakeLiteralByte_ReturnValue_1, bool Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable, int32 K2Node_CustomEvent_Number, bool CallFunc_IsValid_ReturnValue_4, bool K2Node_SwitchInteger_CmpSuccess_1, bool CallFunc_BooleanAND_ReturnValue_3, AActor* K2Node_Select_Default_1, FVector CallFunc_K2_GetActorLocation_ReturnValue_9, FRotator CallFunc_FindLookAtRotation_ReturnValue_1, FRotator CallFunc_NormalizedDeltaRotator_ReturnValue_1, float CallFunc_BreakRotator_Roll_3, float CallFunc_BreakRotator_Pitch_3, float CallFunc_BreakRotator_Yaw_3, float CallFunc_Divide_FloatFloat_ReturnValue_3, float CallFunc_Multiply_FloatFloat_ReturnValue_2, FRotator CallFunc_MakeRotator_ReturnValue_3, FHitResult CallFunc_K2_AddActorWorldRotation_SweepHitResult_1, UParticleSystem* Temp_object_Variable_14, UParticleSystem* Temp_object_Variable_15, UParticleSystem* Temp_object_Variable_16, UParticleSystem* Temp_object_Variable_17, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, bool CallFunc_IsRobiValid_ReturnValue_14, bool CallFunc_IsValid_ReturnValue_5, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, bool CallFunc_EqualEqual_ByteByte_ReturnValue_4, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_5, bool CallFunc_BooleanOR_ReturnValue_2, uint8 CallFunc_MakeLiteralByte_ReturnValue_2, bool CallFunc_BooleanOR_ReturnValue_3, bool K2Node_CustomEvent_Bool1, bool K2Node_CustomEvent_Bool2, UParticleSystem* Temp_object_Variable_18, bool CallFunc_IsRobiValid_ReturnValue_15, bool CallFunc_IsRobiValid_ReturnValue_16, uint8 CallFunc_MakeLiteralByte_ReturnValue_3, int32 K2Node_CustomEvent_Count, int32 K2Node_CustomEvent_Max_Count, bool K2Node_CustomEvent_Use_Custom_Counter, bool K2Node_CustomEvent_HitA, bool K2Node_CustomEvent_HitB, bool K2Node_CustomEvent_Hit_1, FVector K2Node_CustomEvent_Location_1, FRotator K2Node_CustomEvent_Rotation_1, uint8 K2Node_CustomEvent_SurfaceType_1, APawn* CallFunc_GetPlayerPawn_ReturnValue_3, UPlayer_Character_BP_C* K2Node_DynamicCast_AsPlayer_Character_BP_1, bool K2Node_DynamicCast_bSuccess_1, float K2Node_CustomEvent_DropOn, bool K2Node_CustomEvent_KeepInAir, APawn* CallFunc_GetPlayerPawn_ReturnValue_4, FVector CallFunc_K2_GetActorLocation_ReturnValue_10, FVector CallFunc_K2_GetActorLocation_ReturnValue_11, float CallFunc_BreakVector_X_3, float CallFunc_BreakVector_Y_3, float CallFunc_BreakVector_Z_3, float CallFunc_BreakVector_X_4, float CallFunc_BreakVector_Y_4, float CallFunc_BreakVector_Z_4, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_6, FVector CallFunc_MakeVector_ReturnValue_2, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult_2, bool CallFunc_K2_SetActorLocation_ReturnValue_2, UParticleSystem* Temp_object_Variable_19, UPrimitiveComponent* K2Node_ComponentBoundEvent_HitComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, FVector K2Node_ComponentBoundEvent_NormalImpulse, const FHitResult K2Node_ComponentBoundEvent_Hit, uint8 CallFunc_GetCollisionObjectType_ReturnValue, bool Temp_bool_IsClosed_Variable_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_6, UParticleSystem* Temp_object_Variable_20, uint8 K2Node_CustomEvent_Direction, FVector K2Node_CustomEvent_Origin, FVector CallFunc_K2_GetActorLocation_ReturnValue_12, FVector CallFunc_GetDirectionUnitVector_ReturnValue, FVector CallFunc_Multiply_VectorFloat_ReturnValue_1, FVector CallFunc_Multiply_VectorFloat_ReturnValue_2, float CallFunc_BreakVector_X_5, float CallFunc_BreakVector_Y_5, float CallFunc_BreakVector_Z_5, float CallFunc_BreakVector_X_6, float CallFunc_BreakVector_Y_6, float CallFunc_BreakVector_Z_6, FVector CallFunc_MakeVector_ReturnValue_3, FVector CallFunc_MakeVector_ReturnValue_4, FVector K2Node_Select_Default_2, bool CallFunc_IsRobiValid_ReturnValue_17, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_7, uint8 CallFunc_MakeLiteralByte_ReturnValue_4, float K2Node_CustomEvent_Force, bool K2Node_CustomEvent_UsePlayerZ, FHitResult CallFunc_K2_SetActorTransform_SweepHitResult, bool CallFunc_K2_SetActorTransform_ReturnValue, APawn* CallFunc_GetPlayerPawn_ReturnValue_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_13, FVector CallFunc_K2_GetActorLocation_ReturnValue_14, float CallFunc_BreakVector_X_7, float CallFunc_BreakVector_Y_7, float CallFunc_BreakVector_Z_7, float CallFunc_BreakVector_X_8, float CallFunc_BreakVector_Y_8, float CallFunc_BreakVector_Z_8, float K2Node_Select_Default_3, float K2Node_Select_Default_4, FVector CallFunc_MakeVector_ReturnValue_5, FVector CallFunc_MakeVector_ReturnValue_6, FVector CallFunc_GetDirectionUnitVector_ReturnValue_1, FVector CallFunc_Multiply_VectorFloat_ReturnValue_3, FVector CallFunc_Add_VectorVector_ReturnValue, FVector CallFunc_VLerp_ReturnValue_2, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult_3, bool CallFunc_K2_SetActorLocation_ReturnValue_3, bool K2Node_CustomEvent_SeparateBrakingFriction, uint8 CallFunc_MakeLiteralByte_ReturnValue_5, AController* CallFunc_GetController_ReturnValue, bool K2Node_CustomEvent_Active___Deprecated, bool K2Node_CustomEvent_ChangeState, uint8 K2Node_CustomEvent_EnemyState, bool K2Node_CustomEvent_NextFase, UBlackboardComponent* CallFunc_GetBlackboard_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_18, bool CallFunc_EqualEqual_ByteByte_ReturnValue_7, bool CallFunc_EqualEqual_ByteByte_ReturnValue_8, FName CallFunc_MakeLiteralName_ReturnValue, uint8 CallFunc_MakeLiteralByte_ReturnValue_6, int32 CallFunc_Add_IntInt_ReturnValue, uint8 K2Node_Event_EndPlayReason, bool CallFunc_EqualEqual_ByteByte_ReturnValue_9, bool CallFunc_EqualEqual_ByteByte_ReturnValue_10, bool CallFunc_BooleanOR_ReturnValue_4, bool CallFunc_IsRobiValid_ReturnValue_19, bool CallFunc_RandomBoolWithWeight_ReturnValue, UParticleSystem* Temp_object_Variable_21, FName CallFunc_MakeLiteralName_ReturnValue_1, FVector CallFunc_MakeVector_ReturnValue_7, FTransform CallFunc_MakeTransform_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_11, AShadowDecal_C* CallFunc_FinishSpawningActor_ReturnValue, UParticleSystem* Temp_object_Variable_22, UParticleSystem* Temp_object_Variable_23, APawn* CallFunc_GetPlayerPawn_ReturnValue_6, UPlayer_Character_BP_C* K2Node_DynamicCast_AsPlayer_Character_BP_2, bool K2Node_DynamicCast_bSuccess_2, UParticleSystem* Temp_object_Variable_24, AController* CallFunc_GetController_ReturnValue_1, UEnemy_Master_AiController_C* K2Node_DynamicCast_AsEnemy_Master_Ai_Controller, bool K2Node_DynamicCast_bSuccess_3, UParticleSystem* Temp_object_Variable_25, UParticleSystem* Temp_object_Variable_26, uint8 Temp_byte_Variable_4, UParticleSystem* K2Node_Select_Default_5, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_4, bool K2Node_CustomEvent_Scream, float K2Node_CustomEvent_ScreamScale, bool K2Node_CustomEvent_ShortScream, FVector CallFunc_Conv_FloatToVector_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue_20, int32 Temp_int_Variable_3, int32 CallFunc_Add_IntInt_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue_4, bool CallFunc_IsRobiValid_ReturnValue_21, bool CallFunc_IsRobiValid_ReturnValue_22, FVector CallFunc_K2_GetComponentLocation_ReturnValue, UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue, float CallFunc_BreakVector_X_9, float CallFunc_BreakVector_Y_9, float CallFunc_BreakVector_Z_9, UBossHealth_C* K2Node_DynamicCast_AsBoss_Health, bool K2Node_DynamicCast_bSuccess_4, UEnemyHealth_C* K2Node_DynamicCast_AsEnemy_Health, bool K2Node_DynamicCast_bSuccess_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_15, FTransform CallFunc_MakeTransform_ReturnValue_1, FTransform CallFunc_MakeTransform_ReturnValue_2, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2, UPickUpSpawn_C* CallFunc_FinishSpawningActor_ReturnValue_1, UPickUpSpawn_C* CallFunc_FinishSpawningActor_ReturnValue_2, FTransform CallFunc_MakeTransform_ReturnValue_3, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_3, UPickUpSpawn_C* CallFunc_FinishSpawningActor_ReturnValue_3, FColor CallFunc_Conv_LinearColorToColor_ReturnValue, FParticleSysParam K2Node_MakeStruct_ParticleSysParam_2, FColor CallFunc_Conv_LinearColorToColor_ReturnValue_1, TArray<FParticleSysParam>& K2Node_MakeArray_Array_2, FParticleSysParam K2Node_MakeStruct_ParticleSysParam_3, TArray<FParticleSysParam>& K2Node_MakeArray_Array_3, FTransform CallFunc_MakeTransform_ReturnValue_4, FTransform CallFunc_MakeTransform_ReturnValue_5, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_4, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_5, UPickUpSpawn_C* CallFunc_FinishSpawningActor_ReturnValue_4, FColor CallFunc_Conv_LinearColorToColor_ReturnValue_2, FParticleSysParam K2Node_MakeStruct_ParticleSysParam_4, TArray<FParticleSysParam>& K2Node_MakeArray_Array_4, UPickUpSpawn_C* CallFunc_FinishSpawningActor_ReturnValue_5, FTransform CallFunc_MakeTransform_ReturnValue_6, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_6, FColor CallFunc_Conv_LinearColorToColor_ReturnValue_3, FParticleSysParam K2Node_MakeStruct_ParticleSysParam_5, TArray<FParticleSysParam>& K2Node_MakeArray_Array_5, UPickUpSpawn_C* CallFunc_FinishSpawningActor_ReturnValue_6, FColor CallFunc_Conv_LinearColorToColor_ReturnValue_4, FParticleSysParam K2Node_MakeStruct_ParticleSysParam_6, FTransform CallFunc_MakeTransform_ReturnValue_7, TArray<FParticleSysParam>& K2Node_MakeArray_Array_6, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_7, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_5, UPickUpSpawn_C* CallFunc_FinishSpawningActor_ReturnValue_7, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_6, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_7, FColor CallFunc_Conv_LinearColorToColor_ReturnValue_5, FParticleSysParam K2Node_MakeStruct_ParticleSysParam_7, TArray<FParticleSysParam>& K2Node_MakeArray_Array_7, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_8, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_9, int32 Temp_int_Variable_4, const FTransform CallFunc_GetTransform_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_2, bool CallFunc_IsRobiValid_ReturnValue_23, FVector K2Node_CustomEvent_New_Location, bool K2Node_CustomEvent_Visibility, ESlateVisibility K2Node_Select_Default_6, bool CallFunc_NotEqual_ByteByte_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_5, float K2Node_CustomEvent_Health_1, float K2Node_CustomEvent_Delay, bool K2Node_CustomEvent_Moving, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_RandomIntegerInRange_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue_1, uint8 CallFunc_MakeLiteralByte_ReturnValue_7, bool CallFunc_EqualEqual_ByteByte_ReturnValue_12, int32 CallFunc_PostEventAtLocation_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_3, bool K2Node_SwitchInteger_CmpSuccess_2, bool K2Node_CustomEvent_BeginPlay, float CallFunc_NormalizeToRange_ReturnValue_1, float K2Node_CustomEvent_Damage, bool K2Node_CustomEvent_Play_Custom_Animation, UGameInstance* CallFunc_GetGameInstance_ReturnValue, int32 Temp_int_Variable_5, UBlueFire_Game_Instance_C* K2Node_DynamicCast_AsBlue_Fire_Game_Instance, bool K2Node_DynamicCast_bSuccess_6, bool CallFunc_LessEqual_IntInt_ReturnValue_2, int32 K2Node_Select_Default_7, int32 CallFunc_Add_IntInt_ReturnValue_3, float CallFunc_MakeLiteralFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue_1, FVector2D CallFunc_MakeVector2D_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_24, FTimerHandle CallFunc_K2_SetTimer_ReturnValue_8, UUserWidget* CallFunc_GetUserWidgetObject_ReturnValue_1, UEnemy_Behaviour_FX_C* K2Node_DynamicCast_AsEnemy_Behaviour_FX, bool K2Node_DynamicCast_bSuccess_7, bool CallFunc_K2_AttachToComponent_ReturnValue, bool CallFunc_NotEqual_NameName_ReturnValue, float CallFunc_BreakVector_X_10, float CallFunc_BreakVector_Y_10, float CallFunc_BreakVector_Z_10, float CallFunc_Add_FloatFloat_ReturnValue_2, FVector CallFunc_MakeVector_ReturnValue_8, FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult, bool CallFunc_IsRobiValid_ReturnValue_25, float K2Node_Select_Default_8, float K2Node_Select_Default_9, float CallFunc_Multiply_FloatFloat_ReturnValue_3, float CallFunc_FClamp_ReturnValue, float K2Node_Select_Default_10, float CallFunc_Multiply_FloatFloat_ReturnValue_4, float CallFunc_Multiply_FloatFloat_ReturnValue_5, FVector CallFunc_K2_GetActorLocation_ReturnValue_16, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_10, int32 K2Node_CustomEvent_Behaviour, AController* CallFunc_GetController_ReturnValue_2, FName CallFunc_MakeLiteralName_ReturnValue_2, UBlackboardComponent* CallFunc_GetBlackboard_ReturnValue_1, bool K2Node_CustomEvent_Stop, bool Temp_bool_Variable_5, float CallFunc_PlayAnimMontage_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_5, bool Temp_bool_Has_Been_Initd_Variable_2, bool K2Node_CustomEvent_IsAgro, bool K2Node_CustomEvent_Show, float K2Node_CustomEvent_Health, bool Temp_bool_IsClosed_Variable_2, bool CallFunc_IsRobiValid_ReturnValue_26, bool CallFunc_IsRobiValid_ReturnValue_27, bool CallFunc_IsRobiValid_ReturnValue_28, bool K2Node_CustomEvent_Hit, FVector K2Node_CustomEvent_Location, FRotator K2Node_CustomEvent_Rotation, uint8 K2Node_CustomEvent_SurfaceType, FHitResult CallFunc_K2_SetActorLocationAndRotation_SweepHitResult, bool CallFunc_K2_SetActorLocationAndRotation_ReturnValue);
    void Break Attack__DelegateSignature();
    void OnPlayerWarp__DelegateSignature();
    void CallA__DelegateSignature();
    void RelocateFinished__DelegateSignature();
    void TeleportInDone__DelegateSignature();
    void TeleportOutDone__DelegateSignature();
    void Die__DelegateSignature();
}

#endif
