#ifndef UE4SS_SDK_FireKeep_Climb_Hint_HPP
#define UE4SS_SDK_FireKeep_Climb_Hint_HPP

class USequenceDirector_C : ULevelSequenceDirector
{
    FPointerToUberGraphFrame UberGraphFrame;

    void Nuos_Temple_Intro_Controller_Event_0(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_2(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_4(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_5(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Uthas_Intro_Controller_Event_0(UUthas_Intro_Controller_C* Uthas_Intro_Controller);
    void Uthas_Intro_Controller_Event_1(UUthas_Intro_Controller_C* Uthas_Intro_Controller);
    void Uthas_Intro_Controller_Event_2(UUthas_Intro_Controller_C* Uthas_Intro_Controller);
    void Uthas_Intro_Controller_Event_3(UUthas_Intro_Controller_C* Uthas_Intro_Controller);
    void Uthas_Intro_Controller_Event_4(UUthas_Intro_Controller_C* Uthas_Intro_Controller);
    void Uthas_Intro_Controller_Event_5(UUthas_Intro_Controller_C* Uthas_Intro_Controller);
    void Uthas_Intro_Controller_Event_6(UUthas_Intro_Controller_C* Uthas_Intro_Controller);
    void Uthas_Intro_Controller_Event_7(UUthas_Intro_Controller_C* Uthas_Intro_Controller);
    void ExecuteUbergraph_SequenceDirector(int32 EntryPoint, UUthas_Intro_Controller_C* K2Node_CustomEvent_Uthas_Intro_Controller, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_3, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_2, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_1, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller, UUthas_Intro_Controller_C* K2Node_CustomEvent_Uthas_Intro_Controller_7, UUthas_Intro_Controller_C* K2Node_CustomEvent_Uthas_Intro_Controller_6, UUthas_Intro_Controller_C* K2Node_CustomEvent_Uthas_Intro_Controller_5, UUthas_Intro_Controller_C* K2Node_CustomEvent_Uthas_Intro_Controller_4, UUthas_Intro_Controller_C* K2Node_CustomEvent_Uthas_Intro_Controller_3, UUthas_Intro_Controller_C* K2Node_CustomEvent_Uthas_Intro_Controller_2, UUthas_Intro_Controller_C* K2Node_CustomEvent_Uthas_Intro_Controller_1);
}

#endif
