#ifndef UE4SS_SDK_GameMenu_HPP
#define UE4SS_SDK_GameMenu_HPP

class UGameMenu_C : UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UWidgetAnimation* FadeStartGame;
    UWidgetAnimation* RestoreControls;
    UWidgetAnimation* FadeOutAn;
    UWidgetAnimation* ChangeTabAnim;
    UWidgetAnimation* ExitSelect;
    UWidgetAnimation* StartSelect;
    UWidgetAnimation* Idle;
    UWidgetAnimation* FadeIn;
    UAction_Remap_Option_C* Action_Remap_Option;
    UAction_Remap_Option_C* Action_Remap_Option_1;
    UImage* Background;
    UTextBlock* BuildVersion;
    UWidgetSwitcher* ControlPlatformSwitch;
    UControlsUI_ProSwitch_C* ControlsUI_ProSwitch;
    UControlsUI_PS_C* ControlsUI_PS;
    UControlsUI_Stadia_C* ControlsUI_Stadia;
    UControlsUI_Switch_C* ControlsUI_Switch;
    UControlsUI_Xbox_C* ControlsUI_Xbox;
    UWrapBox* DemoSelectWrap;
    UTextBlock* DifficultyDescription;
    UGameMenuTitle_C* Discord;
    UEditableTextBox* EditableTextBox_89;
    UGameMenuTitle_C* Exit;
    UImage* FadeoutAnim;
    UGameMenuTitle_C* File;
    UGameMenuTitle_C* File_1;
    UWrapBox* FileOptions_Wrap;
    UScrollBox* FileScrollBox;
    UFileSelect_C* FileSelect_41;
    UFileSelect_C* FileSelect_78;
    UFileSelect_C* FileSelect_102;
    UFileSelect_C* FileSelect_173;
    UFileSelect_C* FileSelect_485;
    UFileSelect_C* FileSelect_646;
    UFileSelect_C* FileSelect_785;
    UFileSelect_C* FileSelect_921;
    UFileSelect_C* FileSelect_1418;
    UFileSelect_C* FileSelect_1598;
    UFileSelect_C* FileSelect_1750;
    UFileSelect_C* FileSelect_1880;
    UWrapBox* FileSelectedConfirmationBox;
    UWrapBox* FileSelectedConfirmationBox_1;
    UGameDemo_Options_C* GameDemo_Options;
    UGameDemo_Options_C* GameDemo_Options_175;
    UGameMenuTitle_C* GameMenuTitle;
    UGameMenuTitle_C* GameMenuTitle_1;
    UGameMenuTitle_C* GameMenuTitle_2;
    UGameMenuTitle_C* GameMenuTitle_3;
    UGameMenuTitle_C* GameMenuTitle_4;
    UGameMenuTitle_C* GameMenuTitle_5;
    UGameMenuTitle_C* GameMenuTitle_6;
    UGameMenuTitle_C* GameMenuTitle_260;
    UGameMenuTitle_C* GameMenuTitle_425;
    UWrapBox* Gamepad_KeyMap_Options;
    UImage* HorBarTitle;
    UImage* HorBarTitle_1;
    UImage* HorBarTitle_2;
    UImage* Image;
    UImage* Image_0;
    UImage* Image_1;
    UImage* Image_2;
    UImage* Image_3;
    UImage* Image_4;
    UImage* Image_5;
    UImage* Image_6;
    UImage* Image_7;
    UImage* Image_63;
    UImage* Image_86;
    UWrapBox* MainMenuWrap;
    UGameMenuTitle_C* Maker;
    UMenu_ConfirmationBox_C* Menu_ConfirmationBox_Left;
    UMenu_ConfirmationBox_C* Menu_ConfirmationBox_Left_1;
    UMenu_ConfirmationBox_C* Menu_ConfirmationBox_Right;
    UOptionMaster_C* OptionAntialising;
    UOptionMaster_C* OptionCamSensitibity;
    UOptionMaster_C* OptionEffectsVol;
    UOptionMaster_C* OptionIdleCamMovement;
    UOptionMaster_C* OptionInvertHorCam;
    UOptionMaster_C* OptionInvertVerticalCam;
    UOptionMaster_C* OptionLanguage;
    UOptionMaster_C* OptionMaster;
    UOptionMaster_C* OptionMaster_461;
    UOptionMaster_C* OptionMaster_CamAutoAdjust;
    UOptionMaster_C* OptionMaster_CameraShakes;
    UOptionMaster_C* OptionMaster_FPSLimit;
    UOptionMaster_C* OptionMaster_MotionBlur;
    UOptionMaster_C* OptionMaster_Rumble;
    UOptionMaster_C* OptionMaster_ScreenMode;
    UOptionMaster_C* OptionMaster_StadiaPerformance;
    UOptionMaster_C* OptionMusicVol;
    UOptionMaster_C* OptionPostProcess;
    UOptionMaster_C* OptionScreenRes;
    UOptionMaster_C* OptionShadowQuality;
    UOptionMaster_C* OptionSmoothCamRotation;
    UOptionMaster_C* OptionTextureQuality;
    UOverlay* Overlay_0;
    UOverlay* Overlay_1;
    UCanvasPanel* PC;
    UTextBlock* PC_ActionRemap;
    UAction_Remap_Option_C* PC_Camera;
    UAction_Remap_Option_C* PC_Camera_1;
    UAction_Remap_Option_C* PC_Dash;
    UAction_Remap_Option_C* PC_Dash_1;
    UAction_Remap_Option_C* PC_EmoteMenu;
    UAction_Remap_Option_C* PC_EmoteMenu_1;
    UAction_Remap_Option_C* PC_Horizontal_Attack;
    UAction_Remap_Option_C* PC_Horizontal_Attack_1;
    UAction_Remap_Option_C* PC_Interact;
    UAction_Remap_Option_C* PC_Interact_1;
    UAction_Remap_Option_C* PC_Jump;
    UAction_Remap_Option_C* PC_Jump_1;
    UWrapBox* PC_KeyMap_Options;
    UTextBlock* PC_KeyMappingPrompt;
    UAction_Remap_Option_C* PC_Lock;
    UAction_Remap_Option_C* PC_Lock_1;
    UAction_Remap_Option_C* PC_LockSwitch;
    UAction_Remap_Option_C* PC_LockSwitch_1;
    UAction_Remap_Option_C* PC_Movement;
    UAction_Remap_Option_C* PC_Movement_1;
    UAction_Remap_Option_C* PC_Pause;
    UAction_Remap_Option_C* PC_Pause_1;
    UAction_Remap_Option_C* PC_QuickEmote;
    UAction_Remap_Option_C* PC_QuickEmote_1;
    UOverlay* PC_Remap_Prompt_NewKey;
    UAction_Remap_Option_C* PC_RestoreHealth;
    UAction_Remap_Option_C* PC_RestoreHealth_1;
    UAction_Remap_Option_C* PC_Shield;
    UAction_Remap_Option_C* PC_Shield_1;
    UAction_Remap_Option_C* PC_Sprint;
    UAction_Remap_Option_C* PC_Sprint_1;
    UAction_Remap_Option_C* PC_Vertical_Attack;
    UAction_Remap_Option_C* PC_Vertical_Attack_1;
    UGameMenuTitle_C* PlayDemo;
    UCanvasPanel* PS4;
    UAction_Remap_Option_C* RestoreToDefaults;
    UAction_Remap_Option_C* RestoreToDefaults_1;
    UWrapBox* SaveFileWrapBox_1;
    UScrollBox* ScrollBox_103;
    UScrollBox* ScrollBox_231;
    USelectCommands_C* SelectCommands;
    USelectCommands_C* SelectCommands_1;
    USelectCommands_C* SelectCommands_199;
    USelectCommands_C* SelectCommands_960;
    USelectCommands_C* SelectCommands_C;
    USelectCommands_C* SelectCommands_C_0;
    USelectCommands_C* SelectCommands_C_1;
    USelectCommands_C* SelectCommands_C_2;
    USelectCommands_C* SelectCommands_C_3;
    USelectCommands_C* SelectCommands_C_4;
    USelectCommands_C* SelectCommands_C_5;
    USelectCommands_C* SelectCommands_C_6;
    USelectCommands_C* SelectCommands_C_7;
    USelectCommands_C* SelectCommands_C_8;
    UGameMenuTitle_C* Settings;
    UWrapBox* SettingsMainWrap;
    UWrapBox* SettingsMainWrap_1;
    UCanvasPanel* Splash_10;
    UCanvasPanel* Stadia;
    UCanvasPanel* StadiaGamepadMap;
    UCanvasPanel* Switch;
    UCanvasPanel* SwitchPro;
    UTextBlock* TextBlock;
    UTextBlock* TextBlock_0;
    UTextBlock* TextBlock_1;
    UTextBlock* TextBlock_3;
    UTextBlock* TextBlock_4;
    UTextBlock* TextBlock_5;
    UTextBlock* TextBlock_6;
    UTextBlock* TextBlock_7;
    UTextBlock* TextBlock_8;
    UTextBlock* TextBlock_9;
    UTextBlock* TextBlock_10;
    UTextBlock* TextBlock_761;
    UWidgetSwitcher* WidgetSwitcher_0;
    UWidgetSwitcher* WidgetSwitcher_1;
    UWrapBox* WrapBox_0;
    UCanvasPanel* XboxPlatform;
    UTextBlock* XboxUserName;
    UBorder* XboxUserTag;
    UBorder* XboxWarning;
    UImage* XboxWarningImg;
    UTextBlock* XboxWarningTxt;
    AGameMenuController_C* GameMenuController;
    int32 SelectedIndexMain;
    int32 SelectedTab;
    int32 SelectedIndexFileSelect;
    int32 SelectedIndexOptions;
    int32 SelectedMainSettingsIndex;
    int32 SelectedIndexGameSettings;
    UBlueFire_Game_Instance_C* BlueFireGameInstance;
    int32 FileSelectedSelectionIndex;
    bool FileSelectedDeleteScreen;
    bool FileSelectedExists;
    bool Demo;
    int32 SelectedIndexDemo;
    TArray<FName> PC_Default_KeysToMap;
    TArray<FKey> PC_Default_KeysToMapKeys;
    bool KeyMapListenReady;
    FName PC_KeyToReMap;
    int32 PCMapOptionSelectedIndex;
    FKey PC_PreviousKey;
    bool KeyMapListen;
    TArray<FKey> PC_RemapBlockedKeys;
    int32 SelectedOptionFileName;
    int32 SelectedDifficultyOption;
    bool BeatenGameSystem;
    bool WritingFileName;
    FName GamepadKeyToReMap;
    TArray<FName> GamepadDefaultKeysToMap;
    TArray<FKey> GamepadRemapBlockedKeys;
    int32 StadiaMapOptionSelectedIndex;
    TArray<FKey> GamepadDefaultKeysToMapKeys;
    TArray<UWidget*> FileSavesToDelete;
    bool FileSavedDeleted;
    USaveGame* SaveGameObject;
    bool SaveGameExists;
    int32 PS4FileInt;
    int32 FileOptionsIndex;
    int32 DuplicateTarget;
    FGameMenu_CReturn Return;
    void Return();
    bool RenamingFile;
    FText Filename;

    void Is PS4 or Xbox(bool& Result, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue);
    void Completed_BEE5432B4648DC92D1BE03B55BA090E4(USaveGame* SaveGame, bool bSuccess);
    void Completed_429718C04CB3B338F218A0B12323BC44(USaveGame* SaveGame, bool bSuccess);
    void Completed_D257FDB74C3365C0B8167B96C12927F0(USaveGame* SaveGame, bool bSuccess);
    void Completed_F52C275D4516865903A91A859F76A6D5(USaveGame* SaveGame, bool bSuccess);
    void XboxChangeUser();
    void PC_InitializeButtonMapping(bool OnlySelected);
    void PC_EndRemap(bool OnlySelected);
    void PC_CancelRemap();
    void PC_SetRemapKey(const FKey& InputPin);
    void PC_KeysRestoreToDefault();
    void ExitMapping();
    void ErrorMapping();
    void PC_StartRemap();
    void ConfirmKeyMap();
    void RecieveMovementMapping(bool RefreshOnly, uint8 Directions);
    void Stadia_InitializeButtonMapping(bool OnlySelected);
    void Stadia_StartReMap();
    void Stadia_EndReMap(bool OnlySelected);
    void Stadia_CancelRemap();
    void Stadia_SetReMapKey(const FKey& InputPin);
    void Stadia_KeysRestoreToDefault();
    void Stadia_ExitMapping();
    void Stadia_ErrorMapping();
    void XboxSetUserName();
    void XboxShowLoginUI(bool Is Switch Profile);
    void XboxUserTitleScreen();
    void ChangeSelection(bool Up, bool NULL, uint8 Direction);
    void ActivateControl();
    void StartMenu(AGameMenuController_C* GameMenuController, USaveGame* SaveGameObject, bool SaveGameExists);
    void ChangeTab(int32 SelectedTab);
    void LoadSaveFiles();
    void ChangeOption(bool Right);
    void ClearSaveFile();
    void ChangeSelSound(bool Play);
    void LoadSettingsAndApply();
    void FadeOut();
    void Construct();
    void Update();
    void FileSelectedMoveSide(bool Right);
    void FileSelectedConfirm();
    void FileSelectedReset();
    void FileSelectBack();
    void UpdateControlScheme();
    void WriteFileName();
    void CancelWrite();
    void EndType(const FText& Text, uint8 CommitMethod);
    void ConfirmWrite();
    void RecieveConfirmNewFile();
    void ResetFileName();
    void BndEvt__EditableTextBox_89_K2Node_ComponentBoundEvent_1_OnEditableTextBoxChangedEvent__DelegateSignature(const FText& Text);
    void RefreshAll();
    void Move(bool Error);
    void Loop PS4();
    void Check Xbox Series X();
    void DuplicateFile();
    void RunDuplicate();
    void DisplayMessage(FText Text);
    void CallReturn();
    void DuplicateNoSpaceReturn();
    void DuplicateReturnSuccess();
    void ChangeFileName();
    void DeleteSaveFile();
    void ExecuteFileRename();
    void ExecuteUbergraph_GameMenu(int32 EntryPoint, int32 CallFunc_PostEventAtLocation_ReturnValue, FName Temp_name_Variable, FName Temp_name_Variable_1, FName Temp_name_Variable_2, FName Temp_name_Variable_3, FName Temp_name_Variable_4, FName Temp_name_Variable_5, FName Temp_name_Variable_6, FName Temp_name_Variable_7, FName Temp_name_Variable_8, FName Temp_name_Variable_9, FName Temp_name_Variable_10, FName Temp_name_Variable_11, FName Temp_name_Variable_12, FName Temp_name_Variable_13, FName Temp_name_Variable_14, FName Temp_name_Variable_15, FName Temp_name_Variable_16, FName Temp_name_Variable_17, FName Temp_name_Variable_18, FName Temp_name_Variable_19, FName Temp_name_Variable_20, FName Temp_name_Variable_21, FName Temp_name_Variable_22, bool Temp_bool_Variable, int32 Temp_int_Variable, bool Temp_bool_Variable_1, int32 Temp_int_Variable_1, int32 Temp_int_Variable_2, bool Temp_bool_Variable_2, bool K2Node_SwitchInteger_CmpSuccess, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 Temp_int_Variable_3, int32 Temp_int_Variable_4, bool Temp_bool_Variable_3, int32 Temp_int_Variable_5, int32 Temp_int_Variable_6, bool Temp_bool_Variable_4, int32 Temp_int_Variable_7, int32 Temp_int_Variable_8, int32 Temp_int_Variable_9, UPanelWidget* Temp_object_Variable, UPanelWidget* Temp_object_Variable_1, UPanelWidget* Temp_object_Variable_2, UPanelWidget* Temp_object_Variable_3, int32 Temp_int_Variable_10, int32 Temp_int_Variable_11, int32 Temp_int_Variable_12, int32 Temp_int_Variable_13, int32 Temp_int_Variable_14, bool Temp_bool_Variable_5, int32 Temp_int_Variable_15, int32 Temp_int_Variable_16, bool Temp_bool_Variable_6, int32 Temp_int_Variable_17, int32 Temp_int_Variable_18, bool Temp_bool_Variable_7, int32 Temp_int_Variable_19, bool Temp_bool_Variable_8, OnEditableTextBoxCommittedEvent__DelegateSignature K2Node_CreateDelegate_OutputDelegate, int32 Temp_int_Variable_20, int32 Temp_int_Variable_21, bool Temp_bool_Variable_9, RefreshAll__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, int32 Temp_int_Variable_22, int32 Temp_int_Variable_23, uint8 Temp_byte_Variable, uint8 Temp_byte_Variable_1, bool Temp_bool_Variable_10, bool Temp_bool_Variable_11, OnAsyncHandleSaveGame__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, USaveGame* K2Node_CustomEvent_SaveGame_3, bool K2Node_CustomEvent_bSuccess_3, bool Temp_bool_Variable_12, USaveGame* Temp_object_Variable_4, USaveGame* K2Node_CustomEvent_SaveGame_2, bool K2Node_CustomEvent_bSuccess_2, OnAsyncHandleSaveGame__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, bool Temp_bool_Variable_13, USaveGame* Temp_object_Variable_5, UBlueFireSaveGame_C* K2Node_DynamicCast_AsBlue_Fire_Save_Game, bool K2Node_DynamicCast_bSuccess, int32 Temp_int_Variable_24, FText Temp_text_Variable, FText Temp_text_Variable_1, FText Temp_text_Variable_2, OnAsyncHandleSaveGame__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, USaveGame* K2Node_CustomEvent_SaveGame_1, bool K2Node_CustomEvent_bSuccess_1, bool Temp_bool_Variable_14, USaveGame* Temp_object_Variable_6, Return__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, Return__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, bool Temp_bool_Variable_15, int32 Temp_int_Variable_25, int32 Temp_int_Variable_26, bool Temp_bool_Variable_16, FText Temp_text_Variable_3, FText Temp_text_Variable_4, USaveGame* K2Node_CustomEvent_SaveGame, bool K2Node_CustomEvent_bSuccess, OnAsyncHandleSaveGame__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, bool Temp_bool_Variable_17, USaveGame* Temp_object_Variable_7, FString CallFunc_Get_Xbox_User_Name_User_Name, FString CallFunc_Right_ReturnValue, bool CallFunc_Get_Xbox_User_Is_Logged_IsLogged, FString CallFunc_Concat_StrStr_ReturnValue, FString CallFunc_Replace_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue, FName Temp_name_Variable_23, UInputSettings* CallFunc_GetInputSettings_ReturnValue, FName Temp_name_Variable_24, FName Temp_name_Variable_25, bool K2Node_CustomEvent_OnlySelected_3, int32 CallFunc_GetChildrenCount_ReturnValue, bool K2Node_CustomEvent_OnlySelected_2, const FKey K2Node_CustomEvent_InputPin_1, FText CallFunc_Key_GetDisplayName_ReturnValue, bool CallFunc_Key_IsGamepadKey_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue, FText CallFunc_Key_GetDisplayName_ReturnValue_1, FString CallFunc_Conv_TextToString_ReturnValue_1, FString CallFunc_Replace_ReturnValue_1, FName CallFunc_Conv_StringToName_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, FPlatformInputInfoStructure CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, FName Temp_name_Variable_26, TArray<FInputActionKeyMapping>& CallFunc_GetActionMappingByName_OutMappings, FInputActionKeyMapping CallFunc_Array_Get_Item, FName Temp_name_Variable_27, FString CallFunc_Conv_NameToString_ReturnValue, FInputActionKeyMapping K2Node_MakeStruct_InputActionKeyMapping, FString CallFunc_Concat_StrStr_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_2, FName Temp_name_Variable_28, FString CallFunc_Concat_StrStr_ReturnValue_3, UInputSettings* CallFunc_GetInputSettings_ReturnValue_1, FName Temp_name_Variable_29, int32 Temp_int_Loop_Counter_Variable, FName Temp_name_Variable_30, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, UWidget* CallFunc_GetChildAt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, UAction_Remap_Option_C* K2Node_DynamicCast_AsAction_Remap_Option, bool K2Node_DynamicCast_bSuccess_1, UInputSettings* CallFunc_GetInputSettings_ReturnValue_2, FName Temp_name_Variable_31, int32 Temp_int_Array_Index_Variable, FName Temp_name_Variable_32, FName Temp_name_Variable_33, int32 Temp_int_Loop_Counter_Variable_2, FName Temp_name_Variable_34, int32 CallFunc_Add_IntInt_ReturnValue_2, UWidget* CallFunc_GetChildAt_ReturnValue_1, UAction_Remap_Option_C* K2Node_DynamicCast_AsAction_Remap_Option_1, bool K2Node_DynamicCast_bSuccess_2, FName Temp_name_Variable_35, FText CallFunc_GetText_ReturnValue, UWidget* CallFunc_GetChildAt_ReturnValue_2, UAction_Remap_Option_C* K2Node_DynamicCast_AsAction_Remap_Option_2, bool K2Node_DynamicCast_bSuccess_3, UWidget* CallFunc_GetActiveWidget_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, FName Temp_name_Variable_36, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, FName Temp_name_Variable_37, FName Temp_name_Variable_38, FName Temp_name_Variable_39, bool K2Node_CustomEvent_RefreshOnly, uint8 K2Node_CustomEvent_Directions, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, bool CallFunc_EqualEqual_ByteByte_ReturnValue_4, bool CallFunc_EqualEqual_ByteByte_ReturnValue_5, bool CallFunc_EqualEqual_ByteByte_ReturnValue_6, bool CallFunc_BooleanOR_ReturnValue, FName Temp_name_Variable_40, bool CallFunc_BooleanOR_ReturnValue_1, FName Temp_name_Variable_41, int32 Temp_int_Array_Index_Variable_1, FName Temp_name_Variable_42, int32 CallFunc_PostEventAtLocation_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_3, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_4, UInputSettings* CallFunc_GetInputSettings_ReturnValue_3, FName Temp_name_Variable_43, FName Temp_name_Variable_44, bool K2Node_CustomEvent_OnlySelected_1, bool K2Node_CustomEvent_OnlySelected, const FKey K2Node_CustomEvent_InputPin, bool CallFunc_Key_IsGamepadKey_ReturnValue_1, FText CallFunc_Key_GetDisplayName_ReturnValue_2, FString CallFunc_Conv_TextToString_ReturnValue_2, FString CallFunc_Replace_ReturnValue_2, FName CallFunc_Conv_StringToName_ReturnValue_1, FName Temp_name_Variable_45, FPlatformInputInfoStructure CallFunc_GetDataTableRowFromName_OutRow_1, bool CallFunc_GetDataTableRowFromName_ReturnValue_1, TArray<FInputActionKeyMapping>& CallFunc_GetActionMappingByName_OutMappings_1, int32 Temp_int_Loop_Counter_Variable_3, FInputActionKeyMapping CallFunc_Array_Get_Item_1, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 Temp_int_Array_Index_Variable_2, FName Temp_name_Variable_46, FName Temp_name_Variable_47, FInputActionKeyMapping K2Node_MakeStruct_InputActionKeyMapping_1, FName Temp_name_Variable_48, UInputSettings* CallFunc_GetInputSettings_ReturnValue_4, FName Temp_name_Variable_49, int32 Temp_int_Variable_27, FName Temp_name_Variable_50, int32 CallFunc_Add_IntInt_ReturnValue_4, UInputSettings* CallFunc_GetInputSettings_ReturnValue_5, int32 Temp_int_Variable_28, FName Temp_name_Variable_51, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_5, FName Temp_name_Variable_52, FName Temp_name_Variable_53, int32 Temp_int_Variable_29, int32 CallFunc_Add_IntInt_ReturnValue_6, FName Temp_name_Variable_54, int32 CallFunc_PostEventAtLocation_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_6, FName Temp_name_Variable_55, UWidget* CallFunc_GetChildAt_ReturnValue_3, int32 CallFunc_Array_Length_ReturnValue, UAction_Remap_Option_C* K2Node_DynamicCast_AsAction_Remap_Option_3, bool K2Node_DynamicCast_bSuccess_4, int32 CallFunc_GetChildrenCount_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, FName CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_1, TArray<FInputActionKeyMapping>& CallFunc_GetActionMappingByName_OutMappings_2, bool CallFunc_Less_IntInt_ReturnValue, FInputActionKeyMapping CallFunc_Array_Get_Item_3, FKey CallFunc_Array_Get_Item_4, FInputActionKeyMapping K2Node_MakeStruct_InputActionKeyMapping_2, int32 Temp_int_Variable_30, int32 CallFunc_Add_IntInt_ReturnValue_7, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, UWidget* CallFunc_GetChildAt_ReturnValue_4, UAction_Remap_Option_C* K2Node_DynamicCast_AsAction_Remap_Option_4, bool K2Node_DynamicCast_bSuccess_5, UWidget* CallFunc_GetChildAt_ReturnValue_5, UAction_Remap_Option_C* K2Node_DynamicCast_AsAction_Remap_Option_5, bool K2Node_DynamicCast_bSuccess_6, FText CallFunc_GetText_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_7, bool Temp_bool_Has_Been_Initd_Variable, uint8 Temp_byte_Variable_2, int32 CallFunc_PostEventAtLocation_ReturnValue_7, int32 CallFunc_PostEventAtLocation_ReturnValue_8, FName K2Node_Select_Default, UWidget* CallFunc_GetChildAt_ReturnValue_6, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_1, UAction_Remap_Option_C* K2Node_DynamicCast_AsAction_Remap_Option_6, bool K2Node_DynamicCast_bSuccess_7, UWidget* CallFunc_GetActiveWidget_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_8, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue_1, int32 Temp_int_Variable_31, bool CallFunc_EqualEqual_ByteByte_ReturnValue_9, bool CallFunc_EqualEqual_ByteByte_ReturnValue_10, int32 Temp_int_Variable_32, bool CallFunc_BooleanOR_ReturnValue_2, bool CallFunc_BooleanOR_ReturnValue_3, bool Temp_bool_Variable_18, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_SelectInt_ReturnValue, int32 K2Node_Select_Default_1, int32 CallFunc_SelectInt_ReturnValue_1, int32 CallFunc_Percent_IntInt_ReturnValue, FString CallFunc_Conv_IntToString_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, int32 Temp_int_Variable_33, int32 Temp_int_Variable_34, bool Temp_bool_Variable_19, bool Temp_bool_Variable_20, int32 K2Node_Select_Default_2, int32 K2Node_Select_Default_3, bool Temp_bool_Variable_21, bool Temp_bool_Variable_22, FName Temp_name_Variable_56, bool K2Node_Select_Default_4, UPanelWidget* K2Node_Select_Default_5, UWidget* CallFunc_GetChildAt_ReturnValue_7, UAction_Remap_Option_C* K2Node_DynamicCast_AsAction_Remap_Option_7, bool K2Node_DynamicCast_bSuccess_8, int32 CallFunc_GetChildrenCount_ReturnValue_2, bool CallFunc_LessEqual_IntInt_ReturnValue_1, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 CallFunc_GetChildrenCount_ReturnValue_3, int32 Temp_int_Variable_35, int32 CallFunc_Subtract_IntInt_ReturnValue, bool K2Node_CustomEvent_Is_Switch_Profile, int32 CallFunc_Array_Length_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_3, bool CallFunc_Array_Contains_ReturnValue_1, int32 Temp_int_Variable_36, int32 Temp_int_Variable_37, int32 Temp_int_Variable_38, uint8 Temp_byte_Variable_3, int32 K2Node_Select_Default_6, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_8, bool Temp_bool_IsClosed_Variable, bool CallFunc_Array_IsValidIndex_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_5, bool CallFunc_BooleanAND_ReturnValue_1, int32 CallFunc_Clamp_ReturnValue, bool K2Node_CustomEvent_Up, bool K2Node_CustomEvent_Null, uint8 K2Node_CustomEvent_Direction, bool CallFunc_EqualEqual_ByteByte_ReturnValue_11, bool CallFunc_EqualEqual_ByteByte_ReturnValue_12, bool CallFunc_BooleanOR_ReturnValue_4, int32 K2Node_Select_Default_7, int32 K2Node_Select_Default_8, int32 K2Node_Select_Default_9, int32 K2Node_Select_Default_10, int32 K2Node_Select_Default_11, int32 K2Node_Select_Default_12, int32 K2Node_Select_Default_13, int32 K2Node_Select_Default_14, int32 K2Node_Select_Default_15, FTimerHandle CallFunc_K2_SetTimer_ReturnValue, AGameMenuController_C* K2Node_CustomEvent_GameMenuController, USaveGame* K2Node_CustomEvent_SaveGameObject, bool K2Node_CustomEvent_SaveGameExists, int32 K2Node_CustomEvent_SelectedTab, int32 CallFunc_Add_IntInt_ReturnValue_9, int32 Temp_int_Array_Index_Variable_3, bool K2Node_SwitchInteger_CmpSuccess_1, int32 Temp_int_Array_Index_Variable_4, FName CallFunc_Array_Get_Item_5, UWidget* CallFunc_GetChildAt_ReturnValue_8, FInputActionKeyMapping K2Node_MakeStruct_InputActionKeyMapping_3, UGameMenuTitle_C* K2Node_DynamicCast_AsGame_Menu_Title, bool K2Node_DynamicCast_bSuccess_9, TArray<FInputActionKeyMapping>& CallFunc_GetActionMappingByName_OutMappings_3, bool CallFunc_EqualEqual_NameName_ReturnValue, FInputActionKeyMapping CallFunc_Array_Get_Item_6, bool CallFunc_EqualEqual_KeyKey_ReturnValue, bool CallFunc_NotEqual_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable_4, int32 CallFunc_Add_IntInt_ReturnValue_10, FName Temp_name_Variable_57, int32 CallFunc_Add_IntInt_ReturnValue_11, int32 CallFunc_Add_IntInt_ReturnValue_12, FString CallFunc_Conv_IntToString_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_13, FString CallFunc_Concat_StrStr_ReturnValue_4, int32 Temp_int_Array_Index_Variable_5, bool K2Node_CustomEvent_Right_1, int32 Temp_int_Loop_Counter_Variable_5, int32 CallFunc_Add_IntInt_ReturnValue_14, FString CallFunc_Conv_IntToString_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_15, FString CallFunc_Concat_StrStr_ReturnValue_5, FName Temp_name_Variable_58, int32 CallFunc_Add_IntInt_ReturnValue_16, UWidget* CallFunc_GetChildAt_ReturnValue_9, UGameMenuTitle_C* K2Node_DynamicCast_AsGame_Menu_Title_1, bool K2Node_DynamicCast_bSuccess_10, FName Temp_name_Variable_59, int32 K2Node_Select_Default_16, int32 CallFunc_Add_IntInt_ReturnValue_17, bool K2Node_CustomEvent_Play, FName Temp_name_Variable_60, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_1, bool CallFunc_Array_IsValidIndex_ReturnValue_1, int32 CallFunc_GetChildrenCount_ReturnValue_4, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue_2, int32 CallFunc_Clamp_ReturnValue_1, UWidget* CallFunc_GetChildAt_ReturnValue_10, bool CallFunc_IsValid_ReturnValue, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_2, bool CallFunc_Array_IsValidIndex_ReturnValue_2, bool CallFunc_Not_PreBool_ReturnValue_3, int32 CallFunc_GetChildrenCount_ReturnValue_5, int32 CallFunc_Subtract_IntInt_ReturnValue_2, UWidget* CallFunc_GetChildAt_ReturnValue_11, int32 CallFunc_Clamp_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_1, int32 Temp_int_Variable_39, bool CallFunc_LessEqual_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_18, FName Temp_name_Variable_61, UGameInstance* CallFunc_GetGameInstance_ReturnValue, UBlueFire_Game_Instance_C* K2Node_DynamicCast_AsBlue_Fire_Game_Instance, bool K2Node_DynamicCast_bSuccess_11, int32 CallFunc_Get_Language_Index_Index, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_3, UGameInstance* CallFunc_GetGameInstance_ReturnValue_1, UBlueFire_Game_Instance_C* K2Node_DynamicCast_AsBlue_Fire_Game_Instance_1, bool K2Node_DynamicCast_bSuccess_12, bool K2Node_CustomEvent_Right, int32 Temp_int_Loop_Counter_Variable_6, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_19, int32 Temp_int_Variable_40, FName Temp_name_Variable_62, int32 CallFunc_Add_IntInt_ReturnValue_20, FName Temp_name_Variable_63, bool K2Node_SwitchInteger_CmpSuccess_2, int32 Temp_int_Variable_41, int32 Temp_int_Variable_42, int32 CallFunc_Add_IntInt_ReturnValue_21, int32 CallFunc_Add_IntInt_ReturnValue_22, int32 Temp_int_Array_Index_Variable_6, FKey CallFunc_Array_Get_Item_7, FName CallFunc_Array_Get_Item_8, FInputActionKeyMapping K2Node_MakeStruct_InputActionKeyMapping_4, TArray<FInputActionKeyMapping>& CallFunc_GetActionMappingByName_OutMappings_4, FInputActionKeyMapping CallFunc_Array_Get_Item_9, FName Temp_name_Variable_64, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_4, int32 Temp_int_Loop_Counter_Variable_7, bool CallFunc_Less_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_23, int32 Temp_int_Variable_43, FName Temp_name_Variable_65, UWidget* CallFunc_GetChildAt_ReturnValue_12, UGameMenuTitle_C* K2Node_DynamicCast_AsGame_Menu_Title_2, bool K2Node_DynamicCast_bSuccess_13, bool CallFunc_LessEqual_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_24, FName Temp_name_Variable_66, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_3, int32 CallFunc_GetChildrenCount_ReturnValue_6, int32 CallFunc_Subtract_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_25, bool CallFunc_LessEqual_IntInt_ReturnValue_4, bool CallFunc_Array_IsValidIndex_ReturnValue_3, bool CallFunc_Not_PreBool_ReturnValue_4, int32 CallFunc_Clamp_ReturnValue_3, bool CallFunc_EqualEqual_IntInt_ReturnValue_6, bool CallFunc_Not_PreBool_ReturnValue_5, UWidget* CallFunc_GetChildAt_ReturnValue_13, UGameDemo_Options_C* K2Node_DynamicCast_AsGame_Demo_Options, bool K2Node_DynamicCast_bSuccess_14, FString K2Node_Select_Default_17, FText CallFunc_Conv_StringToText_ReturnValue_1, UWidget* CallFunc_GetChildAt_ReturnValue_14, UGameDemo_Options_C* K2Node_DynamicCast_AsGame_Demo_Options_1, bool K2Node_DynamicCast_bSuccess_15, FName Temp_name_Variable_67, bool CallFunc_EqualEqual_ByteByte_ReturnValue_13, bool CallFunc_EqualEqual_ByteByte_ReturnValue_14, bool CallFunc_EqualEqual_ByteByte_ReturnValue_15, bool CallFunc_BooleanOR_ReturnValue_5, bool K2Node_SwitchInteger_CmpSuccess_3, bool CallFunc_BooleanOR_ReturnValue_6, FName Temp_name_Variable_68, UWidget* CallFunc_GetChildAt_ReturnValue_15, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_4, UPanelWidget* K2Node_Select_Default_18, bool CallFunc_Array_IsValidIndex_ReturnValue_4, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_5, UWidget* CallFunc_Array_Get_Item_10, int32 CallFunc_Array_Length_ReturnValue_4, UOptionMaster_C* K2Node_DynamicCast_AsOption_Master, bool K2Node_DynamicCast_bSuccess_16, bool CallFunc_Less_IntInt_ReturnValue_3, bool CallFunc_Not_PreBool_ReturnValue_6, UWidget* CallFunc_GetChildAt_ReturnValue_16, UOptionMaster_C* K2Node_DynamicCast_AsOption_Master_1, bool K2Node_DynamicCast_bSuccess_17, int32 CallFunc_GetChildrenCount_ReturnValue_7, UWidget* CallFunc_GetChildAt_ReturnValue_17, int32 CallFunc_Subtract_IntInt_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_2, int32 CallFunc_Clamp_ReturnValue_4, UWidget* CallFunc_GetChildAt_ReturnValue_18, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_6, bool CallFunc_Array_IsValidIndex_ReturnValue_5, int32 CallFunc_GetChildrenCount_ReturnValue_8, int32 CallFunc_Subtract_IntInt_ReturnValue_5, bool CallFunc_Not_PreBool_ReturnValue_7, bool CallFunc_LessEqual_IntInt_ReturnValue_5, int32 CallFunc_Clamp_ReturnValue_5, UWidget* CallFunc_GetChildAt_ReturnValue_19, bool CallFunc_IsValid_ReturnValue_3, UWidget* CallFunc_GetChildAt_ReturnValue_20, int32 Temp_int_Variable_44, UPanelWidget* K2Node_Select_Default_19, UWidget* CallFunc_GetChildAt_ReturnValue_21, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_7, UWidget* CallFunc_Array_Get_Item_11, int32 CallFunc_Array_Length_ReturnValue_5, UOptionMaster_C* K2Node_DynamicCast_AsOption_Master_2, bool K2Node_DynamicCast_bSuccess_18, bool CallFunc_Less_IntInt_ReturnValue_4, bool CallFunc_LessEqual_IntInt_ReturnValue_6, int32 CallFunc_Add_IntInt_ReturnValue_26, FName Temp_name_Variable_69, bool K2Node_SwitchEnum_CmpSuccess, int32 CallFunc_GetChildrenCount_ReturnValue_9, UWidget* CallFunc_GetChildAt_ReturnValue_22, int32 CallFunc_Subtract_IntInt_ReturnValue_6, bool CallFunc_LessEqual_IntInt_ReturnValue_7, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_8, bool CallFunc_Array_IsValidIndex_ReturnValue_6, int32 CallFunc_GetChildrenCount_ReturnValue_10, int32 CallFunc_Subtract_IntInt_ReturnValue_7, bool CallFunc_Not_PreBool_ReturnValue_8, int32 CallFunc_Clamp_ReturnValue_6, UWidget* CallFunc_GetChildAt_ReturnValue_23, bool CallFunc_IsValid_ReturnValue_4, const FText K2Node_CustomEvent_Text_1, uint8 K2Node_CustomEvent_CommitMethod, bool CallFunc_EqualEqual_ByteByte_ReturnValue_16, FString CallFunc_Conv_TextToString_ReturnValue_3, TArray<FString>& CallFunc_GetCharacterArrayFromString_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue_4, int32 CallFunc_Array_Length_ReturnValue_6, int32 CallFunc_Len_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_8, bool CallFunc_Less_IntInt_ReturnValue_5, int32 CallFunc_Clamp_ReturnValue_7, FString CallFunc_LeftChop_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue_2, FName Temp_name_Variable_70, FName Temp_name_Variable_71, bool K2Node_SwitchInteger_CmpSuccess_4, int32 Temp_int_Variable_45, UWidget* CallFunc_GetChildAt_ReturnValue_24, bool CallFunc_LessEqual_IntInt_ReturnValue_8, int32 CallFunc_Add_IntInt_ReturnValue_27, int32 Temp_int_Loop_Counter_Variable_8, bool CallFunc_Less_IntInt_ReturnValue_6, int32 CallFunc_Add_IntInt_ReturnValue_28, int32 CallFunc_Clamp_ReturnValue_8, int32 CallFunc_Add_IntInt_ReturnValue_29, const FText K2Node_ComponentBoundEvent_Text, UPlayerController* CallFunc_GetPlayerController_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue_5, FString CallFunc_LeftChop_ReturnValue_1, TArray<FString>& CallFunc_GetCharacterArrayFromString_ReturnValue_1, FText CallFunc_Conv_StringToText_ReturnValue_3, int32 CallFunc_Array_Length_ReturnValue_7, bool CallFunc_Greater_IntInt_ReturnValue_1, FName Temp_name_Variable_72, FName Temp_name_Variable_73, FName Temp_name_Variable_74, FName Temp_name_Variable_75, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_9, int32 CallFunc_GetChildrenCount_ReturnValue_11, int32 CallFunc_Subtract_IntInt_ReturnValue_9, UWidget* CallFunc_GetChildAt_ReturnValue_25, bool CallFunc_LessEqual_IntInt_ReturnValue_9, int32 CallFunc_Add_IntInt_ReturnValue_30, FText K2Node_Select_Default_20, bool CallFunc_Array_IsValidIndex_ReturnValue_7, UWidget* CallFunc_GetChildAt_ReturnValue_26, bool CallFunc_IsValid_ReturnValue_5, bool CallFunc_Not_PreBool_ReturnValue_9, int32 CallFunc_Clamp_ReturnValue_9, UWidget* CallFunc_GetChildAt_ReturnValue_27, FName Temp_name_Variable_76, int32 CallFunc_PostEventAtLocation_ReturnValue_9, bool K2Node_CustomEvent_Error, int32 CallFunc_PostEventAtLocation_ReturnValue_10, int32 CallFunc_PostEventAtLocation_ReturnValue_11, int32 CallFunc_PostEventAtLocation_ReturnValue_12, int32 CallFunc_PostEventAtLocation_ReturnValue_13, FName Temp_name_Variable_77, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_10, bool CallFunc_Array_IsValidIndex_ReturnValue_8, FName Temp_name_Variable_78, bool CallFunc_Not_PreBool_ReturnValue_10, int32 CallFunc_PostEventAtLocation_ReturnValue_14, UWidget* K2Node_Select_Default_21, UWidget* K2Node_Select_Default_22, FName Temp_name_Variable_79, FName Temp_name_Variable_80, UWidget* CallFunc_GetChildAt_ReturnValue_28, bool CallFunc_EqualEqual_ByteByte_ReturnValue_17, UWidget* CallFunc_Array_Get_Item_12, int32 CallFunc_Array_Length_ReturnValue_8, bool CallFunc_RemoveChild_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_7, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_18, bool CallFunc_BooleanOR_ReturnValue_7, FName Temp_name_Variable_81, bool CallFunc_EqualEqual_StrStr_ReturnValue, bool CallFunc_DeleteGameInSlot_ReturnValue, UAsyncActionHandleSaveGame* CallFunc_AsyncLoadGameFromSlot_ReturnValue, bool CallFunc_DoesSaveGameExist_ReturnValue, bool CallFunc_IsValid_ReturnValue_6, bool CallFunc_NotEqual_IntInt_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2, bool K2Node_SwitchEnum_CmpSuccess_1, FName Temp_name_Variable_82, bool K2Node_Select_Default_23, int32 Temp_int_Variable_46, int32 Temp_int_Variable_47, int32 CallFunc_Add_IntInt_ReturnValue_31, bool CallFunc_EqualEqual_IntInt_ReturnValue_7, UWidget* CallFunc_GetChildAt_ReturnValue_29, UAction_Remap_Option_C* K2Node_DynamicCast_AsAction_Remap_Option_8, bool K2Node_DynamicCast_bSuccess_19, bool CallFunc_LessEqual_IntInt_ReturnValue_10, int32 CallFunc_Add_IntInt_ReturnValue_32, UWidget* CallFunc_GetChildAt_ReturnValue_30, int32 CallFunc_Add_IntInt_ReturnValue_33, UFileSelect_C* K2Node_DynamicCast_AsFile_Select, bool K2Node_DynamicCast_bSuccess_20, FString CallFunc_Conv_IntToString_ReturnValue_3, UFileSelect_C* K2Node_DynamicCast_AsFile_Select_1, bool K2Node_DynamicCast_bSuccess_21, FString CallFunc_Concat_StrStr_ReturnValue_6, USaveGame* CallFunc_LoadGameFromSlot_ReturnValue, bool CallFunc_DoesSaveGameExist_ReturnValue_1, UBlueFireSaveGame_C* K2Node_DynamicCast_AsBlue_Fire_Save_Game_1, bool K2Node_DynamicCast_bSuccess_22, bool CallFunc_LessEqual_IntInt_ReturnValue_11, int32 CallFunc_Add_IntInt_ReturnValue_34, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_5, FName Temp_name_Variable_83, UBlueFireSaveGame_C* K2Node_DynamicCast_AsBlue_Fire_Save_Game_2, bool K2Node_DynamicCast_bSuccess_23, uint8 Temp_byte_Variable_4, bool CallFunc_Is_PS4_or_Xbox_Result, bool CallFunc_Is_PS4_or_Xbox_Result_1, FName Temp_name_Variable_84, FName Temp_name_Variable_85, int32 CallFunc_Add_IntInt_ReturnValue_35, int32 CallFunc_Add_IntInt_ReturnValue_36, UWidget* CallFunc_GetChildAt_ReturnValue_31, int32 CallFunc_Add_IntInt_ReturnValue_37, UFileSelect_C* K2Node_DynamicCast_AsFile_Select_2, bool K2Node_DynamicCast_bSuccess_24, FString CallFunc_Conv_IntToString_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_7, UFileSelect_C* K2Node_DynamicCast_AsFile_Select_3, bool K2Node_DynamicCast_bSuccess_25, UAsyncActionHandleSaveGame* CallFunc_AsyncLoadGameFromSlot_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_7, bool CallFunc_LessEqual_IntInt_ReturnValue_12, FName Temp_name_Variable_86, FName Temp_name_Variable_87, FName Temp_name_Variable_88, FName Temp_name_Variable_89, bool K2Node_SwitchInteger_CmpSuccess_5, FName Temp_name_Variable_90, int32 Temp_int_Array_Index_Variable_7, FName Temp_name_Variable_91, TArray<UControlsUI_Master_C*>& K2Node_MakeArray_Array, UControlsUI_Master_C* CallFunc_Array_Get_Item_13, int32 CallFunc_Array_Length_ReturnValue_9, bool CallFunc_Less_IntInt_ReturnValue_8, FName Temp_name_Variable_92, int32 Temp_int_Variable_48, FName Temp_name_Variable_93, FName Temp_name_Variable_94, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_11, UWidget* CallFunc_Array_Get_Item_14, int32 CallFunc_Array_Length_ReturnValue_10, UFileSelect_C* K2Node_DynamicCast_AsFile_Select_4, bool K2Node_DynamicCast_bSuccess_26, bool CallFunc_Less_IntInt_ReturnValue_9, bool CallFunc_IsEmpty_Empty, bool CallFunc_BooleanAND_ReturnValue_3, int32 Temp_int_Variable_49, int32 CallFunc_PostEventAtLocation_ReturnValue_15, UWidget* CallFunc_GetChildAt_ReturnValue_32, UGameMenuTitle_C* K2Node_DynamicCast_AsGame_Menu_Title_3, bool K2Node_DynamicCast_bSuccess_27, bool CallFunc_LessEqual_IntInt_ReturnValue_13, int32 CallFunc_Add_IntInt_ReturnValue_38, FName Temp_name_Variable_95, bool CallFunc_EqualEqual_IntInt_ReturnValue_8, bool CallFunc_Is_PS4_or_Xbox_Result_2, FText CallFunc_MakeLiteralText_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue_6, FName Temp_name_Variable_96, int32 CallFunc_Add_IntInt_ReturnValue_39, FString CallFunc_Conv_IntToString_ReturnValue_5, FString CallFunc_Concat_StrStr_ReturnValue_8, FText K2Node_CustomEvent_Text, FName Temp_name_Variable_97, FName Temp_name_Variable_98, FName Temp_name_Variable_99, UWidget* CallFunc_GetChildAt_ReturnValue_33, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue_12, UGameMenuTitle_C* K2Node_DynamicCast_AsGame_Menu_Title_4, bool K2Node_DynamicCast_bSuccess_28, int32 CallFunc_GetChildrenCount_ReturnValue_12, int32 CallFunc_Subtract_IntInt_ReturnValue_10, UWidget* CallFunc_GetChildAt_ReturnValue_34, bool CallFunc_LessEqual_IntInt_ReturnValue_14, UGameMenuTitle_C* K2Node_DynamicCast_AsGame_Menu_Title_5, bool K2Node_DynamicCast_bSuccess_29, FName Temp_name_Variable_100, int32 Temp_int_Array_Index_Variable_8, FName CallFunc_Array_Get_Item_15, FInputActionKeyMapping K2Node_MakeStruct_InputActionKeyMapping_5, TArray<FInputActionKeyMapping>& CallFunc_GetActionMappingByName_OutMappings_5, FInputActionKeyMapping CallFunc_Array_Get_Item_16, bool CallFunc_EqualEqual_NameName_ReturnValue_1, bool CallFunc_EqualEqual_KeyKey_ReturnValue_1, FName Temp_name_Variable_101, FName K2Node_Select_Default_24, int32 CallFunc_Add_IntInt_ReturnValue_40, bool CallFunc_Array_IsValidIndex_ReturnValue_9, UWidget* CallFunc_GetChildAt_ReturnValue_35, bool CallFunc_IsValid_ReturnValue_8, bool CallFunc_Not_PreBool_ReturnValue_11, int32 CallFunc_Clamp_ReturnValue_10, FText K2Node_Select_Default_25, int32 CallFunc_PostEventAtLocation_ReturnValue_16, UBlueFireSaveGame_C* K2Node_DynamicCast_AsBlue_Fire_Save_Game_3, bool K2Node_DynamicCast_bSuccess_30, UAsyncActionHandleSaveGame* CallFunc_AsyncSaveGameToSlot_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_9, UBlueFireSaveGame_C* K2Node_DynamicCast_AsBlue_Fire_Save_Game_4, bool K2Node_DynamicCast_bSuccess_31, bool CallFunc_SaveGameToSlot_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_9, int32 CallFunc_PostEventAtLocation_ReturnValue_17, FString CallFunc_Concat_StrStr_ReturnValue_10, bool CallFunc_Is_PS4_or_Xbox_Result_3, FString CallFunc_Left_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_41, FString CallFunc_Conv_IntToString_ReturnValue_6, FString CallFunc_Concat_StrStr_ReturnValue_11, FText CallFunc_GetText_ReturnValue_2, UAsyncActionHandleSaveGame* CallFunc_AsyncSaveGameToSlot_ReturnValue_1, FString CallFunc_Conv_TextToString_ReturnValue_7, bool CallFunc_IsValid_ReturnValue_10, bool CallFunc_SaveGameToSlot_ReturnValue_1, UBlueFireSaveGame_C* K2Node_DynamicCast_AsBlue_Fire_Save_Game_5, bool K2Node_DynamicCast_bSuccess_32, int32 CallFunc_PostEventAtLocation_ReturnValue_18, int32 CallFunc_PostEventAtLocation_ReturnValue_19, int32 CallFunc_PostEventAtLocation_ReturnValue_20, int32 CallFunc_PostEventAtLocation_ReturnValue_21);
    void Return__DelegateSignature();
}

#endif
