#ifndef UE4SS_SDK_HUD_HPP
#define UE4SS_SDK_HUD_HPP

class UHUD_C : UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UWidgetAnimation* ConsumeItem;
    UWidgetAnimation* ChangeItemAnim;
    UWidgetAnimation* FadeHUD;
    UWidgetAnimation* CollectCurrency;
    UWidgetAnimation* ChargeSpecialMove;
    UWidgetAnimation* Target;
    UImage* BBB;
    UImage* BBT;
    UTextBlock* CurrencyAmount;
    UImage* CurrencyGlow;
    UTextBlock* DeveloperModeTxt;
    UImage* Dpad;
    UImage* EquippedItem;
    UImage* EquippedItemFrame;
    UTextBlock* HexLeftAmount;
    UImage* Image_69;
    UWrapBox* LifeBox;
    ULifePoint_C* LifePoint;
    ULifePoint_C* LifePoint_1;
    ULifePoint_C* LifePoint_2;
    ULifePoint_C* LifePoint_3;
    ULifePoint_C* LifePoint_4;
    ULifePoint_C* LifePoint_5;
    ULifePoint_C* LifePoint_6;
    ULifePoint_C* LifePoint_7;
    ULifePoint_C* LifePoint_8;
    ULifePoint_C* LifePoint_9;
    ULifePoint_C* LifePoint_10;
    ULifePoint_C* LifePoint_11;
    ULifePoint_C* LifePoint_12;
    ULifePoint_C* LifePoint_13;
    ULifePoint_C* LifePoint_14;
    ULifePoint_C* LifePoint_15;
    ULifePoint_C* LifePoint_16;
    ULifePoint_C* LifePoint_17;
    ULifePoint_C* LifePoint_74;
    ULifePoint_C* LifePoint_176;
    UWrapBox* LootBox;
    UBorder* MainBorder;
    UTextBlock* NewCurrency;
    UImage* RageBar;
    UWrapBox* SpiritBox;
    USpiritCharge_C* SpiritCharge;
    USpiritCharge_C* SpiritCharge_130;
    USpiritCharge_C* SpiritCharge_335;
    USpiritCharge_C* SpiritCharge_441;
    UVerticalBox* VerticalBox_119;
    float currentvar;
    float target var;
    APlayer_Character_BP_C* Player;
    UMaterialInstanceDynamic* LifeMat;
    UBlueFire_Game_Instance_C* GameInstance;
    int32 DisplayedCurrency;
    int32 SetCurrency;
    float SetCurrencyFloat;
    UMaterialInstanceDynamic* AimTimeMat;
    bool Hidden;
    UMaterialInstanceDynamic* AimInsideMat;
    UMaterialInstanceDynamic* AimMatExterior;
    float RagePercent;
    UMaterialInstanceDynamic* RageBarMat;
    float LifePercent;
    float LifeLerpPercent;
    float RageLerpPercent;
    int32 TempHealth;
    bool Animate;
    TArray<ULifePoint_C*> LifeSlots;
    bool LifeReduce;
    int32 PreviousHealth;
    bool AddLife;
    bool HidePermanent;
    bool TempSpiritNotAdded;
    TArray<UWidget*> ChildrenSpiritCache;

    float Get_Rage_Percent_0(float CallFunc_GetWorldDeltaSeconds_ReturnValue, float CallFunc_FInterpTo_ReturnValue, float CallFunc_FInterpTo_ReturnValue_1, float CallFunc_NormalizeToRange_ReturnValue, float CallFunc_NormalizeToRange_ReturnValue_1);
    void UpdateSpiritWrap();
    void UpdateLifeHud(bool Animate, bool ChangeSlotCount, bool AddLife);
    void HealthSlotsRun(bool FirstRun);
    void UpdateSlotCount();
    void AddLoot(FText Name, UMaterialInterface* Image, FText Description, int32 Value);
    void Construct();
    void TargetOn();
    void TargetOff();
    void RecieveHit(bool Anim);
    void LoadItems();
    void UpdateCurrency(int32 Add, bool Sound, bool Negative, bool Max Limit);
    void UpdateCurrencyLatest();
    void HideHUD();
    void ShowHUD();
    void LoadCurrency(int32 Currency);
    void SilentUpdateCurrency(int32 Currency);
    void HexGreyed();
    void HexActive();
    void UpdateRage(float InPercent, float Rage);
    void UpdateItems(bool ChangeAnim);
    void ItemUpdate(int32 Offset, UImage* ItemImage, UTextBlock* AmountText, UWidget* Frame);
    void ChangeItemUse();
    void ConsumeItemPlay();
    void Change Color Currency(bool Limit);
    void Hide PermanenteHUD();
    void Tick(FGeometry MyGeometry, float InDeltaTime);
    void Reset Displayed Currency();
    void ExecuteUbergraph_HUD(int32 EntryPoint, UMaterialInstance* CallFunc_GetUIPlatform_UIMaterial, bool CallFunc_GetUIPlatform_NonSquareSize, FVector2D CallFunc_GetUIPlatform_Size, WidgetAnimationDynamicEvent__DelegateSignature K2Node_CreateDelegate_OutputDelegate, TArray<UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue, FLinearColor Temp_struct_Variable, FLinearColor Temp_struct_Variable_1, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_2, ULifePoint_C* CallFunc_Create_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_Not_PreBool_ReturnValue, bool Temp_bool_Variable, int32 CallFunc_Array_Length_ReturnValue_3, bool Temp_bool_Variable_1, bool K2Node_CustomEvent_Animate, bool K2Node_CustomEvent_ChangeSlotCount, bool K2Node_CustomEvent_AddLife, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, UGameInstance* CallFunc_GetGameInstance_ReturnValue, UBlueFire_Game_Instance_C* K2Node_DynamicCast_AsBlue_Fire_Game_Instance, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsRobiValid_ReturnValue, bool Temp_bool_Variable_2, bool CallFunc_IsRobiValid_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue_2, bool Temp_bool_Variable_3, bool K2Node_CustomEvent_FirstRun, float CallFunc_NormalizeToRange_ReturnValue, float CallFunc_Lerp_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, FVector2D CallFunc_MakeVector2D_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue, float CallFunc_Multiply_IntFloat_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_1, float CallFunc_Divide_FloatFloat_ReturnValue_1, float CallFunc_NormalizeToRange_ReturnValue_1, uint8 CallFunc_MakeLiteralByte_ReturnValue, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Multiply_IntInt_ReturnValue, PCGamepadChange__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, UPanelSlot* CallFunc_AddChild_ReturnValue, uint8 CallFunc_MakeLiteralByte_ReturnValue_1, bool CallFunc_IsRobiValid_ReturnValue_3, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable, UWidget* CallFunc_Array_Get_Item, USpiritCharge_C* K2Node_DynamicCast_AsSpirit_Charge, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Divide_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue, ULifePoint_C* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_5, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_SelectInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_4, int32 CallFunc_Array_Length_ReturnValue_6, int32 Temp_int_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_5, int32 CallFunc_SelectInt_ReturnValue_1, int32 CallFunc_SelectInt_ReturnValue_2, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2, UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue, int32 CallFunc_Round_ReturnValue, FText CallFunc_Conv_IntToText_ReturnValue, UPlayer_Character_BP_C* CallFunc_GetActorOfClass_ReturnValue, FString CallFunc_Conv_IntToString_ReturnValue, FText K2Node_CustomEvent_Name, UMaterialInterface* K2Node_CustomEvent_Image, FText K2Node_CustomEvent_Description, int32 K2Node_CustomEvent_Value, APawn* CallFunc_GetPlayerPawn_ReturnValue, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue, UPlayer_Character_BP_C* K2Node_DynamicCast_AsPlayer_Character_BP, bool K2Node_DynamicCast_bSuccess_2, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_1, bool K2Node_CustomEvent_Anim, int32 K2Node_CustomEvent_add, bool K2Node_CustomEvent_Sound, bool K2Node_CustomEvent_Negative, bool K2Node_CustomEvent_Max_Limit, float CallFunc_Conv_IntToFloat_ReturnValue_2, float CallFunc_SelectFloat_ReturnValue, float CallFunc_SelectFloat_ReturnValue_1, FString CallFunc_SelectString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue, FText CallFunc_Conv_StringToText_ReturnValue, bool CallFunc_NotEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_6, int32 Temp_int_Array_Index_Variable_2, uint8 CallFunc_Array_Get_Item_2, FTimerHandle CallFunc_K2_SetTimer_ReturnValue, float CallFunc_GetWorldDeltaSeconds_ReturnValue, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_2, UCollectedItem_C* CallFunc_Create_ReturnValue_1, bool CallFunc_Greater_FloatFloat_ReturnValue, UPanelSlot* CallFunc_AddChild_ReturnValue_1, bool CallFunc_Less_FloatFloat_ReturnValue, bool K2Node_Select_Default, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_3, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_4, int32 K2Node_CustomEvent_Currency_1, FText CallFunc_Conv_IntToText_ReturnValue_1, int32 K2Node_CustomEvent_Currency, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, FText CallFunc_Conv_IntToText_ReturnValue_2, int32 Temp_int_Array_Index_Variable_3, uint8 CallFunc_Array_Get_Item_3, bool CallFunc_EqualEqual_ByteByte_ReturnValue, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_2, FName CallFunc_Conv_StringToName_ReturnValue, FSpiritsInfo CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, float K2Node_CustomEvent_InPercent, float K2Node_CustomEvent_Rage, bool K2Node_CustomEvent_ChangeAnim, bool CallFunc_IsRobiValid_ReturnValue_4, USpiritCharge_C* CallFunc_Create_ReturnValue_2, UWrapBoxSlot* CallFunc_AddChildToWrapBox_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable_1, bool CallFunc_Not_PreBool_ReturnValue_1, int32 K2Node_CustomEvent_Offset, UImage* K2Node_CustomEvent_ItemImage, UTextBlock* K2Node_CustomEvent_AmountText, UWidget* K2Node_CustomEvent_Frame, float Temp_float_Variable, float Temp_float_Variable_1, int32 Temp_int_Loop_Counter_Variable_2, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_7, float Temp_float_Variable_2, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, float Temp_float_Variable_3, FText CallFunc_MakeLiteralText_ReturnValue, float Temp_float_Variable_4, int32 Temp_int_Loop_Counter_Variable_3, int32 Temp_int_Variable_1, bool CallFunc_Less_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_8, int32 Temp_int_Loop_Counter_Variable_4, int32 Temp_int_Array_Index_Variable_4, bool CallFunc_Less_IntInt_ReturnValue_4, ULifePoint_C* CallFunc_Array_Get_Item_4, int32 CallFunc_Add_IntInt_ReturnValue_9, int32 CallFunc_Multiply_IntInt_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_10, float K2Node_Select_Default_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue_2, bool CallFunc_IsRobiValid_ReturnValue_5, float Temp_float_Variable_5, float CallFunc_NormalizeToRange_ReturnValue_2, int32 Temp_int_Array_Index_Variable_5, UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_1, UWidget* CallFunc_Array_Get_Item_5, USpiritCharge_C* K2Node_DynamicCast_AsSpirit_Charge_1, bool K2Node_DynamicCast_bSuccess_3, bool CallFunc_HasItem_Success, int32 CallFunc_HasItem_ItemAmount, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, float Temp_float_Variable_6, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_5, float Temp_float_Variable_7, FString K2Node_Select_Default_2, FName CallFunc_Conv_StringToName_ReturnValue_1, bool CallFunc_HasItem_Success_1, int32 CallFunc_HasItem_ItemAmount_1, FItem CallFunc_GetDataTableRowFromName_OutRow_1, bool CallFunc_GetDataTableRowFromName_ReturnValue_1, int32 CallFunc_SelectInt_ReturnValue_3, FString CallFunc_Conv_IntToString_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_1, FText CallFunc_Conv_StringToText_ReturnValue_1, float Temp_float_Variable_8, int32 CallFunc_Subtract_IntInt_ReturnValue_2, float Temp_float_Variable_9, int32 CallFunc_Abs_Int_ReturnValue, int32 CallFunc_Divide_IntInt_ReturnValue_1, int32 CallFunc_PostEventAtLocation_ReturnValue_1, int32 CallFunc_Clamp_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_3, float CallFunc_Multiply_FloatFloat_ReturnValue_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, float K2Node_Select_Default_3, bool K2Node_CustomEvent_Limit, float CallFunc_FClamp_ReturnValue, FLinearColor K2Node_Select_Default_4, FSlateColor K2Node_MakeStruct_SlateColor, int32 CallFunc_Add_IntInt_ReturnValue_11, float CallFunc_Conv_IntToFloat_ReturnValue_4, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_6, int32 Temp_int_Variable_2, float K2Node_Select_Default_5, int32 Temp_int_Loop_Counter_Variable_5, bool CallFunc_Less_IntInt_ReturnValue_5, int32 CallFunc_Add_IntInt_ReturnValue_12, FGeometry K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, float CallFunc_NormalizeToRange_ReturnValue_3, float CallFunc_GetWorldDeltaSeconds_ReturnValue_1, float CallFunc_FInterpTo_ReturnValue, float CallFunc_FInterpTo_ReturnValue_1);
}

#endif
