#ifndef UE4SS_SDK_InsideTemple_HPP
#define UE4SS_SDK_InsideTemple_HPP

class USequenceDirector_C : ULevelSequenceDirector
{
    FPointerToUberGraphFrame UberGraphFrame;

    void SequenceEvent__ENTRYPOINTSequenceDirector_5(UInsideTemple_Controller_C* InsideTemple_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_4(UInsideTemple_Controller_C* InsideTemple_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_3(UInsideTemple_Controller_C* InsideTemple_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_2(UInsideTemple_Controller_C* InsideTemple_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_1(UInsideTemple_Controller_C* InsideTemple_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_0(UInsideTemple_Controller_C* InsideTemple_Controller);
    void Nuos_Intro_Controller_Event_0(UNuos_Intro_Controller_C* Nuos_Intro_Controller);
    void Nuos_Intro_Controller_Event_1(UNuos_Intro_Controller_C* Nuos_Intro_Controller);
    void Nuos_Intro_Controller_Event_2(UNuos_Intro_Controller_C* Nuos_Intro_Controller);
    void InsideTemple_Controller_Event_0(UInsideTemple_Controller_C* InsideTemple_Controller);
    void InsideTemple_Controller_Event_1(UInsideTemple_Controller_C* InsideTemple_Controller);
    void InsideTemple_Controller_Event_2(UInsideTemple_Controller_C* InsideTemple_Controller);
    void InsideTemple_Controller_Event_3(UInsideTemple_Controller_C* InsideTemple_Controller);
    void InsideTemple_Controller_Event_4(UInsideTemple_Controller_C* InsideTemple_Controller);
    void InsideTemple_Controller_Event_5(UInsideTemple_Controller_C* InsideTemple_Controller);
    void InsideTemple_Controller_Event_6(UInsideTemple_Controller_C* InsideTemple_Controller);
    void ExecuteUbergraph_SequenceDirector(int32 EntryPoint, UInsideTemple_Controller_C* K2Node_CustomEvent_InsideTemple_Controller, UNuos_Intro_Controller_C* K2Node_CustomEvent_Nuos_Intro_Controller_2, UNuos_Intro_Controller_C* K2Node_CustomEvent_Nuos_Intro_Controller_1, UNuos_Intro_Controller_C* K2Node_CustomEvent_Nuos_Intro_Controller, UInsideTemple_Controller_C* K2Node_CustomEvent_InsideTemple_Controller_6, UInsideTemple_Controller_C* K2Node_CustomEvent_InsideTemple_Controller_5, UInsideTemple_Controller_C* K2Node_CustomEvent_InsideTemple_Controller_4, UInsideTemple_Controller_C* K2Node_CustomEvent_InsideTemple_Controller_3, UInsideTemple_Controller_C* K2Node_CustomEvent_InsideTemple_Controller_2, UInsideTemple_Controller_C* K2Node_CustomEvent_InsideTemple_Controller_1);
}

#endif
