#ifndef UE4SS_SDK_MainDialogWB_HPP
#define UE4SS_SDK_MainDialogWB_HPP

class UMainDialogWB_C : UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    UWidgetAnimation* TextFadeStyle;
    UWidgetAnimation* PressOption;
    UWidgetAnimation* ShowShop;
    UWidgetAnimation* InventoryTabSwitch;
    UWidgetAnimation* ActionsBorderFadeIn;
    UWidgetAnimation* MainFade;
    UWidgetAnimation* FadeIn;
    UWidgetAnimation* AutomaticFadeIn;
    UWidgetAnimation* GlowButton;
    UTextBlock* AcceptAction;
    UBorder* ActionsBorder;
    URichTextBlock* ActualText;
    UImage* Background;
    UBorder* BorderResponses;
    UBorder* BorderText;
    UTextBlock* CancelAction;
    UImage* CancelButton;
    UTextBlock* Category;
    UTextBlock* CharacterName;
    UImage* CircleA;
    UImage* CircleB;
    UOverlay* Currency;
    UTextBlock* CurrencyAmount;
    UDialogOption_C* DialogOption;
    UDialogOption_C* DialogOption_83;
    UImage* Image;
    UImage* Image_0;
    UImage* Image_1;
    UImage* Image_2;
    UImage* Image_3;
    UImage* Image_4;
    UImage* Image_5;
    UImage* Image_6;
    UImage* Image_7;
    UImage* Image_8;
    UImage* Image_9;
    UImage* Image_10;
    UImage* Image_11;
    UImage* Image_12;
    UImage* Image_13;
    UImage* Image_55;
    UImage* Image_199;
    UBorder* InventoryBorder;
    UInventoryItem_C* InventoryItem;
    UInventoryItem_C* InventoryItem_0;
    UInventoryItem_C* InventoryItem_1;
    UInventoryItem_C* InventoryItem_2;
    UInventoryItem_C* InventoryItem_62;
    UInventoryItem_C* InventoryItem_114;
    UInventoryItem_C* InventoryItem_168;
    UInventoryItem_C* InventoryItem_257;
    UInventoryItem_C* InventoryItem_341;
    UInventoryItem_C* InventoryItem_417;
    UInventoryItem_C* InventoryItem_487;
    UInventoryItem_C* InventoryItem_565;
    UInventoryItem_C* InventoryItem_C_0;
    UInventoryItem_C* InventoryItem_C_1;
    UInventoryItem_C* InventoryItem_C_2;
    UInventoryItem_C* InventoryItem_C_3;
    UInventoryItem_C* InventoryItem_C_4;
    UInventoryItem_C* InventoryItem_C_5;
    UInventoryItem_C* InventoryItem_C_6;
    UInventoryItem_C* InventoryItem_C_7;
    UInventoryItem_C* InventoryItem_C_8;
    UTextBlock* InventoryItemName;
    UWidgetSwitcher* InventorySwitcher;
    UWrapBox* ItemsBox;
    UWrapBox* KeyItemsBox;
    UBorder* MainBorder;
    UImage* Ok;
    UTextBlock* PlayerSouls;
    UTextBlock* Price;
    UWrapBox* ReponsesBox;
    URichTextBlock* SetShape;
    UBorder* ShopBorder;
    UTextBlock* ShopCurrencyAmount;
    UTextBlock* ShopCurrencyAmount_1;
    UTextBlock* ShopDescription;
    UImage* ShopItemMaterial;
    UShopItemWBP_C* ShopItemWBP;
    UShopItemWBP_C* ShopItemWBP_73;
    UShopItemWBP_C* ShopItemWBP_186;
    UShopItemWBP_C* ShopItemWBP_C_0;
    UShopItemWBP_C* ShopItemWBP_C_1;
    UShopItemWBP_C* ShopItemWBP_C_2;
    UTextBlock* ShopMainItem;
    UScrollBox* ShopScrollBox;
    UImage* SimpleGlow;
    UTextBlock* SwordDamage;
    UTextBlock* TextBlock_0;
    float Speed;
    FMainDialogWB_CExitDialog ExitDialog;
    void ExitDialog();
    bool MessageFinished;
    bool LastLine;
    int32 CurrentLine;
    int32 TotalLines;
    TArray<FText> Text;
    AMainDialogController_C* TextController;
    bool NextCharacterIsMarker;
    TEnumAsByte<TextMarkerTypes::Type> Markertype;
    UTextBlock* CurrentTextBox;
    FLinearColor TextColor;
    UObject* GameInstanceRef;
    uint8 InputImageEnum;
    bool MessageIsQuestion;
    bool QuestionYesSelected;
    int32 QuestionRepeatLine;
    bool NoDelay;
    FMainDialogWB_CNextLineED NextLineED;
    void NextLineED(int32 CurrentLine);
    float AutoTimeDuration;
    bool FadeStyle;
    float AutoTimeTillNext;
    TEnumAsByte<TextMarkerTypes::Type> QuestionResponseAction;
    FMainDialogWB_CFinished Finished;
    void Finished();
    TArray<FText> Responses;
    int32 SelectedOptionIndex;
    bool Visible;
    UDialogText_C* InvisibleText;
    int32 InventoryTab;
    UBlueFire_Game_Instance_C* GameInstance;
    TArray<UInventoryItem_C*> InventoryItems;
    int32 SelectedItem;
    int32 SelectedKeyItem;
    TArray<UInventoryItem_C*> InventoryPassiveItems;
    int32 MaxPassiveItems;
    bool PlayerSell;
    bool PlayerBuy;
    TEnumAsByte<DialogType::Type> DialogType;
    TArray<UShopItemWBP_C*> ShopItems;
    TArray<FInventory> ShopInventory;
    int32 SelectedShopItem;
    int32 Amount;
    TEnumAsByte<DialogType::Type> InternalDialogType;
    FText NPCName;
    bool SellConfirmation;
    int32 WorldShop;
    bool SellMoment;
    bool ShopsOpen;
    UAkAudioEvent* AkEvent;
    bool UseAkSoundsArray;
    TArray<UAkAudioEvent*> AkSoundsArray;
    float TickCounter;
    int32 SellItemAmount;
    bool TextLineStop;
    bool CanPressConfirmInput;
    FMainDialogWB_CAbilityUnlock AbilityUnlock;
    void AbilityUnlock(uint8 Ability);
    TEnumAsByte<Abilities::Type> UnlockedAbility;
    FMainDialogWB_COptionChange OptionChange;
    void OptionChange(int32 CurrentOption);
    FMainDialogWB_CLastLineCall LastLineCall;
    void LastLineCall();
    AActor* Owner;
    bool CustomOptionTexts;
    TArray<FText> CustomOptionArrayText;
    float TextOpacity;
    ANPCBound_C* Bound;
    FMainDialogWB_CExit Exit;
    void Exit();
    bool OpenBracket;
    bool CutsceneTextStyle;
    APlayer_Character_BP_C* Player;
    bool ShowCurrencyOnQuestion;
    FString SpecialString;
    FString SpecialStringB;
    int32 SpecialStringSwitcher;
    bool IsRareShop;
    bool ShowItemNNotCurrency;
    TEnumAsByte<Items::Type> ItemToShow;
    int32 InventoryLength;
    bool ShopReload;

    void WriteShopArrayToGI(TArray<FInventory>& Shop, TArray<FInventory> SelectedShop, bool K2Node_SwitchInteger_CmpSuccess);
    void GetShopArray(TArray<FInventory>& Array, TArray<FInventory> SelectedShop, FInventory K2Node_MakeStruct_Inventory, TArray<FInventory>& K2Node_MakeArray_Array, bool CallFunc_Array_IsValidIndex_ReturnValue, bool K2Node_SwitchInteger_CmpSuccess);
    void Continue();
    void Tick(FGeometry MyGeometry, float InDeltaTime);
    void Write(const FText& InText);
    void UpdateActions(FText CancelAction, FText AcceptAction);
    void HideActions();
    void InitializeShop();
    void LoadShopItems();
    void UpdateShopSelectionCursor();
    void ShopMoveSelection(uint8 Directions, bool RefreshOnly);
    void UpdateShopItemDescription();
    void ShowShopCurrency();
    void EndShop();
    void ShopConfirmInput();
    void ReloadShop();
    void ContSell(int32 SellItemAmount);
    void UpdateShopText(FText Name, FText Description, UMaterialInterface* Material);
    void DirectSellOrb();
    void CloseTick();
    void UpdateInventorySelectionCursor();
    void UpdateInventoryAction();
    void InventoryRecieveMovement(uint8 Directions, bool RefreshOnly);
    void ChangeInventoryTab(bool Right, bool Refresh);
    void LoadInventoryItems();
    void LoadInventoryKeyItems();
    void QuickInventoryTabChange(bool Right);
    void InventoryConfirmInput();
    void UpdateInventoryDescription();
    void UpdateInventoryItemText(FText Description, FText Name);
    void HideInventoryDescriptionBox();
    void InitializeInventory();
    void LoadInventoryCurrency();
    void EndInventory();
    void ReloadInventory();
    void ReloadShopDelegate();
    void Remove();
    void NewTextLine(const TArray<FText>& TextLines, FText NPCName, const TArray<FText>& Responses, int32 SelectedOptionIndex, uint8 DialogType, int32 Shop, bool Center, UAkAudioEvent* AkEvent, bool UseAkSoundsArray, const TArray<UAkAudioEvent*>& AkEvents, bool CustomOptionTexts, TArray<FText>& CustomOptionArray, bool FadeStyle, bool ShowCurrencyOnQuestion, uint8 Item, bool ShowItemNNotCurrency);
    void NextLine();
    void RecieveConfirmationInput();
    void OptionVerticalMovement(uint8 Direction);
    void NextLineShow();
    void SpawnControl();
    void Construct();
    void ShowDialogUI();
    void HideDialogUI();
    void OkVisible();
    void OkHidden();
    void TextConfirmation();
    void RecieveMovementInput(uint8 Direction);
    void RecieveCancelInput();
    void RecieveThumbstickRInput(uint8 Index);
    void InitializeShops();
    void HideShops();
    void TextLine(const TArray<FText>& TextLines, const TArray<FText>& Responses, int32 SelectedOptionIndex, uint8 DialogType);
    void NewInternalTextLine(const TArray<FText>& TextLines, const TArray<FText>& Responses, int32 SelectedOptionIndex, uint8 DialogType);
    void OptionsChangeAmount(bool Right, const bool Max);
    void RepeatShop();
    void OptionClick();
    void SetAction();
    void ResetShopInitialize();
    void CursorMoveError();
    void SetPlatformIcon();
    void EndWrite();
    void AllowNextLine();
    void OptionChangeText(const TArray<FText>& Text);
    void NoBackground();
    void Update HUD();
    void GodMode(bool BlackText, float In Position Y);
    void ExecuteUbergraph_MainDialogWB(int32 EntryPoint, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool Temp_bool_Variable, int32 Temp_int_Variable, int32 Temp_int_Variable_1, uint8 Temp_byte_Variable, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, bool Temp_bool_Variable_3, bool Temp_bool_Variable_4, bool Temp_bool_Variable_5, int32 Temp_int_Variable_2, int32 Temp_int_Variable_3, int32 Temp_int_Variable_4, uint8 Temp_byte_Variable_1, bool Temp_bool_Variable_6, bool Temp_bool_Variable_7, bool Temp_bool_Variable_8, bool Temp_bool_Variable_9, bool Temp_bool_Variable_10, uint8 Temp_byte_Variable_2, int32 Temp_int_Variable_5, int32 Temp_int_Variable_6, uint8 Temp_byte_Variable_3, FText Temp_text_Variable, uint8 Temp_byte_Variable_4, bool Temp_bool_Variable_11, uint8 Temp_byte_Variable_5, uint8 Temp_byte_Variable_6, PCGamepadChange__DelegateSignature K2Node_CreateDelegate_OutputDelegate, bool Temp_bool_Variable_12, int32 CallFunc_Array_Length_ReturnValue, UAkAudioEvent* Temp_object_Variable, UAkAudioEvent* Temp_object_Variable_1, bool Temp_bool_Variable_13, FText Temp_text_Variable_1, FSlateColor K2Node_MakeStruct_SlateColor, int32 CallFunc_MakeLiteralInt_ReturnValue, UDialogOption_C* CallFunc_Create_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, FTransform CallFunc_MakeTransform_ReturnValue, AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, AMainDialogController_C* CallFunc_FinishSpawningActor_ReturnValue, bool Temp_bool_Variable_14, bool CallFunc_MakeLiteralBool_ReturnValue, bool CallFunc_MakeLiteralBool_ReturnValue_1, bool CallFunc_MakeLiteralBool_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_1, UAkAudioEvent* Temp_object_Variable_2, FGeometry K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, float CallFunc_Add_FloatFloat_ReturnValue, const FText K2Node_CustomEvent_InText, FString CallFunc_Conv_TextToString_ReturnValue, UAkAudioEvent* Temp_object_Variable_3, TArray<FString>& CallFunc_GetCharacterArrayFromString_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_2, bool Temp_bool_Variable_15, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue, int32 Temp_int_Variable_7, int32 Temp_int_Variable_8, bool Temp_bool_Variable_16, FString Temp_string_Variable, int32 Temp_int_Variable_9, bool CallFunc_EqualEqual_StrStr_ReturnValue, FString CallFunc_Conv_BoolToString_ReturnValue, int32 CallFunc_MakeLiteralInt_ReturnValue_1, FString CallFunc_MakeLiteralString_ReturnValue, int32 Temp_int_Variable_10, FString Temp_string_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_1, FString CallFunc_Concat_StrStr_ReturnValue_2, FText CallFunc_Conv_StringToText_ReturnValue, FString CallFunc_Conv_TextToString_ReturnValue_1, TArray<FString>& CallFunc_GetCharacterArrayFromString_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_2, bool Temp_bool_Variable_17, bool Temp_bool_Variable_18, bool CallFunc_MakeLiteralBool_ReturnValue_3, int32 Temp_int_Variable_11, bool CallFunc_MakeLiteralBool_ReturnValue_4, bool Temp_bool_Variable_19, bool CallFunc_MakeLiteralBool_ReturnValue_5, int32 Temp_int_Variable_12, int32 Temp_int_Variable_13, bool Temp_bool_Variable_20, int32 Temp_int_Variable_14, bool Temp_bool_Variable_21, int32 Temp_int_Variable_15, bool Temp_bool_Variable_22, int32 Temp_int_Variable_16, int32 Temp_int_Variable_17, bool Temp_bool_Variable_23, FString Temp_string_Variable_2, bool Temp_bool_Variable_24, bool Temp_bool_Variable_25, bool Temp_bool_Variable_26, FString CallFunc_MakeLiteralString_ReturnValue_1, bool Temp_bool_Variable_27, int32 CallFunc_SelectInt_ReturnValue, int32 CallFunc_SelectInt_ReturnValue_1, bool Temp_bool_Variable_28, bool CallFunc_MakeLiteralBool_ReturnValue_6, bool Temp_bool_Variable_29, bool Temp_bool_Variable_30, FString CallFunc_SelectString_ReturnValue, bool Temp_bool_Variable_31, bool Temp_bool_Variable_32, bool Temp_bool_Variable_33, bool CallFunc_Not_PreBool_ReturnValue, bool Temp_bool_Variable_34, bool Temp_bool_Variable_35, bool Temp_bool_Variable_36, int32 Temp_int_Variable_18, float CallFunc_MakeLiteralFloat_ReturnValue, bool Temp_bool_Variable_37, bool CallFunc_MakeLiteralBool_ReturnValue_7, bool CallFunc_MakeLiteralBool_ReturnValue_8, bool Temp_bool_Variable_38, FString CallFunc_GetCurrentLanguage_ReturnValue, bool Temp_bool_Variable_39, bool CallFunc_EqualEqual_StrStr_ReturnValue_1, int32 CallFunc_SelectInt_ReturnValue_2, FText K2Node_CustomEvent_CancelAction, FText K2Node_CustomEvent_AcceptAction, bool CallFunc_Greater_IntInt_ReturnValue, FText CallFunc_ToLower_Out, FText CallFunc_ToLower_Out_1, FText CallFunc_MakeLiteralText_ReturnValue, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_1, bool CallFunc_EqualEqual_TextText_ReturnValue, uint8 K2Node_CustomEvent_Directions_1, bool K2Node_CustomEvent_RefreshOnly_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, FText CallFunc_Conv_IntToText_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, int32 Temp_int_Variable_19, bool Temp_bool_Variable_40, int32 Temp_int_Variable_20, int32 CallFunc_Add_IntInt_ReturnValue_3, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, int32 Temp_int_Variable_21, FString CallFunc_Array_Get_Item, int32 CallFunc_Add_IntInt_ReturnValue_4, bool CallFunc_EqualEqual_StrStr_ReturnValue_2, bool CallFunc_EqualEqual_StrStr_ReturnValue_3, bool CallFunc_EqualEqual_StrStr_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_3, bool CallFunc_EqualEqual_StrStr_ReturnValue_5, int32 CallFunc_Add_IntInt_ReturnValue_5, int32 CallFunc_Add_IntInt_ReturnValue_6, bool CallFunc_GreaterEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_7, bool CallFunc_Not_PreBool_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_8, int32 CallFunc_Add_IntInt_ReturnValue_9, int32 CallFunc_Add_IntInt_ReturnValue_10, int32 CallFunc_Add_IntInt_ReturnValue_11, FString CallFunc_Array_Get_Item_1, FString CallFunc_Array_Get_Item_2, bool K2Node_SwitchString_CmpSuccess, bool CallFunc_EqualEqual_StrStr_ReturnValue_6, TArray<UShopItemWBP_C*>& K2Node_MakeArray_Array, int32 CallFunc_Array_Length_ReturnValue_4, bool CallFunc_Less_IntInt_ReturnValue, int32 Temp_int_Variable_22, FText Temp_text_Variable_2, int32 CallFunc_Array_Length_ReturnValue_5, int32 Temp_int_Variable_23, int32 CallFunc_Array_Length_ReturnValue_6, int32 CallFunc_Subtract_IntInt_ReturnValue_1, FInventory CallFunc_Array_Get_Item_3, FText CallFunc_Conv_IntToText_ReturnValue_1, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1, FName CallFunc_Conv_StringToName_ReturnValue, FName CallFunc_Conv_StringToName_ReturnValue_1, FSpiritsInfo CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, FWeaponsInfo CallFunc_GetDataTableRowFromName_OutRow_1, bool CallFunc_GetDataTableRowFromName_ReturnValue_1, FString CallFunc_Conv_IntToString_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_4, FText CallFunc_Conv_StringToText_ReturnValue_1, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_2, bool K2Node_SwitchEnum_CmpSuccess, FName CallFunc_Conv_StringToName_ReturnValue_2, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_3, FTunicsInfo CallFunc_GetDataTableRowFromName_OutRow_2, bool CallFunc_GetDataTableRowFromName_ReturnValue_2, FName CallFunc_Conv_StringToName_ReturnValue_3, FItem CallFunc_GetDataTableRowFromName_OutRow_3, bool CallFunc_GetDataTableRowFromName_ReturnValue_3, FString Temp_string_Variable_3, FString CallFunc_Concat_StrStr_ReturnValue_5, FString CallFunc_Concat_StrStr_ReturnValue_6, FString CallFunc_Concat_StrStr_ReturnValue_7, FString CallFunc_Concat_StrStr_ReturnValue_8, FText CallFunc_Conv_StringToText_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_9, FString CallFunc_Concat_StrStr_ReturnValue_10, FText CallFunc_Conv_StringToText_ReturnValue_3, FString CallFunc_Concat_StrStr_ReturnValue_11, FString CallFunc_Concat_StrStr_ReturnValue_12, FText CallFunc_Conv_StringToText_ReturnValue_4, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Variable_24, FInventory CallFunc_Array_Get_Item_4, const TArray<FText>& K2Node_MakeArray_Array_1, bool K2Node_SwitchEnum_CmpSuccess_1, bool K2Node_SwitchInteger_CmpSuccess, const TArray<FText>& K2Node_MakeArray_Array_2, bool CallFunc_HasItem_Success, int32 CallFunc_HasItem_ItemAmount, FString CallFunc_Conv_IntToString_ReturnValue_1, const TArray<FText>& K2Node_MakeArray_Array_3, int32 Temp_int_Variable_25, const TArray<FText>& K2Node_MakeArray_Array_4, const TArray<FText>& K2Node_MakeArray_Array_5, FInventory CallFunc_Array_Get_Item_5, FString CallFunc_Conv_IntToString_ReturnValue_2, int32 CallFunc_Multiply_IntInt_ReturnValue, bool CallFunc_GetAsset_Success, int32 CallFunc_GetAsset_Index, bool K2Node_SwitchEnum_CmpSuccess_2, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_4, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, FString CallFunc_Concat_StrStr_ReturnValue_13, FName CallFunc_Conv_StringToName_ReturnValue_4, FString CallFunc_Concat_StrStr_ReturnValue_14, FItem CallFunc_GetDataTableRowFromName_OutRow_4, bool CallFunc_GetDataTableRowFromName_ReturnValue_4, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, bool CallFunc_EqualEqual_ByteByte_ReturnValue_4, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_GetItem_Success, bool CallFunc_GetItem_SpecialPopUp, bool CallFunc_EqualEqual_ByteByte_ReturnValue_5, int32 Temp_int_Variable_26, int32 Temp_int_Variable_27, TArray<FInventory>& CallFunc_GetShopArray_Array, bool Temp_bool_Variable_41, FInventory CallFunc_Array_Get_Item_6, int32 CallFunc_Subtract_IntInt_ReturnValue_2, FInventory K2Node_MakeStruct_Inventory, bool CallFunc_LessEqual_IntInt_ReturnValue_1, FInventory CallFunc_Array_Get_Item_7, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_6, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue, int32 Temp_int_Variable_28, int32 K2Node_CustomEvent_SellItemAmount, int32 CallFunc_Multiply_IntInt_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue_1, bool CallFunc_GetCurrency_Success, FText K2Node_CustomEvent_Name_1, FText K2Node_CustomEvent_Description_1, UMaterialInterface* K2Node_CustomEvent_Material, int32 Temp_int_Variable_29, int32 Temp_int_Variable_30, bool Temp_bool_Variable_42, int32 Temp_int_Variable_31, int32 Temp_int_Variable_32, int32 CallFunc_Subtract_IntInt_ReturnValue_3, uint8 Temp_byte_Variable_7, int32 CallFunc_Clamp_ReturnValue, const TArray<FText>& K2Node_MakeArray_Array_6, const TArray<FText>& K2Node_MakeArray_Array_7, int32 Temp_int_Variable_33, int32 Temp_int_Variable_34, bool Temp_bool_Variable_43, bool CallFunc_HasItem_Success_1, int32 CallFunc_HasItem_ItemAmount_1, int32 CallFunc_Add_IntInt_ReturnValue_12, bool CallFunc_Greater_IntInt_ReturnValue_1, FText CallFunc_MakeLiteralText_ReturnValue_1, FText CallFunc_MakeLiteralText_ReturnValue_2, const TArray<FText>& K2Node_MakeArray_Array_8, const TArray<FText>& K2Node_MakeArray_Array_9, FString CallFunc_MakeLiteralString_ReturnValue_2, FText CallFunc_Conv_StringToText_ReturnValue_5, const TArray<FText>& K2Node_MakeArray_Array_10, int32 Temp_int_Variable_35, int32 Temp_int_Variable_36, int32 Temp_int_Variable_37, int32 CallFunc_GetChildrenCount_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_4, UWidget* CallFunc_GetChildAt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, UDialogOption_C* K2Node_DynamicCast_AsDialog_Option, bool K2Node_DynamicCast_bSuccess, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_4, TArray<UInventoryItem_C*>& K2Node_MakeArray_Array_11, int32 CallFunc_Array_Length_ReturnValue_7, int32 Temp_int_Array_Index_Variable_1, int32 CallFunc_Array_Length_ReturnValue_8, FString CallFunc_Array_Get_Item_8, int32 CallFunc_Add_IntInt_ReturnValue_13, bool CallFunc_EqualEqual_StrStr_ReturnValue_7, FString CallFunc_Array_Get_Item_9, bool CallFunc_EqualEqual_StrStr_ReturnValue_8, bool CallFunc_Array_IsValidIndex_ReturnValue, FString CallFunc_Concat_StrStr_ReturnValue_15, bool CallFunc_EqualEqual_StrStr_ReturnValue_9, bool CallFunc_EqualEqual_StrStr_ReturnValue_10, bool CallFunc_EqualEqual_StrStr_ReturnValue_11, bool CallFunc_Array_IsValidIndex_ReturnValue_1, uint8 K2Node_CustomEvent_Directions, bool K2Node_CustomEvent_RefreshOnly, bool Temp_bool_Has_Been_Initd_Variable, bool K2Node_CustomEvent_Right_2, bool K2Node_CustomEvent_refresh, bool Temp_bool_IsClosed_Variable, bool K2Node_SwitchInteger_CmpSuccess_1, bool Temp_bool_Variable_44, bool K2Node_SwitchInteger_CmpSuccess_2, int32 CallFunc_Array_Length_ReturnValue_9, int32 Temp_int_Variable_38, bool Temp_bool_Variable_45, bool Temp_bool_Variable_46, bool Temp_bool_Variable_47, FText CallFunc_Conv_IntToText_ReturnValue_2, bool Temp_bool_Variable_48, uint8 Temp_byte_Variable_8, int32 Temp_int_Loop_Counter_Variable_1, bool K2Node_Select_Default, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_14, bool Temp_bool_Has_Been_Initd_Variable_1, int32 Temp_int_Loop_Counter_Variable_2, bool CallFunc_Less_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_15, bool Temp_bool_IsClosed_Variable_1, int32 Temp_int_Variable_39, bool Temp_bool_Has_Been_Initd_Variable_2, bool Temp_bool_Variable_49, bool Temp_bool_Variable_50, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, bool CallFunc_EqualEqual_IntInt_ReturnValue_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_5, int32 K2Node_Select_Default_1, bool CallFunc_EqualEqual_IntInt_ReturnValue_6, int32 K2Node_Select_Default_2, bool CallFunc_BooleanOR_ReturnValue_2, bool CallFunc_BooleanOR_ReturnValue_3, int32 K2Node_Select_Default_3, bool CallFunc_BooleanOR_ReturnValue_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_7, int32 K2Node_Select_Default_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_8, bool CallFunc_EqualEqual_IntInt_ReturnValue_9, bool CallFunc_EqualEqual_IntInt_ReturnValue_10, bool CallFunc_BooleanOR_ReturnValue_5, bool CallFunc_EqualEqual_IntInt_ReturnValue_11, bool CallFunc_BooleanOR_ReturnValue_6, bool CallFunc_BooleanOR_ReturnValue_7, bool CallFunc_EqualEqual_IntInt_ReturnValue_12, bool CallFunc_BooleanOR_ReturnValue_8, int32 K2Node_Select_Default_5, bool CallFunc_EqualEqual_IntInt_ReturnValue_13, bool CallFunc_EqualEqual_IntInt_ReturnValue_14, bool CallFunc_BooleanOR_ReturnValue_9, bool CallFunc_BooleanOR_ReturnValue_10, int32 K2Node_Select_Default_6, int32 K2Node_Select_Default_7, int32 K2Node_Select_Default_8, int32 K2Node_Select_Default_9, bool CallFunc_EqualEqual_IntInt_ReturnValue_15, bool CallFunc_EqualEqual_IntInt_ReturnValue_16, bool CallFunc_EqualEqual_IntInt_ReturnValue_17, bool CallFunc_BooleanOR_ReturnValue_11, bool CallFunc_EqualEqual_IntInt_ReturnValue_18, bool CallFunc_BooleanOR_ReturnValue_12, bool Temp_bool_IsClosed_Variable_2, bool CallFunc_BooleanOR_ReturnValue_13, int32 K2Node_Select_Default_10, int32 K2Node_Select_Default_11, int32 CallFunc_Add_IntInt_ReturnValue_16, UWidget* CallFunc_GetChildAt_ReturnValue_1, int32 CallFunc_Clamp_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, uint8 Temp_byte_Variable_9, int32 K2Node_Select_Default_12, bool Temp_bool_Variable_51, int32 CallFunc_Add_IntInt_ReturnValue_17, UWidget* CallFunc_GetChildAt_ReturnValue_2, int32 CallFunc_Clamp_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_1, bool Temp_bool_Variable_52, bool K2Node_CustomEvent_Right_1, int32 CallFunc_Add_IntInt_ReturnValue_18, bool CallFunc_Array_IsValidIndex_ReturnValue_2, bool K2Node_Select_Default_13, uint8 Temp_byte_Variable_10, bool K2Node_Select_Default_14, FText K2Node_CustomEvent_Description, FText K2Node_CustomEvent_Name, UShopItemWBP_C* CallFunc_Create_ReturnValue_1, FText CallFunc_Conv_StringToText_ReturnValue_6, UPanelSlot* CallFunc_AddChild_ReturnValue, FText CallFunc_MakeLiteralText_ReturnValue_3, int32 CallFunc_Array_Add_ReturnValue, ESlateVisibility Temp_byte_Variable_11, int32 CallFunc_Add_IntInt_ReturnValue_19, int32 K2Node_Select_Default_15, FInventory CallFunc_Array_Get_Item_10, bool CallFunc_Array_IsValidIndex_ReturnValue_3, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_5, FName CallFunc_Conv_StringToName_ReturnValue_5, bool Temp_bool_Variable_53, FItem CallFunc_GetDataTableRowFromName_OutRow_5, bool CallFunc_GetDataTableRowFromName_ReturnValue_5, bool CallFunc_Not_PreBool_ReturnValue_2, int32 CallFunc_Divide_IntInt_ReturnValue, bool Temp_bool_Variable_54, bool Temp_bool_Variable_55, int32 CallFunc_MakeLiteralInt_ReturnValue_2, int32 Temp_int_Variable_40, int32 CallFunc_Add_IntInt_ReturnValue_20, bool Temp_bool_Variable_56, APawn* CallFunc_GetPlayerPawn_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue, UPlayer_Character_BP_C* K2Node_DynamicCast_AsPlayer_Character_BP, bool K2Node_DynamicCast_bSuccess_1, uint8 Temp_byte_Variable_12, UInventoryItem_C* CallFunc_Array_Get_Item_11, bool K2Node_Select_Default_16, int32 CallFunc_Add_IntInt_ReturnValue_21, int32 Temp_int_Array_Index_Variable_2, ESlateVisibility Temp_byte_Variable_13, bool Temp_bool_Variable_57, const TArray<FText>& K2Node_MakeArray_Array_12, bool Temp_bool_Variable_58, bool K2Node_SwitchEnum_CmpSuccess_3, bool K2Node_SwitchInteger_CmpSuccess_3, bool Temp_bool_Variable_59, bool CallFunc_Array_IsValidIndex_ReturnValue_4, UInventoryItem_C* CallFunc_Array_Get_Item_12, bool CallFunc_Array_IsValidIndex_ReturnValue_5, const TArray<FText>& K2Node_MakeArray_Array_13, FString CallFunc_Conv_IntToString_ReturnValue_3, bool Temp_bool_Variable_60, int32 CallFunc_PostEventAtLocation_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_3, int32 CallFunc_PostEventAtLocation_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_22, int32 Temp_int_Array_Index_Variable_3, UShopItemWBP_C* CallFunc_Array_Get_Item_13, bool CallFunc_EqualEqual_IntInt_ReturnValue_19, bool Temp_bool_Variable_61, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_5, ESlateVisibility K2Node_Select_Default_17, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_6, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_7, int32 CallFunc_PostEventAtLocation_ReturnValue_3, bool K2Node_Select_Default_18, bool K2Node_Select_Default_19, bool K2Node_Select_Default_20, uint8 Temp_byte_Variable_14, FText CallFunc_MakeLiteralText_ReturnValue_4, const TArray<FText>& K2Node_MakeArray_Array_14, bool K2Node_Select_Default_21, FString CallFunc_MakeLiteralString_ReturnValue_3, FText CallFunc_Conv_StringToText_ReturnValue_7, const TArray<FText>& K2Node_MakeArray_Array_15, int32 K2Node_Select_Default_22, int32 Temp_int_Variable_41, int32 K2Node_Select_Default_23, FText CallFunc_Conv_IntToText_ReturnValue_3, int32 Temp_int_Variable_42, bool K2Node_Select_Default_24, bool Temp_bool_Variable_62, int32 K2Node_Select_Default_25, int32 CallFunc_Add_IntInt_ReturnValue_23, int32 Temp_int_Variable_43, int32 CallFunc_Clamp_ReturnValue_3, int32 Temp_int_Variable_44, uint8 K2Node_Select_Default_26, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_6, bool K2Node_Select_Default_27, FName CallFunc_Conv_StringToName_ReturnValue_6, FItem CallFunc_GetDataTableRowFromName_OutRow_6, bool CallFunc_GetDataTableRowFromName_ReturnValue_6, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_7, FName CallFunc_Conv_StringToName_ReturnValue_7, int32 CallFunc_Divide_IntInt_ReturnValue_1, FItem CallFunc_GetDataTableRowFromName_OutRow_7, bool CallFunc_GetDataTableRowFromName_ReturnValue_7, int32 K2Node_Select_Default_28, int32 K2Node_Select_Default_29, int32 CallFunc_Multiply_IntInt_ReturnValue_2, bool CallFunc_GetCurrency_Success_1, bool CallFunc_Not_PreBool_ReturnValue_3, int32 CallFunc_Divide_IntInt_ReturnValue_2, bool K2Node_Select_Default_30, int32 K2Node_Select_Default_31, bool CallFunc_BooleanAND_ReturnValue_1, int32 K2Node_Select_Default_32, int32 CallFunc_Multiply_IntInt_ReturnValue_3, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_8, FString CallFunc_Conv_IntToString_ReturnValue_4, FName CallFunc_Conv_StringToName_ReturnValue_8, FItem CallFunc_GetDataTableRowFromName_OutRow_8, bool CallFunc_GetDataTableRowFromName_ReturnValue_8, bool CallFunc_UseItem_Success, int32 CallFunc_UseItem_CurrentAmount, bool CallFunc_Not_PreBool_ReturnValue_4, uint8 Temp_byte_Variable_15, bool K2Node_Select_Default_33, bool CallFunc_BooleanAND_ReturnValue_2, int32 K2Node_Select_Default_34, int32 CallFunc_Add_IntInt_ReturnValue_24, int32 Temp_int_Variable_45, UWidget* CallFunc_GetChildAt_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_2, int32 CallFunc_Multiply_IntInt_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_25, bool CallFunc_LessEqual_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_26, int32 CallFunc_Clamp_ReturnValue_4, UPanelWidget* K2Node_Select_Default_35, const TArray<UInventoryItem_C*>& K2Node_Select_Default_36, int32 CallFunc_PostEventAtLocation_ReturnValue_4, int32 CallFunc_Clamp_ReturnValue_5, int32 CallFunc_PostEventAtLocation_ReturnValue_5, bool CallFunc_IsAnimationPlaying_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_27, int32 CallFunc_GetPouchInfo_Current_Limit, int32 CallFunc_GetPouchInfo_Max_Limit, int32 CallFunc_PostEventAtLocation_ReturnValue_6, bool CallFunc_Greater_IntInt_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_7, const TArray<FText>& K2Node_MakeArray_Array_16, const TArray<FText>& K2Node_MakeArray_Array_17, bool K2Node_SwitchInteger_CmpSuccess_4, const TArray<FText>& K2Node_CustomEvent_TextLines_2, FText K2Node_CustomEvent_NPCName, const TArray<FText>& K2Node_CustomEvent_Responses_2, int32 K2Node_CustomEvent_SelectedOptionIndex_2, uint8 K2Node_CustomEvent_DialogType_2, int32 K2Node_CustomEvent_Shop, bool K2Node_CustomEvent_Center, UAkAudioEvent* K2Node_CustomEvent_AkEvent, bool K2Node_CustomEvent_UseAkSoundsArray, const TArray<UAkAudioEvent*>& K2Node_CustomEvent_AkEvents, bool K2Node_CustomEvent_CustomOptionTexts, TArray<FText>& K2Node_CustomEvent_CustomOptionArray, bool K2Node_CustomEvent_FadeStyle, bool K2Node_CustomEvent_ShowCurrencyOnQuestion, uint8 K2Node_CustomEvent_Item, bool K2Node_CustomEvent_ShowItemNNotCurrency, FText CallFunc_Array_Get_Item_14, int32 CallFunc_Subtract_IntInt_ReturnValue_5, bool CallFunc_EqualEqual_IntInt_ReturnValue_20, int32 CallFunc_Add_IntInt_ReturnValue_28, bool CallFunc_IsRobiValid_ReturnValue, int32 CallFunc_GetChildrenCount_ReturnValue_1, UWidget* CallFunc_GetChildAt_ReturnValue_4, int32 CallFunc_Subtract_IntInt_ReturnValue_6, UDialogOption_C* K2Node_DynamicCast_AsDialog_Option_1, bool K2Node_DynamicCast_bSuccess_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_21, UAkAudioEvent* K2Node_Select_Default_37, int32 CallFunc_PostEventAtLocation_ReturnValue_8, uint8 K2Node_CustomEvent_Direction_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_7, bool CallFunc_EqualEqual_ByteByte_ReturnValue_8, bool CallFunc_EqualEqual_ByteByte_ReturnValue_9, bool CallFunc_BooleanOR_ReturnValue_14, bool K2Node_Select_Default_38, bool CallFunc_BooleanAND_ReturnValue_3, int32 K2Node_Select_Default_39, UInventoryItem_C* CallFunc_Create_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue_1, UPanelSlot* CallFunc_AddChild_ReturnValue_1, FText CallFunc_MakeLiteralText_ReturnValue_5, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_8, int32 Temp_int_Variable_46, int32 Temp_int_Variable_47, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_9, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_10, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_11, int32 Temp_int_Variable_48, int32 Temp_int_Variable_49, int32 Temp_int_Variable_50, int32 K2Node_Select_Default_40, FString K2Node_Select_Default_41, FString CallFunc_Concat_StrStr_ReturnValue_16, FString Temp_string_Variable_4, FString CallFunc_Concat_StrStr_ReturnValue_17, bool Temp_bool_Has_Been_Initd_Variable_3, FText CallFunc_Array_Get_Item_15, int32 CallFunc_Array_Length_ReturnValue_10, int32 CallFunc_Array_Length_ReturnValue_11, bool CallFunc_Less_IntInt_ReturnValue_3, int32 CallFunc_Subtract_IntInt_ReturnValue_7, bool CallFunc_EqualEqual_IntInt_ReturnValue_22, UPanelSlot* CallFunc_AddChild_ReturnValue_2, int32 Temp_int_Array_Index_Variable_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_23, UInventoryItem_C* CallFunc_Array_Get_Item_16, bool CallFunc_EqualEqual_IntInt_ReturnValue_24, UWidget* CallFunc_GetChildAt_ReturnValue_5, bool CallFunc_EqualEqual_IntInt_ReturnValue_25, UDialogOption_C* K2Node_DynamicCast_AsDialog_Option_2, bool K2Node_DynamicCast_bSuccess_3, int32 CallFunc_GetChildrenCount_ReturnValue_2, int32 CallFunc_Subtract_IntInt_ReturnValue_8, int32 CallFunc_Add_IntInt_ReturnValue_29, bool CallFunc_LessEqual_IntInt_ReturnValue_3, UWidget* CallFunc_GetChildAt_ReturnValue_6, bool CallFunc_IsRobiValid_ReturnValue_1, FString Temp_string_Variable_5, FString Temp_string_Variable_6, int32 Temp_int_Variable_51, bool Temp_bool_IsClosed_Variable_3, FString K2Node_Select_Default_42, float Temp_float_Variable, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_12, int32 Temp_int_Loop_Counter_Variable_4, UGameInstance* CallFunc_GetGameInstance_ReturnValue, UBlueFire_Game_Instance_C* K2Node_DynamicCast_AsBlue_Fire_Game_Instance, bool K2Node_DynamicCast_bSuccess_4, bool CallFunc_Less_IntInt_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_30, uint8 K2Node_CustomEvent_Direction, bool K2Node_SwitchEnum_CmpSuccess_4, bool K2Node_SwitchEnum_CmpSuccess_5, uint8 K2Node_CustomEvent_Index, float Temp_float_Variable_1, bool K2Node_Select_Default_43, int32 Temp_int_Array_Index_Variable_5, UInventoryItem_C* CallFunc_Array_Get_Item_17, bool K2Node_SwitchEnum_CmpSuccess_6, bool CallFunc_EqualEqual_IntInt_ReturnValue_26, const TArray<FText>& K2Node_CustomEvent_TextLines_1, const TArray<FText>& K2Node_CustomEvent_Responses_1, int32 K2Node_CustomEvent_SelectedOptionIndex_1, uint8 K2Node_CustomEvent_DialogType_1, float Temp_float_Variable_2, const TArray<FText>& K2Node_CustomEvent_TextLines, const TArray<FText>& K2Node_CustomEvent_Responses, int32 K2Node_CustomEvent_SelectedOptionIndex, uint8 K2Node_CustomEvent_DialogType, int32 Temp_int_Variable_52, float K2Node_Select_Default_44, bool CallFunc_EqualEqual_ByteByte_ReturnValue_10, bool K2Node_SwitchEnum_CmpSuccess_7, bool K2Node_CustomEvent_Right, const bool K2Node_CustomEvent_Max, UWidget* CallFunc_GetChildAt_ReturnValue_7, UDialogOption_C* K2Node_DynamicCast_AsDialog_Option_3, bool K2Node_DynamicCast_bSuccess_5, int32 K2Node_Select_Default_45, int32 CallFunc_Add_IntInt_ReturnValue_31, bool CallFunc_Greater_IntInt_ReturnValue_4, FInventory CallFunc_Array_Get_Item_18, bool K2Node_SwitchEnum_CmpSuccess_8, bool CallFunc_NotEqual_TextText_ReturnValue, UWidget* CallFunc_GetChildAt_ReturnValue_8, UDialogOption_C* K2Node_DynamicCast_AsDialog_Option_4, bool K2Node_DynamicCast_bSuccess_6, FInventory CallFunc_Array_Get_Item_19, TArray<FInventory>& CallFunc_GetShopArray_Array_1, bool K2Node_SwitchEnum_CmpSuccess_9, bool CallFunc_EqualEqual_IntInt_ReturnValue_27, int32 Temp_int_Loop_Counter_Variable_5, bool CallFunc_Less_IntInt_ReturnValue_5, int32 CallFunc_Add_IntInt_ReturnValue_32, UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_13, FText CallFunc_MakeLiteralText_ReturnValue_6, FText CallFunc_MakeLiteralText_ReturnValue_7, FText CallFunc_MakeLiteralText_ReturnValue_8, FText K2Node_Select_Default_46, int32 Temp_int_Variable_53, int32 CallFunc_Add_IntInt_ReturnValue_33, bool Temp_bool_Variable_63, const FText K2Node_Select_Default_47, FText CallFunc_MakeLiteralText_ReturnValue_9, FText K2Node_Select_Default_48, bool K2Node_SwitchEnum_CmpSuccess_10, bool K2Node_SwitchEnum_CmpSuccess_11, int32 CallFunc_PostEventAtLocation_ReturnValue_9, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, FVector CallFunc_K2_GetActorLocation_ReturnValue, bool CallFunc_IsRobiValid_ReturnValue_2, int32 CallFunc_PostEventAtLocation_ReturnValue_10, int32 CallFunc_PostEventAtLocation_ReturnValue_11, int32 CallFunc_PostEventAtLocation_ReturnValue_12, APawn* CallFunc_GetPlayerPawn_ReturnValue_2, FVector CallFunc_K2_GetActorLocation_ReturnValue_1, APawn* CallFunc_GetPlayerPawn_ReturnValue_3, UAkAudioEvent* CallFunc_Array_Get_Item_20, FVector CallFunc_K2_GetActorLocation_ReturnValue_2, bool CallFunc_IsRobiValid_ReturnValue_3, int32 CallFunc_PostEventAtLocation_ReturnValue_13, int32 CallFunc_PostEventAtLocation_ReturnValue_14, UMaterialInstance* CallFunc_GetUIPlatform_UIMaterial, bool CallFunc_GetUIPlatform_NonSquareSize, FVector2D CallFunc_GetUIPlatform_Size, APawn* CallFunc_GetPlayerPawn_ReturnValue_4, UPlayer_Character_BP_C* K2Node_DynamicCast_AsPlayer_Character_BP_1, bool K2Node_DynamicCast_bSuccess_7, FTimerHandle CallFunc_K2_SetTimer_ReturnValue, UMaterialInstance* CallFunc_GetUIPlatform_UIMaterial_1, bool CallFunc_GetUIPlatform_NonSquareSize_1, FVector2D CallFunc_GetUIPlatform_Size_1, int32 Temp_int_Variable_54, bool K2Node_SwitchEnum_CmpSuccess_12, FInventory CallFunc_Array_Get_Item_21, bool CallFunc_Array_IsValidIndex_ReturnValue_6, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_9, FName CallFunc_Conv_StringToName_ReturnValue_9, bool CallFunc_LessEqual_IntInt_ReturnValue_4, FItem CallFunc_GetDataTableRowFromName_OutRow_9, bool CallFunc_GetDataTableRowFromName_ReturnValue_9, int32 CallFunc_Add_IntInt_ReturnValue_34, bool CallFunc_Not_PreBool_ReturnValue_5, bool K2Node_Select_Default_49, bool Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable, bool CallFunc_BooleanAND_ReturnValue_4, float CallFunc_Divide_FloatFloat_ReturnValue, int32 CallFunc_FTrunc_ReturnValue, bool CallFunc_GreaterEqual_FloatFloat_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue_5, bool CallFunc_EqualEqual_IntInt_ReturnValue_28, const TArray<FText>& K2Node_CustomEvent_Text, FText CallFunc_Array_Get_Item_22, FString CallFunc_Conv_IntToString_ReturnValue_5, FText CallFunc_Array_Get_Item_23, UAkAudioEvent* Temp_object_Variable_4, const TArray<FText>& K2Node_MakeArray_Array_18, UAkAudioEvent* Temp_object_Variable_5, bool CallFunc_MakeLiteralBool_ReturnValue_9, uint8 K2Node_Select_Default_50, bool K2Node_SwitchEnum_CmpSuccess_13, bool Temp_bool_Has_Been_Initd_Variable_4, int32 CallFunc_PostEventAtLocation_ReturnValue_15, bool Temp_bool_Variable_64, UAkAudioEvent* K2Node_Select_Default_51, bool CallFunc_IsRobiValid_ReturnValue_4, int32 CallFunc_PostEventAtLocation_ReturnValue_16, int32 CallFunc_Array_Length_ReturnValue_12, int32 CallFunc_Subtract_IntInt_ReturnValue_9, bool Temp_bool_IsClosed_Variable_4, FText CallFunc_Conv_IntToText_ReturnValue_4, FString CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_10, FName CallFunc_Conv_StringToName_ReturnValue_10, bool K2Node_CustomEvent_BlackText, float K2Node_CustomEvent_In_Position_Y, FItem CallFunc_GetDataTableRowFromName_OutRow_10, bool CallFunc_GetDataTableRowFromName_ReturnValue_10, FVector2D CallFunc_MakeVector2D_ReturnValue, bool CallFunc_HasItem_Success_2, int32 CallFunc_HasItem_ItemAmount_2, FText CallFunc_Conv_IntToText_ReturnValue_5, FText K2Node_Select_Default_52, UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue, FText CallFunc_MakeLiteralText_ReturnValue_10, int32 CallFunc_Add_IntInt_ReturnValue_35, FInventory CallFunc_Array_Get_Item_24, int32 K2Node_Select_Default_53, int32 K2Node_Select_Default_54, bool CallFunc_LessEqual_IntInt_ReturnValue_6, bool CallFunc_BooleanAND_ReturnValue_5, int32 CallFunc_Clamp_ReturnValue_6, int32 K2Node_Select_Default_55, int32 CallFunc_GetChildrenCount_ReturnValue_3, UWidget* CallFunc_GetChildAt_ReturnValue_9, int32 CallFunc_Subtract_IntInt_ReturnValue_10, UDialogOption_C* K2Node_DynamicCast_AsDialog_Option_5, bool K2Node_DynamicCast_bSuccess_8, bool CallFunc_EqualEqual_IntInt_ReturnValue_29, UAkAudioEvent* K2Node_Select_Default_56, int32 CallFunc_PostEventAtLocation_ReturnValue_17);
    void Exit__DelegateSignature();
    void LastLineCall__DelegateSignature();
    void OptionChange__DelegateSignature(int32 CurrentOption);
    void AbilityUnlock__DelegateSignature(uint8 Ability);
    void Finished__DelegateSignature();
    void NextLineED__DelegateSignature(int32 CurrentLine);
    void ExitDialog__DelegateSignature();
}

#endif
