#ifndef UE4SS_SDK_Moving_Path_Actor_Straight_HPP
#define UE4SS_SDK_Moving_Path_Actor_Straight_HPP

class AMoving_Path_Actor_Straight_C : AActor
{
    FPointerToUberGraphFrame UberGraphFrame;
    UAkComponent* Play_Travel_Platform_Magic_Carpet_Void_Loop;
    UAkComponent* Ak;
    UBoxComponent* Box;
    USceneComponent* DefaultSceneRoot;
    AMoving_Path_Spline_C* Path;
    float Distance;
    float Speed;
    float MaxDistance;
    APlayer_Character_BP_C* Player;
    UAkAudioEvent* PlaySound;

    void UserConstructionScript(bool CallFunc_IsRobiValid_ReturnValue, FVector CallFunc_GetLocationAtDistanceAlongSpline_ReturnValue, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult, bool CallFunc_K2_SetActorLocation_ReturnValue);
    void ReceiveTick(float DeltaSeconds);
    void BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void Reset();
    void ExecuteUbergraph_Moving_Path_Actor_Straight(int32 EntryPoint, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_1, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_1, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_2, bool Temp_bool_IsClosed_Variable, bool Temp_bool_Has_Been_Initd_Variable, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_2, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_3, bool Temp_bool_Has_Been_Initd_Variable_1, Die__DelegateSignature K2Node_CreateDelegate_OutputDelegate, float K2Node_Event_DeltaSeconds, float CallFunc_GetSplineLength_ReturnValue, float CallFunc_Multiply_FloatFloat_ReturnValue, FVector CallFunc_GetLocationAtDistanceAlongSpline_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, float CallFunc_FClamp_ReturnValue, FVector CallFunc_GetLocationAtDistanceAlongSpline_ReturnValue_1, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult, bool CallFunc_K2_SetActorLocation_ReturnValue, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_3, UPrimitiveComponent* K2Node_ComponentBoundEvent_OverlappedComponent, AActor* K2Node_ComponentBoundEvent_OtherActor, UPrimitiveComponent* K2Node_ComponentBoundEvent_OtherComp, int32 K2Node_ComponentBoundEvent_OtherBodyIndex, bool K2Node_ComponentBoundEvent_bFromSweep, const FHitResult K2Node_ComponentBoundEvent_SweepResult, UPlayer_Character_BP_C* K2Node_DynamicCast_AsPlayer_Character_BP, bool K2Node_DynamicCast_bSuccess, const TArray<FAkExternalSourceInfo>& Temp_struct_Variable_4, int32 CallFunc_PostAkEvent_ReturnValue, FVector CallFunc_K2_GetActorLocation_ReturnValue, float CallFunc_GetDistanceTo_ReturnValue, FVector CallFunc_Subtract_VectorVector_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue, float CallFunc_VSize_ReturnValue, const OnAkPostEventCallback__DelegateSignature Temp_delegate_Variable_4, bool CallFunc_Greater_FloatFloat_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_PostAkEvent_ReturnValue_1, bool CallFunc_EqualEqual_FloatFloat_ReturnValue, bool Temp_bool_Has_Been_Initd_Variable_2, int32 CallFunc_PostAssociatedAkEvent_ReturnValue, bool Temp_bool_IsClosed_Variable_1, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool Temp_bool_IsClosed_Variable_2, bool CallFunc_IsRobiValid_ReturnValue, int32 CallFunc_PostAkEvent_ReturnValue_2, bool CallFunc_IsRobiValid_ReturnValue_1, FVector CallFunc_GetLocationAtDistanceAlongSpline_ReturnValue_2, FHitResult CallFunc_K2_SetActorLocation_SweepHitResult_1, bool CallFunc_K2_SetActorLocation_ReturnValue_1, int32 CallFunc_PostAkEvent_ReturnValue_3);
}

#endif
