#ifndef UE4SS_SDK_Nuos_Temple_End_HPP
#define UE4SS_SDK_Nuos_Temple_End_HPP

class USequenceDirector_C : ULevelSequenceDirector
{
    FPointerToUberGraphFrame UberGraphFrame;

    void SequenceEvent__ENTRYPOINTSequenceDirector_19(UNPC_GodNuos_C* NPC_GodNuos);
    void SequenceEvent__ENTRYPOINTSequenceDirector_18(UNPC_GodNuos_C* NPC_GodNuos);
    void SequenceEvent__ENTRYPOINTSequenceDirector_17(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_16(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_15(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_14(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_13(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_12(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_11(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_10(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_9(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_8(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_7(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_6(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_5(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_4(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_3(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_2(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_1(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_0(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Intro_Controller_Event_0(UNuos_Intro_Controller_C* Nuos_Intro_Controller);
    void Nuos_Intro_Controller_Event_1(UNuos_Intro_Controller_C* Nuos_Intro_Controller);
    void Nuos_Intro_Controller_Event_2(UNuos_Intro_Controller_C* Nuos_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_0(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_1(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_End_Controller_Event_0(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_1(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_2(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_3(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_4(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_6(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_7(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_8(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_9(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_10(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_11(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_12(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_13(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void NPC_GodNuos_Event_0(UNPC_GodNuos_C* NPC_GodNuos);
    void Nuos_Temple_End_Controller_Event_5(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_14(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_15(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void NPC_GodNuos_Event_1(UNPC_GodNuos_C* NPC_GodNuos);
    void Nuos_Temple_End_Controller_Event_16(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_17(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_18(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_19(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_20(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_21(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void Nuos_Temple_End_Controller_Event_22(UNuos_Temple_End_Controller_C* Nuos_Temple_End_Controller);
    void ExecuteUbergraph_SequenceDirector(int32 EntryPoint, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller, UNuos_Intro_Controller_C* K2Node_CustomEvent_Nuos_Intro_Controller_2, UNuos_Intro_Controller_C* K2Node_CustomEvent_Nuos_Intro_Controller_1, UNuos_Intro_Controller_C* K2Node_CustomEvent_Nuos_Intro_Controller, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_1, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_22, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_21, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_20, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_19, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_18, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_17, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_16, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_15, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_14, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_13, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_12, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_11, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_10, UNPC_GodNuos_C* K2Node_CustomEvent_NPC_GodNuos_1, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_9, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_8, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_7, UNPC_GodNuos_C* K2Node_CustomEvent_NPC_GodNuos, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_6, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_5, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_4, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_3, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_2, UNuos_Temple_End_Controller_C* K2Node_CustomEvent_Nuos_Temple_End_Controller_1);
}

#endif
