#ifndef UE4SS_SDK_Nuos_Temple_Intro_HPP
#define UE4SS_SDK_Nuos_Temple_Intro_HPP

class USequenceDirector_C : ULevelSequenceDirector
{
    FPointerToUberGraphFrame UberGraphFrame;

    void SequenceEvent__ENTRYPOINTSequenceDirector_9(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_8(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_7(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_6(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_5(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_4(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_3(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_2(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_1(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_0(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_0(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_2(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_3(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_4(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_1(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_5(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_6(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_7(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_8(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_9(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void ExecuteUbergraph_SequenceDirector(int32 EntryPoint, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_9, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_8, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_7, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_6, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_5, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_4, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_3, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_2, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_1);
}

#endif
