#ifndef UE4SS_SDK_SpiritMasterMeet_HPP
#define UE4SS_SDK_SpiritMasterMeet_HPP

class USequenceDirector_C : ULevelSequenceDirector
{
    FPointerToUberGraphFrame UberGraphFrame;

    void SequenceEvent__ENTRYPOINTSequenceDirector_5(UNPC_SpiritHunter_C* NPC_SpiritHunter_A02);
    void SequenceEvent__ENTRYPOINTSequenceDirector_4(UNPC_SpiritHunter_C* NPC_SpiritHunter_A02);
    void SequenceEvent__ENTRYPOINTSequenceDirector_3(USpiritMasterMeet_Controller_C* SpiritMasterMeet_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_2(USpiritMasterMeet_Controller_C* SpiritMasterMeet_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_1(USpiritMasterMeet_Controller_C* SpiritMasterMeet_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_0(USpiritMasterMeet_Controller_C* SpiritMasterMeet_Controller);
    void Nuos_Temple_Intro_Controller_Event_0(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void Nuos_Temple_Intro_Controller_Event_1(UNuos_Temple_Intro_Controller_C* Nuos_Temple_Intro_Controller);
    void NPC_Mira2_Event_0(UNPC_Mira_C* NPC_Mira2);
    void Mira_Intro_Controller_Event_0(UMira_Intro_Controller_C* Mira_Intro_Controller);
    void Mira_Intro_Controller_Event_1(UMira_Intro_Controller_C* Mira_Intro_Controller);
    void SpiritMasterMeet_Controller_Event_0(USpiritMasterMeet_Controller_C* SpiritMasterMeet_Controller);
    void SpiritMasterMeet_Controller_Event_1(USpiritMasterMeet_Controller_C* SpiritMasterMeet_Controller);
    void SpiritMasterMeet_Controller_Event_2(USpiritMasterMeet_Controller_C* SpiritMasterMeet_Controller);
    void SpiritMasterMeet_Controller_Event_3(USpiritMasterMeet_Controller_C* SpiritMasterMeet_Controller);
    void NPC_SpiritHunter_A02_Event_0(UNPC_SpiritHunter_C* NPC_SpiritHunter_A02);
    void SpiritMasterMeet_Controller_Event_4(USpiritMasterMeet_Controller_C* SpiritMasterMeet_Controller);
    void NPC_SpiritHunter_A02_Event_1(UNPC_SpiritHunter_C* NPC_SpiritHunter_A02);
    void ExecuteUbergraph_SequenceDirector(int32 EntryPoint, UNPC_SpiritHunter_C* K2Node_CustomEvent_NPC_SpiritHunter_A02, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller_1, UNuos_Temple_Intro_Controller_C* K2Node_CustomEvent_Nuos_Temple_Intro_Controller, UNPC_Mira_C* K2Node_CustomEvent_NPC_Mira2, UMira_Intro_Controller_C* K2Node_CustomEvent_Mira_Intro_Controller_1, UMira_Intro_Controller_C* K2Node_CustomEvent_Mira_Intro_Controller, USpiritMasterMeet_Controller_C* K2Node_CustomEvent_SpiritMasterMeet_Controller_4, USpiritMasterMeet_Controller_C* K2Node_CustomEvent_SpiritMasterMeet_Controller_3, USpiritMasterMeet_Controller_C* K2Node_CustomEvent_SpiritMasterMeet_Controller_2, USpiritMasterMeet_Controller_C* K2Node_CustomEvent_SpiritMasterMeet_Controller_1, UNPC_SpiritHunter_C* K2Node_CustomEvent_NPC_SpiritHunter_A02_1, USpiritMasterMeet_Controller_C* K2Node_CustomEvent_SpiritMasterMeet_Controller);
}

#endif
