#ifndef UE4SS_SDK_Telescope_BP_HPP
#define UE4SS_SDK_Telescope_BP_HPP

class ATelescope_BP_C : AInteractionMaster_C
{
    FPointerToUberGraphFrame UberGraphFrame;
    UArrowComponent* Arrow;
    UStaticMeshComponent* Telescope_SM;
    AActor* Cam;

    void ReceiveBeginPlay();
    void PressButton();
    void ReceiveTick(float DeltaSeconds);
    void ExecuteUbergraph_Telescope_BP(int32 EntryPoint, bool Temp_bool_Variable, bool CallFunc_Not_PreBool_ReturnValue, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, UPlayerController* CallFunc_GetPlayerController_ReturnValue, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue_1, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue_2, UPlayerController* CallFunc_GetPlayerController_ReturnValue_1, APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue_3, APawn* CallFunc_GetPlayerPawn_ReturnValue, APawn* CallFunc_GetPlayerPawn_ReturnValue_1, FTransform CallFunc_K2_GetComponentToWorld_ReturnValue, FVector CallFunc_BreakTransform_Location, FRotator CallFunc_BreakTransform_Rotation, FVector CallFunc_BreakTransform_Scale, int32 CallFunc_PostEventAtLocation_ReturnValue, FHitResult CallFunc_K2_SetActorLocationAndRotation_SweepHitResult, bool CallFunc_K2_SetActorLocationAndRotation_ReturnValue, int32 CallFunc_PostEventAtLocation_ReturnValue_1, float K2Node_Event_DeltaSeconds, APawn* CallFunc_GetPlayerPawn_ReturnValue_2, const FTransform CallFunc_GetTransform_ReturnValue, const FTransform CallFunc_GetTransform_ReturnValue_1, FVector CallFunc_BreakTransform_Location_1, FRotator CallFunc_BreakTransform_Rotation_1, FVector CallFunc_BreakTransform_Scale_1, FVector CallFunc_BreakTransform_Location_2, FRotator CallFunc_BreakTransform_Rotation_2, FVector CallFunc_BreakTransform_Scale_2, float CallFunc_BreakVector_X, float CallFunc_BreakVector_Y, float CallFunc_BreakVector_Z, float CallFunc_BreakVector_X_1, float CallFunc_BreakVector_Y_1, float CallFunc_BreakVector_Z_1, float CallFunc_Subtract_FloatFloat_ReturnValue, float CallFunc_Add_FloatFloat_ReturnValue, bool CallFunc_Less_FloatFloat_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue);
}

#endif
