#ifndef UE4SS_SDK_VoidsWon_10_VoidGate_Sequencer_HPP
#define UE4SS_SDK_VoidsWon_10_VoidGate_Sequencer_HPP

class USequenceDirector_C : ULevelSequenceDirector
{
    FPointerToUberGraphFrame UberGraphFrame;

    void Von_Cinematics_VoidLament_Event_0(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void VoidLament_Controller_Event_0(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_1(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_2(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_3(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_4(UVoidLament_Controller_C* VoidLament_Controller);
    void Von_Cinematics_VoidLament_Event_1(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void ExecuteUbergraph_SequenceDirector(int32 EntryPoint, UVon_Cinematics_VoidLament_C* K2Node_CustomEvent_Von_Cinematics_VoidLament, UVon_Cinematics_VoidLament_C* K2Node_CustomEvent_Von_Cinematics_VoidLament_1, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_4, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_3, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_2, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_1, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller);
}

#endif
