#ifndef UE4SS_SDK_VoidLament_HPP
#define UE4SS_SDK_VoidLament_HPP

class USequenceDirector_C : ULevelSequenceDirector
{
    FPointerToUberGraphFrame UberGraphFrame;

    void SequenceEvent__ENTRYPOINTSequenceDirector_15(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_14(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void SequenceEvent__ENTRYPOINTSequenceDirector_13(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_12(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_11(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_10(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_9(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_8(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_7(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_6(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_5(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_4(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_3(UVoidLament_Controller_C* VoidLament_Controller);
    void SequenceEvent__ENTRYPOINTSequenceDirector_2(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void SequenceEvent__ENTRYPOINTSequenceDirector_1(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void SequenceEvent__ENTRYPOINTSequenceDirector_0(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void Von_Cinematics_VoidLament_Event_0(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void VoidLament_Controller_Event_0(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_2(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_3(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_4(UVoidLament_Controller_C* VoidLament_Controller);
    void Von_Cinematics_VoidLament_Event_1(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void VoidLament_Controller_Event_5(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_6(UVoidLament_Controller_C* VoidLament_Controller);
    void Von_Cinematics_VoidLament_Event_2(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void Von_Cinematics_VoidLament_Event_3(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void Von_Cinematics_VoidLament_Event_4(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void VoidLament_Controller_Event_8(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_9(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_10(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_11(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_12(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_13(UVoidLament_Controller_C* VoidLament_Controller);
    void Von_Cinematics_VoidLament_Event_5(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void VoidLament_Controller_Event_14(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_15(UVoidLament_Controller_C* VoidLament_Controller);
    void Von_Cinematics_VoidLament_Event_7(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void VoidLament_Controller_Event_1(UVoidLament_Controller_C* VoidLament_Controller);
    void VoidLament_Controller_Event_7(UVoidLament_Controller_C* VoidLament_Controller);
    void Von_Cinematics_VoidLament_Event_8(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void Von_Cinematics_VoidLament_Event_9(UVon_Cinematics_VoidLament_C* Von_Cinematics_VoidLament);
    void VoidLament_Controller_Event_17(UVoidLament_Controller_C* VoidLament_Controller);
    void ExecuteUbergraph_SequenceDirector(int32 EntryPoint, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller, UVon_Cinematics_VoidLament_C* K2Node_CustomEvent_Von_Cinematics_VoidLament_8, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_16, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_15, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_14, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_13, UVon_Cinematics_VoidLament_C* K2Node_CustomEvent_Von_Cinematics_VoidLament_7, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_12, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_11, UVon_Cinematics_VoidLament_C* K2Node_CustomEvent_Von_Cinematics_VoidLament_6, UVon_Cinematics_VoidLament_C* K2Node_CustomEvent_Von_Cinematics_VoidLament_5, UVon_Cinematics_VoidLament_C* K2Node_CustomEvent_Von_Cinematics_VoidLament_4, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_10, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_9, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_8, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_7, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_6, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_5, UVon_Cinematics_VoidLament_C* K2Node_CustomEvent_Von_Cinematics_VoidLament_3, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_4, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_3, UVon_Cinematics_VoidLament_C* K2Node_CustomEvent_Von_Cinematics_VoidLament_2, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_2, UVoidLament_Controller_C* K2Node_CustomEvent_VoidLament_Controller_1, UVon_Cinematics_VoidLament_C* K2Node_CustomEvent_Von_Cinematics_VoidLament_1, UVon_Cinematics_VoidLament_C* K2Node_CustomEvent_Von_Cinematics_VoidLament);
}

#endif
