#ifndef UE4SS_SDK_Von_Cinematics_06_HPP
#define UE4SS_SDK_Von_Cinematics_06_HPP

class AVon_Cinematics_06_C : UCharacter
{
    FPointerToUberGraphFrame UberGraphFrame;
    UDecalComponent* Decal;
    UBillboardComponent* LocationVFX;
    UStaticMeshComponent* Sword1;
    UStaticMeshComponent* Sword;
    UVon_Cinematics_AnimBP_C* AnimBP;

    void OnNotifyEnd_E793CC744C00F7124186C09B9F4BE107(FName NotifyName);
    void OnNotifyBegin_E793CC744C00F7124186C09B9F4BE107(FName NotifyName);
    void OnInterrupted_E793CC744C00F7124186C09B9F4BE107(FName NotifyName);
    void OnBlendOut_E793CC744C00F7124186C09B9F4BE107(FName NotifyName);
    void OnCompleted_E793CC744C00F7124186C09B9F4BE107(FName NotifyName);
    void OnNotifyEnd_A8D5606E46E9A7760A04718736BD8A09(FName NotifyName);
    void OnNotifyBegin_A8D5606E46E9A7760A04718736BD8A09(FName NotifyName);
    void OnInterrupted_A8D5606E46E9A7760A04718736BD8A09(FName NotifyName);
    void OnBlendOut_A8D5606E46E9A7760A04718736BD8A09(FName NotifyName);
    void OnCompleted_A8D5606E46E9A7760A04718736BD8A09(FName NotifyName);
    void OnNotifyEnd_76393D9644927BB995C9ED9B423DBE71(FName NotifyName);
    void OnNotifyBegin_76393D9644927BB995C9ED9B423DBE71(FName NotifyName);
    void OnInterrupted_76393D9644927BB995C9ED9B423DBE71(FName NotifyName);
    void OnBlendOut_76393D9644927BB995C9ED9B423DBE71(FName NotifyName);
    void OnCompleted_76393D9644927BB995C9ED9B423DBE71(FName NotifyName);
    void ReceiveBeginPlay();
    void VonLand();
    void VonTakeOff();
    void GiveSanctuary();
    void ExecuteUbergraph_Von_Cinematics_06(int32 EntryPoint, int32 CallFunc_PostEventAtLocation_ReturnValue, FName K2Node_CustomEvent_NotifyName_14, FName K2Node_CustomEvent_NotifyName_13, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FName K2Node_CustomEvent_NotifyName_12, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FName K2Node_CustomEvent_NotifyName_11, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FName K2Node_CustomEvent_NotifyName_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, FName Temp_name_Variable, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, FName K2Node_CustomEvent_NotifyName_9, FName K2Node_CustomEvent_NotifyName_8, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, FName K2Node_CustomEvent_NotifyName_7, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, FName K2Node_CustomEvent_NotifyName_6, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, FName K2Node_CustomEvent_NotifyName_5, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, FName Temp_name_Variable_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, FName K2Node_CustomEvent_NotifyName_4, FName K2Node_CustomEvent_NotifyName_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, FName K2Node_CustomEvent_NotifyName_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_11, FName K2Node_CustomEvent_NotifyName_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_12, FName K2Node_CustomEvent_NotifyName, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_13, FName Temp_name_Variable_2, UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, UVon_Cinematics_AnimBP_C* K2Node_DynamicCast_AsVon_Cinematics_Anim_BP, bool K2Node_DynamicCast_bSuccess, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_14, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, bool CallFunc_IsValid_ReturnValue, FVector CallFunc_K2_GetComponentLocation_ReturnValue, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1, FVector CallFunc_K2_GetComponentLocation_ReturnValue_1, UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_2);
}

#endif
