#ifndef UE4SS_SDK_Von_Cinematics_VoidLament_HPP
#define UE4SS_SDK_Von_Cinematics_VoidLament_HPP

class AVon_Cinematics_VoidLament_C : UCharacter
{
    FPointerToUberGraphFrame UberGraphFrame;
    UDecalComponent* Decal;
    UStaticMeshComponent* Sword1;
    UStaticMeshComponent* Sword;
    UVon_Cinematics_AnimBP_C* AnimBP;

    void OnNotifyEnd_ED847B3B45852B3F0DE8C99258B9CA16(FName NotifyName);
    void OnNotifyBegin_ED847B3B45852B3F0DE8C99258B9CA16(FName NotifyName);
    void OnInterrupted_ED847B3B45852B3F0DE8C99258B9CA16(FName NotifyName);
    void OnBlendOut_ED847B3B45852B3F0DE8C99258B9CA16(FName NotifyName);
    void OnCompleted_ED847B3B45852B3F0DE8C99258B9CA16(FName NotifyName);
    void OnNotifyEnd_16A88E14482A376DBB2D20A86362DACC(FName NotifyName);
    void OnNotifyBegin_16A88E14482A376DBB2D20A86362DACC(FName NotifyName);
    void OnInterrupted_16A88E14482A376DBB2D20A86362DACC(FName NotifyName);
    void OnBlendOut_16A88E14482A376DBB2D20A86362DACC(FName NotifyName);
    void OnCompleted_16A88E14482A376DBB2D20A86362DACC(FName NotifyName);
    void OnNotifyEnd_8A45F60149D72F558B6AF5AE9DD3A91D(FName NotifyName);
    void OnNotifyBegin_8A45F60149D72F558B6AF5AE9DD3A91D(FName NotifyName);
    void OnInterrupted_8A45F60149D72F558B6AF5AE9DD3A91D(FName NotifyName);
    void OnBlendOut_8A45F60149D72F558B6AF5AE9DD3A91D(FName NotifyName);
    void OnCompleted_8A45F60149D72F558B6AF5AE9DD3A91D(FName NotifyName);
    void OnNotifyEnd_F75466EE4246491EBC94FFAD46E6E111(FName NotifyName);
    void OnNotifyBegin_F75466EE4246491EBC94FFAD46E6E111(FName NotifyName);
    void OnInterrupted_F75466EE4246491EBC94FFAD46E6E111(FName NotifyName);
    void OnBlendOut_F75466EE4246491EBC94FFAD46E6E111(FName NotifyName);
    void OnCompleted_F75466EE4246491EBC94FFAD46E6E111(FName NotifyName);
    void ReceiveBeginPlay();
    void VonTurn180_A();
    void FinCutscene();
    void VonHeadDown();
    void VonTurn180_B();
    void VonUpHead();
    void ExecuteUbergraph_Von_Cinematics_VoidLament(int32 EntryPoint, FName K2Node_CustomEvent_NotifyName_19, FName K2Node_CustomEvent_NotifyName_18, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate, FName K2Node_CustomEvent_NotifyName_17, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_1, FName K2Node_CustomEvent_NotifyName_16, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_2, FName K2Node_CustomEvent_NotifyName_15, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_3, FName Temp_name_Variable, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_4, FName K2Node_CustomEvent_NotifyName_14, FName K2Node_CustomEvent_NotifyName_13, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_5, FName K2Node_CustomEvent_NotifyName_12, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_6, FName K2Node_CustomEvent_NotifyName_11, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_7, FName K2Node_CustomEvent_NotifyName_10, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_8, FName Temp_name_Variable_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_9, FName K2Node_CustomEvent_NotifyName_9, FName K2Node_CustomEvent_NotifyName_8, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_10, FName K2Node_CustomEvent_NotifyName_7, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_11, FName K2Node_CustomEvent_NotifyName_6, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_12, FName K2Node_CustomEvent_NotifyName_5, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_13, FName Temp_name_Variable_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_14, FName K2Node_CustomEvent_NotifyName_4, FName K2Node_CustomEvent_NotifyName_3, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_15, FName K2Node_CustomEvent_NotifyName_2, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_16, FName K2Node_CustomEvent_NotifyName_1, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_17, FName K2Node_CustomEvent_NotifyName, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_18, FName Temp_name_Variable_3, UAnimInstance* CallFunc_GetAnimInstance_ReturnValue, UVon_Cinematics_AnimBP_C* K2Node_DynamicCast_AsVon_Cinematics_Anim_BP, bool K2Node_DynamicCast_bSuccess, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue, OnMontagePlayDelegate__DelegateSignature K2Node_CreateDelegate_OutputDelegate_19, bool CallFunc_IsValid_ReturnValue, FString CallFunc_CheckState_Same_ID, bool CallFunc_CheckState_Used, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_2, UPlayMontageCallbackProxy* CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_3);
}

#endif
